Update records documentation
TBD54566975/developer.tbd.website pull request #1004
Opened 2023-11-15 15:44 UTC by acekyd

## What type of PR is this? (check all applicable)

- [x] 📝 Documentation Update
- [x] 📖 Content

## Description

This PR updates the API documentation for `records.read()`

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

![processing](https://media3.giphy.com/media/OV4CwX1Uhs5hknLA0s/giphy.gif?cid=ecf05e478h7erxrmgvzjhwawp0uz4xe5ocw9fypl3dnccae5&ep=v1_gifs_search&rid=giphy.gif&ct=g)

2023-11-15 15:49 UTC, angiejones requested changes

2023-11-15 15:49 UTC, angiejones commented on site/api/web5-js/dwn/records.mdx
> +                                    type: 'Signer',
this one is an object so should have `isObject: true` and drill down another level with the properties of the `Signer` object

2023-11-26 17:58 UTC, angiejones commented on site/api/web5-js/dwn/records.mdx
> +                                    type: 'Signer',
@acekyd I used the [Signer](https://github.com/TBD54566975/dwn-sdk-js/blob/597c102dddfd4a3ac29557a900a3cfb7e90e936e/src/types/signer.ts#L4) interface to get the needed details

2023-11-26 18:01 UTC, angiejones approved these changes

2023-11-27 14:16 UTC, acekyd commented on site/api/web5-js/dwn/records.mdx
> +                                    type: 'Signer',
Oh right! Keeping this in mind. Thank you @angiejones

2023-11-29 12:29 UTC, merged