adds support for windows in documentation
TBD54566975/developer.tbd.website pull request #1028
Opened 2023-11-25 10:03 UTC by samejima-san

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR updates documentation to include Windows, also adds tabs so you can pick your operating system.

## Related Tickets & Documents

Resolves #1005 

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-11-25 10:04 UTC, samejima-san commented
right now I am having trouble getting the code block to render properly, so i am going to work on this more tomorrow. This PR is just to show progress.

2023-11-26 16:47 UTC, angiejones requested changes

2023-11-26 16:47 UTC, angiejones commented on site/package.json
please restore this file

2023-11-26 16:47 UTC, angiejones commented on site/src/css/docs.css
No impactful change here, can restore this file

2023-11-26 16:47 UTC, angiejones commented on site/src/components/ReusableTabs.jsx
> +    MacCommand: `curl -X PUT localhost:8080/v1/dids/key -d '{"keyType":"Ed25519"}'`,
don't want these as defaults, especially since we're no longer supporting SSI Service. Should probably not have any defaults since we'd likely use these for other projects as well

2024-09-29 22:57 UTC, closed without merging