PFI Developer Guide
TBD54566975/developer.tbd.website pull request #1047
Opened 2023-11-29 18:33 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR introduces the developer guide for PFIs in Typescript

## Related Tickets & Documents

Resolves #1006

2023-11-29 19:39 UTC, leordev commented on package-lock.json
please use pnpm, so we can get rid of this file

2023-11-29 19:42 UTC, leordev commented
I noticed the PR contains code but they are not using our code snippets testing framework. Should they be added for tbdex too? cc @dayhaysoos

2023-11-29 19:42 UTC, angiejones commented on package.json
> +    "start-server-and-test": "^2.0.3",
is this a needed bump?

2023-11-29 20:12 UTC, angiejones requested changes

2023-11-29 20:12 UTC, angiejones commented on site/docs/tbdex/anatomy-of-a-pfi.mdx
we should add a PFI folder and put the PFI-related guides under there

2023-11-29 21:06 UTC, dayhaysoos commented on package.json
> +    "start-server-and-test": "^2.0.3",
Hmm not sure how that made it in here considering I have a script that prevents committing from ranged versioning. Gonna look into this, but this should def not get bumped up

2023-11-29 21:08 UTC, dayhaysoos commented
> I noticed the PR contains code but they are not using our code snippets testing framework. Should they be added for tbdex too? cc @dayhaysoos

It would be reasonable to turn these into code snippets but I don't know if Chris has time to add them to this PR.

2023-11-30 00:50 UTC, angiejones commented on package.json
> +    "start-server-and-test": "^2.0.3",
```suggestion
    "start-server-and-test": "^2.0.2",
```

2023-11-30 02:40 UTC, angiejones requested changes

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/onboarding.mdx
> +Before beginning development of your PFI’s code, you’ll need to create an identity to make your PFI discoverable on the network. The tbDEX network is built to be decentralized, which is why you’ll ne
note: I don't see the ability to create DHT dids from `web5/dids` yet

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/required-sdks.mdx
> +To implement a PFI, you’ll need to make use of the following SDKs:
Link out to the SDKs' GitHub READMe files

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/anatomy-of-a-pfi.mdx
> +const httpApi = new TbdexHttpServer({ exchangesApi: ExchangeApiProvider, offeringsApi: OfferingApiProvider })
should show how to install tbdex/http-server and how to import these classes
https://github.com/TBD54566975/tbdex-js/tree/main/packages/http-server/src#tbdex-http-server

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/anatomy-of-a-pfi.mdx
> +```
```suggestion
```js
```

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/anatomy-of-a-pfi.mdx
> +    const subject = aliceMessageKinds.has(message.kind) ? message.from : message.to
what is `aliceMessageKinds`?

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/creating-quotes.mdx
> +   const subject = aliceMessageKinds.has(message.kind) ? message.from : message.to
what is `aliceMessageKinds`?

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/creating-offerings.mdx
> +Once the Offering has been generated, you can store it in your database using code as shown in the
this is cut short

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/creating-offerings.mdx
> +   <td>requiredClaims
we should open an issue to create a new guide on how to specify Required Claims

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/creating-quotes.mdx
> +RFQ storage was discussed in the [Exchange API Provider](docs/tbdex/anatomy-of-a-pfi) section, so this section will discuss the next 3 steps.
```suggestion
RFQ storage was discussed in the [Exchange API Provider](docs/tbdex/anatomy-of-a-pfi) section, so this section will discuss the next steps.
```

don't wanna hard code the number of steps just in case we ever have to add/remove one. we'd likely forget to also update this number

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/processing-orders.mdx
> +Order storage was discussed in the [Offerings API Provider](docs/tbdex/anatomy-of-a-pfi) section, so this section will discuss the next 3 steps.
```suggestion
Order storage was discussed in the [Offerings API Provider](docs/tbdex/anatomy-of-a-pfi) section, so this section will discuss the next steps.
```

don't wanna hard code the number of steps just in case we ever have to add/remove one. we'd likely forget to also update this number

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/anatomy-of-a-pfi.mdx
> +    const result = await dataProvider.insert(
where does the `dataProvider` object come from?

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/creating-quotes.mdx
> +After receiving an RFQ and finding the matching Offering for it, you’ll want to verify that the Wallet satisfies the necessary requirements for the Offering. The RFQ class offers the `[verifyOffering
```suggestion
After receiving an RFQ and finding the matching Offering for it, you’ll want to verify that the Wallet satisfies the necessary requirements for the Offering. The RFQ class offers the [verifyOfferingRequirements](/docs/tbdex/api-reference/tbdex-js/protocol/classes/rfq/#verifyofferingrequirements) method to do so, which uses PEX to check that the claim or credential provided in the RFQ satisfies the presentation definition that was given on the offering. That may look like this:
```

link wasn't being resolved:

<img width="828" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/c182a35e-595c-4aa9-a966-77ffb779847c">

https://deploy-preview-1047--tbd-website-developer.netlify.app/docs/tbdex/creating-quotes#verifying-the-wallets-credentials

2023-11-30 02:40 UTC, angiejones commented on site/docs/tbdex/processing-orders.mdx
> +      const orderStatus = OrderStatus.create(
show how to import OrderStatus

2023-11-30 07:51 UTC, angiejones commented
> > I noticed the PR contains code but they are not using our code snippets testing framework. Should they be added for tbdex too? cc @dayhaysoos
> 
> It would be reasonable to turn these into code snippets but I don't know if Chris has time to add them to this PR.

this is what i flagged in [Discord](https://discord.com/channels/937858703112155166/949067751803191397/1170191681094680607). we're not using Web5 here so need to add test support for the tbDEX SDKs. In all supported languages. This requires some discussion on how to enable this

2023-11-30 17:06 UTC, chris-tbd commented on site/docs/tbdex/onboarding.mdx
> +Before beginning development of your PFI’s code, you’ll need to create an identity to make your PFI discoverable on the network. The tbDEX network is built to be decentralized, which is why you’ll ne
For this section I'm holding off on adding more details until we have Key Management rather than changing the guidance here quickly. Should be able to fill this out along with key management in the next two weeks

2023-11-30 17:30 UTC, chris-tbd commented on site/docs/tbdex/anatomy-of-a-pfi.mdx
> +Referring back to the [message types](docs/tbdex/message-types), you’ll notice that of the five listed, three of them will be sent from Wallets to PFIs: RFQ, Order, and Close. As a result, you’ll wan
Added

2023-11-30 17:30 UTC, chris-tbd commented on site/docs/tbdex/required-sdks.mdx
> +To implement a PFI, you’ll need to make use of the following SDKs:
Added

2023-11-30 17:30 UTC, chris-tbd commented on site/docs/tbdex/creating-quotes.mdx
> +RFQ storage was discussed in the [Exchange API Provider](docs/tbdex/anatomy-of-a-pfi) section, so this section will discuss the next 3 steps.
Updated

2023-11-30 17:30 UTC, chris-tbd commented on site/docs/tbdex/processing-orders.mdx
> +Order storage was discussed in the [Offerings API Provider](docs/tbdex/anatomy-of-a-pfi) section, so this section will discuss the next 3 steps.
Updated

2023-11-30 17:31 UTC, chris-tbd commented on site/docs/tbdex/creating-quotes.mdx
> +After receiving an RFQ and finding the matching Offering for it, you’ll want to verify that the Wallet satisfies the necessary requirements for the Offering. The RFQ class offers the `[verifyOffering
Updated

2023-11-30 17:31 UTC, chris-tbd commented on site/docs/tbdex/processing-orders.mdx
> +      const orderStatus = OrderStatus.create(
Added

2023-11-30 18:33 UTC, chris-tbd commented on package-lock.json
Removed

2023-11-30 18:34 UTC, chris-tbd commented on package.json
> +    "start-server-and-test": "^2.0.3",
Fixed

2023-11-30 18:34 UTC, chris-tbd commented on site/docs/tbdex/creating-quotes.mdx
> +After receiving an RFQ and finding the matching Offering for it, you’ll want to verify that the Wallet satisfies the necessary requirements for the Offering. The RFQ class offers the `[verifyOffering
Updated

2023-11-30 18:34 UTC, chris-tbd commented on site/docs/tbdex/anatomy-of-a-pfi.mdx
Added

2023-11-30 18:36 UTC, chris-tbd commented
> It would be reasonable to turn these

Spoke with @dayhaysoos about this, I'm going to push to get these done  next week

2023-11-30 22:07 UTC, chris-tbd commented on site/docs/tbdex/creating-offerings.mdx
> +Once the Offering has been generated, you can store it in your database using code as shown in the
Added

2023-11-30 22:07 UTC, chris-tbd commented on site/docs/tbdex/creating-quotes.mdx
> +   const subject = aliceMessageKinds.has(message.kind) ? message.from : message.to
Addressed

2023-11-30 22:19 UTC, dayhaysoos approved these changes

2023-11-30 22:23 UTC, angiejones requested changes

2023-11-30 22:23 UTC, angiejones commented on site/docs/tbdex/pfi/_category_.json
for some reason, tbDEX is no longer showing on the docs menu

https://nkn2pm-51423.csb.app/docs/

2023-11-30 22:57 UTC, angiejones commented on site/docs/tbdex/pfi/_category_.json
false alarm

2023-12-01 01:56 UTC, angiejones approved these changes

2023-12-01 02:03 UTC, merged