Corrected deleteTextRecord code snippet.
TBD54566975/developer.tbd.website pull request #1071
Opened 2023-12-13 18:23 UTC by austinvach

The code snippet was missing record.id which was causing a reference error. https://github.com/TBD54566975/developer.tbd.website/issues/1070

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-12-13 23:12 UTC, angiejones commented
hey @austinvach! congrats on your first-ever PR! We're honored that you chose TBD to contribute to ❤️

Adding `record.id` is optional here, because the variable name is the same as the property name and in JavaScript, you don't have to repeat it. 

```js
export async function deleteTextRecord(web5, did, recordId) {
  const deleteResult = await web5.dwn.records.delete({
    message: {
      recordId,
    },
  });

  return deleteResult;
}
```

However, for documentation, I think it would be good to be as explicit as possible to avoid any confusion. So, I say all of that to say - let's get your fix in!

You'll need to add your fix to [quickstart.js](https://github.com/TBD54566975/developer.tbd.website/blob/main/site/code-snippets/web5/quickstart.js#L37) instead of `code-snippets-map.json`. code-snippets-map.json is automatically generated from the code snippets throughout the site, so your manual change there won't persist.

Let us know if you have any questions! 😊

2023-12-13 23:12 UTC, angiejones requested changes
left note to make change in a different file

2023-12-14 01:31 UTC, austinvach commented
Done. Thanks for the guidance.

2023-12-14 04:36 UTC, angiejones commented on site/code-snippets/web5/quickstart.js
> +      recordId: record.id,
```suggestion
      recordId: recordId
```

It needs to use that argument from line 34

2023-12-14 04:37 UTC, angiejones requested changes

2023-12-14 04:37 UTC, angiejones commented on site/src/util/code-snippets-map.json
> +  "deleteTextRecord": "const deleteResult = await web5.dwn.records.delete({\n    message: {\n      recordId: record.id,\n    },\n  });"
```suggestion
  "deleteTextRecord": "const deleteResult = await web5.dwn.records.delete({\n    message: {\n      recordId: recordId,\n    },\n  });"
```

2023-12-14 04:38 UTC, angiejones approved these changes

2023-12-14 07:51 UTC, merged