Update Offering Page for PFIs
TBD54566975/developer.tbd.website pull request #1106
Opened 2023-12-22 22:29 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Updates to PFI tbDEX docs
- Update the title of "Anatomy of a PFI" to "Structuring Your PFI App" to improve clarity of purpose to readers.
- Update content of "Structuring Your PFI App" page to include more information about how PFIs are able to expose their Offerings data to Wallets and let them know that they don't need to expose any APIs to Wallets.
- Rename the "Creating Offerings" page to just "Offerings" and include more detail on the schema, definition, and structure of the Offerings object. It now includes more specific information and exhaustive lists of types, along with more code examples to help PFI developers create their own Offerings.

## Added code snippets?
- [ x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note
These are JSON, I don't believe we need tests for these but am not sure 

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-12-22 23:27 UTC, angiejones requested changes

2023-12-22 23:27 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +To find more information on currency code strings to ensure your PFI uses a valid and correct value, see the [currency lists provided here](https://www.six-group.com/en/products-services/financial-in
whats this link? i dont see any currency lists

2023-12-22 23:27 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +| `required`               | string[]  | A list of all the properties described `requiredPaymentDetails`.
I dont see the `required` and `feeSubunits` properties anymore in the API Guide
https://tbd54566975.github.io/tbdex-js/types/_tbdex_protocol.PaymentMethod.html

2023-12-22 23:27 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +Note that the while `type` and `description` fields are more intuitive and standard for you to include in your `requiredPaymentDetails` schema, you have the flexibility to detail any requirements you
```suggestion
Note that while `type` and `description` fields are more intuitive and standard for you to include in your `requiredPaymentDetails` schema, you have the flexibility to detail any requirements you have in this object. Each `payinMethod` or `payoutMethod` can be represented by an array of `PaymentMethods`.
```

2023-12-22 23:27 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +```json
This example is a bit abstract and makes it hard for me to imagine what the values should be. Should we maybe include an example with real values for the properties?

2023-12-22 23:27 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +Before placing an Offer on an RFQ that a Wallet has submitted for your Offering, you'll likely want to verify some kind of information about the owner of that Wallet. To do this, you'll request a cla
```suggestion
In order to comply with certain financial regulations, you may require information about the customer you are transacting with. You can obtain this information via [Verifiable Credentials](/docs/web5/learn/verifiable-credentials). 
```

2023-12-22 23:27 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +You will specify the `requiredClaims` of your Offering by following [the DIF Presentation Definition](https://identity.foundation/presentation-exchange/#presentation-definition) - a way of defining w
```suggestion
To specify the exact credentials you need, you can do so in the `requiredClaims` section of your Offering by following [the DIF Presentation Definition](https://identity.foundation/presentation-exchange/#presentation-definition). You'll specify all required forms and details of proof, optional selection rules, and define flexibility where possible when different types of input may satisfy the requirements.
```

2023-12-22 23:27 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +```json
use the Sanctions example as a more realistic use case for PFIs
https://developer.tbd.website/docs/tbdex/wallet/managing-credentials/#required-claims

2023-12-22 23:28 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> -# Creating Offerings
how come the name change?

2023-12-22 23:29 UTC, angiejones commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +### Credentials and Claims
```suggestion
### Required Claims
```

2023-12-28 16:41 UTC, chris-tbd commented on site/docs/tbdex/pfi/creating-offerings.mdx
> -# Creating Offerings
I think "creating offerings" is more narrow, this guide is actually covering offerings as a whole - this will also be more in line with upcoming changes I'd like to make explaining Exchanges

2023-12-28 16:43 UTC, chris-tbd commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +To find more information on currency code strings to ensure your PFI uses a valid and correct value, see the [currency lists provided here](https://www.six-group.com/en/products-services/financial-in
The link actually provides 3 currency lists under "Current and Historical Lists" - I just can't link straight to the header. For whatever reason they divide it into three lists so there isn't just one to link to

2023-12-28 17:02 UTC, chris-tbd commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +```json
Added

2023-12-28 17:04 UTC, chris-tbd commented on site/docs/tbdex/pfi/creating-offerings.mdx
> +```json
Updated with concrete values

2023-12-28 23:37 UTC, angiejones approved these changes

2023-12-28 23:38 UTC, merged