Restructure troubleshooting menu
TBD54566975/developer.tbd.website pull request #1108
Opened 2023-12-27 10:55 UTC by acekyd

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] 📝 Documentation Update
- [x] 📖 Content

## Description

This PR restructures the troubleshooting + JS Frameworks menu links under Web5 SDK > Build. With this we are able to consolidate these related information together and people can look at both common errors and framework specific errors as we continue to grow. 

Side effect however is existing shared links would be broken. Welcoming thoughts. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

2023-12-27 18:54 UTC, blackgirlbytes approved these changes
yes! we needed this

2023-12-28 00:44 UTC, blackgirlbytes commented
Only comment is that I think Angie moved the troubleshooting guide to a more obvious place..outside of build. I liked it where she placed it, but I'm loving the move delineation of Next.js and Vue errors

2023-12-28 05:16 UTC, angiejones requested changes
Can you move this to be a peer to Build? Here's how it is today. So just add `troubleshooting` as a peer to `build`

<img width="268" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/e920b894-4d54-474b-8d91-515d8ca1fa23">

2023-12-28 16:44 UTC, angiejones approved these changes

2023-12-28 21:50 UTC, merged