PR to add a one-page for tbDEX issuers
TBD54566975/developer.tbd.website pull request #1111
Opened 2023-12-28 21:14 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds a tbDEX Issuer documentation page that serves as a one-pager for tbDEX issuers to get their service up-and-running.

## Added code snippets?
- [ x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ x] 🙋 no, because I need help

### No tests? Add a note
Need help getting tests up and running for these

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-12-28 23:27 UTC, angiejones requested changes

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +In our example above, we can offer a class property that stores all the sanctions lists checked against to issue the credential. You have wide flexibility with what you can store in your credential c
```suggestion
In the example above, you provide a class property that stores all the sanctions lists checked against to issue the credential. You have wide flexibility with what you can store in the credential model class, which means that you're free to include any public attributes that may be relevant to the credential you are issuing.
```

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +Your credential model is ** not ** the place to store private information about the user you are issuing the credential to, such as banking information or other PII.
do you mean the model class or the credential itself?

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +** BLOCKED ON THIS PART TO SHOW HOW TO ACTUALLY TAKE IN INFO TO BE VERIFIED **
I think there's some misunderstanding here. I've removed the word "verify" a couple of times throughout the guide. A verifier has a very distinct meaning in the context of VCs, and is a different entity than the issuer. A verifier is someone you give an issued credential to.

The issuer is the one making claims. They wouldn't necessarily take any info and verify it. They'd do their own checks (check a real Sanctions list, or check an internal system to make sure the person is an employee, or actually earned a degree from their university). The issuer is the one qualified to make to the claim

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +** BLOCKED ON THIS PART TO SHOW HOW TO ACTUALLY TAKE IN INFO TO BE VERIFIED **
Now what you might want to highlight is the act of a applying for or requesting a credential from an issuer

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +        // Mint the credential
```suggestion
        // Create the credential
```

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +Now the `vc` object you have at the end of this snippet will be a raw VC that looks like this:
```suggestion
The `vc` object that's returned will be a raw VC that looks like this:
```

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +To complete your basic VC issuance flow, you can now sign and return the credential. Signing will return a [VC JSON Web Token](/docs/web5/build/verifiable-credentials/jwt-to-vc#what-is-a-jwt), which
```suggestion
To complete the issuance, you must sign the credential. Signing will return a [VC JSON Web Token](/docs/web5/build/verifiable-credentials/jwt-to-vc#what-is-a-jwt), which is ideal for secure transmission of the credential:
```

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +With that, you've implmented a basic API service to accept requests, process user data, and issue a VC!
```suggestion
With that, you've implmented a basic credential issuance service to accept requests and issue VCs.
```

2023-12-28 23:27 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +## Additional Resources
let's delete this section

2023-12-29 18:47 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +## Background
I believe your other comments overlapped with this so we should be good to resolve this one

2023-12-29 18:47 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +## Additional Resources
Are you referring to the "Additional Resources" Section?

2023-12-29 18:57 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +```typescript
Updated

2023-12-29 18:57 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +```typescript
Removed

2023-12-29 18:57 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +Note that the method above does require installing the `@web5/dids` package.
Removed

2023-12-29 18:57 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +Your credential model is ** not ** the place to store private information about the user you are issuing the credential to, such as banking information or other PII.
Updated with clarifying text

2023-12-29 18:58 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +** BLOCKED ON THIS PART TO SHOW HOW TO ACTUALLY TAKE IN INFO TO BE VERIFIED **
Thanks for clarifying - I updated the language to be more clear about the difference between verify and check, and this should help devs understand it.

2023-12-29 19:11 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +## Additional Resources
yes

2023-12-29 19:15 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
can you rename this file to `onboarding.mdx`?

2023-12-29 19:16 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +## Background
looking at the deploy preview, this section doesn't add any additional value and can be removed completely

https://deploy-preview-1111--tbd-website-developer.netlify.app/docs/tbdex/issuer/quickstart#background

2023-12-29 19:18 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +A credential issuer app runs as an API service that exposes endpoints where third parties can request credentials. You can see a full end-to-end implementation of a credential issuer's workflow [in o
this is still pointing to the Taylor Swift example. Please update this to point to the generic VC Issuance guide instead

2023-12-29 19:20 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +With all of this, you can start up your basic express API service in a `main.ts` file that looks as follows:
couple of unanswered questions here

2023-12-29 19:22 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +Your credential model is ** not ** the place to store private information about the user you are issuing the credential to, such as banking information or other PII.
ok this is not true. in fact, we're specifically gonna need KYC credentials that will store private PII info. I recommend just removing this sentence altogether.

2023-12-29 21:36 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +A credential issuer app runs as an API service that exposes endpoints where third parties can request credentials. You can see a full end-to-end implementation of a credential issuer's workflow [in o
I was pretty sure I wrote a suggestion for this paragraph but now I cant find it 😫 let me try again...

```suggestion
A Credential Issuer app runs as an API service that exposes endpoints where third parties can request credentials. 

If you already have an Issuer app up and running,  check out the guide on [how to issue credentials with Web5](/docs/web5/build/verifiable-credentials/vc-issuance/).

If you need to create a Credential Issuer app from scratch, continue on with this guide where we'll cover how to: 
```

2023-12-29 21:37 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +- Create a web server using a technology like ** [express](https://expressjs.com/) ** that will serve as an API endpoint.
```suggestion
- Create a web server using a technology like ** [Express](https://expressjs.com/) ** that will serve as an API endpoint.
```

2023-12-29 21:38 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +- Implement your issuance path, where you'll accept a request for issuance, perform checks required to verify the requester's information, and mint the credential.
```suggestion
- Implement an issuance path where you'll accept a request for issuance, perform any necessary checks, and issue the credential.
```

2023-12-29 21:45 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +            res.status(401).json({
should this be a return statement? otherwise, it'll still create the credential after the fail, right?

```suggestion
            return res.status(401).json({
```

2023-12-29 21:49 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +```typescript title=index.ts
should this be `main`? that's why I asked if `main.ts` is your main entry point in that other comment. wanted to make sure I'm not introducing a new file (index) if it should be main

```suggestion
```typescript title=main.ts
```

2023-12-29 21:50 UTC, angiejones requested changes

2023-12-29 21:50 UTC, angiejones commented on site/docs/tbdex/issuer/quickstart.mdx
> +Within your service's entry point file (e.g. index.js), import the following:
```suggestion
Within your service's entry point file (e.g. main.ts), import the following:
```

2023-12-30 07:17 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +## Additional Resources
Removed

2023-12-30 07:19 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +Your credential model is ** not ** the place to store private information about the user you are issuing the credential to, such as banking information or other PII.
Going to remove - just so I can better understand, how is it that credentials can store PII without exposing that? If the credential is being passed around don't we want to remove PII and just let the VC stand for the claim?

2023-12-30 07:22 UTC, chris-tbd commented on site/docs/tbdex/issuer/quickstart.mdx
> +With all of this, you can start up your basic express API service in a `main.ts` file that looks as follows:
Updated all to main.js (switched of ts to js as well)

2023-12-30 21:53 UTC, angiejones approved these changes

2023-12-31 18:21 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +            signer = verificationResult.signer;
should this be the `sub` property from the JWT that was passed in?

2024-01-04 16:15 UTC, chris-tbd commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +            signer = verificationResult.signer;
I was referencing this implementation here https://github.com/TBD54566975/workshop-tbdex-abc-vc-issuer/blob/main/src/api.ts

Is that reference out of date? I'm not too familiar with grabbing this info out of the JWT so want to double check

2024-01-04 16:37 UTC, merged

2024-01-04 17:46 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +            signer = verificationResult.signer;
that one makes a safe assumption that the person who signed the credential is also the subject of the credential (a self-issued VC). that was for the workshop use case. For a generic use case, that's not a safe assumption. It would be safer to use the subject of the jwt as the subject of the VC you're about to issue