refactor 'message-types.mdx' to 'key concepts' where it will cover me…
TBD54566975/developer.tbd.website pull request #1114
Opened 2023-12-30 07:52 UTC by chris-tbd

…ssages, offerings, and exchanges.

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-12-31 08:13 UTC, angiejones requested changes

2024-01-04 17:56 UTC, chris-tbd commented on site/docs/tbdex/message-types.mdx
> +## Messages
Can confirm there are no urls to this header exactly, we just need to confirm if it's okay to change the filename and therefore the base url

2024-01-04 18:11 UTC, angiejones commented on site/docs/tbdex/message-types.mdx
> +[Offerings](/docs/tbdex/pfi/creating-offerings) describe a currency pair that can be exchanged and include requirements, conditions, and constraints needed to fulfill the described swap. They are cre
https://tbd54566975.github.io/tbdex-js/interfaces/_tbdex_http_server.OfferingsApi.html

2024-01-04 18:23 UTC, chris-tbd commented on site/docs/tbdex/message-types.mdx
> +[Offerings](/docs/tbdex/pfi/creating-offerings) describe a currency pair that can be exchanged and include requirements, conditions, and constraints needed to fulfill the described swap. They are cre
Updated

2024-01-05 02:56 UTC, angiejones approved these changes

2024-01-05 02:56 UTC, merged