update language to use allowlist instead of whitelist
TBD54566975/developer.tbd.website pull request #1126
Opened 2024-01-04 16:43 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Updated usage of "whitelist" to "allowlist" in tbDEX guides

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note
Just updating language

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ x] 🙅 no documentation needed

### No docs? Add a note
Updating language, not changing any actual content

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-01-04 17:11 UTC, angiejones commented on site/docs/tbdex/wallet/allowlist-pfis.mdx
> +allowlisting is the process of approving or recognizing specific PFIs as trusted entities.
```suggestion
Allowlisting is the process of approving or recognizing specific PFIs as trusted entities. 
```

2024-01-04 17:13 UTC, angiejones commented on site/docs/tbdex/wallet/allowlist-pfis.mdx
> +## allowlist PFI
```suggestion
## Allowlist PFI
```

2024-01-04 17:29 UTC, angiejones commented on site/docs/tbdex/key-concepts.mdx
this one is part of another PR. I put some comments on that one

2024-01-04 17:36 UTC, angiejones commented
Really appreciate the thoughtfulness of the word change. Wondering if this will come off as contradictory to tbDEX being a permissionless network though.

2024-01-04 18:12 UTC, chris-tbd commented
Should we use a phrase like "Add Searchable PFIs," "Add PFIs," or "Enable PFIs" instead? Because I do see how allowlist/whitelist is confusing since we aren't actually "allowing" the PFI to interact with the wallet, we're just enabling it

2024-01-05 15:48 UTC, angiejones commented on site/docs/tbdex/key-concepts.mdx
@chris-tbd can you remove this file from the PR? I think you should be able to do `checkout site/docs/tbdex/key-concepts.mdx`

2024-01-05 18:58 UTC, angiejones requested changes

2024-01-05 18:58 UTC, angiejones commented on site/docs/tbdex/key-concepts.mdx
remove this file from PR

2024-01-05 22:17 UTC, angiejones approved these changes

2024-01-05 22:55 UTC, merged