Basic protocol roles guide
TBD54566975/developer.tbd.website pull request #1130
Opened 2024-01-05 22:37 UTC by blackgirlbytes

Putting this in draft mode because I need help/feedback for a few reasons @angiejones , @acekyd :
1) None of my code snippets are generating even though I did run `pnpm test`
2) Location of guide. I made a new Protocols guide under Build because there's already a lot in the Learn > Protocols section. Not sure if this is the best spot. Let me know where to put it.
3) There's one failing test and that's the createContextRole code snippet. This fails because in order to create a context role, I need to create a record, and then a child record, and then I need to send that record to the recipient..and then use the recordId to create a role, which is fine to do in an app, but trying to think of the easiest way to do this for a unit test. Would love thoughts!

Thanks so much!

2024-01-05 23:00 UTC, angiejones commented
> Putting this in draft mode because I need help/feedback for a few reasons @angiejones , @acekyd :
> 
> 1. None of my code snippets are generating even though I did run `pnpm test`
> 2. Location of guide. I made a new Protocols guide under Build because there's already a lot in the Learn > Protocols section. Not sure if this is the best spot. Let me know where to put it.
> 3. There's one failing test and that's the createContextRole code snippet. This fails because in order to create a context role, I need to create a record, and then a child record, and then I need to send that record to the recipient..and then use the recordId to create a role, which is fine to do in an app, but trying to think of the easiest way to do this for a unit test. Would love thoughts!
> 
> Thanks so much!

run `pnpm build` to generate the snippets

2024-01-06 01:39 UTC, angiejones requested changes

2024-01-06 01:39 UTC, angiejones commented on site/__tests__/web5/build/protocols/create-protocol-roles.test.js
> +            //preventing test from failing if the user has already been assigned a global role
this test worked the first time i ran it, but when i ran it again it failed with `ProtocolAuthorizationDuplicateGlobalRoleRecipient`. all tests should be able to be re-runnable without breaking. 

i wonder if we can just delete this record at the end of the test. I'll try...

2024-01-06 01:39 UTC, angiejones commented on site/docs/web5/build/protocols/create-protocol-roles.mdx
> +The first role is a `$globalRole` defined at the root level of the protocol structure called `admin`. The `admin` actor can perform actions on data in any context defined in this protocol, such as ev
At this point, I'm pretty far down in the guide and haven't seen any code yet. So it's hard for me to follow along without some sort of visual. By time I get to this line I'm a bit lost because I don't see a "first role" yet. I recommend showing some code snippets here and earlier on

2024-01-06 01:57 UTC, angiejones commented on site/docs/web5/build/protocols/create-protocol-roles.mdx
> +- **$globalRole** -  used to assign universally applicable permissions. For example, an admin role with access to all areas of a system could be a `$globalRole`. Global roles are defined at the root
Without knowing any better, it's really easy to assume "admin" is a built-in role. I think you should overly-clarify that this is literally a word you picked to represent a specific role and it has no meaning until you give it some.

2024-01-06 02:32 UTC, angiejones commented
tests fixed now 😊

2024-01-06 04:04 UTC, blackgirlbytes commented on site/docs/web5/build/protocols/create-protocol-roles.mdx
> +Roles management is a common concept in everyday web applications. For example, in a cloud-based word processor, such as Google Docs, users can set permissions and share documents, determining who ca
yeah like when you share a doc or folder with someone and you say this to this person can view, this person can edit, and this person can leave comments. I think maybe I should remove this paragraph because maybe it's more suitable in a blog post. This might distract from the point now that I'm looking at it again

2024-01-08 03:10 UTC, angiejones commented on site/docs/web5/build/protocols/create-protocol-roles.mdx
In helping folks understand roles, I've realized that they also need an example in the guide showing how to write a (normal) record given the role that they've been granted.

So, for example, can you show an example of a guest creating a record?

2024-01-08 03:14 UTC, angiejones commented on site/docs/web5/build/protocols/create-protocol-roles.mdx
> +After installing the protocol on the actors' DWNs, assign roles using the records interface.
```suggestion
After installing the protocol on the actors' DWNs, assign roles by using the records interface to store these roles in the recipient's DWN. This is synonymous to writing access permissions to a database.
```

2024-01-09 18:21 UTC, blackgirlbytes commented
Pausing this for when this issue is completed: https://github.com/TBD54566975/web5-js/issues/369

2024-01-12 04:09 UTC, blackgirlbytes commented
Going to close this. Will reopen when protocol roles are merged

2024-01-12 04:09 UTC, closed without merging