Initial commit
TBD54566975/developer.tbd.website pull request #1140
Opened 2024-01-09 17:25 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds a key management page under the build/dids vertical. It will add Kotlin code snippets.

## Related Tickets & Documents
N/A

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [x ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ x] 🙋 no, because I need help

### No tests? Add a note

Need help with Kotlin code snippet testing

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-01-09 22:32 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +The `web5/crypto` package contains a variety of key manager implementations, including a basic [`InMemoryKeyManager`]() designed for development environment testing, as well as an [`AwsKeyManager`]()
build is failing because of the missing links. I assume these are coming?

2024-01-11 04:08 UTC, angiejones requested changes

2024-01-11 04:19 UTC, angiejones commented on site/docs/tbdex/pfi/onboarding.mdx
> +Because you may be handling sensitive data on behalf of your users, be sure to understand proper [key management](/docs/web5/build/decentralized-identifiers/how-to-create-did/) before launching your
```suggestion
:::tip
Because you may be handling sensitive data on behalf of your users, be sure to understand proper [key management](/docs/web5/build/decentralized-identifiers/how-to-create-did/) before launching your PFI.
:::
```

2024-01-11 05:23 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Cryptographic keys are an integral part of DIDs and DIDs are designed to represent secure identity, which is why good key management is essential to developing your Web5 app. Key management provides
```suggestion
[Decentralized Identifiers (DIDs)](/docs/web5/learn/decentralized-identifiers) are associated with public and private keys. The private key, which should be kept secret, is used to sign information or transactions, demonstrating control over the DID. Proper [key management](https://en.wikipedia.org/wiki/Key_management) ensures that private keys are securely stored and used, reducing the risk of unauthorized access or misuse.
```

2024-01-11 05:27 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Key management is built right into the `DidMethod` implementations provided in the `Web5` SDK, such as `DidDht`. Here is how you'll create or load a DID with a `KeyManager`:
```suggestion
The Web5 SDK provides a key manager by default, as well as the option for you to use your own.

Here's an example that uses Web5's `InMemoryKeyManager` for development environments, and an external [AWS Key Management Service](https://docs.aws.amazon.com/kms/latest/developerguide/overview.html) for production environments:
```

2024-01-11 05:28 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +## Quickstart
```suggestion

```

2024-01-11 05:33 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +The `Web5` SDK provides a variety of `KeyManager` implementations, which will allow you connect to storage - in-memory storage in the case of `InMemoryKeyManager` and AWS Key Management Service in th
I really don't see the need for anything from this paragraph on down, but I'll leave it to @frankhinek and @mistermoe to make the call here

2024-01-11 05:34 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +sidebar_position: 2
can you add `sidebar_position: 1` to the 'Create a DID' guide so that the KMS guide appears after that one?

2024-01-11 16:06 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +        val did = DidDht.create(keyManager)
this gives a syntax error: 'Variable 'keyManager' must be initialized'

2024-01-11 16:06 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +    var did: DidDht;
this has a warning: 'Variable 'did' is never used'

2024-01-11 16:37 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +        val did = DidDht(uri = "some_uri", keyManager)
the constructor for DidDht is

```kt
public class DidDht(
  uri: String, 
  keyManager: KeyManager,
  public val didDocument: DIDDocument? = null,
  private val didDhtApi: DidDhtApi
) 
```

2024-01-18 14:43 UTC, amika-sq commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +- **Secure Enclave** storage is normally on mobile devices and other devices with specialized key storage hardware.
We cannot take advantage of the Secure Enclave, as it does not support either Ed25519 or Secp256k1. We should be removing any references to Secure Enclave from our guides.

2024-01-18 20:36 UTC, frankhinek commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Cryptographic keys are an integral part of DIDs and DIDs are designed to represent secure identity, which is why good key management is essential to developing your Web5 app. Key management provides
Great rewrite @angiejones

2024-01-18 20:55 UTC, frankhinek commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +The `Web5` SDK provides a variety of `KeyManager` implementations, which will allow you connect to storage - in-memory storage in the case of `InMemoryKeyManager` and AWS Key Management Service in th
There are certainly advanced topics in terms of key management, but I wouldn't recommend organizing them in terms of "database, storage, and management layer."  If we want to include advanced key management, it should likely be written as its own guide that gets into the considerations and customization options for secure key management.  It would likely also need to be divided up by runtime environment since options vary greatly for native mobile, web browser, and backend service.

This is a quick, off the top of my head rewrite:

```suggestion
The Web5 SDK offers two distinct `KeyManager` implementations:

- `InMemoryKeyManager`: This implementation utilizes in-memory, ephemeral storage for managing keys. It's ideal for scenarios where temporary key management is sufficient, such as in testing environments. Since the keys are stored in memory, they are lost when the application is terminated.

- `AwsKeyManager`: This implementation integrates with the AWS Key Management Service (KMS), providing a secure and robust solution for key management. It's well-suited for production environments where a high level of security and availability are critical.

Both implementations facilitate key generation and signature operations essential for creating and managing DIDs. Each caters to distinct security needs, and the choice between them should be based on the specific requirements of your application.
```

2024-01-18 21:33 UTC, closed without merging