Add Language Switcher support
TBD54566975/developer.tbd.website pull request #1144
Opened 2024-01-11 02:19 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ x] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR enables a dropdown language switcher to support Javascript and Kotlin

## Related Tickets & Documents

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note
Just adding the functionality in for future PRs

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-01-11 03:04 UTC, angiejones requested changes

2024-01-11 03:04 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> -import CodeSnippet from '@site/src/components/CodeSnippet';
this breaks the DID guide. Need to add this back

<img width="820" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/14dce6fc-6c4d-4255-8ed8-110f6e0158a2">

2024-01-11 04:05 UTC, angiejones commented on site/src/components/LanguageSwitchBlock.jsx
> +const LanguageSwitchBlock = ({ javascriptContent, kotlinContent }) => {
what about the other languages?

2024-01-17 21:25 UTC, angiejones requested changes

2024-01-17 21:25 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
let's add the switcher support to this guide in a followup PR because I proposed several changes to the content of this guide in https://github.com/TBD54566975/developer.tbd.website/pull/1140

2024-01-17 21:25 UTC, angiejones commented on site/src/components/LanguageContext.jsx
what do folks think about making a `language` folder under `components` since there are 6 components needed for this feature? feels it may be wise to have a grouping

2024-01-17 22:20 UTC, blackgirlbytes commented on site/src/components/LanguageContext.jsx
I like that idea!

2024-01-18 00:39 UTC, chris-tbd commented on site/src/components/LanguageContext.jsx
Making that change now

2024-01-18 00:42 UTC, chris-tbd commented
Ready for reviews again

2024-01-18 03:11 UTC, michaelneale commented
![image](https://github.com/TBD54566975/developer.tbd.website/assets/14976/c2f2634e-de04-4ed7-9357-3b497682daa8)
could we make it a bit more obvious - I had to hunt around for it (scrolled right passed it!) somehow?

2024-01-18 03:33 UTC, angiejones commented
> ![image](https://private-user-images.githubusercontent.com/14976/297600119-c2f2634e-de04-4ed7-9357-3b497682daa8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NDkwMDUsIm5iZiI6MTcwNTU0ODcwNSwicGF0aCI6Ii8xNDk3Ni8yOTc2MDAxMTktYzJmMjYzNGUtZGUwNC00ZWQ3LTkzNTctM2I0OTc2ODJkYWE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDAzMzE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYjkwZTIxM2NiYTZmMjkyZWEwYjM4NGVhYTg2M2VhOTgxNjVjZGJjNGQ1MTliYjQ1ZWRkY2E2YjdmODMxZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rou2ZJ4v4Gu2M3Mzx-BuUZTOK02S5JA8TvrgpSLPVWo) 

> could we make it a bit more obvious - I had to hunt around for it (scrolled right passed it!) somehow?

agreed. needs some overall styling

2024-01-18 16:42 UTC, chris-tbd commented
Updated the switcher to be clearer per @angiejones and @michaelneale 
<img width="1495" alt="Screenshot 2024-01-18 at 10 42 18 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/129119076/db4c6e49-af03-4799-bb59-8956d7189f13">

2024-01-18 22:37 UTC, angiejones commented on site/docs/hello-world.mdx
> +<LanguageSwitchBlock>
The team talked about having a control above the code blocks so that you wouldn't have to scroll back up if you wanted to switch when you encountered a code snippet. How does that get added?

Many of us agreed we'd like this as tabs. Is that possible with this system?

2024-01-18 22:40 UTC, ALRubinger commented
@chris-tbd On our topic of "selecting the language", [Stripe has a cool approach](https://stripe.com/docs/expand/use-cases):
Selecting a new language in the tab is a global selection, and all other code blocks change to the language selected. Means they don't need a separate language selector in the navbar (real estate IMO we should be protective of :slightly_smiling_face: ) WDYT?

![image (1)](https://github.com/TBD54566975/developer.tbd.website/assets/199891/32a1c8c8-1617-4e68-a99a-cff86c7c5bc4)

2024-01-18 22:56 UTC, angiejones commented on site/docs/hello-world.mdx
> +        <CodeBlock language="kotlin">
wondering if <CodeBlock> is a requirement here or can we continue to use the 3 ticks

2024-01-19 00:19 UTC, angiejones commented on site/src/components/language/LanguageSwitchHeader.jsx
I don't quite understand the need for this component. Will every guide need to use this? Ca it be included in the LanguageSwitcher component?

2024-01-19 00:22 UTC, angiejones commented on site/src/components/language/LanguageSwitcher.jsx
> +    console.log(`changing language to ${newLanguage}`);
```suggestion

```

2024-01-19 00:22 UTC, angiejones commented on site/src/components/language/LanguageContext.jsx
> +    console.log(`set language to ${newLanguage}`);
```suggestion

```

2024-01-19 00:22 UTC, angiejones commented on site/src/components/language/LanguageContext.jsx
> +      console.log(`updating url path lang with ${language}`);
```suggestion

```

2024-01-19 00:23 UTC, angiejones commented on site/src/components/language/LanguageSupport.jsx
> +    console.log(`Languages supported are ${languages}. Defaulting to ${languagesArray[0]}`);
```suggestion

```

2024-01-19 00:55 UTC, ALRubinger commented
> > @chris-tbd On our topic of "selecting the language", [Stripe has a cool approach](https://stripe.com/docs/expand/use-cases): Selecting a new language in the tab is a global selection, and all other code blocks change to the language selected. Means they don't need a separate language selector in the navbar (real estate IMO we should be protective of 🙂 ) WDYT?
> > ![image (1)](https://private-user-images.githubusercontent.com/199891/297900199-32a1c8c8-1617-4e68-a99a-cff86c7c5bc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTc5ODYsIm5iZiI6MTcwNTYxNzY4NiwicGF0aCI6Ii8xOTk4OTEvMjk3OTAwMTk5LTMyYTFjOGM4LTE2MTctNGU2OC1hOTlhLWNmZjg2YzdjNWJjNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOFQyMjQxMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzA1MGRjNDE5YTA5M2I0MmU2ZjkxMWU1OTU3MGJlOTJiNjEwZmJhYzkyNzI2YWNhMmRlNzk1MDY2MTY0YjBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uWT67EwZC7slC1re7VTKtqbbxW2ttigcjy3PuuVjMbo)
> 
> @ALRubinger Chris brought this up in the call and said that the content of the doc may change too dependeing on language (e.g. links to API Ref for more info)

Yup, and also the exceptional cases of "what if a language is selected globally but some blocks don't have that language implemented".

2024-01-19 00:59 UTC, angiejones commented on site/docs/hello-world.mdx
> +\n
just tried it locally and when i removed this, the page crashed. the need for the escape characters here and on lines 27, 37, 48, etc make this really clunky. Remember these will be executable code snippets run by our tests. We can't (and shouldn't need to) have these extra requirements in order to view code

2024-01-19 01:08 UTC, angiejones commented on site/docs/hello-world.mdx
> +\n
ok this works:

```html
    <div language="JavaScript">
        <p>Because sometimes you might want to write JavaScript code talking about credential creation:</p>
        <CodeSnippet functionName='deleteRecordFromDid'/>
    </div> 
```

this is more in line with how we'd use it. haven't tried for Kotlin since I don't think we have CodeSnippet support for that language yet

2024-01-19 15:36 UTC, dayhaysoos commented on site/src/components/language/LanguageSwitchHeader.jsx
The language switcher component is just the drop down (or possible tabs in the future) that handles the logic on what to present.

This component is needed to render the relative language based on the switcher logic. Every guide is going to need it.

2024-01-19 15:38 UTC, dayhaysoos reviewed
I don't have any feedback that wasn't already mentioned. Will let you respond to Angie and ALR before approval

2024-01-19 15:50 UTC, angiejones commented on site/src/components/language/LanguageSwitchHeader.jsx
I'm referring to the header

<LanguageSwitchHeader text="Language Switcher Hello World"/>

2024-01-19 16:30 UTC, chris-tbd commented on site/src/components/language/LanguageSwitchHeader.jsx
The intention behind the `LangaugeSwitchHeader` is that it's a replacement for our normal `h1` headers:

```
/// This is how we currently write the header/title to our docs, which will show an h1
# Key Management

/// This is how we'd write it going forward with this new class, which will automatically add the language
/// Switcher to the title instead of us having to add it to the navbar, which can be difficult in docusaurus.
<LanguageSwitchHeader text="Key Management"/>

2024-01-19 16:35 UTC, chris-tbd commented on site/docs/hello-world.mdx
> +        <CodeBlock language="kotlin">
`<CodeBlock>` is unfortunately a requirement here because of the way MDX and JSX are compiled into HTML - basically once we start writing MDX inside of a JSX component like `LanguageSwitchBlock`, we can revert back to JSX again. Ideally I'd like to have us write the snippets in separate files that have the appropriate extension (i.e. .js or .kt) and then we have a way to suck those into MDX and cleanly convert them to strings.

2024-01-19 17:29 UTC, chris-tbd commented on site/docs/hello-world.mdx
> +<LanguageSwitchBlock>
This is possible, although it adds a layer of complexity because now the tabs/dropdowns/any switching mechanism both observes and modifies the language state. It's not impossible by any means, just finicky. Across the board we don't seem to have consensus on exactly how language switching should work from a UI perspective, specifically where the switching affordance should go and how many there should be.

If you're okay with it I would like to start without having the tabs and then we can add those in as a follow-up, I was hoping to loop @ALRubinger in as well to see how we'd like to lay things out. I agree with him that going Stripe-style with one global switcher is ideal rather than on code snippets, because we are changing both code *and* text/links. Since more content is just changing than code I believe tab switcher is not as good as a top-level switcher.

2024-01-19 17:32 UTC, chris-tbd commented on site/docs/hello-world.mdx
> +\n
I spoke with @dayhaysoos and we outlined what our code snippets will look like once his new system is in place:

Snippets would live under site/__test__/kotlin/kotlin-sample-snippet.kt
That file could contain one or many kotlin code snippets, and each .kt file would contain all the snippets for a corresponding guide. We'd then add this import at the top of the `MDX` file:

`import kotlinSnippet from '!!raw-loader!@site/snippets/kotlin/hellow-world.snippet.kt'`

Then finally the `CodeSnippet` that I wrote onto this Hello World page would be replaced with the following, but still display the exact same snippet that would then be easily readable and formattable in the .kt file:

`<CodeSnippet snippet={kotlinSnippet} language="kotlin">`

2024-01-19 18:47 UTC, chris-tbd reviewed
Addressed comments

2024-01-19 20:15 UTC, angiejones commented on site/src/components/language/LanguageSwitchHeader.jsx
yes I'm asking can you take this away. It's a bit overkill just to write an H1 header. Seems the compnent is just adding some styling.  Can we add that to a stylesheet or to the related components?

2024-01-19 21:39 UTC, angiejones commented on site/docs/hello-world.mdx
> +<LanguageSwitchBlock>
why cant we just put a lang-specific class on the tab and dropdown elements and when something is selected, you make that class active on all Tabs and Dropdowns. would that work?

2024-01-22 19:56 UTC, chris-tbd commented on site/docs/hello-world.mdx
> +<LanguageSwitchBlock>
^ That would mean we're swizzling the Tabs component or rolling our own like we are in this PR. Swizzling forks us from main docusaurus development which poses some risks for updates breaking functionality but isn't out of the question.

2024-01-22 19:57 UTC, chris-tbd commented on site/src/components/language/LanguageSwitchHeader.jsx
Would it be okay to just remove this component and rely on code blocks for language switching then @angiejones

2024-01-26 00:07 UTC, EbonyLouis commented
@angiejones I started working off of my own branch when I moved to Chris' branch I ran into a state issue I'll debug tomorrow. On my branch I only needed to change this line in `languageContext.jsx`:
`const [language, setLanguage] = useState('js');` to get the snippets to render, but you'll see to get it to work I had to change the tabs to `js` instead of `JavaScript` as well. 

- I added the ability to hardcode within the Shnip component  
- To add the custom admonition we need to upgrade to v3.1 based on the docs, I'll test locally tomorrow to see if this v upgrade will break anything on the site if not implementing it will be straightforward.

2024-01-26 03:15 UTC, angiejones commented
> @angiejones I started working off of my own branch when I moved to Chris' branch I ran into a state issue I'll debug tomorrow. On my branch I only needed to change this line in `languageContext.jsx`: `const [language, setLanguage] = useState('js');` to get the snippets to render, but you'll see to get it to work I had to change the tabs to `js` instead of `JavaScript` as well.
> 
> * I added the ability to hardcode within the Shnip component
> * To add the custom admonition we need to upgrade to v3.1 based on the docs, I'll test locally tomorrow to see if this v upgrade will break anything on the site if not implementing it will be straightforward.

@EbonyLouis ok sounds like a lot of work. If it looks like something that will take more than a day or 2, let's go with the <Shnip> component you came up with

2024-01-26 20:49 UTC, EbonyLouis commented
1. This is the[ test file](https://deploy-preview-1144--tbd-website-developer.netlify.app/docs/web5/build/verifiable-credentials/testing?lang=JavaScript) that is utilizing the new `Shnip` component. Changing versions caused a lot of errors, this is something I can work through but I don't think we should let it hold us up. 
2. Passed on the last issue to Chris to get a new pair of eyes on it I feel like its a super simple fix that I'm overlooking.

2024-01-28 08:27 UTC, angiejones commented
updated issue description with latest info

2024-01-30 20:06 UTC, EbonyLouis commented
@angiejones all set

2024-01-30 23:51 UTC, angiejones approved these changes

2024-01-30 23:51 UTC, merged