initial guide; code snippets and tests need to be added
TBD54566975/developer.tbd.website pull request #1149
Opened 2024-01-12 04:10 UTC by blackgirlbytes

Nick is changing the code snippets system, so I didn't write tests or the code snippets yet. Will do in the morning. Opening PR for a review if anyone ends having time ..that way I can merge the changes and tests and code snippets tomorrow.

2024-01-12 04:10 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +The KMS field stands for Key Management Store. It acts as a password manager for cryptographic keys. If you don't specify a particular key management service, such as AWS Key Management Service or Go
I seen a PR for KMS, once merged..I can link it here

2024-01-12 04:11 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/_category_.json
> +  "position": 4
should this be it's own section or under DWNs?

2024-01-12 04:11 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +await agent.start({ passphrase: 'insecure-static-phrase' });
this is hardcoded into the web5.ts source code. other passphrases don't work with it lol

2024-01-12 04:13 UTC, angiejones commented on site/docs/web5/build/Agent/_category_.json
> +  "position": 4
DWNs

2024-01-12 04:15 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +# Create an identity agent
```suggestion
# Using Identity Agents
```

2024-01-12 04:16 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/_category_.json
> +  "position": 4
okay done

2024-01-12 04:23 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +Identity agents manage [Decentralized Identifiers (DIDs)](https://developer.tbd.website/docs/web5/learn/decentralized-identifiers), data, and communication between [Decentralized Web Nodes (DWNs)](ht
```suggestion
Identity agents manage [DIDs](https://developer.tbd.website/docs/web5/learn/decentralized-identifiers), data, and communication between [DWNs](https://developer.tbd.website/docs/web5/learn/decentralized-web-nodes). 

For convenience, the `Web5.connect()` function uses a default identity agent. However, Web5 also provides the ability for users to utilize their own custom agent. 

This guide provides an overview of how to create an identity agent, import a DID into the agent, and connect the agent to a Web5 app.
```

2024-01-12 04:26 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +This guide focuses on utilizing `DidIonMethod` and `DidKeyMethod` for setting up an identity agent. Currently, DID methods like the `DidDhtMethod` are not supported in this context.
gasp regarding did:dht. i want to share this info but also i cant help but think we'll forget to come in this collapsed section and update this when it's no longer the case. any ideas on how to track this? is there an issue that you know of for adding support for did:dht?

2024-01-12 04:29 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +Create an instance of the Web5 User Agent to begin your identity agent setup.
```suggestion
Create an instance of `Web5UserAgent` to begin setting up the Identity Agent
```

2024-01-12 04:29 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +await agent.start({ passphrase: 'insecure-static-phrase' });
😭

2024-01-12 04:30 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +await agent.start({ passphrase: 'insecure-static-phrase' });
@frankhinek is this the intent?

if so, Rizel please put a note in here saying it can't be changed.

2024-01-12 04:34 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +Generating a portable DID document requires the following steps
```suggestion
If you'd like to associate DWNs with a DID, you can do so. In the following example, we'll use the TBD-hosted DWN endpoints:
```

2024-01-12 04:35 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +const serviceEndpointNodes = await getTechPreviewDwnEndpoints();
```suggestion
// selects DWN endpoints that are provided by default during the Web5 tech preview period
const serviceEndpointNodes = await getTechPreviewDwnEndpoints();
```

2024-01-12 04:35 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +const didOptions = await DidIonMethod.generateDwnOptions({ serviceEndpointNodes });
```suggestion

// generates key pairs used for authorization and encryption when interfacing with DWNs
const didOptions = await DidIonMethod.generateDwnOptions({ serviceEndpointNodes });
```

2024-01-12 04:37 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +const portableDid = await DidIonMethod.create(didOptions);
```suggestion

// creates a new DID and its associated data
const portableDid = await DidIonMethod.create(didOptions);
```

2024-01-12 04:37 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +- **getTechPreviewDwnEndpoints()** - selects up to 2 DWN endpoints that are provided by default during the Tech Preview period.
```suggestion
```

2024-01-12 04:37 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +- **getTechPreviewDwnEndpoints()** - selects up to 2 DWN endpoints that are provided by default during the Tech Preview period.
moved these to be inline comments

2024-01-12 04:38 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> + * **DidIonMethod.generateDwnOptions({ serviceEndpointNodes })** - generates two key pairs used for authorization and encryption purposes when interfacing with DWNs. The IDs of these keys are referen
```suggestion
```

2024-01-12 04:38 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> + * **DidIonMethod.create(didOptions)** - creates the DID document with the given options
```suggestion
```

2024-01-12 04:40 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +## Import your portable DID
```suggestion
## Import DID
```

2024-01-12 04:41 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +## Import your portable DID
don't use the phrase "your DID" as most people who are building with Web5 are working with users' DIDs, not their own

2024-01-12 04:41 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +Importing your portable DID, gives the identity agent permission to manage data on your behalf. This step links your agent you your unique decentralized identifier (DID).
```suggestion
Importing a DID gives the Identity Agent permission to manage data on the DID holder's behalf.
```

2024-01-12 04:46 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +The KMS field stands for Key Management Store. It acts as a password manager for cryptographic keys. If you don't specify a particular key management service, such as AWS Key Management Service or Go
```suggestion
The `kms` field stands for Key Management Service and can securely store and manage the cryptographic keys associated with a DID. If you don't specify a particular key management service, such as AWS Key Management Service or Google Cloud Key Management, Web5 will default to an in-memory key manager.
```

2024-01-12 04:47 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +Now, you can take portable DID and your identity agent to connect to Web5 and return an instance of Web5.
```suggestion
To use a custom Identity Agent with Web5, pass the DID and the agent into `Web5.connect()`:
```

2024-01-12 04:48 UTC, angiejones commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +## Interact with the Web5 API
you can delete this section

2024-01-12 12:42 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +## Import your portable DID
ohhh true okay!

2024-01-12 12:45 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +This guide focuses on utilizing `DidIonMethod` and `DidKeyMethod` for setting up an identity agent. Currently, DID methods like the `DidDhtMethod` are not supported in this context.
I think this issue will add service endpoints to did dht and then we should be able to use it. https://github.com/TBD54566975/web5-js/issues/368

2024-01-12 12:48 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +await agent.start({ passphrase: 'insecure-static-phrase' });
Reference: https://github.com/TBD54566975/web5-js/blob/44c38a116dec0b357ca15d807eb513f819341e50/packages/api/src/web5.ts#L116-L121

2024-01-12 17:16 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +This guide focuses on utilizing `DidIonMethod` and `DidKeyMethod` for setting up an identity agent. Currently, DID methods like the `DidDhtMethod` are not supported in this context.
```suggestion
This guide focuses on utilizing `DidIonMethod` and `DidKeyMethod` for setting up an identity agent. Currently,  `DidDhtMethod` is not supported in this context.
```

2024-01-12 17:18 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +For security purposes, the identity agent prompts the end user to enter a secure passphrase when it initially launches. In this example, `insecure-static-phrase` is used as a placeholder.
```suggestion
For security purposes, the identity agent prompts the end user to enter a secure passphrase when it initially launches. For now, `insecure-static-phrase` must be used.
```

2024-01-12 17:19 UTC, angiejones approved these changes
couple of small change requests, but looks good overall

2024-01-12 17:45 UTC, frankhinek commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +await agent.start({ passphrase: 'insecure-static-phrase' });
No, not at all.  The intent is to NOT use the default passphrase.  The only reason it is there is to make it easy to get started in the first 5 minutes.  A developer should always prompt the user to select their own passphrase.

In fact going forward, a warning will be logged in the event the user isn't prompted to select their own passphrase.

2024-01-12 18:42 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +await agent.start({ passphrase: 'insecure-static-phrase' });
oh so they can use whatever passphrase they want? Because I tried out different ones and I got an error.  Like I tried out this
```js
await userAgent.start({ passphrase: 'my-static-passphrase' });
```

and I got a "Wrong tag" error 

@frankhinek

2024-01-12 19:07 UTC, blackgirlbytes commented on site/docs/web5/build/Agent/how-to-create-identity-agent.mdx
> +await agent.start({ passphrase: 'insecure-static-phrase' });
NEVER MIND I FIGURED IT OUT. I had to clear my cache because the data I had was encrypted with the old passphrase. I will update this and remove my note about them having to use that passphrase. Thank you!!!

2024-01-12 20:32 UTC, frankhinek commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +Identity [agents](http://localhost:3000/docs/web5/learn/agents) manage [DIDs](https://developer.tbd.website/docs/web5/learn/decentralized-identifiers), data, and communication between [DWNs](https://
```suggestion
Identity [agents](https://developer.tbd.website/docs/web5/learn/agents/) manage [DIDs](https://developer.tbd.website/docs/web5/learn/decentralized-identifiers), data, and communication between [DWNs](https://developer.tbd.website/docs/web5/learn/decentralized-web-nodes). 
```

2024-01-12 20:39 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +Identity [agents](http://localhost:3000/docs/web5/learn/agents) manage [DIDs](https://developer.tbd.website/docs/web5/learn/decentralized-identifiers), data, and communication between [DWNs](https://
oop thank you!

2024-01-12 20:46 UTC, frankhinek commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +For convenience, the `Web5.connect()` function uses a default identity agent. However, Web5 also provides the ability for users to utilize their own custom agent.
I would also suggest highlighting something like:

Identity Agents are a specialized kind of agent that are primarily designed to enable people to manage multiple  decentralized identities and to make it easy to use your existing identities across multiple web apps.

When calling `Web5.connect()`, rather than creating a local User Agent and a new decentralized identity, with an Identity Agent you can connect the web app to an existing identity.

2024-01-12 20:50 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +For convenience, the `Web5.connect()` function uses a default identity agent. However, Web5 also provides the ability for users to utilize their own custom agent.
okay, will add!

2024-01-13 01:09 UTC, blackgirlbytes commented
@angiejones I actually chatted with @frankhinek and he prefers I show the identity agent wrapper. We talked about how he wanted it shown, so I made changes based on that. I still have more to test. But I tested two so far

2024-01-13 01:11 UTC, blackgirlbytes commented on site/__tests__/web5/build/decentralized-web-nodes/use-identity-agents.test.js
> +    //     const socialMediaIdentity = await createSocialMediaIdentity(agent);
calling the Identity Agent times out, so maybe I need to mock it.

2024-01-13 01:11 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +
added these lines based on Frank's feedback

2024-01-13 01:12 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +While the `Web5.connect()` function creates a local User Agent and a **new** identity, Identity Agents allow you to connect a web app to an **existing** identity.
added these lines based on Frank's feedback

2024-01-13 04:14 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/use-identity-agents.js
> +export async function createDidOptions({ serviceEndpointNodes }) {
how come this and `getDwnEndpoints()` are separate snippets instead of just one snippet? Shouldn't probably spare the developer from having to copy two separate code blocks

2024-01-13 04:16 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +<summary>Expected Output</summary>
output of what? maybe rename this to make it clear this is what's stored in `didOptions`

2024-01-13 04:17 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +Now that `didOptions` contains cryptographic key pairs and service endpoints, you can create as many identities as necessary. Each identity, linked to a unique DID, represents and compartmentalizes d
cool!

2024-01-14 05:38 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +For security purposes, the identity agent prompts the end user to enter a secure passphrase when it initially launches.
does this mean, the developer's app should prompt the user for a passphrase?

2024-01-14 05:44 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/use-identity-agents.js
> +export async function createDidOptions({ serviceEndpointNodes }) {
yeah this led to an error because the variable names aren't the same across the separate snippets. the developer ends up with:

```js
const endpoints = await getTechPreviewDwnEndpoints();
const didOptions = await DidIonMethod.generateDwnOptions({ serviceEndpointNodes });
```

where `serviceEndpointNodes` should be `endpoints`

2024-01-14 05:53 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
it's still not clear how to i reuse my agent outside of this program

2024-01-14 06:08 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/use-identity-agents.js
> +    const auth = await agent.start({ passphrase: 'default-passphrase' });
this returns `void`. no need to assign to a variable. I don't want us to provide unneccessary code to devs just so our tests pass. dev experience comes first.

for testing purposes, you can `return agent.agentDid` and make sure it's a did

```js
export async function authenticateIdentityAgent(agent) {
     await agent.start({ passphrase: 'default-passphrase' });
     return agent.agentDid;
}
```

2024-01-15 15:47 UTC, blackgirlbytes commented on site/code-snippets/web5/build/decentralized-web-nodes/use-identity-agents.js
> +export async function createDidOptions({ serviceEndpointNodes }) {
yes, I know. I intended to change it to the below..I just had quick committed some changes before I went out yesterday :
```js
const serviceEndpointNodes = await getTechPreviewDwnEndpoints(); 
const didOptions = await DidIonMethod.generateDwnOptions({ serviceEndpointNodes });
```

2024-01-15 21:29 UTC, acekyd approved these changes

2024-01-15 23:12 UTC, angiejones requested changes
more changes coming on tests etc

2024-01-15 23:13 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/use-identity-agents.js
> +export async function createDidOptions({ serviceEndpointNodes }) {
oh ok. will put this in draft since you're still working on it ❤️

2024-01-16 14:57 UTC, blackgirlbytes commented
I can't figure out how to fix the timing issues between the agent and Web5 when it comes to the tests.

2024-01-16 15:46 UTC, blackgirlbytes commented on site/code-snippets/web5/build/decentralized-web-nodes/use-identity-agents.js
> +    const auth = await agent.start({ passphrase: 'default-passphrase' });
thanks!

2024-01-16 21:11 UTC, blackgirlbytes commented
Tomorrow morning Nick and I are going to set up a conditional test suite to not run web5 if we're testing the identity agent

2024-01-16 21:59 UTC, frankhinek commented on package.json
> +    "@web5/identity-agent": "^0.2.5",
Probably a good idea to pin the version.  Since we're still pre-1.0, minor version releases from `0.2.6` onward might have changed that need some edits before supporting.

2024-01-16 21:59 UTC, frankhinek commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time an end user launches an application that uses an Identity Agent, they'll need to authenticate with a one-time passphrase for security purposes.
The front-end of the identity agent app.

In other words, the app IS the identity agent.   It isn't "connecting" to anything -- the point of an identity app is to manage identities and that's what the `IdentityAgent` implementation was built for.  An example would be the mobile Identity App that Tim is building but you could also have a desktop electron identity app.  Since this is an example, it would be a browser based version.

2024-01-16 21:59 UTC, frankhinek commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
The program would be an identity management app so you would interact with the agent through some front end app that is party of the identity management app.

2024-01-16 22:24 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time an end user launches an application that uses an Identity Agent, they'll need to authenticate with a one-time passphrase for security purposes.
so the identity agent creation and the web5 connection shouldn't be shown in the same program. these are 2 different apps.

i think we're missing the glue piece. if I'm a web5 app developer, what do i do to engage with an identity app such that I can then pass it into `connect()`?

2024-01-17 01:56 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time an end user launches an application that uses an Identity Agent, they'll need to authenticate with a one-time passphrase for security purposes.
Thanks for the clarification, Frank!

+1 to Angie's question. For me, I understand that the Identity Agent's purpose is to manage identities. 

But after I wrote the initial draft I did start (over)thinking because I want to provide clarity to our community..and I think I went off course. The question for me is: A Web5 app needs to obtain identity information from the identity agent to interact with the user's decentralized identity. How does it do that?

Here's my understanding of the workflow based on this conversation: 
1. The user opens the identity agent app (which could be a mobile app, a desktop application, or a browser-based application).
2. The **identity agent** prompts the user to authenticate, by entering a passphrase or biometric auth or whatever. (It says at first launch. Does this mean the first time the user ever uses the identity agent?)
3.  Once authenticated, the user can view, manage, or create new identities (social, professional, or whatever)
4. User finds a Web5 app that they want to use
5. The Web5 app says..give me your DID so you can start using it
6. User says okay I want to use my social Identity so I'm going to paste in the DID associated with my social identity into this Web5 app. (I think maybe what I was imagining was their would be some code or an automated process within our identity agent, so that we could integrate the Web5 app with the identity agent and you won't have copy and paste your did into the Web5 app..and maybe this is the glue that Angie is looking for)
7. Then the Web5 app, takes your the DID that your provided and connects to the Web5 ecosystem.

Thoughts? @frankhinek

2024-01-17 05:13 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time an end user launches an application that uses an Identity Agent, they'll need to authenticate with a one-time passphrase for security purposes.
This is from August, not sure if it's still 100% accurate, but may help with some details
https://hackmd.io/@frankhinek/ryge2ayh3

2024-01-17 14:24 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time an end user launches an application that uses an Identity Agent, they'll need to authenticate with a one-time passphrase for security purposes.
Thank you! Yes, that helped with my question about first launch.

But I still want to be able to answer this question you had " if I'm a web5 app developer, what do i do to engage with an identity app such that I can then pass it into connect()". 

Because for right now, all I know is that the end user can take the DID from the identity agent and copy/paste it into the Web5 app.

2024-01-17 22:26 UTC, frankhinek commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time an end user launches an application that uses an Identity Agent, they'll need to authenticate with a one-time passphrase for security purposes.
Hey @blackgirlbytes -- sent a number of files over to see if any address the question adequately.

Once we figure out if any of that info helps, we can post / revise here 😄

2024-01-17 23:05 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time an end user launches an application that uses an Identity Agent, they'll need to authenticate with a one-time passphrase for security purposes.
Thank you! Read the items and talked to frank on the phone. 

Web5 app has a QR code section that says connect to Identity agent — you take your identity agent and you scan that QR code and then the identity agent adds that profile/identity to the app.

Or could be a deep link and you might type in something to add your identity.

Going to take my final pass at the documentation. 

![image](https://github.com/TBD54566975/developer.tbd.website/assets/22990146/442d75d8-dd31-46b1-bb09-0c6000825e05)

2024-01-19 05:02 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +The first time you launch an Identity Agent, you will be prompted to authenticate with a one-time passphrase for security purposes.
this is confusing since this doesn't happen with any of the code we're showing. Should we tell them they should build that into their identity agent app code?

2024-01-19 05:03 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +## Doesn't Web5.connect() create a DID for me?
nit: consider making this a regular sentence vs a header. it seems a bit out of place looking at it with the other headers

2024-01-19 05:05 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
I think we should clearly specify that this is a separate application and not in the same program where you call `Web5.connect()`

2024-01-19 05:06 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +## Connect User DIDs to DWNs
```suggestion
## Connect DIDs to DWNs
```

2024-01-19 05:06 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/use-identity-agents.js
> +// generates key pairs used for authorization and encryption when interfacing with DWNs
```suggestion

// generates key pairs used for authorization and encryption when interfacing with DWNs
```

added a blank line for readability

2024-01-19 05:11 UTC, angiejones requested changes

2024-01-19 05:11 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +* The `kms` field stands for Key Management Service and can securely store and manage the cryptographic keys associated with a DID. If you don't specify a particular key management service, such as A
```suggestion
* The `kms` field stands for [Key Management Service](/docs/web5/build/decentralized-identifiers/key-management) and can securely store and manage the cryptographic keys associated with a DID. If you don't specify a particular key management service, such as AWS Key Management Service, Web5 will default to an in-memory key manager.
```

I dont think Google's is supported

2024-01-19 05:11 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
I see you state it later on. Up to you if you think we should call it out early in the guide as well

2024-01-19 06:15 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
okay, just added some more clarity the line in the beginning to show that they are separate apps: `This guide will walk you through creating an Identity Agent as a standalone application to manage multiple user identities and connect to a separate Web5 application.`

2024-01-19 19:38 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +While the `Web5.connect()` function generates a **new** identity and a local User Agent, Identity Agents allow you to connect a web app to an **existing** identity. This is useful for maintaining a c
```suggestion
By default, the `Web5.connect()` function generates a **new** identity; however, Identity Agents allow you to connect to a Web5 app with an **existing** identity. This is useful for maintaining a cohesive online presence. 
```

2024-01-19 19:44 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +```js
can you add this as a code snippet vs hard-coding? Can skip adding tests if this poses a problem with our current setup

2024-01-19 20:14 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/using-identity-agents.mdx
> +```js
done! :)

2024-01-19 20:19 UTC, angiejones approved these changes

2024-01-19 20:48 UTC, merged