Bluehawk integration
TBD54566975/developer.tbd.website pull request #1156
Opened 2024-01-19 20:56 UTC by dayhaysoos

This PR introduces the new CodeSnippet System. Work in progress.

TODO:

- [ ] README for new system
- [ ] Manual testing
- [ ] Remove unnecessary files/edits

2024-01-23 15:56 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +<CodeSnippet snippet={kotlinTest} language="kotlin" />
I get real nervous when y'all start playing in these real guides 😫

2024-01-23 16:02 UTC, dayhaysoos commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +<CodeSnippet snippet={kotlinTest} language="kotlin" />
oh my bad lemme remove this lol

2024-01-24 02:16 UTC, angiejones approved these changes

2024-01-24 16:37 UTC, blackgirlbytes commented
this was a good experience for me..so I agree that this should be merged

2024-01-24 19:40 UTC, angiejones commented on bh-test/how-to-create-did.test.snippet.createDidDht.js
whats this new folder?

2024-01-24 19:41 UTC, angiejones requested changes

2024-01-24 19:41 UTC, angiejones commented on site/__tests__/kotlin/test-example.kt
seems this file was for testing purposes. can we remove now?

2024-01-24 19:43 UTC, angiejones commented on site/snippets/web5/build/decentralized-identifiers/createDidIon.snippet.js
question: does every snippet need its own file?

2024-01-25 15:57 UTC, dayhaysoos commented on site/snippets/web5/build/decentralized-identifiers/createDidIon.snippet.js
@angiejones Yes, all snippets that will be tested will have their own files.

If you need snippets that aren't going to be tested then you could make them directly in the MDX files themselves

2024-01-25 16:29 UTC, dayhaysoos commented on site/snippets/kotlin/kotlin-test.snippet.kt
deleted

2024-01-25 17:15 UTC, angiejones commented on site/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
> +    const didDht = await DidDhtMethod.create({ publish: true });
Nick, one last question. Is there a way to respect indention for the snippets. The first line isn't indented when displayed, which makes the code look janky

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/e5a679fe-9db2-45fc-b3eb-e5400273e607)

2024-01-25 17:32 UTC, dayhaysoos commented on site/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
> +    const didDht = await DidDhtMethod.create({ publish: true });
Gonna look into this

2024-01-25 18:22 UTC, leordev commented on CONTRIBUTING.md
> +Setting Up Your Environment
I think it was supposed to be a title, plus it needs some line breaks? otherwise its printing as one phrase (click preview markdown)

![image](https://github.com/TBD54566975/developer.tbd.website/assets/6147142/ddc825ad-fcba-4332-ad43-05e87d4ebce7)

2024-01-25 18:24 UTC, leordev commented on CONTRIBUTING.md
> +After creating your snippets, run the command pnpm run shnip. This will generate a folder called snippets and create a directory structure similar to where the file is.
```suggestion
After creating your snippets, run the command `pnpm run shnip`. This will generate a folder called snippets and create a directory structure similar to where the file is.
```

2024-01-25 18:27 UTC, leordev commented on extract-snippets.js
> +  const snippetEndTag = ':snippet-end:';
This is hardcoded whereas the `snippet.config.json` suggests having a `snippetTags` dynamic values. Will it work if we setup a different tag in the config?

2024-01-25 18:27 UTC, angiejones approved these changes

2024-01-25 18:28 UTC, leordev commented on extract-snippets.js
> +      console.log('Snippet start tag not followed by newline. Skipping...');
It would be nice if you could print the entire line + the location (fileName, file Line num and column), so that the developer can see where it happened and fix it.

2024-01-25 18:29 UTC, leordev commented on extract-snippets.js
> +      console.log('No closing tag found for a snippet. Skipping...');
Same as above!

2024-01-25 18:34 UTC, leordev commented on shnippet/src/index.js
> +module.exports = SnippetExtractor;
oh... I guess I was reviewing a not relevant file (`extract-snippets.js`), can you please remove it from the PR if I'm correct about that file not being relevant anymore? (And my console points apply here, except for the tags which you are getting from the config already!)

2024-01-25 18:45 UTC, leordev approved these changes
Great addition!👏 👏  Eager to see snippets with new langs! <3

2024-01-25 18:49 UTC, dayhaysoos commented on extract-snippets.js
> +  const snippetEndTag = ':snippet-end:';
I haven't tested, I have a feeling it won't work. Let me try to address that

2024-01-25 19:03 UTC, merged