code snippet for parsing jwt in kotlin
TBD54566975/developer.tbd.website pull request #1162
Opened 2024-01-24 21:55 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds code snippets for parsing a JWT in Kotlin. Small PR to keep moving forward. Have after work events today.

## Related Tickets & Documents

https://app.asana.com/0/1205524815434802/1206268818053068

2024-01-25 07:37 UTC, angiejones requested changes

2024-01-25 07:37 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/jwt-to-vc.mdx
>  This returns the VC in JSON:
in Kotlin, it returns `VerifiableCredential`. Maybe change this to "This returns the VC object:" and use tabs to show the Kotlin object. I think it would be this, but double check:

```kt
VeriableCredential(
  vcDataModel=VcDataModel(
    context=[
      'https://www.w3.org/2018/credentials/v1'
    ],
    type=[
      'VerifiableCredential', 
      'EmploymentCredential'
    ],
    id='urn:uuid:8fd52030-1caf-4978-a35d-d417eb8e00b2',
    issuer='did:dht:kfdtbcm9zgocf5matf9fxtnnffhhzxc7mgbwr4k3x3qziaucpp4y',
    issuanceDate='2023-12-21T17:02:01Z',
    credentialSubject=CredentialSubject(
      id='did:dht:y39m48ozoete7z6fzaangcos87fhuh1dzi7f7jwbjft7otskh9to',
      position='Software Developer',
      startDate='2021-04-01T12:34:56Z',
      employmentStatus='Contractor'
    ),
    expirationDate='2022-09-30T12:34:56Z'
  )
)
```

2024-01-25 10:13 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/jwt-to-vc.mdx
>  This returns the VC in JSON:
oh thanks for noticing! I didn't even realize the difference because they looked so similar. When I print out the VC results in Kotlin, it doesn't show the vcDataModel property. It just starts at credential. I'll update the issue a VC page to match the results here too.  


Parsed VC Kotlin
```kotlin
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ],
  "type": [
    "VerifiableCredential",
    "EmploymentCredential"
  ],
  "id": "urn:uuid:258a185e-2e1c-499c-9b41-ca64be1c23ac",
  "issuer": "did:key:zQ3shkqfLFSLADFhdAA7E1EwibEBrBBeKGbx2oQwRpbQ2yQ81",
  "issuanceDate": "2024-01-25T09:48:22Z",
  "credentialSubject": {
    "id": "did:key:zQ3shvKAJGqcysHE4dXuYjgHsNsWaGYbzmA4eusFBNLbLhavw",
    "position": "Software Developer",
    "startDate": "2023-04-01T12:34:56Z",
    "employmentStatus": "Contractor"
  }
}
```

Create a VC kotlin
```kotlin
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1"
  ],
  "type": [
    "VerifiableCredential",
    "EmploymentCredential"
  ],
  "id": "urn:uuid:b8d773c0-857e-4c77-bb8b-226bd9fa6791",
  "issuer": "did:key:zQ3shjTTCnygcaVAxQnsn3QjTEgB1t4zW6pVuL2U2RUTNpHgQ",
  "issuanceDate": "2024-01-25T09:54:54Z",
  "credentialSubject": {
    "id": "did:key:zQ3shUhAbWxFd2CVLCM6VHxcfLujdiDVtDDCoES7G2xBWxKyp",
    "position": "Software Developer",
    "startDate": "2023-04-01T12:34:56Z",
    "employmentStatus": "Contractor"
  }
}
```

Parsed VC Javascript
```js
{
  vcDataModel: {
    '@context': [ 'https://www.w3.org/2018/credentials/v1' ],
    type: [ 'VerifiableCredential', 'EmploymentCredential' ],
    id: 'urn:uuid:8fd52030-1caf-4978-a35d-d417eb8e00b2',
    issuer: 'did:dht:kfdtbcm9zgocf5matf9fxtnnffhhzxc7mgbwr4k3x3qziaucpp4y',
    issuanceDate: '2023-12-21T17:02:01Z',
    credentialSubject: {
      id: 'did:dht:y39m48ozoete7z6fzaangcos87fhuh1dzi7f7jwbjft7otskh9to',
      position: 'Software Developer',
      startDate: '2021-04-01T12:34:56Z',
      employmentStatus: 'Contractor'
    },
    expirationDate: '2022-09-30T12:34:56Z'
  }
}
```

Create VC JavaScript
```js
{
  "vcDataModel": {
    "@context": [
      "https://www.w3.org/2018/credentials/v1"
    ],
    "type": [
      "VerifiableCredential",
      "EmploymentCredential"
    ],
    "id": "urn:uuid:84953246-a77f-4c5a-a336-69a55bd92989",
    "issuer": "did:dht:fhzeks5bkferfztk6m63xjkg7a4hbf7snk444g8f1h1xapt391ty",
    "issuanceDate": "2023-03-31T06:08:49Z",
    "credentialSubject": {
      "id": "did:dht:usnoybts46xnei6brftkixe5qsbypxcye4th397bs4tyouqouyho",
      "position": "Software Developer",
      "startDate": "2023-04-01T12:34:56Z",
      "employmentStatus": "Contractor"
    },
    "expirationDate": "2023-09-30T12:34:56Z"
  }
}
```

2024-01-25 14:06 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/jwt-to-vc.mdx
>  This returns the VC in JSON:
this is the same isn't it? lol

2024-01-26 14:08 UTC, acekyd approved these changes
Approved - following Angie's comments

2024-01-26 15:39 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/jwt-to-vc.mdx
>  This returns the VC in JSON:
yea, I think the only difference is it doesn't show the property vcDataModel for Kotlin. You think I should still show the diff output for Kotlin vs JS?

2024-01-28 21:41 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/vc-issuance.mdx
> +    "issuer": "did:key:zQ3shjTTCnygcaVAxQnsn3QjTEgB1t4zW6pVuL2U2RUTNpHgQ",
okay, done. 

I could be overthinking, but the create VC in kotlin now matches the JWT in Kotlin and the JWT in JS. BUT the create VC has different values because the values aren't hardcoded.

2024-01-28 22:42 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/jwt-to-vc.mdx
> +  ```kotlin
```suggestion
  ```js
```

I know technically this is a Kotlin object, but it's really a JSON representation of such. Changing to 'js' just so that it's easier to read on the site (keys white, values pink)

2024-01-28 22:42 UTC, angiejones approved these changes

2024-01-28 22:53 UTC, merged

2024-01-29 01:30 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/jwt-to-vc.mdx
> +  ```kotlin
oh true true