VC workflow with Kotlin Code snippets (WIP)
TBD54566975/developer.tbd.website pull request #1173
Opened 2024-01-29 23:58 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds code snippets for VC workflow.

Going out, but I'll be back. Put on pause because validateDefinition doesn't work even though people say it does. I'm thinking the update hasn't been released yet. And also, encountering errors with the below. Will figure it out when I'm back

```kotlin
    val presentationDefinition = PresentationDefinitionV2(
        id = "presDefId123",
        name = "Swifties Fan Club Presentation Definition",
        purpose = "for proving membership in the fan club",
        inputDescriptors = listOf(
            InputDescriptorV2(
                id = "legitness",
                purpose = "are you legit or not?",
                constraints = ConstraintsV2(
                    fields = listOf(
                        FieldV2(
                            path = listOf("$.credentialSubject.legit")
                        )
                    )
                )
            )
        )
    )

    try {
        PresentationExchange.satisfiesPresentationDefinition(listOf(signedVcJwt), presentationDefinition)
        println("\nVC Satisfies Presentation Definition!\n")
    } catch (e: Exception) {
        println("VC does not satisfy Presentation Definition: ${e.message}")
    }
    ```

2024-01-30 15:16 UTC, blackgirlbytes commented
> @blackgirlbytes let me know the error you're getting with the validation. I ran into some problems early on too. wondering if yours is the same

@angiejones I'm getting the error below. I could be completely wrong, so if you have a different issue let me know..but I think validateDefinition is something that Neal added to web5-kt AFTER the most recent release of the SDK. The version I have (which I think is the most recent release) only does satisifiesPresentation from what I read in the source code.Maybe we can make a ticket to update the guides after they do the release.
<img width="686" alt="Screenshot 2024-01-30 at 10 13 07 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/ca7605db-04be-4aaa-a0e2-33b700448188">

2024-01-30 15:21 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +println("Presentation Result: ${presentationResult}")
i dont know how to get the result of the presentation. The JS results are already there, but wasn't sure if the Kotlin results look different or if I even needed to. When I print out the results, I get this `web5.sdk.credentials.model.PresentationSubmission@2b8bb184`

and then I found that Im able to print out line by line like this

```kt
    val presentationResult = PresentationExchange.createPresentationFromCredentials(listOf(signedSimpleVcJwt), presentationDefinition)
   println(presentationResult)
    println(" - Id: ${presentationResult.id}")
    ```
    
    Another possible option I found is this
    
    ```kt
    import com.fasterxml.jackson.databind.ObjectMapper
    
            val presentationResult = PresentationExchange.createPresentationFromCredentials(listOf(signedSimpleVcJwt), presentationDefinition)
        println("Presentation result below")
        val objectMapper = ObjectMapper()
        val presentationJson = objectMapper.writeValueAsString(presentationResult)
        println(presentationJson)
        ```
        
        And that prints out the following
        ```json
        {"id":"bad616a0-ff29-4027-a0fe-5e9b07a8525b","definitionId":"presDefId123","descriptorMap":[{"id":"legitness","format":"jwt_vc","path":"$.verifiableCredential[0]"}]}
        ```
        
        I don't know what's the best option or if I should just leave it

2024-01-30 15:24 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +```
This version of the SDK does not have a validateDefinition method from my research. After they're next release, Neal's changes which include validateDefinition should be there. He added that code to the SDK weeks ago, which is why I think most of the engineers believe it exists, but that version of code doesn't seem to be released

2024-01-30 18:34 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +println("Presentation Result: ${presentationResult}")
I learned that in order to get the entire presentationResult in Kotlin, I need to use VerifiablePresentation. however, I don't see this value in my version of the SDK. They say it's also coming to JS. I think maybe we can make an issue to follow up with this doc once that's made available 

See context: https://sq-tbd.slack.com/archives/C02KATKPLRY/p1706636685905689?thread_ts=1706636326.768709&cid=C02KATKPLRY

2024-01-30 23:04 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +println("Presentation Result: ${presentationResult}")
try [toString()](https://tbd54566975.github.io/web5-kt/docs/htmlMultiModule/credentials/web5.sdk.credentials/-verifiable-credential/to-string.html)

2024-01-30 23:10 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +  mavenCentral()
The 2 dependencies below come from this repository. Can you try commenting out lines 36-38 to see if those are needed

2024-01-31 04:53 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +  maven("https://repository.jboss.org/nexus/content/repositories/thirdparty-releases/")
Can you try commenting out line 38 to see if that dependency is needed. I have no idea which dependency we're getting from here

2024-01-31 04:58 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +val fanClubIssuerDid = fanClubIssuerDidObject.resolve()
how come you need to resolve?

2024-01-31 04:58 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +    // indicates if the fan is a genuine Swiftie
```suggestion

    // indicates if the fan is a genuine Swiftie
```

2024-01-31 05:01 UTC, angiejones requested changes

2024-01-31 05:01 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +val fanClubIssuerDid = fanClubIssuerDidObject.resolve()
ah you're trying to get to the did string. it's been updated to `did.uri`

```suggestion

```

2024-01-31 05:02 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +val fanClubIssuerDidObject = DidKey.create(InMemoryKeyManager())
```suggestion
val fanClubIssuerDid = DidKey.create(InMemoryKeyManager())
```

2024-01-31 05:02 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +val aliceDid = aliceDidObject.resolve()
```suggestion

```

2024-01-31 05:02 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +val aliceDidObject = DidKey.create(InMemoryKeyManager())
```suggestion
val aliceDid = DidKey.create(InMemoryKeyManager())
```

2024-01-31 05:03 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +    issuer = fanClubIssuerDid.didDocument.id.toString(),
```suggestion
    issuer = fanClubIssuerDid.uri,
```

2024-01-31 05:03 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +    subject = aliceDid.didDocument.id.toString(),
```suggestion
    subject = aliceDid.uri,
```

2024-01-31 05:06 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +val signedVcJwt = vc.sign(fanClubIssuerDidObject)
```suggestion
val signedVcJwt = vc.sign(fanClubIssuerDid)
```

2024-01-31 05:11 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +val presentationDefinition = PresentationDefinitionV2(
@nitro-neal this feels pretty clunky from a developer experience perspective. is there a `builder()` or something to make this easier?

2024-01-31 20:10 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +println("Presentation Result: ${presentationResult}")
hmm, toString() doesn't change it 😞

2024-01-31 21:44 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +println("Presentation Result: ${presentationResult}")
So, @nitro-neal told me about using VerifiablePresentation.create() so I might have to use that here

2024-02-01 04:57 UTC, angiejones commented
putting this in draft until ready for review

2024-02-01 22:57 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +  ]
VerifiablePresentation.create only returns a partial result and PresentationExchange.createPresentationFromCredentials returns another partial result. And I think we're supposed to combine both results like this 

```kotlin
 val vcJwts: Iterable<String> = listOf("vcjwt1", "vcjwt2")

    val presentationSubmission = PresentationSubmission(
      id = "presentationSubmissionId",
      definitionId = "definitionId",
      descriptorMap = listOf(
        InputDescriptorMapping(
          id = "descriptorId",
          format = "format",
          path = "path"
        )
      )
    )

    val vp = VerifiablePresentation.create(
      vcJwts = vcJwts,
      holder = holderDid.uri,
      additionalData = mapOf("presentation_submission" to presentationSubmission)
    )

    val vpDataModelMap = vp.vpDataModel.toMap()
    val mappedPresentationSubmission = vpDataModelMap["presentation_submission"] as? PresentationSubmission
```

Reference: https://github.com/TBD54566975/web5-kt/blob/main/credentials/src/test/kotlin/web5/sdk/credentials/VerifiablePresentationTest.kt#L58

`VerifiablePresentation.create()` is coming to JavaScript soon.


so I'm not sure how to make this align with JS

2024-02-04 17:10 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +Before we start issuing and verifying credentials, let's set up our environment by installing the <LanguageSwitchLink text='@web5/credentials' links='{"JavaScript": "https://www.npmjs.com/package/@we
is this the best place to point kotlin devs to? https://github.com/TBD54566975/web5-kt

2024-02-04 17:11 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +const aliceDid = await DidIonMethod.create();
anything with import in JS has to be an inline snippet because I cant call import inside of a function..unless we decide to put the import in a separate code snippet from the actual logic

2024-02-04 17:11 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
>  }
anything with import in JS has to be an inline snippet because I cant call import inside of a function..unless we decide to put the import in a separate code snippet from the actual logic

2024-02-04 17:12 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
>  const definitionValidation = PresentationExchange.validateDefinition({ presentationDefinition });
anything with import in JS has to be an inline snippet because I cant call import inside of a function..unless we decide to put the import in a separate code snippet from the actual logic

2024-02-04 17:13 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +  ]}
it returns Kotlin.Unit..I think that's like void or undefined. I was unable to parse it into a string. Also what's the best way to represent this . Should I just not write anything for Kotlin?

2024-02-04 17:26 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/pom.xml
> +            </dependency>
apparently I needed this to create a VC and handle the JSON in my tests

2024-02-04 17:32 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +  ]}
heres what kotlin.unit is I guess https://stackoverflow.com/questions/22654932/what-is-the-purpose-of-unit-returning-in-functions

2024-02-05 12:12 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/FanClubVcTest.kt
> +
main way to get presentation submission details in full is to use Verifiable Presentation. See Neal's message: https://sq-tbd.slack.com/archives/C02KATKPLRY/p1706636644340719?thread_ts=1706636326.768709&cid=C02KATKPLRY

2024-02-05 14:58 UTC, blackgirlbytes commented
This is ready for review!

2024-02-05 20:04 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/fan-club-vc.mdx
> +Before we start issuing and verifying credentials, let's set up our environment by installing the <LanguageSwitchLink text='@web5/credentials' links='{"JavaScript": "https://www.npmjs.com/package/@we
thank you!

2024-02-05 20:28 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/FanClubVcTest.kt
> +
Ticket created: https://app.asana.com/0/1204316590307635/1206523815756423

2024-02-05 20:34 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/web5/build/verifiable-credentials/fan-club-vc.test.js
> +      const aliceDid = await DidIonMethod.create();
Ticket created: https://app.asana.com/0/1204316590307635/1206523815756425

2024-02-05 20:35 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/FanClubVcTest.kt
> +        val definitionValidation = PresentationExchange.validateDefinition(presentationDefinition)
yes, I need to separate the imports to be able to do assertions on it. Doing that now.

2024-02-05 21:34 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/FanClubVcTest.kt
> +        val definitionValidation = PresentationExchange.validateDefinition(presentationDefinition)
done!

2024-02-06 13:20 UTC, blackgirlbytes commented
Test failures related to this: https://discord.com/channels/937858703112155166/1204316134220767252/1204316179431170088

2024-02-07 13:09 UTC, blackgirlbytes commented
I rebased and pulled in unnecessary POM changes. I'm going to just close this PR and create a new one to reduce any chances of messing up our dependency management

2024-02-07 13:09 UTC, closed without merging