FormFree recap blog
TBD54566975/developer.tbd.website pull request #1178
Opened 2024-01-30 23:21 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [x] 🚩 Other

## Description

This PR adds a blog post highlighting the livestream we did with FormFree. We should highlight it since they're in our incubation program and they are using our technology.

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-01-30 23:28 UTC, blackgirlbytes commented
Failing because of broken links. I don't get how to do the links here

2024-01-30 23:50 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +*This post highlights key moments from our collaborative live stream with leaders and builders at FormFree. Join our weekly live streams every Friday at 12pm ET/9 am PT. We're learning how innovators
```suggestion
*This post highlights key moments from our collaborative live stream with leaders and builders at FormFree. Join our weekly live streams every Friday at 12pm ET/9 am PT. We're learning how innovators and community members are advancing the Self-Sovereign Identity and Global Payments industry. Tune in next time via [Twitch](https://twitch.tv/tbdevs ) or in our community [Discord](https://discord.com/invite/tbd).*
```

build was breaking due to broken links

2024-01-31 00:38 UTC, blackgirlbytes commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +*This post highlights key moments from our collaborative live stream with leaders and builders at FormFree. Join our weekly live streams every Friday at 12pm ET/9 am PT. We're learning how innovators
ohhh thank you. I was so confused which links were broken.

2024-01-31 04:27 UTC, angiejones requested changes

2024-01-31 04:27 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +The Fair Isaac Corporation score, more fondly known as a FICO score, is a three-digit score that helps lenders in the U.S. evaluate the likelihood of a borrower repaying a loan. A higher score indica
```suggestion
The Fair Isaac Corporation score, better known as a FICO score, is a three-digit score that helps lenders in the U.S. evaluate the likelihood of a borrower repaying a loan. A higher score indicates greater reliability. However, achieving a high FICO score — or any credit score — largely depends on accruing and gradually repaying debt. This may come as a disadvantage for various groups of people who may not have a credit score, including veterans, formerly incarcerated individuals, immigrants, young adults, and folks who prefer cash transactions.
```

2024-01-31 04:27 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +## "It's like Tinder for banks!"
lol

2024-01-31 04:27 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +During the live stream, FormFree Software Engineer Jon West showcased a product called Passport. The demo highlighted Passport's ability to match borrowers with lenders. This feature inspired an audi
```suggestion
During the live stream, FormFree Software Engineer, Jon West, showcased their [Passport](https://passport.formfree.com/) product. The demo highlighted Passport's ability to match borrowers with lenders. This feature inspired an audience member to comment, 'It's like Tinder for banks!'"
```

2024-01-31 04:28 UTC, angiejones commented
great post, @blackgirlbytes!

2024-01-31 04:35 UTC, blackgirlbytes commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +  <meta name="twitter:image" content="https://developer.tbd.website/assets/images/shifting-loan-power-to-borrowers.png" />
okay, thank you! I couldnt remember how we get the generated url and I was trying to search through my slack messages for it, but couldn't find.

2024-01-31 05:41 UTC, blackgirlbytes commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +"'Our current credit system says, 'Saddle yourself, so we can give you more to saddle,'" the President of [FormFree](https://www.formfree.com/), Eric Lapin, remarked in one a TBD live stream. His com
okay fixed

2024-01-31 05:57 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +_"'Our current credit system says, 'Saddle yourself, so we can give you more to saddle.'"_ Eric Lapin, President of FormFree made this comment during a recent TBD live stream. His comment sheds light
there's an extra apostrophe here

```suggestion
_"Our current credit system says, 'Saddle yourself, so we can give you more to saddle.'"_ Eric Lapin, President of FormFree made this comment during a recent TBD live stream. His comment sheds light on a fundamental paradox of the U.S. credit system: it often requires you to accumulate debt as a prerequisite for obtaining loans, leading to more debt. This systemic issue is underscored by [recent data from the Federal Reserve Bank of New York](https://www.newyorkfed.org/microeconomics/sce/credit-access#/experiences-credit-demand1), which reveals that 1 in 5 applicants for mortgages, car loans, or other types of loans were rejected — the highest rate in five years. This trend disproportionately impacts Black and Latino applicants. Guided by their slogan, 'Democratizing lending for all people without bias,' FormFree developed a platform built with Web5 and AI to address these issues.
```

2024-01-31 06:00 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +- [Decentralized Identifiers (DID)](https://developer.tbd.website/docs/web5/learn/decentralized-identifiers) - After sign up, the application associates a user's account with a DID.
```suggestion
- [Decentralized Identifiers (DID)](/docs/web5/learn/decentralized-identifiers) - After sign up, the application associates a user's account with a DID.
```

2024-01-31 06:00 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +- [Verifiable Credentials (VC)](https://developer.tbd.website/docs/web5/learn/verifiable-credentials) - A borrower's credit profile is secured as a Verifiable Credential enabling the borrower's infor
```suggestion
- [Verifiable Credentials (VC)](/docs/web5/learn/verifiable-credentials) - A borrower's credit profile is secured as a Verifiable Credential enabling the borrower's information to stay anonymous and tamper-proof.
```

2024-01-31 06:01 UTC, angiejones commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +As part of our [incubation program](https://developer.tbd.website/community/incubation-projects/), organizations such as [FormFree](https://www.formfree.com/), [Sophtron](https://sophtron.com/index),
```suggestion
As part of our [incubation program](/community/incubation-projects/), organizations such as [FormFree](https://www.formfree.com/), [Sophtron](https://sophtron.com/index), and [MX](https://www.mx.com/) are working in partnership to build Web5 protocols that will help their products evolve.
```

2024-01-31 06:02 UTC, angiejones approved these changes

2024-01-31 11:55 UTC, acekyd commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +_"'Our current credit system says, 'Saddle yourself, so we can give you more to saddle.'"_ Eric Lapin, President of FormFree made this comment during a recent TBD live stream. His comment sheds light
Should we link "TBD live stream" here to the Twitch channel (twitch.tv/tbdevs)? Might provide additional context and also direct people to the weekly streams.

2024-01-31 12:05 UTC, acekyd approved these changes

2024-01-31 12:53 UTC, blackgirlbytes commented on site/blog/2024-01-30-shifting-loan-power-to-brrowers.md
> +_"'Our current credit system says, 'Saddle yourself, so we can give you more to saddle.'"_ Eric Lapin, President of FormFree made this comment during a recent TBD live stream. His comment sheds light
yes, let me do that!

2024-01-31 13:13 UTC, merged