Add Kotlin Snippets to PFI/Structuring a PFI App
TBD54566975/developer.tbd.website pull request #1181
Opened 2024-01-31 07:15 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR updates the "Structuring a PFI App" page to add Kotlin code snippets

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x ] 🙋 no, because I need help

### No tests? Add a note

Kotlin testing isn't available yet

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-01-31 16:30 UTC, angiejones commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.js
> +// :snippet-start: configJs
these are global names, so try to use ones that are very specific

2024-02-01 04:14 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +    <CodeSnippet snippet={configJs} />
<Shnip> is the component to use

2024-02-01 04:16 UTC, angiejones commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.js
> +async create(offering: Offering) {
when testing locally, please use JS. this is TS and is not compiling

2024-02-01 04:18 UTC, angiejones requested changes

2024-02-01 04:18 UTC, angiejones commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.js
This file is not compiling. Please use JavaScript, not TypeScript.

2024-02-01 04:22 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +import configJs from '!!raw-loader!@site/snippets/tbdex/pfi/configJs.snippet.js'
@dayhaysoos I know you're gonna improve this but just showing you how much overhead this is (11 code imports required for one guide)

2024-02-01 04:23 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +<Tabs>
can use the new `<Shnip>` system now

2024-02-01 22:45 UTC, chris-tbd commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.js
> +// :snippet-start: configJs
Updated

2024-02-02 04:54 UTC, angiejones commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.kt
> +// :snippet-start: pfiOverviewWriteKt
any reason why we need these empty snippets?

2024-02-02 05:17 UTC, angiejones commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.kt
> +    port = 8080,
`port` and `pfiDid` are not a part of the JS snippet. should they be? has that made it into a tbdex release yet?

2024-02-02 05:19 UTC, angiejones commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.kt
> +val tbdexServer = TbdexHttpServer(serverConfig)
js and kotlin have diff var names here

```js
const httpApi = new TbdexHttpServer({ exchangesApi, offeringsApi })
```

2024-02-02 05:28 UTC, angiejones requested changes

2024-02-02 05:28 UTC, angiejones commented on site/__tests__/tbdex/pfi/pfi-overview.snippet.kt
> +    call.respond(HttpStatusCode.Accepted)
these aren't in your JS examples

```js
httpApi.submit('rfq', async (ctx, rfq) => {
    await ExchangesApiProvider.write({ message: rfq})
})
```

2024-02-02 05:36 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +    { snippetContent: writeKt, language: 'Kotlin'}
This snippet is blank so is showing snippet not found

<img width="411" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/6d8c44a7-e331-4bd4-8ffd-59a3a5ebf65d">

2024-02-02 05:37 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +    { snippetContent: readOfferingsKt, language: 'Kotlin'}
missing kotlin snippets for the next 2

<img width="474" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/f1a09550-1f4e-46f9-8011-f81045dfbf6a">

2024-02-05 16:57 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/pfi-overview.snippet.kt
> +    pfiDid = DidDht.create(AwsKeyManager()).uri,
by time they are here, they already have a DID. let's just change this to `did.uri`

```suggestion
    pfiDid = did.uri,
```

2024-02-07 20:24 UTC, chris-tbd reviewed
Addressed

2024-02-07 21:16 UTC, angiejones requested changes

2024-02-07 21:16 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +    val httpApi = TbdexHttpServer(serverConfig)
this variable is called `tbDexServer` in JS. Should we keep them the same across the examples to reduce confusion?

```js
const tbDexServer = new TbdexHttpServer({ 
  exchangesApi: exchangesApiProvider, 
  offeringsApi: offeringsApiProvider 
})
```

2024-02-07 21:16 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfi-structure.js
> +    console.log.info(`PFI listening on port ${8080}`)
```suggestion
    console.log('PFI listening on port 8080')
```

This is not valid JS. Please test code before committing it.

2024-02-07 21:16 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +class MockDataProvider {
the file name and the classname must be the same

2024-02-07 21:16 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
is the purpose of this file to be a mock data provider or is this a regular test file? there's snippets in here, which means there needs to be assertions so that we know when these snippets are out of date

2024-02-07 21:16 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfi-structure.js
> +          return Offering.factory(result.offering)
I dont see a `factory` function in the [API Ref guide](https://tbd54566975.github.io/tbdex-js/classes/_tbdex_http_server.Offering.html). What's this?

2024-02-07 21:16 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfi-structure.js
this file needs assertions for every snippet that uses anything from the tbdex SDK

2024-02-07 22:54 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfi-structure.js
> +          return Offering.factory(result.offering)
Not sure how that got in there, removed

2024-02-07 22:54 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +class MockDataProvider {
Does this need to get exported into a separate file? Or can we leave it in here for now?

2024-02-07 22:54 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfi-structure.js
> +    console.log.info(`PFI listening on port ${8080}`)
Fixed

2024-02-08 03:51 UTC, angiejones requested changes

2024-02-08 03:51 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfi-structure.js
> +this.pfiDid = await DidDhtMethod.create({ publish: true});
PFI dids must have [PFI service endpoint](https://developer.tbd.website/docs/tbdex/pfi/onboarding/#create-did-with-service-endpoint). We already have a guide on creating the DID, so no need to create it again here within the snippet. Can just reference it as `pfiDid`, and actually create it before the snippet. Also for testing purposes, don't publish the did

2024-02-08 03:51 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +    val httpApi = TbdexHttpServer(serverConfig)
thoughts on this?

2024-02-08 04:28 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfi-structure.js
> +this.pfiDid = await DidDhtMethod.create({ publish: true});
Updated

2024-02-08 04:32 UTC, angiejones approved these changes

2024-02-08 07:27 UTC, angiejones requested changes
test code locally and make sure it compiles before committing

<img width="1398" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/ac1dfdd5-10e9-4d98-a8ed-492eed7b7cbd">

2024-02-08 07:33 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +            pfiDid = pfiDid,
this does not compile

```suggestion
            pfiDid = pfiDid.uri,
```

2024-02-08 07:34 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +        val pfiDid = DidDht.create(InMemoryKeyManager(), options)
this is not imported

2024-02-08 07:35 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +
```suggestion
import web5.sdk.crypto.InMemoryKeyManager
import web5.sdk.dids.methods.dht.CreateDidDhtOptions

```

2024-02-08 17:14 UTC, angiejones approved these changes

2024-02-08 17:15 UTC, merged