update create a did + kotlin
TBD54566975/developer.tbd.website pull request #1190
Opened 2024-02-01 18:16 UTC by acekyd

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] 📝 Documentation Update
- [x] 🧑‍💻 Code Snippet

## Description

This PR adds and updates kotlin snippets to Create a DID. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206268818054117

2024-02-01 19:51 UTC, angiejones commented on site/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.kt
> +    publish = true
can you put this all one one line? it's short enough

2024-02-01 19:55 UTC, angiejones approved these changes

2024-02-02 16:03 UTC, acekyd commented on site/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.kt
> +    publish = true
Thanks!

2024-02-02 16:10 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    inlineSnippets={[
how come unable to use external snippet here?

2024-02-02 16:33 UTC, angiejones requested changes

2024-02-02 16:33 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +    assertEquals("1","1")
can we add a real test now? just make sure did, portableDID, did, and didDocument aren't null

2024-02-02 16:33 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +  fun `createDidKt works`() {
change to something less generic like "able to create DIDs"

2024-02-02 16:33 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +    // :snippet-start: createDidKeyKt
can we separate these into 2 separate functions?

2024-02-02 19:21 UTC, acekyd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +    // :snippet-start: createDidKeyKt
On it

2024-02-02 19:22 UTC, acekyd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +    assertEquals("1","1")
Oh damn! I forgot I pushed that. Was debugging why the test was failing. But yes we can do a real test now.

2024-02-04 04:45 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
> +    expect(requiredImports).toBeDefined();
can remove test for imports

2024-02-04 04:46 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
> +    const requiredImports = `
```suggestion

```

2024-02-04 04:46 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
> +    `
```suggestion
    
```

2024-02-04 04:47 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
> +    expect(requiredImports).toBeDefined();
```suggestion
   
```

2024-02-04 04:48 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +// key manager
```suggestion

```

2024-02-04 04:48 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +//did:dht
```suggestion

```

2024-02-04 04:48 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +//did:key
```suggestion

```

2024-02-04 04:50 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +    assertTrue(did.startsWith("did:"), "DID should start with 'did:'")
```suggestion
    assertTrue(did.startsWith("did:dht:"), "DID should start with 'did:dht'")
```

2024-02-04 05:05 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToCreateDidTest.kt
> +
any way to get cryptographic keys associated with DID in Kotlin?

2024-02-04 05:55 UTC, angiejones approved these changes

2024-02-04 10:33 UTC, merged