Added Kotlin Shnips for PEX
TBD54566975/developer.tbd.website pull request #1199
Opened 2024-02-05 11:56 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [x] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds tests and kotlin snippets for Presentation Exchange. The last two cannot be converted to Kotlin because they're not implemented yet. See issue for validate submission https://github.com/TBD54566975/web5-kt/issues/133

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-05 12:11 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/PresentationExchangeTest.kt
> +    // :snippet-end:
main way to get presentation submission details in full is to use Verifiable Presentation. See Neal's message: https://sq-tbd.slack.com/archives/C02KATKPLRY/p1706636644340719?thread_ts=1706636326.768709&cid=C02KATKPLRY

2024-02-05 14:58 UTC, blackgirlbytes commented
Ready for review!

2024-02-05 16:20 UTC, angiejones requested changes

2024-02-05 16:20 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +<LanguageSwitcher languages="JavaScript, Kotlin" />
move this above the title

2024-02-05 16:20 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  <CodeSnippet functionName="pex_createPresentationFromCredentials" />
need to remove this

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/77720452-38cb-4475-b9fe-21aa3f73beaa)

2024-02-05 16:20 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  This method returns a `PresentationResult` which contains the presentation:
is this sentence accurate for Kotlin?

2024-02-05 16:20 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/PresentationExchangeTest.kt
> +    // :snippet-end:
seems it's coming soon in JS? we can update the JS snippet then

> To get this same result in kt (and soon in js) will need to use VerifiablePresentation.create()

2024-02-05 16:20 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  ## Validate Presentation Submission
the code snippet here is only in JS

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/408a4935-5527-482c-aa6c-5a72143c095b)

2024-02-05 16:20 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  ## Validate Presentation Submission
same for the next section

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/ed8e6d00-f9de-49e4-8f73-6c0eb5f554c2)

2024-02-05 16:28 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +<LanguageSwitcher languages="JavaScript, Kotlin" />
it breaks the doc when i move it above the title
<img width="1419" alt="Screenshot 2024-02-05 at 11 27 45 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/fcbd1911-b10c-4772-8117-50

<img width="1244" alt="Screenshot 2024-02-05 at 11 27 39 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/737d3a21-b560-4423-bb14-88e9065a1c79">
92264336ca">

2024-02-05 16:31 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  ## Validate Presentation Submission
I left a comment about this in my PR description 


Validate Submission is not in the Kotlin SDK yet
https://github.com/TBD54566975/web5-kt/issues/133

2024-02-05 16:50 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  This method returns a `PresentationResult` which contains the presentation:
no but we dont have the functionality to switch the content in our language switcher. we only have the functionality to switch links. Let me try something out real quick and see if I can do that

2024-02-05 17:08 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  This method returns a `PresentationResult` which contains the presentation:
okay I added something for us to switch the content.

2024-02-05 17:27 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  ## Validate Presentation Submission
for the very last section, they don't need to do that because they've already created a VerifiablePresentation that they can submit with VerifiablePresentation.create().  Now that I created the functionality to change the content and the code with Shnip..I will add that in a second

This PR is a little more thorough because there are more methods that match with in the SDKs: https://github.com/TBD54566975/developer.tbd.website/pull/1199 . It's been sitting. Take your time though because I know you're heads down today!

2024-02-05 18:45 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +<LanguageSwitcher languages="JavaScript, Kotlin" />
```md
---
title: Presentation Exchange
hide_title: true
sidebar_position: 3
---

//imports

<LanguageSwitcher languages="JavaScript, Kotlin"/>

```

2024-02-05 19:14 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
>  ## Validate Presentation Submission
okay I gave a code snippet of how they can do the presentation submission from Verifiable Presentation create to  vpDataModelMap["presentation_submission"] as? PresentationSubmission

2024-02-05 20:07 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +<LanguageSwitcher languages="JavaScript, Kotlin" />
never mind..I finally understood what you were saying. This is solved.

2024-02-05 20:25 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/PresentationExchangeTest.kt
> +    // :snippet-end:
Created ticket https://app.asana.com/0/1204316590307635/1206523815756423

2024-02-06 13:19 UTC, blackgirlbytes commented
Test failures related to this: https://discord.com/channels/937858703112155166/1204316134220767252/1204316179431170088

2024-02-06 19:45 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/PresentationExchangeTest.kt
> +    val signedNameAndDobVcJwt = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDprZXk6ejZNa2pwUzRHVUFoYmdCSmg2azJnZTZvWTQ0UUxyRXA3NXJadHNqYVRLb3JSRGR0I3o2TWtqcFM0R1VBaGJnQkpoNmsyZ2U2b1k0NFFMckVwNz
I think I need to put this in a separate file because this file takes particularly long to load. I just need to figure out how to import these variables from a file into another file in Kotlin

2024-02-06 19:56 UTC, acekyd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/PresentationExchangeTest.kt
> +import web5.sdk.credentials.model.PresentationSubmission
Can import all the models in one line with model.*

2024-02-06 20:07 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/PresentationExchangeTest.kt
> +import web5.sdk.credentials.model.PresentationSubmission
okay done!

2024-02-06 20:08 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +      content: 'This functionality is soon to be implemented in the Kotlin SDK.' ,
👍🏾

2024-02-06 20:14 UTC, angiejones approved these changes

2024-02-06 21:42 UTC, merged