PFI/Quotes Kotlin Snippets
TBD54566975/developer.tbd.website pull request #1209
Opened 2024-02-06 18:51 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Add Kotlin snippets for PFI/Quotes page

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

### No tests? Add a note
Kotlin tests currently blocked

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-06 22:00 UTC, angiejones commented
putting in draft while chris works through the compilation errors

2024-02-08 07:41 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    val data = mapOf(
to be in sync with JS example, add the preceding comment
```suggestion
   // Write the message to your exchanges database
    val data = mapOf(
```

2024-02-08 07:44 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    if (offering is Offering && message is Rfq) {
there is no `if` statement in the JS snippet. If you need this for your setup/testing purposes, move the `// snippet:start` line to after this (also move the `// snippet-end` up a line before the closing brace

2024-02-08 07:46 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    if (offering is Offering && message is Rfq) {
alternatively, if an `if` is needed, you should add it to the JS snippet

2024-02-08 07:48 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +    try {
```suggestion
    // :snippet-start: pfiQuotesProcessJs
    try {
```

The PFI receives the RFQ, they don't create it. so showing a snippet where they create a RFQ with no requirements and then verifying the requirements 2 lines later doesn't make sense

2024-02-08 07:49 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +    // :snippet-start: pfiQuotesProcessJs
```suggestion

```

2024-02-08 07:54 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +            expiresAt: new Date(2024, 4, 1).toISOString(),
make this equivalent to this Kotlin snippet

```kotlin
OffsetDateTime.now().plusDays(10)
```

in JS, it's something like:

```js
let currentDate = new Date();
currentDate.setDate(currentDate.getDate() + 10);
```

2024-02-08 07:56 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +            from: config.did.id,
shouldn't this be `pfiDid.did`?

2024-02-08 08:00 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +    await quote.sign(config.did.privateKey, config.did.kid)
`sign` takes a did now. https://tbd54566975.github.io/tbdex-kt/protocol/tbdex.sdk.protocol.models/-message/sign.html

```suggestion
    await quote.sign(pfiDid)
```

2024-02-09 00:28 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    if (offering is Offering && message is Rfq) {
It's in here as a function of how we do types in the Kotlin SDK. This is going to be a part of safely converting the message to an RFQ since both are optionals in Kotlin but not in JS. Start of a series of messages in Discord about this here: https://discord.com/channels/937858703112155166/949067728709369856/1204488507280597042

2024-02-09 00:28 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +            expiresAt: new Date(2024, 4, 1).toISOString(),
Updated

2024-02-09 00:28 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +            from: config.did.id,
Updated

2024-02-09 04:06 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +    "from": "did:ex:pfi",
```suggestion
    "from": pfiDid.uri,
```

2024-02-09 04:10 UTC, angiejones requested changes

2024-02-09 04:10 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOnboardingTest.kt
>      assertEquals("PFI", did.didDocument?.services?.get(0)?.type, "DID should start with 'did:key'")
how is this passing when it's using `did` and you renamed it to `pfiDid`? 

```suggestion
    assertEquals("PFI", pfiDid.didDocument?.services?.get(0)?.type, "DID has PFI service type")
```

2024-02-09 04:10 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    val pfiDid = DidJwk.create(InMemoryKeyManager())
use `DidDht` and add the PFI service type

2024-02-09 04:11 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +        from = message.metadata.to,
```suggestion
        from = pfiDid.uri,
```

2024-02-09 04:19 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    exchangesApiProvider.write(quote)
in the JS snippet, you use `this`. is there a way to make these consistent so that the reader knows what the `this` class refers to? 

JS
```js
await quote.sign(pfiDid)
this.write(quote)
```

In the Structuring PFI Doc, you're writing messages like such:
```js
tbDexServer.submit('order', async (ctx, order) => {
    await exchangesApiProvider.write({ message: order })
})
```

2024-02-09 04:22 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOnboardingTest.kt
>      assertEquals("PFI", did.didDocument?.services?.get(0)?.type, "DID should start with 'did:key'")
ah it's not passing

https://github.com/TBD54566975/developer.tbd.website/actions/runs/7839445505/job/21392477069?pr=1209#step:10:13855

2024-02-09 19:23 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    exchangesApiProvider.write(quote)
Made consistent

2024-02-09 19:23 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +        from = message.metadata.to,
Fixed

2024-02-09 19:23 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +    val pfiDid = DidJwk.create(InMemoryKeyManager())
Fixed

2024-02-09 19:24 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOnboardingTest.kt
>      assertEquals("PFI", did.didDocument?.services?.get(0)?.type, "DID should start with 'did:key'")
Fixed

2024-02-09 19:24 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +    "from": "did:ex:pfi",
Leaving this for right now - this will matter for assertions, but before assertions happen I'll need to spin out all these mock providers. I'm going to end up passing this value as a variable later.

2024-02-09 19:57 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +          serviceEndpoint: 'tbdex-pfi.tbddev.org'
```suggestion
          serviceEndpoint: 'https://example.com/service'
```

2024-02-10 01:45 UTC, angiejones approved these changes

2024-02-10 01:45 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +class DataProvider {
any reason why this class isn't split out into something reusable? the same class is in the pfi-structure.js file

2024-02-10 01:45 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.js
> +let sampleOffering = {
for future reference (and as a followup cleanup action item), you can use `DevTools` for some of this stuff 
https://tbd54566975.github.io/tbdex-js/classes/_tbdex_protocol.DevTools.html

2024-02-12 16:11 UTC, merged