Verify VCs - Kotlin Code Snippets
TBD54566975/developer.tbd.website pull request #1214
Opened 2024-02-07 22:53 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds Kotlin code snippets to the Verify VCs guide

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-08 17:42 UTC, angiejones commented
@blackgirlbytes, @nitro-neal put in some enhancements that allows us to verify an entire presentation at once as opposed to looping through all VCs. Can you check to see if that has been merged in web5.js and web5-kt yet and if so, update both of these snippets?

2024-02-08 18:08 UTC, blackgirlbytes commented
It looks like it's not yet merged in JS https://github.com/TBD54566975/web5-js/pull/382/files

But it is in Kotlin. Let me update to show it in Kotlin.

2024-02-08 19:01 UTC, blackgirlbytes commented
note to self for when I get back from errand

## Get assertion method Id

val didDocumentString: String = // your DID document string

// Parse the DID document
val objectMapper = jacksonObjectMapper()
val didDocument: Map<String, Any> = objectMapper.readValue(didDocumentString)

// Access the assertionMethod section
val assertionMethods = didDocument["assertionMethod"] as? List<Map<String, Any>>

// Extract the first assertion method ID
val assertionMethodId = assertionMethods?.firstOrNull()?.get("id") as? String

## Create VP

val verifiablePresentation = VerifiablePresentation.create(
    vcJwts = listOf(vcJwt1, vcJwt2),
    holder = "did:ion:EiBYBnt0m0y73V07U9-rdKtU-FgebRUhUT4ULAsJBgzvSg",
    additionalData = mapOf("presentation_submission" to presentationResult)
)

## convert to JWT
val vpJwt = verifiablePresentation.sign(yourDid, yourAssertionMethodId)

### verify 
try {
    VerifiablePresentation.verify(vpJwt)
    println("VP Verification successful!")
} catch (e: Exception) {
    println("VP Verification failed: ${e.message}")
}

2024-02-09 05:27 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/VerifyVcTest.kt
> +    holder = "did:ion:EiBYBnt0m0y73V07U9-rdKtU-FgebRUhUT4ULAsJBgzvSg:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIj
can we use did:dht?

2024-02-09 05:30 UTC, angiejones commented
> note to self for when I get back from errand
> 
> ## Get assertion method Id
> val didDocumentString: String = // your DID document string
> 
> // Parse the DID document val objectMapper = jacksonObjectMapper() val didDocument: Map<String, Any> = objectMapper.readValue(didDocumentString)
> 
> // Access the assertionMethod section val assertionMethods = didDocument["assertionMethod"] as? List<Map<String, Any>>
> 
> // Extract the first assertion method ID val assertionMethodId = assertionMethods?.firstOrNull()?.get("id") as? String
> 
> ## Create VP
> val verifiablePresentation = VerifiablePresentation.create( vcJwts = listOf(vcJwt1, vcJwt2), holder = "did:ion:EiBYBnt0m0y73V07U9-rdKtU-FgebRUhUT4ULAsJBgzvSg", additionalData = mapOf("presentation_submission" to presentationResult) )
> 
> ## convert to JWT
> val vpJwt = verifiablePresentation.sign(yourDid, yourAssertionMethodId)
> 
> ### verify
> try { VerifiablePresentation.verify(vpJwt) println("VP Verification successful!") } catch (e: Exception) { println("VP Verification failed: ${e.message}") }

do you think we should have a section for `VerifiablePresentation.verify()` and also `VerifiableCredential.verify()` so people have multiple examples?

2024-02-09 14:02 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/VerifyVcTest.kt
> +    holder = "did:ion:EiBYBnt0m0y73V07U9-rdKtU-FgebRUhUT4ULAsJBgzvSg:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIj
yes! I just took the did ion out from the JWT in the JS example.

2024-02-09 14:03 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/VerifyVcTest.kt
> +    holder = "did:ion:EiBYBnt0m0y73V07U9-rdKtU-FgebRUhUT4ULAsJBgzvSg:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIj
oh wait actually I might have to use did key. I remember i tried to switch to did dht but I think it's missing something because it gives me this error: " Expected kid in JWS header to dereference a DID Document Verification Method of type JsonWebKey2020 with a publicKeyJwk"

If I change to ion or key the error goes away

2024-02-09 14:04 UTC, blackgirlbytes commented
> > note to self for when I get back from errand
> > ## Get assertion method Id
> > val didDocumentString: String = // your DID document string
> > // Parse the DID document val objectMapper = jacksonObjectMapper() val didDocument: Map<String, Any> = objectMapper.readValue(didDocumentString)
> > // Access the assertionMethod section val assertionMethods = didDocument["assertionMethod"] as? List<Map<String, Any>>
> > // Extract the first assertion method ID val assertionMethodId = assertionMethods?.firstOrNull()?.get("id") as? String
> > ## Create VP
> > val verifiablePresentation = VerifiablePresentation.create( vcJwts = listOf(vcJwt1, vcJwt2), holder = "did:ion:EiBYBnt0m0y73V07U9-rdKtU-FgebRUhUT4ULAsJBgzvSg", additionalData = mapOf("presentation_submission" to presentationResult) )
> > ## convert to JWT
> > val vpJwt = verifiablePresentation.sign(yourDid, yourAssertionMethodId)
> > ### verify
> > try { VerifiablePresentation.verify(vpJwt) println("VP Verification successful!") } catch (e: Exception) { println("VP Verification failed: ${e.message}") }
> 
> do you think we should have a section for `VerifiablePresentation.verify()` and also `VerifiableCredential.verify()` so people have multiple examples?

yes, I like that idea. I was trying to figure out how I would structure this, and your suggestion is great!

2024-02-12 14:15 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/VerifyVcTest.kt
> +    holder = "did:ion:EiBYBnt0m0y73V07U9-rdKtU-FgebRUhUT4ULAsJBgzvSg:eyJkZWx0YSI6eyJwYXRjaGVzIjpbeyJhY3Rpb24iOiJyZXBsYWNlIiwiZG9jdW1lbnQiOnsicHVibGljS2V5cyI6W3siaWQiOiJkd24tc2lnIiwicHVibGljS2V5SndrIj
used did key because dht doesnt have kid in JWS header to dereference a DID Document Verification Method of type JsonWebKey2020 with a publicKeyJwk

2024-02-12 14:29 UTC, blackgirlbytes commented
Ready for review again!

2024-02-12 15:49 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/verify-vc.mdx
> +title: Verify VCs and VPs
```suggestion
title: Verify Credentials
```

2024-02-12 15:49 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/verify-vc.mdx
> +# Verify VCs and VPs
```suggestion
# Verify Credentials
```

2024-02-12 15:53 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/verify-vc.mdx
> +The information in this section is only applicable to the Kotlin SDK.
can you make a GitHub issue to track this and associate it with the web5-js issue that'll introduce this functionality?

2024-02-12 15:58 UTC, angiejones requested changes

2024-02-12 15:58 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/verify-vc.mdx
> +Aggregating one or more VCs into a VP provides the following benefits:
everything from here to line 222 should go in the [PEX guide](https://developer.tbd.website/docs/web5/build/verifiable-credentials/presentation-exchange#create-presentation) under Create Presentations. This guide is just for verifying something

2024-02-12 15:58 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/verifiablecredentials/VerifyVcTest.kt
> +            println("VP Verification successful!")
```suggestion

```

2024-02-12 16:01 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/verify-vc.mdx
> +The information in this section is only applicable to the Kotlin SDK.
https://github.com/TBD54566975/developer.tbd.website/issues/1227
https://app.asana.com/0/1204316590307635/1206582227892438

2024-02-12 16:02 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/verify-vc.mdx
> +Aggregating one or more VCs into a VP provides the following benefits:
okay will take it out and move it to there.

2024-02-12 16:03 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/verify-vc.mdx
> +Aggregating one or more VCs into a VP provides the following benefits:
okay done

2024-02-12 17:06 UTC, angiejones approved these changes

2024-02-12 17:27 UTC, merged