Shnip improvements
TBD54566975/developer.tbd.website pull request #1215
Opened 2024-02-08 01:58 UTC by dayhaysoos

WIP

2024-02-08 16:10 UTC, angiejones commented on shnippet/src/cli.js
> +    console.log(`Cleared: ${outputDirectory}`);
```suggestion

```

2024-02-08 16:10 UTC, angiejones commented on shnippet/src/cli.js
> +      console.log(`Setting output directory structure to '${structureValue}'`);
```suggestion

```

2024-02-08 16:11 UTC, angiejones commented on shnippet/src/index.js
> +        console.log("Snippet start tag not followed by newline. Skipping...");
```suggestion

```

2024-02-08 16:12 UTC, angiejones commented on shnippet/src/index.js
> +      console.log(`Snippet written to: ${outputPath}`);
```suggestion

```

2024-02-08 19:52 UTC, blackgirlbytes commented on site/src/components/language/Shnip.jsx
> +                  snippetName={snippetName}
Just curious..what's the difference between snippet, functionname, and snippetname again? 

functionName is the old way right? 
And snippet is the current way..like we pass the function name into snippet..but then what's snippetname?

2024-02-09 18:51 UTC, finn-tbd approved these changes

2024-02-09 19:49 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidKey', language: 'Kotlin' },
how does it support the same name for multiple languages?

Team, is this something we want to do? Or should we make a naming convention. Just in the past week, I've needed to search for snippets by name in order to update them. I think that would become harder if there's N number of snippets all with the same name but in diff languages

2024-02-09 19:53 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidDht', language: 'JavaScript' },
are inline snippets still supported with this system? if so, can you use the new approach with one of the existing guides that have inline snippet?

2024-02-09 20:16 UTC, dayhaysoos commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidKey', language: 'Kotlin' },
Hey Angie, just realized this isn't currently working as expected but to answer your question, they will be separated by directory. So the paths would be something like:

`/snippets/js/createDidDht.snippet`

and for the kotlin file:

`/snippets/kt/createDidDht.snippet`

The only thing that really matters for me is that these files need to be JS modules. Lemme know what the team prefers, I personally think this would be easier to navigate but I understand how it would be noisy with the Command + P search from VS Code

2024-02-09 20:22 UTC, dayhaysoos commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidKey', language: 'Kotlin' },
Just made an update so it behaves as I described

2024-02-09 20:23 UTC, dayhaysoos commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidDht', language: 'JavaScript' },
They should be, I haven't made any changes to the Shnip component that would remove the inline snippets. Definitely worth double checking tho

2024-02-09 22:15 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidKey', language: 'Kotlin' },
yeah i think I want some kind of naming convention too because I've been giving the code snippets really bad names lol but I like that Nick separated them by directory

2024-02-12 17:22 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +<LanguageSwitcher languages="JavaScript, Kotlin"/>
```suggestion

```

this is duplicated on line 10

2024-02-12 17:25 UTC, angiejones requested changes

2024-02-12 17:25 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> -<Shnip
Please add this back. We are missing the code

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/b178641a-4b05-42ef-8138-bc139a7788e3)

Should be:
![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/3ed770fe-8604-473e-8763-c83400f70a96)

2024-02-12 17:28 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidDht', language: 'JavaScript' },
Couple of issues with the component changes:

- we lost the indenting you put in place
- the `//` from the ending snippet comment is being displayed

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/21849cce-b85a-4ee2-96ed-e0adfd7c2610)

2024-02-12 17:57 UTC, blackgirlbytes commented
hmm it seems like we lost line breaks for some situations

<img width="952" alt="Screenshot 2024-02-12 at 12 53 21 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/f4f6e2fa-33bd-44c6-ad72-8385971736ec">

2024-02-12 18:00 UTC, blackgirlbytes requested changes
hmm it seems like we lost line breaks for some situations. It seems to not be parsing how it used to parse before. 

<img width="952" alt="Screenshot 2024-02-12 at 12 53 21 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/f4f6e2fa-33bd-44c6-ad72-8385971736ec">

2024-02-12 18:12 UTC, blackgirlbytes commented
Also in the deploy preview, everything looks good, but when I try to run this locally, I get errors that these code snippets dont exist. Maybe I'm missing an install or maybe this isn't actually a problem, but I just wanted to give a heads up before we merge

<img width="1587" alt="Screenshot 2024-02-12 at 12 51 03 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/ccca4ad3-ebd4-4439-9d11-7594880135d8">

2024-02-12 20:03 UTC, angiejones commented
> Also in the deploy preview, everything looks good, but when I try to run this locally, I get errors that these code snippets dont exist. Maybe I'm missing an install or maybe this isn't actually a problem, but I just wanted to give a heads up before we merge
> 
> <img alt="Screenshot 2024-02-12 at 12 51 03 PM" width="1587" src="https://private-user-images.githubusercontent.com/22990146/304183806-ccca4ad3-ebd4-4439-9d11-7594880135d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3Njg0NTksIm5iZiI6MTcwNzc2ODE1OSwicGF0aCI6Ii8yMjk5MDE0Ni8zMDQxODM4MDYtY2NjYTRhZDMtZWJkNC00NDM5LTlkMTEtNzU5NDg4MDEzNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDIwMDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZmRkNWZjYWE5NzViYTI1NzMxZmMyYWE4M2Y3MGExOTE3NGZkOWE2ZGQ5NDI4ZTZkNGZmNjg5ODJhZWQ4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w22KSL3OEQAJhJ-tAY0DzLnC3L5UNY_XPqlkd_oO9as">

did you run `pnpm build`?

2024-02-13 00:54 UTC, blackgirlbytes commented
> > Also in the deploy preview, everything looks good, but when I try to run this locally, I get errors that these code snippets dont exist. Maybe I'm missing an install or maybe this isn't actually a problem, but I just wanted to give a heads up before we merge
> > <img alt="Screenshot 2024-02-12 at 12 51 03 PM" width="1587" src="https://private-user-images.githubusercontent.com/22990146/304183806-ccca4ad3-ebd4-4439-9d11-7594880135d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3Njg0NTksIm5iZiI6MTcwNzc2ODE1OSwicGF0aCI6Ii8yMjk5MDE0Ni8zMDQxODM4MDYtY2NjYTRhZDMtZWJkNC00NDM5LTlkMTEtNzU5NDg4MDEzNWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDIwMDIzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZmRkNWZjYWE5NzViYTI1NzMxZmMyYWE4M2Y3MGExOTE3NGZkOWE2ZGQ5NDI4ZTZkNGZmNjg5ODJhZWQ4YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w22KSL3OEQAJhJ-tAY0DzLnC3L5UNY_XPqlkd_oO9as">
> 
> did you run `pnpm build`?

oh okay yeah you're right. I missed that step. Running pnpm build worked. Ignore that comment then lol

2024-02-14 18:32 UTC, dayhaysoos commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidDht', language: 'JavaScript' },
Hey @angiejones, I genuinely don't think I can do anything about this right now. I've spent too much time on it. 

I believe it properly handles the case for actual functions but for some reason I can't properly match indentation for single lines after the tag is made.


This screenshot shows how it looks when you have functions within the tags of the snippets.

![Screenshot 2024-02-14 at 12 45 53 PM](https://github.com/TBD54566975/developer.tbd.website/assets/1852675/4d4f2c3c-e9d3-4c78-bd67-cf2449c878a4)

I would love to revisit this in a separate sprint, however, the longer this PR goes on the more work there is to undo as dev rel continues creating content.

Lemme know what you think

2024-02-14 18:40 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidDht', language: 'JavaScript' },
ok we can merge this and then do a fast follow up to make the snippets pretty

2024-02-15 05:22 UTC, angiejones requested changes

2024-02-15 05:22 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> -<Shnip
@dayhaysoos this is still messed up. the imports go above `did:dht` and now the code snippets for `did:dht` are missing

This is what it should look like: 
https://developer.tbd.website/docs/web5/build/decentralized-identifiers/how-to-create-did

2024-02-15 16:14 UTC, dayhaysoos commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> +    { snippetName: 'createDidDht', language: 'JavaScript' },
This was finally addressed, just FYI

2024-02-15 16:50 UTC, dayhaysoos commented on site/docs/web5/build/decentralized-identifiers/how-to-create-did.mdx
> -<Shnip
Done!

2024-02-15 17:49 UTC, blackgirlbytes commented
found one small thing 

https://discord.com/channels/937858703112155166/1201968928520409088/1207743583604445184

2024-02-15 18:02 UTC, angiejones approved these changes

2024-02-15 21:32 UTC, blackgirlbytes approved these changes

2024-02-15 22:27 UTC, merged