Add support for Breadcrumbs and Custom Code Language to Shnip
TBD54566975/developer.tbd.website pull request #1233
Opened 2024-02-13 16:20 UTC by acekyd

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] ✨ New Feature

## Description

This PR adds support for Breadcrumbs through `nestedSnippets` and also allows specifying custom code language to use for imported snippets e.g rendering bash under the JS tab. 

In use here #1232 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

![](https://i.pinimg.com/originals/2f/73/4d/2f734dcb9281d981d6bdaec1d3c59f5a.gif)

2024-02-13 17:24 UTC, blackgirlbytes commented on site/src/components/language/Shnip.jsx
> -                    language={codeLanguage.toLowerCase() || language.toLowerCase()}
wait why remove the toLowerCase part? I think I added that, but I don't remember why I did 😅

2024-02-13 17:24 UTC, blackgirlbytes commented
okay, awesome! Glad you added this so that the language switcher in the other PR will actually work!

2024-02-13 17:25 UTC, blackgirlbytes approved these changes

2024-02-13 17:26 UTC, acekyd commented on site/src/components/language/Shnip.jsx
> -                    language={codeLanguage.toLowerCase() || language.toLowerCase()}
Oh I added it here and for some reason it was breaking the build. The one you added is still below and works with the build.

2024-02-13 18:11 UTC, angiejones requested changes
- Missing the dropdown on the pages
- When switching one tab to Kotlin, the other does not switch

https://deploy-preview-1233--tbd-website-developer.netlify.app/docs/tbdex/pfi/required-sdks?lang=Kotlin

<img width="861" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/9bb97a93-7d90-4f4b-bad1-e0874a8acb30">

2024-02-13 18:24 UTC, blackgirlbytes commented on site/src/components/language/Shnip.jsx
> -                    language={codeLanguage.toLowerCase() || language.toLowerCase()}
oh okay!

2024-02-13 18:27 UTC, blackgirlbytes commented
> * Missing the dropdown on the pages
> * When switching one tab to Kotlin, the other does not switch
> 
> https://deploy-preview-1233--tbd-website-developer.netlify.app/docs/tbdex/pfi/required-sdks?lang=Kotlin
> 
> <img alt="image" width="861" src="https://private-user-images.githubusercontent.com/15972783/304508733-9bb97a93-7d90-4f4b-bad1-e0874a8acb30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4NDkwMzIsIm5iZiI6MTcwNzg0ODczMiwicGF0aCI6Ii8xNTk3Mjc4My8zMDQ1MDg3MzMtOWJiOTdhOTMtN2Q5MC00ZjRiLWJhZDEtZTA4NzRhOGFjYjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDE4MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkYjljNDkwOTExZmE0YzIwMjBhMjQ3YjViNzQ4MGU5ZTU1N2ZhYzY3YWRmNGI4YTY0OGYzYTE0ODI3MzQyNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nk3-YWUupxklIjDF_Wo1VUEHUUcQ2RMBDeOWxdvzirg">

Oh I was thinking if he merged this, and then that would enable him to pull in these changes to his other PR that adds the  global language switching tab

2024-02-13 18:29 UTC, acekyd commented
Yes @blackgirlbytes. I wanted to keep this PR clean and focus on just the breadcrumbs update. And then #1232 would make the changes once this is merge. But I'll just combine everything here to make it easier since they are connected. @angiejones

2024-02-13 20:27 UTC, chris-tbd approved these changes

2024-02-13 20:53 UTC, dayhaysoos approved these changes

2024-02-13 21:26 UTC, angiejones approved these changes

2024-02-13 21:26 UTC, angiejones commented
Ace thank you so much for cleaning this up! much appreciated 🙏🏾

2024-02-13 21:27 UTC, merged

2024-02-13 23:42 UTC, angiejones commented
> Yes @blackgirlbytes. I wanted to keep this PR clean and focus on just the breadcrumbs update. And then #1232 would make the changes once this is merge. But I'll just combine everything here to make it easier since they are connected. @angiejones

Oh I'm sorry y'all. I didn't realize there were 2 PRs

2024-02-14 09:33 UTC, acekyd commented
Haha no worries, Angie! <3