Kotlin validate submission pex
TBD54566975/developer.tbd.website pull request #1234
Opened 2024-02-13 19:46 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds the Kotlin code snippets for validateSubmission(). It also clarifies why we're creating a VP after creating a Presentation from Credentials. Eventually the JS will match this logic, but the SDK code is not merged yet.  

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-13 19:47 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +import web5.sdk.credentials.model.PresentationSubmission
I know I already included import web5.sdk.credentials.model.*, but for some strange reason that doesn't import PresentationSubmission, so that needs to be imported separately.

2024-02-13 19:48 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +import web5.sdk.credentials.model.PresentationSubmission
@nitro-neal any thoughts or advice on why I have to import web5.sdk.credentials.model.PresentationSubmission if I'm doing import web5.sdk.credentials.model.*

2024-02-13 23:10 UTC, angiejones requested changes

2024-02-13 23:10 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +      content: 'Bundle your VCs into one presentation by converting your presentation result into a [Verifiable Presentation](/docs/glossary#verifiable-presentation) with the `VerifiablePresentation.
```suggestion

```

I think we can remove the text. there's nothing special about the Kotlin snippet, and there's text above this already:

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/3e6d0955-0cc3-42f5-a1ed-5ce8a02be02d)

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/368c3a9a-24a0-4222-8e9f-32c3b0b85630)

2024-02-13 23:10 UTC, angiejones commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +      content: 'Once the [Presentation](/docs/glossary#verifiable-presentation) is error-free and has passed the validation checks, you can submit the Verifiable Presentation by providing the lender
For JS, why aren't we signing and returning the JWT like we're doing in Kotlin?

2024-02-13 23:11 UTC, nitro-neal commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +import web5.sdk.credentials.model.PresentationSubmission
That is pretty strange, could be ide or linter problem.

Does PresentationDefinition work with *?

Its probably better to import them individually instead of using * to be more explicit and not import unnecessary things, but yea is strange. I'll see if it happens on my end

2024-02-14 00:00 UTC, blackgirlbytes commented on site/docs/web5/build/verifiable-credentials/presentation-exchange.mdx
> +      content: 'Once the [Presentation](/docs/glossary#verifiable-presentation) is error-free and has passed the validation checks, you can submit the Verifiable Presentation by providing the lender
that's not available yet. I'm still waiting for that to be merged then released https://github.com/TBD54566975/web5-js/pull/382

2024-02-14 03:26 UTC, angiejones approved these changes

2024-02-14 05:28 UTC, merged