Snippets for tbDEX Credential Issuance Guide
TBD54566975/developer.tbd.website pull request #1254
Opened 2024-02-16 20:10 UTC by EbonyLouis

This improves the documentation and adds JS & KT tests for the tbDEX Credential Issuance guide.

issuance of verifiable credentials. The changes include updating package dependencies, adding new documentation, and implementing new tests.

Package dependencies:
* Added `express` as a new dependency
* Added `ktor-server-test-host` as a new kotlin dependency

Documentation:
* [`site/docs/tbdex/issuer/vc-issuance.mdx`](diffhunk://#diff-9e41b81f7d8a1a16c4dd5b46ed5718b051acb4e83678fdcfbaa80fd5485dbee0R1-R13): Updated instructions for environment setup and API service creation, and adding new code snippets for credential issuance. 

Testing:
* [`site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js`](diffhunk://#diff-a18b603b048f3707f802524323f5a101e35c51c0cbc225ded2c5695ec0e3d99fR1-R207): Added a new test file for credential issuance. This file tests the functionality of JWT verification, credential creation, and credential signing.
* [`site/testsuites/testsuite-kotlin/src/tests/kotlin/docs/tbdex/issuer/credentialIssuanceTest.kt`](diffhunk://#diff-a18b603b048f3707f802524323f5a101e35c51c0cbc225ded2c5695ec0e3d99fR1-R207): Added a new test file for credential issuance. This file tests the functionality of JWT verification, credential creation, and credential signing.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206393561850035

2024-02-16 20:41 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +1. Create a file to serve as your API's entry point (e.g. `main.js`), this is the `entry point` file that was created during the Express setup.
```suggestion
1. Ensure you have a file, such as `main.js`, to act as your API's entry point, which was created during the Express setup.
```

If the file was already created, we probably shouldn't tell them to Create a file

2024-02-16 20:41 UTC, angiejones commented on package.json
> +    "supertest": "6.3.3",
is this a new dependency? what's this for?

2024-02-16 20:48 UTC, EbonyLouis commented on package.json
> +    "supertest": "6.3.3",
at one point I was doing the most in my test testing the endpoint and then i realized I was doing too much again lol, so it's not needed anymore.

2024-02-17 02:20 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +  // we'll implement the API route here
```suggestion
  // implement the API route here
```

for future reference, in the tbDEX guides, I'd like us to steer away from terms like "we're". These are developers working in professional environments. They aren't completing a tutorial, they are building this for their company.

2024-02-17 02:21 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +4. Next, create an `api.js` file, this file will define the core API routes and logic for issuing credentials:
```suggestion
4. Next, create an `api.js` file. This file will define the core API routes and logic for issuing credentials:
```

2024-02-17 02:40 UTC, angiejones requested changes

2024-02-17 02:40 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +We'll use Express to set up the VC issuance service. Follow these instructions to [install Express](https://expressjs.com/en/starter/installing.html).
```suggestion
This example demonstrates how to use Express to set up the VC issuance service. Follow these instructions to [install Express](https://expressjs.com/en/starter/installing.html).
```

2024-02-17 02:40 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +In order to run this code, lets create a super simple `checkSanctionsLists()` function, you can place this at the top of your `api.js` file:
```suggestion
In order to run this code, create a `checkSanctionsLists()` function in your `api.js` file:
```

2024-02-17 02:40 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +Now back in your `"/check-sanctions"` endpoint, we're going to handle the results of the sanction check and create a Verifiable Credential:
```suggestion
The `/check-sanctions` endpoint should handle the results of the sanction check and create a Verifiable Credential:
```

2024-02-17 02:40 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +The entire PortableDid is used to sign Verifiable Credentials. Please refer to our [Create A DID](/docs/web5/build/decentralized-identifiers/how-to-create-did) Guide for steps on how to create one.
```suggestion
The BearerDid is used to sign Verifiable Credentials that you issue. Refer to the [Create A DID](/docs/web5/build/decentralized-identifiers/how-to-create-did) guide for steps on how to create one.
```

2024-02-17 02:40 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +## Run Issuance Service
```suggestion
## Test Issuance Service
```

since they will be running this in production, we should reframe this as just a test

2024-02-17 02:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +  did: 'did:key:z6MkgUZ55uLZGb4qcCLfZaJwCTXUxhxFJtKwkTaimigbaSqs',
use `DidDht` or `DidJwk`

2024-02-17 02:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +          d: 'xEv-wUYjDOi-SahxPCoKyuh8aqTiV6CtEgUfHg3ys2Y',
```suggestion
          d: '**********',
```

mask out private keys

2024-02-17 02:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +const signerDid = 'did:key:z6MkwcJi3yUN42EgSvrcGFQrC4JcZdzyVZHP9Wf1qQednVTP';
Use DidDht or DidJwk

2024-02-17 02:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +  // this is where you would add all the functionality to
```suggestion
   // This is where you would add the functionality to perform the actual sanction checks
```

2024-02-17 02:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +  // actually perform these sanction checks
```suggestion
  
```

2024-02-17 02:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +      'eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa3djSmkzeVVONDJFZ1N2cmNHRlFyQzRKY1pkenlWWkhQOVdmMXFRZWRuVlRQI3o2TWt3Y0ppM3lVTjQyRWdTdnJjR0ZRckM0SmNaZHp5VlpIUDlXZjFxUWVkblZUUCJ9.eyJ
```suggestion  'eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa3djSmkzeVVONDJFZ1N2cmNHRlFyQzRKY1pkenlWWkhQOVdmMXFRZWRuVlRQI3o2TWt3Y0ppM3lVTjQyRWdTdnJjR0ZRckM0SmNaZHp5VlpIUDlXZjFxUWVkblZUUCJ9.eyJ2YyI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiSWRlbnRpZmljYXRpb25DcmVkZW50aWFsIl0sImlkIjoidXJuOnV1aWQ6MDQ3ZTg0ZWItY2NhMS00NjFlLWFjZjAtMGMyZGE5ZDczOTNhIiwiaXNzdWVyIjoiZGlkOmtleTp6Nk1rd2NKaTN5VU40MkVnU3ZyY0dGUXJDNEpjWmR6eVZaSFA5V2YxcVFlZG5WVFAiLCJpc3N1YW5jZURhdGUiOiIyMDI0LTAyLTE1VDE5OjMyOjE2WiIsImNyZWRlbnRpYWxTdWJqZWN0Ijp7ImlkIjoiZGlkOmtleTp6Nk1rd2NKaTN5VU40MkVnU3ZyY0dGUXJDNEpjWmR6eVZaSFA5V2YxcVFlZG5WVFAiLCJuYW1lIjoiam9obiJ9fSwiaXNzIjoiZGlkOmtleTp6Nk1rd2NKaTN5VU40MkVnU3ZyY0dGUXJDNEpjWmR6eVZaSFA5V2YxcVFlZG5WVFAiLCJzdWIiOiJkaWQ6a2V5Ono2TWt3Y0ppM3lVTjQyRWdTdnJjR0ZRckM0SmNaZHp5VlpIUDlXZjFxUWVkblZUUCJ9.7oFAPckx-vxCbbzKSk9bU7eXlnjBFvMborl9woHCbcvWaLt0LvTRuDfvGDPC24V9D1K5OFpTnnBiN5jtIOmbBg';
```

2024-02-21 01:17 UTC, EbonyLouis commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +      'eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa3djSmkzeVVONDJFZ1N2cmNHRlFyQzRKY1pkenlWWkhQOVdmMXFRZWRuVlRQI3o2TWt3Y0ppM3lVTjQyRWdTdnJjR0ZRckM0SmNaZHp5VlpIUDlXZjFxUWVkblZUUCJ9.eyJ
If i remove this the test will fail

2024-02-21 01:45 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js
> +      'eyJ0eXAiOiJKV1QiLCJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa3djSmkzeVVONDJFZ1N2cmNHRlFyQzRKY1pkenlWWkhQOVdmMXFRZWRuVlRQI3o2TWt3Y0ppM3lVTjQyRWdTdnJjR0ZRckM0SmNaZHp5VlpIUDlXZjFxUWVkblZUUCJ9.eyJ
i was just try to remove the extra line and have it all on one. it's ok though, no biggy

2024-02-21 03:35 UTC, angiejones commented
build is failing and has merge conflicts. 

be sure to run `pnpm build` before running your tests. this error occurs locally, so you can catch it before committing.

```
Module not found: Error: Can"t resolve "@site/snippets/testsuite-kotlin/src/test/kotlin/docs/tbdex/issuer/checkSacntionsListsFunctionKt.snippet.kt" in "/opt/build/repo/site/docs/tbdex/issuer"
[ERROR] Client bundle compiled with errors therefore further build is impossible.
```

and then `pnpm test` exposes this:

```
 FAIL  site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/credentialIssuance.test.js > Direct method functionality tests > .sign() method signs the credential and includes expected fields
TypeError: Cannot read properties of undefined (reading 'verificationMethodKeys')
```

I'm pushing some fixes

2024-02-21 14:55 UTC, EbonyLouis commented
@angiejones thanks I'll do that going forward. I noticed the build fail when I pushed I was going to create an `issuerDid` in the test file to resolve it. 

But I noticed with your changes `.sign()` and `.create()` methods are no longer in the guide for Kotlin, did you want to show the entire code block like JS instead of breaking them up?

2024-02-21 16:54 UTC, angiejones commented
> @angiejones thanks I'll do that going forward. I noticed the build fail when I pushed I was going to create an `issuerDid` in the test file to resolve it.
> 
> But I noticed with your changes `.sign()` and `.create()` methods are no longer in the guide for Kotlin, did you want to show the entire code block like JS instead of breaking them up?

yes @EbonyLouis, the [original](https://developer.tbd.website/docs/tbdex/issuer/vc-issuance#design-the-credential) had everything but sign() in one block. The problem with your approach is the snippets were broken up and therefore weren't compiling. For example, the api.get() wasn't complete with a closing brace in its snippet file because another snippet was basically embedded in it, cutting it off. And the other snippets had return statements but were no longer apart of the api.get() function in their respective snippet files. So, it all got really messed up and I couldn't even get it to build.

2024-02-21 16:57 UTC, angiejones approved these changes

2024-02-21 17:00 UTC, merged