PFI/Quotes Testing
TBD54566975/developer.tbd.website pull request #1269
Opened 2024-02-21 22:20 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

Add JS testing for PFI/Quotes

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-21 23:00 UTC, chris-tbd commented
Looks to be an internal build issue - going to try and retrigger builds to get checks fixed

2024-02-22 00:05 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-start: pfiQuotesProcessJs
can you rename this to reflect the snippet? something like `pfiVerifyOfferingRequirements`

2024-02-22 00:13 UTC, angiejones commented
tests failing due to old class names being used. here's the [API Ref guide](https://tbd54566975.github.io/web5-js/classes/_web5_dids.DidDht.html) which includes the new way to create DIDs

```
 FAIL  site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js > PFI: Quotes
TypeError: Cannot read properties of undefined (reading 'create')
 ❯ site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js:20:33
     18|   beforeAll(async () => {
     19|     // Set up providers and DID
     20|     pfiDid = await DidDhtMethod.create({
```

2024-02-22 00:14 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +import { DidDhtMethod } from '@web5/dids';
In the latest version of web5, which the dev site uses, this is changed to `DidDht`

2024-02-22 00:15 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    pfiDid = await DidDhtMethod.create({
need to use `DidDht` and `options{}`. Search our Wallet guides for many examples of doing it the correct way

2024-02-22 05:09 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-start: pfiQuotesProcessJs
Updated

2024-02-22 05:09 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    const quoteData = DevTools.createQuoteData();
Removed

2024-02-22 05:10 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-start: pfiQuotesSendJs
Renamed

2024-02-22 05:10 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +import { DidDhtMethod } from '@web5/dids';
Updated

2024-02-22 05:10 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    pfiDid = await DidDhtMethod.create({
Updated

2024-02-22 05:17 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/offeringsApiProvider.js
> +                metadata: {
so `Offering.create()` is tbdex code but this snippet has no tests because it's in this provider class. how will we know to change this snippet if the Offerings signature changes in the SDK?

2024-02-22 05:20 UTC, angiejones requested changes

2024-02-22 05:20 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    pfiDid = await DidDht.create({
this requires `options{}`. this would be a syntax error surfaced by running `pnpm build` or `pnpm test`

```js
    pfiDid = await DidDht.create({
      options:{
        publish  : true,
        services : [{
          type            : 'PFI',
          id              : 'pfi',
          serviceEndpoint : 'http://localhost:9000'
        }]
      }
    })
```

2024-02-22 05:33 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
since we have a quotes guide on the wallet side too, let's name this file based on the guide `creatingQuotes.test.js`. That way it's clear which guide this is associated with and also that aspect of quotes this file deals with.

2024-02-22 05:37 UTC, angiejones requested changes

2024-02-22 05:37 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-end:
need an assertion for `await rfq.verifyOfferingRequirements(offering);`  can do this:

```js
    expect(() => {
    // :snippet-start: pfiVerifyOfferingRequirementsJs

     your code

   // :snippet-end:
    }).not.toThrow();
  });

2024-02-22 05:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-start: pfiVerifyOfferingRequirementsJs
looks like you added this snippet name to the wrong snippet. this one is `pfiGetOffering`

2024-02-22 05:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-start: pfiQuotesProcessJs
still the same

2024-02-22 06:59 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/offeringsApiProvider.js
> +                metadata: {
So if the `Offerings` signature had a breaking change (removed field, changed structure, etc.), that would automatically fail this test because `Offering.create()` would throw an error for invalid input. If it had a non-breaking change (i.e. added an optional parameter), then we would not have a check for that

2024-02-22 07:07 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-start: pfiQuotesProcessJs
Fixed

2024-02-22 07:07 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
Updated name

2024-02-22 07:08 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-start: pfiVerifyOfferingRequirementsJs
Fixed

2024-02-22 07:08 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/quotes.test.js
> +    // :snippet-end:
Updated

2024-02-22 16:15 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    }).not.toThrow();
ok this is not actually failing the test when the exception is thrown. I'll go in and add a different solution here. brb

2024-02-22 16:42 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +  test('PFI verifies required claims', async () => {
@chris-tbd I broke this out into its own test. You basically had 2 different tests in one `test()` function. We want to keep them standalone

2024-02-22 19:09 UTC, angiejones requested changes

2024-02-22 19:09 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    pfiDid = await DidDht.create({
this now takes `options{}`. Without that, the services are not actually being added to the DID

2024-02-22 19:11 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    senderDid = await DidDht.create({ publish: true });
```suggestion
    senderDid = await DidDht.create({
      options: { publish: true }
    })
```

2024-02-23 17:12 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    const consoleSpy = vi.spyOn(console, 'log');
got it - thanks for that! When I stepped through with the debugger I didn't see that exception - how did you catch it?

2024-02-23 17:13 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +  test('PFI verifies required claims', async () => {
Understood, thanks

2024-02-23 17:39 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    pfiDid = await DidDht.create({
Updated

2024-02-23 19:33 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    const consoleSpy = vi.spyOn(console, 'log');
I forced it to fail. I never trust a test that I haven't seen fail 😉

2024-02-23 19:35 UTC, angiejones approved these changes

2024-02-26 03:47 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    // :snippet-start: pfiRfqVerifyOfferingRequirementsJs
the Kotlin snippet shows some checks before accessing the rfq object. is any of this needed in JS?

```kotlin
if (offering is Offering && message is Rfq) {
        try {
            val rfq = message as Rfq
            rfq.verifyOfferingRequirements(offering)
        } catch (e: Exception) {
            println("Failed to verify offering requirements: ${e.message}")
        }
    }
```

2024-02-26 15:34 UTC, merged

2024-02-26 16:39 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +    // :snippet-start: pfiRfqVerifyOfferingRequirementsJs
No! this has to do with the inheritance pattern in Kotlin and the fact that JS isn't strictly typed