PFI/Quotes Kotlin Tests
TBD54566975/developer.tbd.website pull request #1272
Opened 2024-02-22 06:47 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-22 17:20 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
the `OfferingsApiProvider` class being embedded within this test class is so confusing, especially since it's used by other tests like your Quote test here. Same for `ExchangesApiProvider`. Can we move them out of here and into their own standalone files, pretty please?

2024-02-22 17:24 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
hmm whats the purpose of the `MockOfferingsApiProvider`? I thought the tests, like this Quote one, would use that?

2024-02-22 17:25 UTC, angiejones requested changes

2024-02-22 17:25 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
>          offeringsApiProvider.setOffering(message.metadata.id.toString(), pfiDid.uri)
Can you update the `setOffering` to take `message.metadata.id` without the `toString()`?

2024-02-22 17:33 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +        // Write the message to your exchanges database
You should write a bug against tbdex-kt because the `message.metadata.id` is of type `TypeId` and `OfferingsApi.getOffering()` requires a String. This forces you (and everyone else) to call `toString()` on this which is not a good DX.

Your line 72:

```kotlin
val offering = offeringsApiProvider.getOffering(message.metadata.id.toString())
```

2024-02-23 18:12 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiQuotesTest.kt
> +        // Write the message to your exchanges database
Agreed, issue here: https://github.com/TBD54566975/tbdex-kt/issues/182

2024-02-23 19:46 UTC, angiejones commented
Compilation errors. These should be caught locally

```
Error:  Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.22:test-compile (default-test-compile) on project kotlin-testsuite: Compilation failure: Compilation failure: 
Error:  /home/runner/work/developer.tbd.website/developer.tbd.website/site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/OfferingsApiProvider.kt:[11,34] Unresolved reference: TypeId
Error:  /home/runner/work/developer.tbd.website/developer.tbd.website/site/testsuites/testsuite-kotlin/src/test/kotlin/docs/utils/MockOfferingsApiProvider.kt:[16,34] Unresolved reference: TypeId
Error:  /home/runner/work/developer.tbd.website/developer.tbd.website/site/testsuites/testsuite-kotlin/src/test/kotlin/docs/utils/MockOfferingsApiProvider.kt:[37,25] Unresolved reference: TypeId
```

2024-02-26 03:33 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/OfferingsApiProvider.kt
> +    // override fun setOffering(id: TypeId, pfiDid: String) {
if you don't need these, let's delete the commented code

2024-02-26 04:12 UTC, angiejones commented
@chris-tbd is this ready to be put in Review status?

2024-02-26 18:06 UTC, angiejones approved these changes

2024-02-26 19:34 UTC, merged