Update Key Management for JS and Kotlin
TBD54566975/developer.tbd.website pull request #1283
Opened 2024-02-23 23:13 UTC by acekyd

## What type of PR is this? (check all applicable)

- [x] 📝 Documentation Update
- [x] 🧑‍💻 Code Snippet

## Description

This PR adds (JS & Kotlin) snippets and tests for Key management documentation

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

2024-02-25 23:47 UTC, angiejones requested changes

2024-02-25 23:47 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/KeyManagementTest.kt
> +        val testKeyManagement = initKeyManagement("production", "did:dht:abc123", null)
send in "dev" for env and "null" for the DID uri so that we're testing that a DID is actually created.

2024-02-25 23:47 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/KeyManagementTest.kt
> +        assertNotNull(testKeyManagement, "Key manager should not be null")
the assertion should test that the key manager for the DID is of type InMemoryManager()

2024-02-25 23:47 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/key-management.test.js
> +        expect(myResult).toBeDefined();
test that the DID has a LocalKeyManager

2024-02-25 23:50 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +[Decentralized Identifiers (DIDs)](/docs/web5/learn/decentralized-identifiers) are associated with public and private keys.
Add the language dropdown before this

2024-02-26 02:51 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/key-management.test.js
> +            did = await new DidDht(didUri, keyManager, didDhtApi);
I dont think DidDht takes these parms
https://tbd54566975.github.io/web5-js/classes/_web5_dids.DidDht.html#constructor

2024-02-27 16:07 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +      title: 'build.gradle.kts',
hm, I think these are older versions of our packages..or does it have to be 0.10.0? I think many places on our docs site say xyz.block:web5-crypto:0.0.11 and xyz.block:web5-dids:0.0.11, so maybe we should add that for consistency?

Also I think we don't have to use inline for these anymore. Might be good to shnip these

2024-02-28 13:06 UTC, acekyd commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +      title: 'build.gradle.kts',
Ah good catch. Thanks @blackgirlbytes. Updating

2024-02-28 13:09 UTC, angiejones requested changes

2024-02-28 13:09 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/key-management.test.js
> +        let did;
```suggestion

```

2024-02-28 13:09 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/key-management.test.js
> +            did = await DidDht.create(keyManager);
```suggestion
            return await DidDht.create(keyManager);
```

2024-02-28 13:09 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/key-management.test.js
> +            did = await DidDht.import({portableDid, keyManager});
```suggestion
            return await DidDht.import({portableDid, keyManager});
```

2024-02-28 13:09 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/key-management.test.js
> +        return did;
```suggestion

```

2024-02-28 13:09 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/key-management.test.js
> +
```suggestion

```

2024-02-28 15:02 UTC, angiejones approved these changes

2024-02-28 16:31 UTC, merged