PFI Orders Tests (Kotlin + JS)
TBD54566975/developer.tbd.website pull request #1288
Opened 2024-02-26 20:11 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-02-26 23:19 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOrdersTest.kt
can you rename to ProcessingOrdersTest.kt to match the guide?

2024-02-26 23:20 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
can you rename to processingOrders.test.js to match the guide?

2024-02-26 23:37 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        const consoleSpy = vi.spyOn(console, 'log');
```suggestion

```
No need to use spy

2024-02-26 23:39 UTC, angiejones requested changes

2024-02-26 23:39 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        try {
can delete 58-65 and just verify that `orderStatus.data.orderStatus` is equal to 'PROCESSING'

2024-02-26 23:41 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        const consoleSpy = vi.spyOn(console, 'log');
same here. no need to overdo the assertions. just make sure `closeMessage.data.reason` is equal to 'COMPLETED'

2024-02-26 23:42 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOrdersTest.kt
> +        assertNotNull(orderStatus.verify(), "OrderStatus signature is invalid")
verify the order status message

2024-02-26 23:48 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +            console.log(`Failed to verify offering requirements: ${e.message}`);
just add an assert fail here

2024-02-26 23:49 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +            console.log(`Failed to verify offering requirements: ${e.message}`);
add assert fail here

2024-02-26 23:50 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        expect(consoleSpy).not.toHaveBeenCalled();
```suggestion
 
```

2024-02-26 23:50 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        consoleSpy.mockRestore();
```suggestion
 
```

2024-02-26 23:50 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        expect(consoleSpy).not.toHaveBeenCalled();
```suggestion
 
```

2024-02-26 23:50 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        consoleSpy.mockRestore();
```suggestion
 
```

2024-02-26 23:51 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOrdersTest.kt
> +        assertNotNull(closeMessage.verify(), "Close signature is invalid")
I dont think this will catch if an exception is thrown. any reason you're not doing the same try/catch block like the other tests?

2024-02-26 23:53 UTC, angiejones requested changes
- update assertions to remove spy
- rename test files

2024-02-27 20:20 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOrdersTest.kt
> +        assertNotNull(closeMessage.verify(), "Close signature is invalid")
I tested with KT and these are caught, I believe we just need them in JS

2024-02-27 20:20 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOrdersTest.kt
> +        assertNotNull(orderStatus.verify(), "OrderStatus signature is invalid")
Added

2024-02-27 20:20 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiOrdersTest.kt
Updated

2024-02-27 20:20 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +            console.log(`Failed to verify offering requirements: ${e.message}`);
Updated

2024-02-27 20:20 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +        const consoleSpy = vi.spyOn(console, 'log');
Removed

2024-02-27 20:20 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
> +            console.log(`Failed to verify offering requirements: ${e.message}`);
Added

2024-02-27 20:20 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/orders.test.js
Updated

2024-02-27 20:34 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/processingOrders.test.js
> +            console.log(`Failed to verify offering requirements: ${e.message}`);
```suggestion

```

2024-02-27 20:35 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/processingOrders.test.js
> +            console.log(`Failed to verify offering requirements: ${e.message}`);
no need for console.log(). assert will print failure to console

2024-02-27 20:35 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/processingOrders.test.js
> +            assert.fail("Failed to verify offering requirements");
```suggestion
            assert.fail(`Failed to verify offering requirements: : ${e.message}`);
```

2024-02-27 20:36 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/processingOrders.test.js
> +            assert.fail("Failed to verify offering requirements");
```suggestion
            assert.fail(`Failed to verify offering requirements: ${e.message}`);
```

2024-02-27 21:10 UTC, angiejones approved these changes

2024-02-27 21:12 UTC, merged