add paymentInstructions to Kotlin snippets and align text on both Kotlin and JS
TBD54566975/developer.tbd.website pull request #1313
Opened 2024-03-07 17:45 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-07 17:56 UTC, blackgirlbytes approved these changes

2024-03-07 19:15 UTC, EbonyLouis approved these changes

2024-03-07 20:35 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +            link: 'https://example.pfi.io/instructions',
```suggestion
            link: 'https://example.com/instructions',
```
let's keep example.com as it's a default domain anyone can legally use in copy

2024-03-07 20:37 UTC, angiejones requested changes

2024-03-07 20:37 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +            link: 'https://example.pfi.io/instructions',
```suggestion
            link: 'https://example.com/paymentInstructions',
```

2024-03-07 20:37 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/CreatingQuotesTest.kt
> +                        link = "https://example.pfi.io/instructions",
```suggestion
                        link = "'https://example.com/paymentInstructions",
```

2024-03-07 20:37 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/CreatingQuotesTest.kt
> +                        link = "https://example.pfi.io/instructions",
```suggestion
                        link = "'https://example.com/paymentInstructions",
```

2024-03-07 20:38 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +            link: 'https://example.pfi.io/instructions',
need to update the JS links too

2024-03-08 00:32 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/creatingQuotes.test.js
> +            link: ''https://example.com/paymentInstructions',
```suggestion
            link: 'https://example.com/paymentInstructions',
```

2024-03-08 00:33 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/CreatingQuotesTest.kt
> +                        link = "'https://example.com/paymentInstructions",
```suggestion
                        link = "https://example.com/paymentInstructions",
```

2024-03-08 00:37 UTC, angiejones approved these changes

2024-03-08 17:23 UTC, merged