Add replyTo field to PFI Callbacks
TBD54566975/developer.tbd.website pull request #1320
Opened 2024-03-11 19:17 UTC by chris-tbd

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-12 00:02 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +    When you recieve an RFQ and an exchange between your PFI and a Wallet is initiated, there is an optional `replyTo` parameter that allows for Wallets to subscribe to callbacks for exchange data. I
```suggestion
When sending an RFQ message, the Wallet may also provide [an optional `replyTo` property](/docs/tbdex/wallet/send-rfq#send-rfq-to-pfi) that allows for Wallets to subscribe to callbacks for subsequent messages. If you receive a `replyTo` property, which is a fully qualified URI (URL or DID), then as the PFI you are responsible for sending all new messages back to the endpoint provided. The URI should be scoped only to that exchange, allowing the caller to to specify a different URI per exchange if they wish. If the `replyTo` property is not present, the caller will poll the exchange to get new messages.
```

2024-03-12 00:04 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/exchangesApiProvider.js
> +        if (message.replyTo != null) {
@phoebe-lew can you review this part to make sure it's correct?

2024-03-12 00:24 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/exchangesApiProvider.js
> +        if (message.replyTo != null) {
@chris-tbd this should be shown in the guide. Currently it's not.

2024-03-12 00:24 UTC, angiejones requested changes

2024-03-12 00:24 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/exchangesApiProvider.js
> +        if (message.replyTo != null) {
@chris-tbd this should be shown in the guide. Currently it's not.

2024-03-12 00:27 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +For example, after writing an `RFQ` to the database, you can [create a Quote](/docs/tbdex/pfi/creating-quotes).
@chris-tbd, I removed the language block since this is applicable in Kotlin as well (bug fix coming soon). Also added  **Callbacks** and **Writing Messages** headers for readability.

2024-03-13 05:17 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/exchangesApiProvider.js
> +        if (message.replyTo != null) {
I'm confused - it's shown in the snippet? Were you hoping for this code to be referenced in a line in the guide itself?

2024-03-13 05:17 UTC, chris-tbd commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +For example, after writing an `RFQ` to the database, you can [create a Quote](/docs/tbdex/pfi/creating-quotes).
Sounds good!

2024-03-13 15:45 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/exchangesApiProvider.js
> +        if (message.replyTo != null) {
hmm i didn't see it [here](https://deploy-preview-1320--tbd-website-developer.netlify.app/docs/tbdex/pfi/anatomy-of-a-pfi#writing-messages) originally, but I see it now. All good 👍🏾

2024-03-13 15:47 UTC, angiejones approved these changes

2024-03-13 15:51 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/exchangesApiProvider.js
> +        if (message.replyTo != null) {
Pheobe says:

> replyTo is currently a field on the POST /exchanges endpoint request body, not the message itself.

2024-03-13 15:54 UTC, angiejones requested changes
`replyTo` is not a property of `message`

```js
await TbdexHttpClient.sendMessage({
    message: rfq,
    replyTo: 'https://example.com/callback'
  });
  ```

2024-03-13 18:14 UTC, chris-tbd commented
> `replyTo` is not a property of `message`
> 
> ```js
> await TbdexHttpClient.sendMessage({
>     message: rfq,
>     replyTo: 'https://example.com/callback'
>   });
> ```

Updated

2024-03-13 19:27 UTC, angiejones approved these changes

2024-03-14 15:38 UTC, merged