Receive Quotes Swift Code snippets
TBD54566975/developer.tbd.website pull request #1327
Opened 2024-03-13 19:52 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [x] 📝 Documentation Update
- [x] 🧑‍💻 Code Snippet

## Description

This PR adds code snippets for receive codes using the Swift SDK

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

_Finally_
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYXUwYWlqdmhtb3IxbWMyb3VuYXRheW1mcXQzZHNwcnUxYnNsODBkZCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/iIoD0pCWEYfGU/giphy.gif)

2024-03-13 19:54 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +            let exchanges = try await tbDEXHttpClient.getExchanges(
I had to use getExchanges because getExchange is not implemented as yet @angiejones

2024-03-13 20:04 UTC, chris-tbd commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +    func mockGetExchange() {
Can we move this function into a `TestUtil.swift` or something similar to how we have `TestData.kt` and `DevTools.js`? I think it'd help clean each test file up a bunch - I can also help with that in a separate PR

2024-03-13 20:06 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +    func mockGetExchange() {
sure good idea

2024-03-13 23:46 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +            print("Failed to convert jsonString to Data")
can we remove the print and fail the test instead?

2024-03-13 23:50 UTC, angiejones requested changes

2024-03-13 23:50 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +            let exchanges = try await tbDEXHttpClient.getExchanges(
Kirah just merged `getExchange()`. Since we point to `main` in the dependencies, you should have it now and can update this.

cc: @chris-tbd

2024-03-13 23:53 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +                    paymentInstruction: nil
is this a required field? why can we set it to nil? should be optional then, yeah? can you double check this and see if we need to open a bug

2024-03-13 23:57 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +        XCTAssertEqual(closeMessage.metadata.exchangeID, exchangeID, "The exchangeID of the found quote does not match 'exchange_123'")
```suggestion
        XCTAssertEqual(closeMessage.metadata.exchangeID, exchangeID, "The exchangeID of the found quote does not match")
```

2024-03-13 23:58 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +        XCTAssertEqual(closeMessage.metadata.exchangeID, exchangeID, "The exchangeID of the found quote does not match 'exchange_123'")
just in case you ever change the variable value up top. the assertion will let us know what was expected, so no need to say it again in the message

2024-03-14 01:25 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +        XCTAssertEqual(closeMessage.metadata.exchangeID, exchangeID, "The exchangeID of the found quote does not match 'exchange_123'")
oh true!

2024-03-14 01:38 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +                    paymentInstruction: nil
oh good find! I took the field out and it still worked. Here's what's returned..It's default set to nil without me setting it.

```
Message<QuoteData>(metadata: tbDEX.MessageMetadata(id: TypeID.TypeID(prefix: "quote", uuid: 018E3A97-FF4D-7964-9E58-3D6E864FA91E), kind: tbDEX.MessageKind.quote, from: "did:dht:4ykjcjdq7udyjq5iy1qbcy98xnd4dkzuizm14ih4rn6953b8ohoo", to: "did:jwk:eyJ4IjoiaUl0T3QyOEZOUDdEdk1lVXVfZTdsMjJ6NHJld2xaaWEyWldFZTVsY0dYSSIsImt0eSI6Ik9LUCIsImFsZyI6IkVkRFNBIiwiY3J2IjoiRWQyNTUxOSIsImtpZCI6ImhucWR1Rl9lQlowZGp2aWdEMTZleHBOVzFnckk5MGt5Z0dUM1hQNkpiY2sifQ", exchangeID: "exchange_123", createdAt: 2024-03-14 01:33:43 +0000), data: tbDEX.QuoteData(expiresAt: 2024-03-14 01:34:43 +0000, payin: tbDEX.QuoteDetails(currencyCode: "USD", amount: "1.00", fee: nil, paymentInstruction: Optional(tbDEX.PaymentInstruction(link: Optional("https://example.com/pay"), instruction: Optional("Pay here")))), payout: tbDEX.QuoteDetails(currencyCode: "AUD", amount: "2.00", fee: Optional("0.50"), paymentInstruction: nil)), signature: nil, private: nil)
```

2024-03-14 01:47 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +            var message = Close(
thanks! I don't need it!

2024-03-14 20:18 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Package.resolved
> +        "revision" : "4f743986ca3344f1594283a10bf06d387ca99864"
updated Swift package to the latest!

2024-03-14 20:23 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/SendingRfqTests.swift
> +                    offeringId: offeringId,   // The ID of the selected offering
This test started failing because of the latest Swift package. RFQs are now structured a little differently I was having a hard time with offeringId so I had to write some additional logic above. Also, I had to move claims outside of the paren.

2024-03-14 20:55 UTC, angiejones requested changes

2024-03-14 20:55 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +                pfiDIDURI: rfq?.metadata.to ?? "",
the PFI DID can't be ""

2024-03-14 20:55 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +                exchangeId: rfq?.metadata.exchangeID ?? ""
exchangeId can't be ""

2024-03-14 21:05 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +                exchangeId: rfq?.metadata.exchangeID ?? ""
ohh okay I did that because I was getting this error that exchangeId parameter in the getExchange function call is optional, but the function expects a non-optional String...but what I could do is unwrap the objects and put it like this..but it wouldn't match the JS and Kotlin code snippets
```swift
        guard let exchangeId = rfq?.metadata.exchangeID else {
            XCTFail("Exchange ID not found")
            return
        }

          let messages = try await tbDEXHttpClient.getExchange(
                pfiDIDURI: pfiDidUri,
                requesterDID: customerDid,
                exchangeId: exchangeId
          )
```

2024-03-14 21:18 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +            let exchanges = try await tbDEXHttpClient.getExchanges(
awesome and done!

2024-03-14 23:03 UTC, blackgirlbytes commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift
> +    func mockGetExchange() {
oksy created a mock data file

2024-03-15 03:44 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/SendingRfqTests.swift
> +                    offeringId: offeringId,   // The ID of the selected offering
no, they wont know how to get the value for that variable. we have to show them how to get it from the offering

2024-03-15 03:52 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/SendingRfqTests.swift
> +                    offeringId: offeringId,   // The ID of the selected offering
this is actually a bug fix that I requested. with the new version of the SDK, this should be:

```swift
offeringId: selectedOffering!.metadata.id
```

2024-03-17 01:53 UTC, angiejones commented
@blackgirlbytes I [simplified](https://github.com/TBD54566975/developer.tbd.website/pull/1327/commits/dbf26d1aecc5a93e11c5e36d1a9731c6be7b2d73) a lot of this. you should be good to push now

2024-03-17 01:56 UTC, angiejones approved these changes

2024-03-18 03:29 UTC, blackgirlbytes commented
Thank you @angiejones. Looking at your updates to improve my Swift skills.

2024-03-18 03:30 UTC, merged