Known Customer Credential-IssuerJS
TBD54566975/developer.tbd.website pull request #1330
Opened 2024-03-14 22:11 UTC by EbonyLouis

This is (1/3) of our tbDEX Playbook guides for the known Customer Credential, along with JS test.

The changes include the creation of the Known Customer Credential Guide- Issuer's Flow, and implementing new JS tests.

### Documentation:

[site/docs/tbdex/issuer/kcc-issuer.mdx](https://github.com/TBD54566975/developer.tbd.website/commit/fa541e5555699030f535837c3599a6077ec52375): KCC Issuer's flow guide 

### Testing:

- [site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialIssuer.test.js](https://github.com/TBD54566975/developer.tbd.website/commit/fa541e5555699030f535837c3599a6077ec52375#diff-b0762acddf90c8709d560e4bb1f7d87b86606aad54678d9de32817a893e88e15): Added a new test file for known customer credential Issuer Flow Guide. This file tests the functionality of JWT verification, JWT Signing, credential creation, and credential signing.

### Technical Aspects to be added (possibly waiting on final confirmation):

- `authorization_pending` https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-token-error-response 
- Deferred Credential Request
- Deferred Credential Response 

### To see the specific tasks where the Asana app for GitHub is being used, see below:
https://app.asana.com/0/1206541162574147/1206744805611842

## [optional] What gif best describes this PR or how it makes you feel?

![](https://media.giphy.com/media/pynZagVcYxVUk/giphy.gif?cid=790b76112wgzhriiny9oe1p1lzwnbe0c1mm74vqlkxbpbn7n&ep=v1_gifs_trending&rid=giphy.gif&ct=g)

2024-03-15 04:36 UTC, angiejones requested changes

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +:::danger
```suggestion
:::danger Important
```

this changes the callout box title to say "IMPORTANT" instead of "DANGER"

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +IMPORTANT: This guide is intended for educational purposes only and does not constitute legal advice. Compliance programs may have varying requirements. Consult your legal and/or compliance advisors
```suggestion
This guide is intended for educational purposes only and does not constitute legal advice. Compliance programs may have varying requirements. Consult your legal and/or compliance advisors to ensure that the KCC is consistent with your legal and compliance obligations.
```

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
Need to put this in a new folder called Known Customer Credential

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/f299d36f-3f2a-4ba8-a252-27f0ae18d5fb)

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +Known Customer Credentials (KCCs) are [Verifiable Credentials](https://developer.tbd.website/docs/web5/learn/verifiable-credentials) designed to streamline the [Know Your Customer(KYC)](/docs/glossar
```suggestion
Known Customer Credentials (KCCs) are [Verifiable Credentials](/docs/web5/learn/verifiable-credentials) designed to streamline the Know Your Customer(KYC) process for tbDEX protocol users. KCCs help in gaining access to PFIs providing regulated financial services. For a comprehensive exploration of the practical applications and compliance considerations of KCCs, refer to our [KCC Guide](/). This resource provides detailed examples and insights into how KCCs align with certain regulatory requirements, offering valuable context for those overseeing the implementation and management of KCCs.
```

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +Known Customer Credentials (KCCs) are [Verifiable Credentials](https://developer.tbd.website/docs/web5/learn/verifiable-credentials) designed to streamline the [Know Your Customer(KYC)](/docs/glossar
please open an Asana issue to make sure we come back and update this with the correct link for the KCC Guide once it's published

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +- Performing [Identity Verification (IDV)](https://csrc.nist.gov/glossary/term/identity_verification#:~:text=1%20under%20Verification-,The%20process%20of%20confirming%20or%20denying%20that%20a%20clai
```suggestion
- Performing Identity Verification (IDV) as a necessary step **before** issuing a Known Customer Credential (KCC), following [Self Issued OpenID Provider V2 (SIOPv2)](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html) and [OpenID for Verifiable Presentation's (OID4VP)](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html) set of specifications.
```

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +For a detailed guide on Known Customer Credentials for Wallets, please refer to our [Wallet's Known Customer Credential Guide](https://hackmd.io/SQwE3SnrRkmeipGGtznJTw)
```suggestion
For a detailed guide on managing Known Customer Credentials as a Wallet application, please refer to the [Known Customer Credential Guide for Wallet Apps](/)
```

make Asana issue to update link once published

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +If you haven't already, please follow our [Credential Issuance Server Setup Guide](https://hackmd.io/4cW3D9BVQGCEuf1CEg47jA?both#Credential-Issuance-Enviornment-Setup-Guide) for detailed instructions
```suggestion
If you haven't already, please follow the [Credential Issuance Server Setup Guide](/) for detailed instructions on the dependencies and packages needed to set up your server.
```

Create Asana issue to update link once published

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +[**IDV Flow diagram**]
let's create an Asana ticket to track this

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +The IDV flow begins when the customer's agent (e.g. Wallet application) sends an HTTP request to the Issuer's [IDV service endpoint](https://hackmd.io/4cW3D9BVQGCEuf1CEg47jA?both#Issuers-Identity) sp
```suggestion
The IDV flow begins when the customer's agent (e.g. Wallet application) sends an HTTP request to the Issuer's [IDV service endpoint](https://hackmd.io/4cW3D9BVQGCEuf1CEg47jA?both#Issuers-Identity) specified in the Issuer's [Decentralized Identifier (DID) Document](/docs/glossary#did-document).
```

Create Asana ticket (one big one is fine) to track this link change

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +<LanguageSwitcher languages="JavaScript, Kotlin, Swift" />
```suggestion
<LanguageSwitcher languages="JavaScript, Kotlin" />
```

Swift not supported

2024-03-15 04:36 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +`vp_token` is a [Verifiable Presentation](/docs/glossary#verifiable-presentation) that contains certified and authenticated claims about the customer. In this guide we'll cover an example `vp_token`
```suggestion
`vp_token` is a [Verifiable Presentation](/docs/glossary#verifiable-presentation) that contains certified and authenticated claims about the customer. In this guide, we'll cover an example `vp_token`. To learn more refer to [OpenID's specs](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html#section-6.1-2.2).
```

2024-03-15 05:17 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +// Wallet id_token JWT response
i think you wanted this ('Wallet.js') to be the name of the file or no?

2024-03-15 12:25 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +When decoded here is the Human-Readable JSON of `id_token` and `vp_token`:
```suggestion
When decoded, here is the JSON of `id_token` and `vp_token`:
```

2024-03-15 12:27 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +When creating a Verifiable Credential you can design a model class to represent the specific type of credential you'd like to issue.
```suggestion
When creating a Verifiable Credential, you can design a model class to represent the specific type of credential you'd like to issue.
```

2024-03-15 12:28 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +Issuing a Known Customer Credential to a customer's Wallet confirms the successful completion of the Identity Verification Process. To create and securely sign this credential we will utilize the [we
```suggestion
Issuing a Known Customer Credential to a customer's Wallet confirms the successful completion of the Identity Verification Process. To create and securely sign this credential, we will utilize the [web5/credentials](https://www.npmjs.com/package/@web5/credentials) package.
```

2024-03-15 12:29 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +- `czZCaGRSa3F0MzpnWDFmQmF0M2JW`: Is the `access_token` that the Wallet recieved from the `/token` endpoint.
```suggestion
- `czZCaGRSa3F0MzpnWDFmQmF0M2JW`: The `access_token` that the Wallet recieved from the `/token` endpoint.
```

2024-03-15 12:30 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +:::danger
```suggestion
:::danger Important
```

2024-03-15 12:33 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +- **`response_type`**: Lets the wallet know the desired format, with `id_token` being required identity token and `vp_token` for _optional_ verifiable presentation token. The inclusion of `vp_token`
```suggestion
- **`response_type`**: Lets the Wallet know the desired format, with `id_token` being required identity token and `vp_token` for _optional_ verifiable presentation token. The inclusion of `vp_token` means a presentation definition is required within the request.
```

2024-03-15 12:33 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +- **`response_uri`**: Indicates the callback url for the wallet, ensuring direct communication between the wallet and the issuer.
```suggestion
- **`response_uri`**: Indicates the callback url for the Wallet, ensuring direct communication between the Wallet and the Issuer.
```

2024-03-15 12:34 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +Wallets use the `credential_issuer` from the Credential Offer to dynamically construct URLs for fetching issuer and authorization server metadata. These URLs, formed by appending `/.well-known/openid
```suggestion
Wallets use the `credential_issuer` from the Credential Offer to dynamically construct URLs for fetching issuer and authorization server metadata. These URLs, formed by appending `/.well-known/openid-credential-issuer` and` /.well-known/oauth-authorization-server` to the `credential_issuer`, allow Wallets to access up-to-date information on issuer capabilities and OAuth 2.0 endpoints. The next steps will cover how to properly configure these endpoints.
```

2024-03-15 12:34 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +- `credential_endpoint`: The endpoint the wallet will use to submit requests to issue credentials. After obtaining an access token, the wallet sends a credential request to this endpoint.
```suggestion
- `credential_endpoint`: The endpoint the Wallet will use to submit requests to issue credentials. After obtaining an access token, the Wallet sends a credential request to this endpoint.
```

2024-03-15 12:35 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialIssuer.test.js
> +  const walletResponse = req.body; // The SIOPv2 Authorization Response from the wallet
```suggestion
  const walletResponse = req.body; // The SIOPv2 Authorization Response from the Wallet
```

2024-03-15 12:35 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialIssuer.test.js
> +   * Extract and verify the ID Token from the wallet's response
```suggestion
   * Extract and verify the ID Token from the Wallet's response
```

2024-03-15 12:35 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialIssuer.test.js
> +     * Extract and verify the VP Token from the wallet's response
```suggestion
     * Extract and verify the VP Token from the Wallet's response
```

2024-03-15 12:36 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialIssuer.test.js
> +      // type of credentials issuer supports & what credential will look like
```suggestion
      // type of credentials Issuer supports and what credential will look like
```

2024-03-15 12:37 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +The SIOPv2 Authorization request contains information about you, the issuer, along with a [Presentation Definition](/docs/web5/build/verifiable-credentials/presentation-definition).
```suggestion
The SIOPv2 Authorization request contains information about you, the Issuer, along with a [Presentation Definition](/docs/web5/build/verifiable-credentials/presentation-definition).
```

2024-03-15 12:38 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +Wallets use the `credential_issuer` from the Credential Offer to dynamically construct URLs for fetching issuer and authorization server metadata. These URLs, formed by appending `/.well-known/openid
```suggestion
Wallets use the `credential_issuer` from the Credential Offer to dynamically construct URLs for fetching Issuer and Authorization Server Metadata. These URLs, formed by appending `/.well-known/openid-credential-issuer` and` /.well-known/oauth-authorization-server` to the `credential_issuer`, allow wallets to access up-to-date information on issuer capabilities and OAuth 2.0 endpoints. The next steps will cover how to properly configure these endpoints.
```

2024-03-15 12:39 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +- `issuer`: The base URL of the issuer's service.
```suggestion
- `issuer`: The base URL of the Issuer's service.
```

2024-03-15 12:39 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-issuer.mdx
> +1. Once the customer accepts your Credential Offer, the Wallet will then send a request for credentials to the endpoint specified in the `credential_endpoint` field of the issuer's metadata. Here is
```suggestion
1. Once the customer accepts your Credential Offer, the Wallet will then send a request for credentials to the endpoint specified in the `credential_endpoint` field of the Issuer's metadata. Here is an example of the Wallet's request:
```

2024-03-15 12:39 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialIssuer.test.js
> +      // Descriptive metadata about the requesting party (issuer)
```suggestion
      // Descriptive metadata about the requesting party (Issuer)
```

2024-03-15 12:40 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialIssuer.test.js
> +      // Descriptive metadata about the requesting party (issuer)
```suggestion
      // Descriptive metadata about the requesting party (Issuer)
```

2024-03-16 18:50 UTC, KendallWeihe commented
I'm seeing a 404 in the preview link and I'm a noob to this repo https://deploy-preview-1330--tbd-website-developer.netlify.app/docs/tbdex/issuer/Known%20Customer%20Credential/kcc-issuer

Could someone point me to the correct link so I can see this work in all it's GUI glory?

2024-03-16 19:00 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Issuing a KCC, following successful IDV.
Could we reference and link to OID4VCI in this bullet point (as we did for the other two specs in the first bullet point)?

https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html

2024-03-16 19:03 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +1. Implement an endpoint to handle incoming GET requests from the Wallet. When a request is received, you'll need to construct the [Self Issued OpenID Provider V2 (SIOPv2)](https://openid.github.io/S
```suggestion
1. Implement an endpoint to handle incoming GET requests from the Wallet. When a request is received, you'll need to construct the [SIOPv2 Authorization Request](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html#section-9).
```

2024-03-16 19:06 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Performing Identity Verification (IDV) as a necessary step **before** issuing a Known Customer Credential (KCC), following [Self Issued OpenID Provider V2 (SIOPv2)](https://openid.github.io/SIOPv2/
bit of a nit, but the word "following" is used here and two lines down in two different ways (this one means "compatible" and the next one means "subsequently"), maybe this line could be reworded to...

```suggestion
- Performing Identity Verification (IDV) as a necessary step **before** issuing a Known Customer Credential (KCC), by implementing an API compatible with [Self Issued OpenID Provider V2 (SIOPv2)](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html) and [OpenID for Verifiable Presentation's (OID4VP)](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html).
```

@decentralgabe what is the proper speak in the specification world for "compatible with?" Or is that proper?

2024-03-16 19:12 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +This approach is used when the goal is solely to authenticate the user without requesting any additional Verifiable Credentials:
```suggestion
This approach is used when a Verifiable Presentation is not an accepted form of IDV:
```

2024-03-16 19:13 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +This approach is used when you need to authenticate the user and also want to request specific Verifiable Credentials:
```suggestion
This approach is used when a Verifiable Presentation **is** an accepted form of IDV:
```

2024-03-16 19:19 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +3. The Wallet will then respond with a POST SIOPv2 Authorization Response. This response will be [JSON Web Tokens (JWTs)](https://jwt.io/). Here's an example response where `vp_token` and `id_token`
```suggestion
3. The Wallet will then respond with a POST [SIOPv2 Authorization Response](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html#section-10). The HTTP request body must include an `id_token` and optionally a `vp_token`, both of which must be [JSON Web Tokens (JWTs)](https://datatracker.ietf.org/doc/html/rfc7519). Here are examples of `id_token` and `vp_token`:
```

2024-03-16 19:19 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +  .Imlzc3VlckRpZC51cmkiLCJub25jZSI6Im4tMFM2X1d6QTJNaiIsImV4cCI6MTYxODg4NDQ3MywiaWF0IjoxNjE4ODgwODcz;
I think this should maybe all be on one line? not sure how the markup works here

2024-03-16 22:26 UTC, angiejones commented
> I'm seeing a 404 in the preview link and I'm a noob to this repo https://deploy-preview-1330--tbd-website-developer.netlify.app/docs/tbdex/issuer/Known%20Customer%20Credential/kcc-issuer
> 
> Could someone point me to the correct link so I can see this work in all it's GUI glory?

Here it is: https://deploy-preview-1330--tbd-website-developer.netlify.app/docs/tbdex/issuer/kcc/kcc-issuer

2024-03-17 18:27 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +  .Imlzc3VlckRpZC51cmkiLCJub25jZSI6Im4tMFM2X1d6QTJNaiIsImV4cCI6MTYxODg4NDQ3MywiaWF0IjoxNjE4ODgwODcz;
Oh okay, I see how the markup renders this, yeah this is good. Disregard.

<img width="699" alt="Screenshot 2024-03-17 at 2 27 33 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/3602993/e4e73349-4d30-4360-a53a-ec4c3a93b8b1">

2024-03-17 18:42 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +3. The Wallet will then respond with a POST SIOPv2 Authorization Response. This response will be [JSON Web Tokens (JWTs)](https://jwt.io/). Here's an example response where `vp_token` and `id_token`
What do you think about this instead...? (my concern is the reader may think the http request body is of type `text/plain` with the encoded JWT, or that decoded examples include the JWS Headers & Signature)

---

3. The Wallet will then respond with an HTTP POST [SIOPv2 Authorization Response](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html#section-10). The HTTP request body must include an `id_token` and optionally a `vp_token`, both of which must be [JSON Web Tokens (JWTs)](https://datatracker.ietf.org/doc/html/rfc7519). Here is an example HTTP POST request body (which includes the optional `vp_token`):

```javascript
// Wallet.js example HTTP POST request body

{
    "id_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJkaWQ6ZGh0OmN1c3RvbWVyRGlkIiwic3ViIjoiZGlkOmRodDpjdXN0b21lckRpZCIsImF1ZCI6Imlzc3VlckRpZC51cmkiLCJub25jZSI6Im4tMFM2X1d6QTJNaiIsImV4cCI6MTYxODg4NDQ3MywiaWF0IjoxNjE4ODgwODczfQGUuY29tL2NyZWRlbnRpYWxzLzE4NzIiLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiSURDYXJkQ3JlZGVudGlhbCJdLCJpc3N1ZXIiOnsiaWQiOiJkaWQ6ZXhhbXBsZTppc3N1ZXIifSwiaXNzdWFuY2VEYXRlIjoiMjAxMC0wMS0wMVQxOToyMzoyNFoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJnaXZlbl9uYW1lIjoiRnJlZHJpayIsImZhbWlseV9uYW1.Imlzc3VlckRpZC51cmkiLCJub25jZSI6Im4tMFM2X1d6QTJNaiIsImV4cCI6MTYxODg4NDQ3MywiaWF0IjoxNjE4ODgwODcz",
    "vp_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVQcmVzZW50YXRpb24iXSwidmVyaWZpYWJsZUNyZWRlbnRpYWwiOlt7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIiwiaHR0cHM6Ly93d3cudzMub3JnLzIwMTgvY3JlZGVudGlhbHMvZXhhbXBsZXMvdjEiXSwiaWQiOiJodHRwczovL2V4YW1wbGUuY29tL2NyZWRlbnRpYWxzLzE4NzIiLCJ0eXBlIjpbIlZlcmlmaWFibGVDcmVkZW50aWFsIiwiSURDYXJkQ3JlZGVudGlhbCJdLCJpc3N1ZXIiOnsiaWQiOiJkaWQ6ZXhhbXBsZTppc3N1ZXIifSwiaXNzdWFuY2VEYXRlIjoiMjAxMC0wMS0wMVQxOToyMzoyNFoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJnaXZlbl9uYW1lIjoiRnJlZHJpayIsImZhbWlseV9uYW1lIjoiU3RyJm9tYmVyZyIs.ImJpcnRoZGF0ZSI6IjE5NDktMDEtMjIifX1dLCJob2xkZXIiOiJkaWQ6ZXhhbXBsZTpob2xkZXIiLCJwcm9vZiI6eyJ0eXBlIjoiRWQyNTUxOVNpZ25hdHVyZTIwMTgiLCJjcmVhdGVkIjoiMjAyMS0wMy0xOVQxNTozMDoxNVoiLCJjaGFsbGVuZ2UiOiJuLTBTNl9XekEyTWoiLCJkb21haW4iOiJodHRwczovL2NsaWVudC5leGFtcGxlLm9yZy9jYiIsImp3cyI6ImV5SmhiR2NpT2lKSVV6STFOaUo5LkhvbGRlcl9GT1JfU0lHTkFUVVJFIiwicHJvb2ZQdXJwb3NlIjoiYXV0aGVudGljYXRpb24iLCJ2ZXJpZmljYXRpb25NZXRob2QiOiJkaWQ6ZXhhbXBsZTpob2xkZXIja2V5LTEifX0"
}
```

The decoded [JWT Claims](https://datatracker.ietf.org/doc/html/rfc7519#section-4) for the `id_token` and `vp_token` are as follows:

```javascript
// Wallet.js id_token decoded JWT claims

{
    "iss": "did:dht:customerDid",
    "sub": "did:dht:customerDid", // Customer's DID string
    "aud": "did:dht:issuerDid", // Issuer's DID string
    "nonce": "n-0S6_WzA2Mj", // Unique string from the Issuer's Auth request
    "exp": 1618884473, // Expiration time
    "iat": 1618880873 // issued at time
}
```

```javascript
// Wallet.js vp_token decoded JWT claims

{
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://identity.foundation/presentation-exchange/submission/v1"
    ],
    "type": ["VerifiablePresentation", "PresentationSubmission"],
    "presentation_submission": {
      "id": "epzZXstAcVNt5MRrcyG91",
      "definition_id": "IDCardCredentials",
      "descriptor_map": [
        {
          "id": "IDCardCredential",
          "format": "jwt_vc",
          "path": "$.verifiableCredential[0]"
        },
        {
          "id": "nationalIdentifierVerification",
          "format": "jwt_vc",
          "path": "$.verifiableCredential[1]"
        }
      ]
    },
    "verifiableCredential": [
      "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDprZXk6ejZNa2VyNDlDbnVnN2hzdkhEZ3Y0NHl2cGR2dE1oNHlMaURYeFM2N2huclVodHQyI3o2TWtlcjQ5Q251Zzdoc3ZIRGd2NDR5dnBkdnRNaDR5TGlEWHhTNjdobnJVaHR0MiJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtlcjQ5Q251Zzdoc3ZIRGd2NDR5dnBkdnRNaDR5TGlEWHhTNjdobnJVaHR0MiIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJFbXBsb3ltZW50Q3JlZGVudGlhbCJdLCJpZCI6InVybjp1dWlkOjcyNDhiOTkyLTkwOTYtNDk2NS1hMGVjLTc3ZDhhODNhMWRmYiIsImlzc3VlciI6ImRpZDprZXk6ejZNa2VyNDlDbnVnN2hzdkhEZ3Y0NHl2cGR2dE1oNHlMaURYeFM2N2huclVodHQyIiwiaXNzdWFuY2VEYXRlIjoiMjAyMy0xMi0yMVQyMDoxMToyNVoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDppb246RWlEMTR4UmY0cTJNWlh1ZWY2X2ZXYnBGbVlTUG94dGFxTkp1SmdEMG96Wl84UTpleUprWld4MFlTSTZleUp3WVhSamFHVnpJanBiZXlKaFkzUnBiMjRpT2lKeVpYQnNZV05sSWl3aVpHOWpkVzFsYm5RaU9uc2ljSFZpYkdsalMyVjVjeUk2VzNzaWFXUWlPaUprZDI0dGMybG5JaXdpY0hWaWJHbGpTMlY1U25kcklqcDdJbU55ZGlJNklrVmtNalUxTVRraUxDSnJkSGtpT2lKUFMxQWlMQ0o0SWpvaWVubGFNbVYzTlhKeVVXdFVjbUV3WlZsVk16WlBTblJzTURCbFJWZHhhalZhV0dkNmNEZFpSVTVKUVNKOUxDSndkWEp3YjNObGN5STZXeUpoZFhSb1pXNTBhV05oZEdsdmJpSmRMQ0owZVhCbElqb2lTbk52YmxkbFlrdGxlVEl3TWpBaWZTeDdJbWxrSWpvaVpIZHVMV1Z1WXlJc0luQjFZbXhwWTB0bGVVcDNheUk2ZXlKamNuWWlPaUp6WldOd01qVTJhekVpTENKcmRIa2lPaUpGUXlJc0luZ2lPaUpQZDJZMFQyMUViamxKWm5SNFdYWnBkRTFHWm1jMVVXeDVMVVV6VWs1b1dsUkdPVlpFTWtnNVQzVjNJaXdpZVNJNkltUnZjVmxtV2s1c1NtRlRNVll4U201bU9HdEZObEF6VkRsd2QzaDNla3hFVTJWc1ZqTlRUa2s1U2xFaWZTd2ljSFZ5Y0c5elpYTWlPbHNpYTJWNVFXZHlaV1Z0Wlc1MElsMHNJblI1Y0dVaU9pSktjMjl1VjJWaVMyVjVNakF5TUNKOVhTd2ljMlZ5ZG1salpYTWlPbHQ3SW1sa0lqb2laSGR1SWl3aWMyVnlkbWxqWlVWdVpIQnZhVzUwSWpwN0ltVnVZM0o1Y0hScGIyNUxaWGx6SWpwYklpTmtkMjR0Wlc1aklsMHNJbTV2WkdWeklqcGJJbWgwZEhCek9pOHZaSGR1TG5SaVpHUmxkaTV2Y21jdlpIZHVOaUlzSW1oMGRIQnpPaTh2WkhkdUxuUmlaR1JsZGk1dmNtY3ZaSGR1TUNKZExDSnphV2R1YVc1blMyVjVjeUk2V3lJalpIZHVMWE5wWnlKZGZTd2lkSGx3WlNJNklrUmxZMlZ1ZEhKaGJHbDZaV1JYWldKT2IyUmxJbjFkZlgxZExDSjFjR1JoZEdWRGIyMXRhWFJ0Wlc1MElqb2lSV2xEWm05bVFUQkpVbU5uY2tWdVVHZHdRbU5RV1ZsV2VFWlliR0pTYjJRd2RVNWZRVkJwTkVrNUxVRmZRU0o5TENKemRXWm1hWGhFWVhSaElqcDdJbVJsYkhSaFNHRnphQ0k2SWtWcFFtd3pWWG80VldGT2REZGxlREJKYjJJMFJFNXNhbFJGVmpaelQwTmtjbFJ3TWxvNE5FTkJPVFJPUWtFaUxDSnlaV052ZG1WeWVVTnZiVzFwZEcxbGJuUWlPaUpGYVVOWk9WRldZbWRKYkUxemRraEZYMVJtTld4a1MxQjBkR3d3WVV4blNrdHNSbmt6Vms0d2QzQTJhVFpSSW4xOSIsImVtcGxveW1lbnRTdGF0dXMiOiJlbXBsb3llZCJ9fX0.Sazc8Ndhs-NKjxvtVMKeC9dxjEkI26fVsp2kFNWM-SYLtxMzKvl5ffeWd81ysHgPmBBSk2ar4dMqGgUsyM4gAQ",
      "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6ImRpZDprZXk6ejZNa2pwUzRHVUFoYmdCSmg2azJnZTZvWTQ0UUxyRXA3NXJadHNqYVRLb3JSRGR0I3o2TWtqcFM0R1VBaGJnQkpoNmsyZ2U2b1k0NFFMckVwNzVyWnRzamFUS29yUkRkdCJ9.eyJpc3MiOiJkaWQ6a2V5Ono2TWtqcFM0R1VBaGJnQkpoNmsyZ2U2b1k0NFFMckVwNzVyWnRzamFUS29yUkRkdCIsInZjIjp7IkBjb250ZXh0IjpbImh0dHBzOi8vd3d3LnczLm9yZy8yMDE4L2NyZWRlbnRpYWxzL3YxIl0sInR5cGUiOlsiVmVyaWZpYWJsZUNyZWRlbnRpYWwiLCJOYW1lQW5kRG9iQ3JlZGVudGlhbCJdLCJpZCI6InVybjp1dWlkOjliZjM2YzY5LTI0ODAtNDllZC1iMTYyLTRlZDEwOWE3MTc3NyIsImlzc3VlciI6ImRpZDprZXk6ejZNa2pwUzRHVUFoYmdCSmg2azJnZTZvWTQ0UUxyRXA3NXJadHNqYVRLb3JSRGR0IiwiaXNzdWFuY2VEYXRlIjoiMjAyMy0xMi0yMVQyMDowNjowMVoiLCJjcmVkZW50aWFsU3ViamVjdCI6eyJpZCI6ImRpZDppb246RWlDS2o2M0FyZlBGcEpsb2lTd3gxQUhxVWtpWlNoSDZGdnZoSzRaTl9fZDFtQTpleUprWld4MFlTSTZleUp3WVhSamFHVnpJanBiZXlKaFkzUnBiMjRpT2lKeVpYQnNZV05sSWl3aVpHOWpkVzFsYm5RaU9uc2ljSFZpYkdsalMyVjVjeUk2VzNzaWFXUWlPaUprZDI0dGMybG5JaXdpY0hWaWJHbGpTMlY1U25kcklqcDdJbU55ZGlJNklrVmtNalUxTVRraUxDSnJkSGtpT2lKUFMxQWlMQ0o0SWpvaWNscFdXbTVJVkVrNWFEWkJUVmxVV0dwT01HcFhTVkYwTTI5ak4xTnJTeTF4Y2kxcVVuSTBUalEzUlNKOUxDSndkWEp3YjNObGN5STZXeUpoZFhSb1pXNTBhV05oZEdsdmJpSmRMQ0owZVhCbElqb2lTbk52YmxkbFlrdGxlVEl3TWpBaWZTeDdJbWxrSWpvaVpIZHVMV1Z1WXlJc0luQjFZbXhwWTB0bGVVcDNheUk2ZXlKamNuWWlPaUp6WldOd01qVTJhekVpTENKcmRIa2lPaUpGUXlJc0luZ2lPaUpaVDFwRE5WSmlUMHQ1T0dadVVUWTJVWEZPUkc5aldFMXZPVXhUZEdNNVYyOWthMHd0ZFZCZlExQnZJaXdpZVNJNklsWnZZM0UxVERodFozQlhXVTFrYjFwS1JrWlJUa1ZDT0hsR0xXTndkRWQzZFdkcFRWVm5hR2t6Y21jaWZTd2ljSFZ5Y0c5elpYTWlPbHNpYTJWNVFXZHlaV1Z0Wlc1MElsMHNJblI1Y0dVaU9pSktjMjl1VjJWaVMyVjVNakF5TUNKOVhTd2ljMlZ5ZG1salpYTWlPbHQ3SW1sa0lqb2laSGR1SWl3aWMyVnlkbWxqWlVWdVpIQnZhVzUwSWpwN0ltVnVZM0o1Y0hScGIyNUxaWGx6SWpwYklpTmtkMjR0Wlc1aklsMHNJbTV2WkdWeklqcGJJbWgwZEhCek9pOHZaSGR1TG5SaVpHUmxkaTV2Y21jdlpIZHVOaUlzSW1oMGRIQnpPaTh2WkhkdUxuUmlaR1JsZGk1dmNtY3ZaSGR1TUNKZExDSnphV2R1YVc1blMyVjVjeUk2V3lJalpIZHVMWE5wWnlKZGZTd2lkSGx3WlNJNklrUmxZMlZ1ZEhKaGJHb [...]

2024-03-17 18:50 UTC, KendallWeihe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/known customer credential/knownCustomerCredentialIssuer.test.js
> +        url: 'https://issuer.example.com/idv/form', // IDV Request form
the `url` is adjacent to the `credential_offer` in the HTTP response body https://github.com/TBD54566975/known-customer-credential#idv-request

2024-03-17 18:53 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +4. Implement a `/siopv2/response` endpoint to process and verify the Wallet's response. If the Wallet's response includes a [Verifiable Presentation](/docs/glossary#verifiable-presentation) (`vp_toke
```suggestion
4. Implement a `/siopv2/response` endpoint to process and verify the Wallet's response. The HTTP response body must always include a `credential_offer`. If the Wallet's response does not include a `vp_token`, as a valid form of IDV, then the HTTP response body must also include a URL directing the Wallet to an Identity Verification form:
```

Some of this language is duplicative of the `:::info` note you have below, so feel free to wrangle it how you think best, but just want to call out that URL is not within the credential offer but beside it ([more info here](https://github.com/TBD54566975/known-customer-credential#idv-request))

2024-03-18 18:14 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Performing Identity Verification (IDV) as a necessary step **before** issuing a Known Customer Credential (KCC), following [Self Issued OpenID Provider V2 (SIOPv2)](https://openid.github.io/SIOPv2/
usually we use the word _conformance_ so something like _conformant with_ would work

2024-03-18 18:15 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +The IDV flow begins when the customer's agent (e.g. Wallet application) sends an HTTP request to the Issuer's [IDV service endpoint](https://hackmd.io/4cW3D9BVQGCEuf1CEg47jA?both#Issuers-Identity) sp
should this point to something besides hackmd?

2024-03-18 18:36 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +`id_token` is a Self Issued Identity Token, that authenticates the customer to the Issuer by sharing the customer's Decentralized Identifier. This guide will cover an example `id_token` to learn more
```suggestion
`id_token` is a Self Issued Identity Token, that authenticates the customer to the Issuer by sharing the customer's Decentralized Identifier. This guide will cover an example `id_token` to learn more refer to [OpenID's specs](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html#name-self-issued-id-token).
```

2024-03-18 18:37 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +3. The Wallet will then respond with a POST SIOPv2 Authorization Response. This response will be [JSON Web Tokens (JWTs)](https://jwt.io/). Here's an example response where `vp_token` and `id_token`
I like pulling it out like this

2024-03-18 19:20 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +The IDV flow begins when the customer's agent (e.g. Wallet application) sends an HTTP request to the Issuer's [IDV service endpoint](https://hackmd.io/4cW3D9BVQGCEuf1CEg47jA?both#Issuers-Identity) sp
Yes all the links will be updated before we merge next week.

2024-03-19 15:07 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- **`urn:ietf:params:oauth:grant-type:pre-authorized_code`**: Grant type that allows the Wallet to follow a Pre-Authorized code flow skipping any PII steps because they've already completed it.
```suggestion
- **`urn:ietf:params:oauth:grant-type:pre-authorized_code`**: Grant type required for the [OID4VCI](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#appendix-B.1) Pre-Authorization flow.
```

2024-03-19 15:07 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +Wallets use the `credential_issuer` from the Credential Offer to dynamically construct URLs for fetching Issuer and Authorization Server Metadata. These URLs, formed by appending `/.well-known/openid
lil space 

```suggestion
Wallets use the `credential_issuer` from the Credential Offer to dynamically construct URLs for fetching Issuer and Authorization Server Metadata. These URLs, formed by appending `/.well-known/openid-credential-issuer` and `/.well-known/oauth-authorization-server` to the `credential_issuer`, allow wallets to access up-to-date information on issuer capabilities and OAuth 2.0 endpoints. The next steps will cover how to properly configure these endpoints.
```

2024-03-19 15:55 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Issuing a KCC, following successful IDV.
@KendallWeihe for this one you're saying we should link to it here?: 

Issuing a KCC, following successful [IDV](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html).

2024-03-19 15:56 UTC, KendallWeihe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/known customer credential/knownCustomerCredentialIssuer.test.js
> +    this.country = country;
Should we add more fields to this or is `country` enough to prove the point?

2024-03-19 15:59 UTC, EbonyLouis commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/known customer credential/knownCustomerCredentialIssuer.test.js
> +    this.country = country;
based on discussions with Moe and Nick at the moment they only want `country` but this could change after this offsite

2024-03-19 15:59 UTC, KendallWeihe commented
From the PR description:

> authorization_pending https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html#name-token-error-response
> Deferred Credential Request
> Deferred Credential Response

We can exclude the deferred credential flows, but we should include the `authorization_pending` because that will be a required error response. I know we don't have that defined in the KCC doc yet, so I'll make that a priority.

2024-03-19 16:04 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Issuing a KCC, following successful IDV.
```suggestion
- Performing Identity Verification (IDV) as a necessary step **before** issuing a Known Customer Credential (KCC), following [Self Issued OpenID Provider V2 (SIOPv2)](https://openid.github.io/SIOPv2/openid-connect-self-issued-v2-wg-draft.html) and [OpenID for Verifiable Presentation's (OID4VP)](https://openid.net/specs/openid-4-verifiable-presentations-1_0.html) set of specifications.
- Designing a KCC, detailing the required properties.
- Issuing a KCC, conformant with [OID4VCI](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html), following successful IDV.
```

2024-03-19 17:48 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Issuing a KCC, conformant with [OID4VCI](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html), following successful IDV.
To be consistent with the first bullet point:

```suggestion
- Issuing a KCC, conformant with [OpenID for Verifiable Credential Issuance (OID4VCI)](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html), following successful IDV.
```

2024-03-19 17:49 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +1. Implement an endpoint to handle incoming GET requests from the Wallet. When a request is received, you'll need to construct the [SIOPv2 Authorization Request](https://openid.github.io/SIOPv2/openi
this is the right link, just calling out it's important we reference the same draft across our docs

2024-03-19 17:52 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +        "path": "$.verifiableCredential[0]"
believe this (and below) should be `$.vp.verifiableCredential[0]`

2024-03-19 17:53 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +        "format": "jwt_vc",
this should be `jwt_vp`

2024-03-19 17:57 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +1. Implement an endpoint to handle incoming GET requests from the Wallet. When a request is received, you'll need to construct the [SIOPv2 Authorization Request](https://openid.github.io/SIOPv2/openi
I had the same thought, and it's going to be difficult to keep these up to date. @decentralgabe I noticed OID4VCI and OID4VP urls are both 1.0 even tho they are marked as a draft, but then the SIOPv2 URL has "draft" within it. Do you know if there is a 1.0 equivalent for the SIOPv2 spec?

Else @EbonyLouis we're going to have to keep an eye on this and once new drafts/URLs are published we'll have to go back through everywhere and update

2024-03-19 18:29 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +The IDV Request Form points to a webpage for the customer to input their Personal Identifiable Information(PII) (e.g.; name, identification number, date of birth, etc).
```suggestion
The IDV Request Form points to a webpage for the customer to input their Personal Identifiable Information (PII) (e.g.; name, identification number, date of birth, etc).  
```

2024-03-19 18:32 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- `credential_configurations_supported`: Defines the format `jwt_vc_json` and the credential.
```suggestion
- `credential_configurations_supported`: Defines the format `jwt_vc_json`, and the credential, including informative display markup.
```

2024-03-19 18:35 UTC, KendallWeihe commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- `czZCaGRSa3F0MzpnWDFmQmF0M2JW`: The `access_token` that the Wallet recieved from the `/token` endpoint.
```suggestion
- `Authorization: Bearer {jwt}`: The `access_token` that the Wallet recieved from the `/token` endpoint.
```

2024-03-19 18:40 UTC, KendallWeihe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/known customer credential/knownCustomerCredentialIssuer.test.js
> +    }
```suggestion
    try {
      const verificationResult = await Jwt.verify({ jwt: proof.jwt });
      customersDidUri = verificationResult.payload.iss; // Customer's DID string

      if (storedCNonce === payload.nonce) {
        accessTokenToCNonceMap.delete(accessToken)
      } else {
        return res.status(401).json({ errors: ['Invalid nonce in proof'] });  
      }
    } catch (error) {
      return res.status(401).json({ errors: ['Invalid JWT in proof'] });
    }
```

2024-03-20 06:15 UTC, angiejones commented
@EbonyLouis I was walking someone through the doc today and realized we don't have the actual JSON of the VC shown anywhere. Can we add this at the end? With some fields being implicit, it would be great to show what the actual credential looks like.

2024-03-20 15:28 UTC, KendallWeihe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/known customer credential/knownCustomerCredentialIssuer.test.js
> +    res.json({
We also need the issuer to invalidate the pre auth code upon successful issuance of the access token

```suggestion
    accessTokenToCNonceMap.set(accessToken, cNonce);

    preAuthCodeToDidMap.delete(code)

    res.json({
```

2024-03-20 15:29 UTC, KendallWeihe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/known customer credential/knownCustomerCredentialIssuer.test.js
> +  /*******************************************
Part 1 of my proposal for how we introduce the `authorization_pending` into this guide

```suggestion
  }

  const idvCompleted = checkIDVStatus(customersDidUri); // some function to check the status of the IDV
  if (idvCompleted) {
    return res.status(400).json({ error: 'authorization_pending' });
  }

  /*******************************************
```

2024-03-20 19:50 UTC, chris-tbd requested changes

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Designing a KCC, detailing the required properties.
Designing and detailing the required properties of a KCC

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +- Issuing a KCC, conformant with [OpenID for Verifiable Credential Issuance (OID4VCI)](https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html), following successful IDV.
nit: remove commas

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +:::info
Do we need to take this out pending tbdex.io launch?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +If you haven't already, please follow the [Credential Issuance Server Setup Guide](/) for detailed instructions on the dependencies and packages needed to set up your server.
Missing link?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +Identity Verification (IDV) is a critical component of typical Know Your Customer (KYC) requirements, where certain types of Personally Identifying Information (PII) are collected and verified from a
I don't think we need to re-state abbreviations here since we already used them earlier in the article

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +[**IDV Flow diagram**]
I will add this

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +
Since this is an issuer-focused guide, I think we may want to add something here to the effect of "by the time you've completed this guide, you'll have the technical tool to perform IDV as well as design and issue a KCC."

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +1. Implement an endpoint to handle incoming GET requests from the Wallet. When a request is received, you'll need to construct the [SIOPv2 Authorization Request](https://openid.github.io/SIOPv2/openi
Remove numbering?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +This approach is used when a Verifiable Presentation is **not** an accepted form of IDV:
Link or explainer on what this is

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +      title: 'Issuer api.js for id_token only ',
Do we need separate titles for each of these, or can we have one title above this?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +This approach is used when a Verifiable Presentation is **not** an accepted form of IDV:
When a Verifiable Presentation is not an accepted form of IDV, you can respond to the customer's Wallet application by requesting only an `id_token` from them:

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +This approach is used when a Verifiable Presentation **is** an accepted form of IDV:
When a Verifiable Presentation is an accepted form of IDV, you can respond to the customer's Wallet application by requesting an `id_token` and a `vp_token` from them:

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +The SIOPv2 Authorization request contains information about you, the Issuer, along with a [Presentation Definition](/docs/web5/build/verifiable-credentials/presentation-definition).
Can you clarify here whether the Authorization request is the request you as the issuer sent or the requests the Wallet sent? The reader might not have internalized the diagram or other info yet so it can be helpful to restate:

"The SOIPv2 Authorization request above that you as the issuer send to your customer contains the following key information about you as well as the Presentation Definition"

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +2. Encode the SIOPv2 Authorization Request and respond:
The numbering is a little confusing since it seems like the above is really 1a) or 1b) - can we clarify the numbering or nix the numbering in favor of using headings?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +2. Encode the SIOPv2 Authorization Request and respond:
Can we do a `...` or something similar to compress the whole `SOIPv2` object above so it isn't taking up so much space? That way we can focus on what's new

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +The decoded [JWT Claims](https://datatracker.ietf.org/doc/html/rfc7519#section-4) for the `id_token` and `vp_token` are as follows:
I realized here that the only definition of the `id_token` comes in a note, and there is no definition for `vp_token`. Can we add clear definitions or links for both of them at the top of these instructions?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +```
To save vertical space let's put these in breadcrumbs or tabs

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +4. Implement a `/siopv2/response` endpoint to process and verify the Wallet's response. The HTTP response body must always include a `credential_offer`. If the Wallet's response does not include a `v
is this a standard endpoint name, or just something that makes the most sense?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +4. Implement a `/siopv2/response` endpoint to process and verify the Wallet's response. The HTTP response body must always include a `credential_offer`. If the Wallet's response does not include a `v
remove comma

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +<Shnip
Is there any way we can break these snippets up, even using breadcrumbs? The comment headers are super helpful, wanted to see if you had any ideas

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +#### Credential Offer Details:
It's unclear what the credential offer is - can we include a definition here or a reference prior to this section since it is referred to in the code?

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +5. Configure the `/.well-known/openid-credential-issuer` endpoint that will return the Issuer's Metadata:
your Issuer metadata

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +When creating a Verifiable Credential, you can design a model class to represent the specific type of credential you'd like to issue.
Link to Web5 docs with background info on credentials and credential design

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +When creating a Verifiable Credential, you can design a model class to represent the specific type of credential you'd like to issue.
We also want to tell devs what does and doesn't go into this design!

2024-03-20 19:50 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +      "jwt": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDpqd2s6ZXlKcmRIa2lPaUpQUzFBaUxDSmpjbllpT2lKRlpESTFOVEU1SWl3aWVDSTZJalp0TFU1NE9HWndSMWxUT0ZoV04xZ3hVVmN4YWxKdVdHNHRUV1JxVWpJM1ptSktZVGhGVmt0bmEyTWlmUSMwI
Do we actually need this snippet in this guide, or just the wallet guide?

2024-03-20 19:51 UTC, chris-tbd commented
Is there a way we can set the `maxHeight` of code blocks? I think they get really long here (understandably so) and making code blocks scrollable could help with readability of the overall guide

2024-03-20 19:58 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +:::info
not sure what you mean?

2024-03-20 19:58 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +If you haven't already, please follow the [Credential Issuance Server Setup Guide](/) for detailed instructions on the dependencies and packages needed to set up your server.
thanks, adding all missing links before we push this out

2024-03-20 20:03 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +When creating a Verifiable Credential, you can design a model class to represent the specific type of credential you'd like to issue.
What do you mean? what doesn't go into it that we need to call out? I think showing the class and the `info` tells them what goes in it? 

Also yea I can link to the VC learn guide again here, what guide do we have that goes over design?

2024-03-20 20:05 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +      "jwt": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDpqd2s6ZXlKcmRIa2lPaUpQUzFBaUxDSmpjbllpT2lKRlpESTFOVEU1SWl3aWVDSTZJalp0TFU1NE9HWndSMWxUT0ZoV04xZ3hVVmN4YWxKdVdHNHRUV1JxVWpJM1ptSktZVGhGVmt0bmEyTWlmUSMwI
yes I'd say so it's good for the issuer to know what the response they need to handle will look like

2024-03-20 20:06 UTC, EbonyLouis commented
> Is there a way we can set the `maxHeight` of code blocks? I think they get really long here (understandably so) and making code blocks scrollable could help with readability of the overall guide

Yea I can look into doing this

2024-03-20 20:06 UTC, angiejones commented
> @EbonyLouis I was walking someone through the doc today and realized we don't have the actual JSON of the VC shown anywhere. Can we add this at the end? With some fields being implicit, it would be great to show what the actual credential looks like.

```js
VerifiableCredential {
  vcDataModel: {
    '@context': [ 'https://www.w3.org/2018/credentials/v1' ],
    type: [ 'VerifiableCredential', 'KnownCustomerCredential' ],
    id: 'urn:uuid:ab2f09de-074e-4822-b6e1-2097f99f2845',
    issuer: 'did:example:issuer',
    issuanceDate: '2024-03-20T20:03:31Z',
    credentialSubject: { id: 'did:example:customer', country_of_residence: 'US' },
    expirationDate: '2025-12-31T23:59:59Z'
  }
}
```

2024-03-20 20:13 UTC, EbonyLouis commented
> > @EbonyLouis I was walking someone through the doc today and realized we don't have the actual JSON of the VC shown anywhere. Can we add this at the end? With some fields being implicit, it would be great to show what the actual credential looks like.
> 
> ```js
> VerifiableCredential {
>   vcDataModel: {
>     '@context': [ 'https://www.w3.org/2018/credentials/v1' ],
>     type: [ 'VerifiableCredential', 'KnownCustomerCredential' ],
>     id: 'urn:uuid:ab2f09de-074e-4822-b6e1-2097f99f2845',
>     issuer: 'did:example:issuer',
>     issuanceDate: '2024-03-20T20:03:31Z',
>     credentialSubject: { id: 'did:example:customer', country_of_residence: 'US' },
>     expirationDate: '2025-12-31T23:59:59Z'
>   }
> }
> ```

@angiejones I added this in already, but I'm not sure why the deploy preview isn't showing it

2024-03-20 20:48 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +:::info
There's no destination link, and I imagine that link would be to tbdex.io, so I was wondering if we need to wait to include this note until that endpoint is available

2024-03-20 20:49 UTC, chris-tbd commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +When creating a Verifiable Credential, you can design a model class to represent the specific type of credential you'd like to issue.
To clarify, I think it may be helpful to have an example of what may go into this in the plaintext here in addition to the class. That way the text and code stay connected

2024-03-21 14:33 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +:::info
ah ok I thought everything was being pushed and going live at the same time, and was going to update the link before pushing. Did we plan on putting this out before the website is live?

2024-03-26 17:23 UTC, EbonyLouis commented on site/docs/tbdex/issuer/kcc/kcc-issuer.mdx
> +2. Encode the SIOPv2 Authorization Request and respond:
it won't compile that way, that's why I think I highlighted it

2024-03-26 17:31 UTC, decentralgabe approved these changes

2024-04-01 18:04 UTC, angiejones requested changes

2024-04-01 18:04 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +    * Create a web server using{' '}
this got messed up again

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/d64ad1d5-d765-4fa8-9178-300fc29889e4)

2024-04-01 18:04 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +    * Create a web server using <a href="https://expressjs.com/">Express</a>{' '}
revert this change

2024-04-01 18:05 UTC, angiejones commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +* Design the credential you'd like to offer. * Implement an issuance path where you'll
revert this change

2024-04-02 18:34 UTC, merged