Wallet Guide: Orders Swift Snippets
TBD54566975/developer.tbd.website pull request #1332
Opened 2024-03-15 19:10 UTC by chris-tbd

This pull request primarily focuses on adding Swift language support to the `Placing Orders` section of the documentation and refactoring the test suite for Swift. The changes include adding Swift code snippets to the documentation, refactoring the `MockData.swift` test file to use methods instead of static data, and adding new tests for placing orders in `PlacingOrdersTests.swift`.

Addition of Swift language support to the documentation:

* [`site/docs/tbdex/wallet/place-order.mdx`](diffhunk://#diff-30ffc9efa98d7b210a7a3b5706f592c5031d895f013c9db048a92b350f401c8dL7-R7): Added Swift language support to the `LanguageSwitcher` and code snippets for creating, signing, and sending orders, and listening for order status and close reason. [[1]](diffhunk://#diff-30ffc9efa98d7b210a7a3b5706f592c5031d895f013c9db048a92b350f401c8dL7-R7) [[2]](diffhunk://#diff-30ffc9efa98d7b210a7a3b5706f592c5031d895f013c9db048a92b350f401c8dR23) [[3]](diffhunk://#diff-30ffc9efa98d7b210a7a3b5706f592c5031d895f013c9db048a92b350f401c8dR35) [[4]](diffhunk://#diff-30ffc9efa98d7b210a7a3b5706f592c5031d895f013c9db048a92b350f401c8dR46) [[5]](diffhunk://#diff-30ffc9efa98d7b210a7a3b5706f592c5031d895f013c9db048a92b350f401c8dR63) [[6]](diffhunk://#diff-30ffc9efa98d7b210a7a3b5706f592c5031d895f013c9db048a92b350f401c8dR98)

Refactoring of the test suite:

* [`site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/MockData.swift`](diffhunk://#diff-2930686e8fe9bbe15052994910e4d3ed41b1a3f848e0a5bbb8f75d825c8392cfL1-R6): Refactored the file to use methods for creating orders, order status, close, and quote objects, and for setting up mock GET and POST calls. Removed the static `mockExchangeJsonString` and `mockExchangeData` data. [[1]](diffhunk://#diff-2930686e8fe9bbe15052994910e4d3ed41b1a3f848e0a5bbb8f75d825c8392cfL1-R6) [[2]](diffhunk://#diff-2930686e8fe9bbe15052994910e4d3ed41b1a3f848e0a5bbb8f75d825c8392cfL89-R211)
* [`site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift`](diffhunk://#diff-b873d079e3968ef4778cab8d70eb00820e93c57b0e933e0fe4506db268cabadaR1-R112): Added new tests for sending order messages and status updates.
* [`site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ReceiveQuoteTests.swift`](diffhunk://#diff-ee318e93e22799d63b527307f144042e0e5e7fa2c0cdb131239ae79d1028d658L26-R33): Updated the `testPollForQuotes` method to use the `mockExchangeWithQuote` method from `MockData.swift` instead of the removed `mockGetExchange` method. [[1]](diffhunk://#diff-ee318e93e22799d63b527307f144042e0e5e7fa2c0cdb131239ae79d1028d658L26-R33) [[2]](diffhunk://#diff-ee318e93e22799d63b527307f144042e0e5e7fa2c0cdb131239ae79d1028d658L51-L55)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206684984656461

2024-03-16 22:52 UTC, angiejones requested changes

2024-03-16 22:52 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        var order = Order(from: customerDid.uri, to: pfiDid.uri, exchangeID: exchangeId, data: .init())
put each property on a new line with the same comments next to each as we have in JS and KT:

```js
const order = Order.create({
  metadata: {
    from: customerDid.uri,         // Customer's DID
    to: quote.metadata.from,       // PFI's DID
    exchangeId: quote.exchangeId  // Exchange ID from the Quote
  }
});
```

```kt
val order = Order.create(
    from = customerDid.uri,                 // Customer's DID
    to = quote.metadata.from,               // PFI's DID
    exchangeId = quote.metadata.exchangeId // Exchange ID from the Quote
)
```

2024-03-16 22:52 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        // :snippet-start: sendOrderSwift
sign and send should be two separate snippets

<img width="869" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/b57e9bec-dd76-470d-aa66-f3227f9fdb93">

2024-03-16 22:52 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        var orderStatusUpdate: String?
these two declarations go in the snippet. See the [JS and KT examples](https://developer.tbd.website/docs/tbdex/wallet/place-order/?lang=JavaScript#listen-for-order-status-updates)

2024-03-16 22:52 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +            let messages = try await tbDEXHttpClient.getExchange(
rename var to `exchange` to be in sync with the JS and KT examples:

```js
const exchange = await TbdexHttpClient.getExchange({
```

```kt
val exchange = TbdexHttpClient.getExchange(
```

2024-03-16 22:52 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        // :snippet-start: getCloseReasonSwift
can this be simplified to one statement such as:

```swift
let reasonForClose = closeMessage?.data.reason
```

that will match the JS and KT snippets:

```js
const reasonForClose = closeMessage.data.reason;
```
```kt
val reasonForClose = closeMessage.data.reason
```

2024-03-19 17:54 UTC, angiejones requested changes

2024-03-19 17:54 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        var order = Order(from: customerDid.uri, to: pfiDid, exchangeID: exchangeId, data: .init())
when you order, you should get the pfiDid from the Quote. Please look at how this is shown in JS and KT

2024-03-19 17:54 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        let pfiDid: String = pfiBearerDid
```suggestion

```

2024-03-19 17:55 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        var order = Order(from: customerDid.uri, to: pfiDid, exchangeID: exchangeId, data: .init())
see my last comment

https://github.com/TBD54566975/developer.tbd.website/pull/1332#discussion_r1527312935

2024-03-19 17:59 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +        let pfiDid: String = pfiBearerDid
for this line and 68, can we not keep renaming the variables throughout? it's super confusing it makes it hard if we need to debug. Let's just name the variables what they should be in the declaration

2024-03-19 18:01 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +                pfiDIDURI: pfiDid,
`pfiDIDURI` should come from the Order message

2024-03-19 18:02 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +                exchangeId: exchangeId)
`exchangeId` should come from the Order message

2024-03-19 18:04 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +            for message in messages {
let's simplify this code. see [this example](https://developer.tbd.website/docs/tbdex/wallet/receive-quote#polling-for-quote) for a reference

2024-03-19 21:18 UTC, chris-tbd commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/PlacingOrdersTests.swift
> +            for message in messages {
We can't simplify this code much more because of some typing issues, but I have an issue filed to help trim this down: https://github.com/TBD54566975/tbdex-swift/issues/62

2024-03-19 21:25 UTC, angiejones requested changes

2024-03-19 21:25 UTC, angiejones commented on site/docs/tbdex/wallet/place-order.mdx
> +    { snippetName: 'getCloseReasonSwift', language: 'Swift' }
this one isn't showing the snippet

<img width="852" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/a5903df4-85f9-41c3-a16f-48b966f1a11b">

2024-03-19 22:26 UTC, angiejones commented on site/docs/tbdex/wallet/place-order.mdx
> +    { snippetName: 'getCloseReasonSwift', language: 'Swift' }
i fixed it

2024-03-19 22:43 UTC, angiejones approved these changes

2024-03-20 16:02 UTC, merged