Issuer setup guide
TBD54566975/developer.tbd.website pull request #1338
Opened 2024-03-19 17:22 UTC by EbonyLouis

2024-03-19 17:36 UTC, angiejones commented on site/docs/tbdex/issuer/vc-serverSetup.mdx
> +- [Known Customer Credential Guide](/)
we know the URL, so we can start adding it in. Will likely fail the build but that's cool. We know not to merge until the other doc is merged

```suggestion
- [Known Customer Credential Guide](/docs/tbdex/issuer/kcc/kcc-issuer/)
```

2024-03-19 17:53 UTC, blackgirlbytes commented on site/docs/tbdex/issuer/vc-issuance.mdx
> +If you need to create a Credential Issuance app from scratch, check out the [Credential Issuance Server Setup Guide](/) for detailed instructions on the dependencies and packages needed to set up you
[Credential Issuance Server Setup Guide](/)

missing path

2024-03-19 18:08 UTC, angiejones approved these changes

2024-03-29 04:54 UTC, angiejones commented on site/docs/tbdex/issuer/vc-serverSetup.mdx
> +4. next, in the same file define your API routes:
```suggestion
4. In the same file, define your API routes:
```

2024-03-29 04:56 UTC, angiejones commented on site/docs/tbdex/issuer/vc-serverSetup.mdx
> +            get("/example-route") {
the routes can be anything, or are we suggesting specific routes?

2024-03-29 05:01 UTC, angiejones requested changes

2024-03-29 05:01 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/issuer/CredentialIssuanceTest.kt
> +    // Update an existing DID with 'IDV' endpoint
these should be 2 separate code snippets with instructions on when to use which

2024-03-29 05:02 UTC, angiejones commented
Note the build is failing due to linking to the Issuer guide that isn't yet published

2024-03-29 15:25 UTC, EbonyLouis commented on site/docs/tbdex/issuer/vc-serverSetup.mdx
> +            get("/example-route") {
The routes can be anything they want them to be with the exception of the two `/.well-known/` endpoints and that's stated in both of the guides so I figured leaving the setup as example-routes was the best. Then while following along with the guide they can use the same route names or change them

2024-04-02 18:02 UTC, merged