Managing credentials Swift update
TBD54566975/developer.tbd.website pull request #1343
Opened 2024-03-21 17:05 UTC by acekyd

This pull request adds Swift language support to the `managing-credentials.mdx` documentation and adding corresponding Swift tests. 

Additions to the documentation:

* [`site/docs/tbdex/wallet/managing-credentials.mdx`](diffhunk://#diff-016ef6f785a1c76d51303131cabf3f90dc679a961cefc392e7975ba51c5a0952L7-R7): Swift has been added as a language option in the `LanguageSwitcher`.
* [`site/docs/tbdex/wallet/managing-credentials.mdx`](diffhunk://#diff-016ef6f785a1c76d51303131cabf3f90dc679a961cefc392e7975ba51c5a0952R41-R44): Swift code snippets have been added to various sections of the documentation. These include obtaining `requiredClaims` from an Offering [[1]](diffhunk://#diff-016ef6f785a1c76d51303131cabf3f90dc679a961cefc392e7975ba51c5a0952R41-R44) narrowing options by filtering [[2]](diffhunk://#diff-016ef6f785a1c76d51303131cabf3f90dc679a961cefc392e7975ba51c5a0952R90-R93) and passing the customer's credentials [[3]](diffhunk://#diff-016ef6f785a1c76d51303131cabf3f90dc679a961cefc392e7975ba51c5a0952R121-R124).

Additions to the test suite:

* [`site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift`](diffhunk://#diff-07d7eed9826796743f52819fb4c46fdbbffd4abe6fca9acbe91b60e8b61676aeR1-R77): A new Swift test file has been added. This tests various functionality related to managing credentials, such as extracting presentation definitions, matching offerings with specific criteria, and selecting credentials from required claims.
  
## What type of PR is this? (check all applicable)

- [x] 📝 Documentation Update
- [x] 🧑‍💻 Code Snippet

This PR is dependent on `MockData` and other test updates from #1328. Also needs an [update](https://github.com/TBD54566975/tbdex-swift/blob/88c95f7cf8bb119a072911e0e6f2dbf2c255f959/Sources/tbDEX/Protocol/Models/Resources/Offering.swift#L32) from the tbdex package for `PresentationDefinitionV2`

2024-03-21 17:30 UTC, angiejones requested changes

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +@testable import tbDEX
can we remove `@testable` so that we're using the SDK just as a user would?

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        XCTAssertNotNil(presentationDefinition)
let's check some of the properties on the PD. Here's the assertions from JS

```js
    expect(presentationDefinition).toBeDefined();
    expect(presentationDefinition).toHaveProperty(
      'id',
      customPresentationDefinition.id,
    );
    expect(presentationDefinition).toHaveProperty('input_descriptors');
    expect(Array.isArray(presentationDefinition.input_descriptors)).toBe(true);
```

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +                let presentationDefinition: PresentationDefinitionV2 = offering.data.requiredClaims
is `PresentationDefinitionV2` required here?

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +                    try PresentationExchange.satisfiesPresentationDefinition(vcJWTs: credentials, presentationDefinition: presentationDefinition)
this is getting cut off in the view, can you spread it across multiple lines?

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        XCTAssertNotEqual(0, matchedOfferings.count)
why is this 0? we should use VCs that will match the PD

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        let credentials = [vcJwtResidence, vcJwtSanctions]
move this above the snippet

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        let selectedCredentials = PresentationExchange.selectCredentials(vcJWTs: credentials, presentationDefinition: presentationDefinition)
```suggestion
        let selectedCredentials = PresentationExchange.selectCredentials(
        	vcJWTs: credentials, 
        	presentationDefinition: offering.data.requiredClaims
        )
```

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        let presentationDefinition = offering.data.requiredClaims
```suggestion

```

2024-03-21 17:30 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        XCTAssertTrue(selectedCredentials.contains(vcJwtResidence) && selectedCredentials.contains(vcJwtSanctions))
lol can you split these into 2 assertions so that if it fails, there's less debugging needed?

2024-03-21 20:46 UTC, acekyd commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +                let presentationDefinition: PresentationDefinitionV2 = offering.data.requiredClaims
Yes it's the only value that can be passed at the moment to`PresentationExhange.satisfiesxxx`. But still dependent on an implementation that isn't yet available. Already spoke to Kirah about this and she's looking into it.

2024-03-21 20:47 UTC, acekyd commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        XCTAssertNotEqual(0, matchedOfferings.count)
It's a NotEqual assertion to make sure the count is not 0.

2024-03-22 18:02 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/tbdex/wallet/ManagingCredentialsTest.swift
> +        XCTAssertNotEqual(0, matchedOfferings.count)
oh sorry i misread

2024-03-27 16:29 UTC, angiejones approved these changes

2024-03-27 17:50 UTC, merged