Add Kotlin tests for verifying PFI routes
TBD54566975/developer.tbd.website pull request #1345
Opened 2024-03-21 18:14 UTC by chris-tbd

This pull request includes changes to the `PfiStructureTest` class in the `site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt` file. The changes add assertions to verify the number and types of callbacks registered in the `tbDexServer`.

The key changes are:

* Added a set of expected callbacks, which includes `SubmitKind.rfq`, `SubmitKind.order`, and `SubmitKind.close`.
* Retrieved the actual callbacks from `tbDexServer` and stored them in `actualCallbacks`.
* Added assertions to check if `actualCallbacks` contains `SubmitKind.rfq`, `SubmitKind.order`, and `SubmitKind.close`.
* Added an assertion to verify that the size of `tbDexServer.callbacks` is 3.

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-03-21 18:14 UTC, chris-tbd commented
Addressing #1297

2024-03-22 15:23 UTC, angiejones requested changes

2024-03-22 15:23 UTC, angiejones commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +        val expectedCallbacks = setOf(SubmitKind.rfq, SubmitKind.order, SubmitKind.close)
not used. can delete

2024-03-22 17:16 UTC, chris-tbd commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/pfi/PfiStructureTest.kt
> +        val expectedCallbacks = setOf(SubmitKind.rfq, SubmitKind.order, SubmitKind.close)
Updated

2024-03-22 17:57 UTC, angiejones approved these changes

2024-03-25 15:31 UTC, merged