known Customer Credential-Wallet
TBD54566975/developer.tbd.website pull request #1346
Opened 2024-03-22 14:38 UTC by EbonyLouis

## TO DO: 
- Add missing links 
- Update Credential when claims are finalized 
- Add graphics

2024-03-22 22:57 UTC, angiejones commented
hmm needs to go in the kcc folder thats not merged yet lol

2024-03-22 23:00 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +Known Customer Credentials (KCCs) are [Verifiable Credentials](/docs/web5/learn/verifiable-credentials) designed to streamline the [Know Your Customer (KYC)](/) process for tbDEX protocol users. KCCs
```suggestion
Known Customer Credentials (KCCs) are [Verifiable Credentials](/docs/web5/learn/verifiable-credentials) designed to streamline the [Know Your Customer (KYC)](/) process for tbDEX protocol users. KCCs help in gaining access to PFIs that provide regulated financial services.
```

2024-03-22 23:02 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +- **Credential Request**: The steps needed for your Wallet App to request a KCC **post** successful IDV, on a users behalf.
```suggestion
- **Credential Request**: The steps needed for your Wallet App to request a KCC on a user's behalf after successful IDV.
```

2024-03-22 23:10 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +- **Credential Management**: How the Wallet utilizes existing credentials for KCC requests and secure storage of the KCC itself.
```suggestion
- **Credential Management**: How the Wallet utilizes existing credentials for KCC requests and securely stores the KCC itself.
```

2024-03-22 23:11 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +For a detailed guide on Known Customer Credentials for **Issuers**, please refer to our [Issuer's Known Customer Credential Guide](/)
```suggestion
For a detailed guide on Known Customer Credentials for **Issuers**, please refer to the [Issuer's Known Customer Credential Guide](/)
```

2024-03-23 00:11 UTC, angiejones requested changes
excellent work, Ebony!

2024-03-23 00:11 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +- `credential_issuer`: The base URL address of the Issuer's service. It is used by the Wallet to retrieve the Issuer's metadata and the Issuer's Authorization Server Metadata.
```suggestion
- `credential_issuer`: The base URL address of the Issuer's service. It is used by the Wallet to retrieve the Issuer's Metadata and the Issuer's Authorization Server Metadata.
```

2024-03-23 00:11 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +Before the Wallet can request a KCC from the Issuer. In the same `handleIssuerResponse()` the Wallet needs to also fetch the Issuer's Authorization Server Metadata. Similarly, by appending `/.well-kn
```suggestion
Before the Wallet can request a KCC from the Issuer, the Wallet needs to also fetch the Issuer's Authorization Server Metadata by appending `/.well-known/oauth-authorization-server` to the `credential_issuer` URL in `handleIssuerResponse()`:
```

2024-03-23 00:11 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +If the IDV process is incomplete, the Issuer will return an `authorization_pending` error. In this case, the Wallet should wait for a short period before attempting another request to the Issuer's `/
should we show the code in a loop with a little sleep? something like we do when [polling tbdex messages from PFIs](https://deploy-preview-1346--tbd-website-developer.netlify.app/docs/tbdex/wallet/receive-quote#polling-for-quote)

2024-03-23 00:11 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +To the user an example KCC may look like this:
```suggestion
To the user, an example KCC may look like this:
```

2024-03-27 15:33 UTC, angiejones commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +    kind: "document_verification",
```suggestion
      kind: "document_verification",
```

2024-03-27 15:35 UTC, decentralgabe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialWallet.test.js
> +              path: ['$.credentialSubject.given_name'],
this (and below) should use `$.vc.credentialSubject....` syntax since we're using vc-jwt

2024-03-27 15:35 UTC, decentralgabe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialWallet.test.js
> +              path: ['$.credentialSubject.given_name'],
I remember @nitro-neal saying some libs use one and others use the other...so perhaps it's better to make the array have both paths available

2024-03-27 15:36 UTC, decentralgabe commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialWallet.test.js
> +      (service) => service.type === 'IDV',
where we do define this idv service type?

2024-03-27 15:37 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +      "credential_signing_alg_values_supported": ["ES256"],
```suggestion
      "credential_signing_alg_values_supported": ["ES256"],
```

believe this should be `EdDSA` and `ES256K`

2024-03-27 15:37 UTC, decentralgabe commented on site/docs/tbdex/issuer/kcc-wallet.mdx
> +          "proof_signing_alg_values_supported": ["ES256"]
same here

2024-03-27 15:55 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/knownCustomerCredentialWallet.test.js
> +      (service) => service.type === 'IDV',
good question. Ebony I saw the IDV service endpoint instructions in the drafts but I dont see it in any of the guides (setup, issuer, wallet). Seems it should go here: 
https://deploy-preview-1338--tbd-website-developer.netlify.app/docs/tbdex/issuer/vc-serversetup#create-a-did

2024-04-02 03:30 UTC, angiejones approved these changes
just need to add to folder after that is merged. overall, looks great! 🙌🏾

2024-04-02 19:04 UTC, merged