Add table for routes that should be implemented
TBD54566975/developer.tbd.website pull request #1352
Opened 2024-03-25 19:57 UTC by chris-tbd

This pull request includes an update to the `anatomy-of-a-pfi.mdx` file in the `site/docs/tbdex/pfi` directory. The change adds a table that lists the required routes to be implemented in the main server entry point. The table includes the HTTP method, endpoint, and a description for each route.

2024-03-25 20:08 UTC, angiejones requested changes
Kotlin tests failing due to compilation error:
https://github.com/TBD54566975/developer.tbd.website/actions/runs/8426165576/job/23073899230?pr=1352#step:7:44

2024-03-25 20:08 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +Here is a list of the reequired routes you'll need to implement:
```suggestion
Here is a list of the required routes you'll need to implement:
```

2024-03-25 20:08 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +      <td>Used to add additional messages to a pre-existing exchange e.g. order or close</td>
```suggestion
      <td>Used to add additional messages (e.g. `Order`, `Close`) to an existing exchange</td>
```

2024-03-25 20:08 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +      <td>Used to send an RFQ aka create an exchange.</td>
```suggestion
      <td>Used to send an RFQ aka create an exchange</td>
```

2024-03-25 20:08 UTC, angiejones commented on site/docs/tbdex/pfi/anatomy-of-a-pfi.mdx
> +      <td>Used to get exchanges</td>
```suggestion
      <td>Used to get the exchange IDs of all exchanges that match a specified filter</td>
```

2024-03-26 00:41 UTC, angiejones commented
> Kotlin tests failing due to compilation error: https://github.com/TBD54566975/developer.tbd.website/actions/runs/8426165576/job/23073899230?pr=1352#step:7:44

Since this was causing everyone's PRs to fail, I deployed a fix
https://github.com/TBD54566975/developer.tbd.website/pull/1355

2024-03-26 17:52 UTC, chris-tbd commented
> Kotlin tests failing due to compilation error: https://github.com/TBD54566975/developer.tbd.website/actions/runs/8426165576/job/23073899230?pr=1352#step:7:44

@angiejones could you re-review now that those are taken care of? And thank you for addressing that!

2024-03-26 19:50 UTC, angiejones approved these changes

2024-03-26 19:56 UTC, chris-tbd commented
@angiejones would you mind merging? I am currently restricted from merging

2024-03-28 14:55 UTC, merged