Sdk version component
TBD54566975/developer.tbd.website pull request #1357
Opened 2024-03-26 19:29 UTC by dayhaysoos

This PR introduces a new component for surfacing dependencies in documentation. The goal is to be adaptive to the multiple language SDKs we provide while also correctly referring to the correct version. Only step left is adding how to use it in the contributing doc

2024-03-26 22:02 UTC, finn-tbd commented on site/src/components/Dependencies.jsx
> +      Dependency = <PackageJson sdkVersions={SDK_VERSIONS} dependencies={dependencies} />;
This should return the `<PackageJson>` component instead of assigning it to a variable and returning the variable.

2024-03-26 22:02 UTC, finn-tbd commented on site/src/components/Dependencies.jsx
> +    if (language === 'javascript') {
should this be a switch statement?

2024-03-26 22:02 UTC, finn-tbd commented on site/src/components/Dependencies.jsx
> +  if (display === 'command') {
should this be a switch statement?

2024-03-26 22:03 UTC, finn-tbd commented on site/src/components/Dependencies.jsx
> +      break;
add kotlin (maven + gradle)

2024-03-26 22:12 UTC, finn-tbd commented on site/src/components/Dependencies.jsx
> +  if (display === 'command') {
alternatively: document other possible values for `display`

2024-03-27 19:04 UTC, dayhaysoos commented on site/src/components/Dependencies.jsx
> +      break;
I think so far the only language we need this for is javascript, going to follow up with Dev Rel on this

2024-03-27 19:15 UTC, dayhaysoos commented on site/src/components/Dependencies.jsx
> +  if (display === 'command') {
From the feedback I got from dev rel, might make sense to rename to "install"

2024-03-28 17:45 UTC, blackgirlbytes commented on CONTRIBUTING.md
> +We havea Dependencies component that helps you display required dependencies for each SDK.
```suggestion
We have a Dependencies component that helps you display required dependencies for each SDK.
```

2024-03-28 17:57 UTC, blackgirlbytes commented
I did a first pass. It mostly seems good, and I hope you don't mind..I pushed a commit to import the Dependencies component to the MDXComponent file because I tried using it in an MDX file and it said the component needed to be imported. 

Another thing is...I'm unclear how to make this work with the language switcher. For example: in this file https://developer.tbd.website/docs/web5/build/verifiable-credentials/fan-club-vc#setting-the-stage we show how to install for JS and how to install for Kotlin and you can just switch back and forth with the Shnip component which is a wrapper for Language Switcher, but how would i do that for the Dependencies component?

Not sure if I am using it wrong. Feel free to correct me!

2024-03-28 20:35 UTC, finn-tbd approved these changes

2024-03-28 21:54 UTC, blackgirlbytes approved these changes

2024-04-03 04:29 UTC, angiejones requested changes

2024-04-03 04:29 UTC, angiejones commented on site/src/components/Dependencies.jsx
can we rename these components so there's a clear indicator in how they differ? From a glance, I can't tell what `Dependencies` does vs `Dependency`. I'd need to read the code each time I want to grab this

2024-04-03 13:52 UTC, dayhaysoos commented on site/src/components/Dependencies.jsx
What do you think about the name `<TabbedDependencies />`?

2024-04-03 15:15 UTC, angiejones approved these changes

2024-04-03 16:48 UTC, merged