Update Key Management docs for Swift
TBD54566975/developer.tbd.website pull request #1361
Opened 2024-03-28 19:42 UTC by acekyd

This pull request primarily focuses on expanding the language support in the key management documentation and adding a new test suite for Swift. The most significant changes include adding Swift as a language option in the `LanguageSwitcher` component, including Swift code snippets in the key management documentation, and introducing a new Swift test suite for key management.

Addition of Swift support:

* [`site/docs/web5/build/decentralized-identifiers/key-management.mdx`](diffhunk://#diff-83dafc02d54448c17f0398fd3c40c396dca039e0cf578a27d052091a2330a988L7-R7): Added Swift as an option in the `LanguageSwitcher` component.
* [`site/docs/web5/build/decentralized-identifiers/key-management.mdx`](diffhunk://#diff-83dafc02d54448c17f0398fd3c40c396dca039e0cf578a27d052091a2330a988L58-R76): Included Swift code snippets in the key management documentation.

New Swift test suite:

* [`site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift`](diffhunk://#diff-ac4debf6560f691c97d6358dbe065cdd4afb982cb45fa47ff534a3dff6a6e762R1-R36): Introduced a new Swift test suite for key management. This test suite includes a test for initializing key management with an `InMemoryKeyManager` and a `BearerDID`.

2024-03-28 19:55 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +@testable import DevSiteTestSuite
i dont think this is needed. can you double check?

2024-03-28 19:56 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +            let keyManager = InMemoryKeyManager() // if production, use a different key manager
by "different" what do you mean? We should give clear guidance

2024-03-28 19:57 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +    func testInitializeKeyManagement() throws {
any reason it's not called `initKeyManagement` like the JS and KT examples?

2024-03-28 19:58 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +        func initializeKeyManagement(portableDID: PortableDID?) throws -> BearerDID {
any reason it's not called `initKeyManagement` like the JS and KT examples?

2024-03-28 19:59 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +        func initializeKeyManagement(portableDID: PortableDID?) throws -> BearerDID {
should it take an `env` variable like the other examples where we show to use a different key manager for Production?

2024-03-29 12:15 UTC, acekyd commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +@testable import DevSiteTestSuite
Yes testable isn't needed indeed.

2024-03-29 13:37 UTC, acekyd commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +        func initializeKeyManagement(portableDID: PortableDID?) throws -> BearerDID {
The hold up with this was trying to figure out what example to show for the production keyManager. On it.

2024-04-01 16:01 UTC, angiejones requested changes
Install instructions missing

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/63d457cf-ad3b-4199-9ed1-046781cd65c9)

2024-04-01 16:05 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +                // if production, use a more secure and production-ready key manager.
@kirahsapong @frankhinek do we have (or plan to have) production-ready key manager support for the web5-swift SDK? Seems iOS would have something, yeah?

2024-04-02 03:40 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +                // if production, use a more secure and production-ready key manager.
Ace, looks like Adam implemented this

https://github.com/TBD54566975/web5-swift/blob/1353f59e105ef09b4705f8675ce329f0f7e4c104/Sources/Web5/Crypto/KeyManager/Local/KeychainKeyManager.swift#L5

2024-04-02 09:57 UTC, acekyd commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +                // if production, use a more secure and production-ready key manager.
Thanks for this. Updated the code and all looks good. Looking forward to any additional security insights.

2024-04-02 16:02 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +            if env == "production" {
```suggestion
            // Determine which key manager to use based on the environment
            if env == "production" {
```

2024-04-02 16:03 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +                // if production, use a more secure and production-ready key manager.
```suggestion

```

2024-04-02 16:04 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +            if portableDID != nil {
```suggestion
            // Initialize or load a DID
            if portableDID != nil {
```

2024-04-02 16:05 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +                return try DIDJWK.create(keyManager: keyManager)
```suggestion
                // Create a new DID
                return try DIDJWK.create(keyManager: keyManager)
```

2024-04-02 16:05 UTC, angiejones commented on site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/KeyManagementTests.swift
> +                return try DIDJWK.import(
```suggestion
                 // Load existing DID
                return try DIDJWK.import(
```

2024-04-03 04:25 UTC, angiejones approved these changes

2024-04-03 07:49 UTC, merged