tbDEX v1 Release
TBD54566975/developer.tbd.website pull request #1364
Opened 2024-04-02 01:26 UTC by leordev

wip draft

2024-04-02 19:59 UTC, angiejones requested changes

2024-04-02 19:59 UTC, angiejones commented on package.json
> +    "@web5/crypto-aws-kms": "0.2.0",
this should be '0.2.1' right?

2024-04-02 19:59 UTC, angiejones commented on package.json
> +    "@web5/dids": "0.4.1",
this should be 0.4.3

2024-04-02 19:59 UTC, angiejones commented on package.json
> +    "@web5/crypto": "0.4.0",
this should be 0.4.1

2024-04-02 20:03 UTC, angiejones commented on package.json
> +    "@web5/crypto": "0.4.0",
```suggestion
    "@web5/crypto": "0.4.1",
```

2024-04-02 20:03 UTC, angiejones commented on package.json
> +    "@web5/crypto-aws-kms": "0.2.0",
```suggestion
    "@web5/crypto-aws-kms": "0.2.1",
```

2024-04-02 20:04 UTC, angiejones commented on package.json
> +    "@web5/dids": "0.4.1",
```suggestion
    "@web5/dids": "0.4.3",
```

2024-04-03 22:05 UTC, angiejones approved these changes

2024-04-08 08:48 UTC, ALRubinger commented
@leordev Kotlin SDKs are released to Maven Central as `1.0.0` for all. Verified in this PR:

```
developer.tbd.website/site/testsuites/testsuite-kotlin $> mvn dependency:tree -Dincludes=xyz.block
[INFO] --- dependency:3.6.1:tree (default-cli) @ kotlin-testsuite ---
[INFO] website.tbd.developer.site:kotlin-testsuite:jar:0.1.0-SNAPSHOT
[INFO] \- xyz.block:tbdex:pom:1.0.0:compile
[INFO]    +- xyz.block:tbdex-httpclient:jar:1.0.0:compile
[INFO]    +- xyz.block:tbdex-httpserver:jar:1.0.0:compile
[INFO]    \- xyz.block:tbdex-protocol:jar:1.0.0:compile
[INFO]       \- xyz.block:web5:pom:1.0.0:compile
[INFO]          +- xyz.block:web5-common:jar:1.0.0:compile
[INFO]          +- xyz.block:web5-credentials:jar:1.0.0:compile
[INFO]          +- xyz.block:web5-crypto:jar:1.0.0:compile
[INFO]          +- xyz.block:web5-dids:jar:1.0.0:compile
[INFO]          \- xyz.block:web5-jose:jar:1.0.0:compile
```

2024-04-08 16:39 UTC, merged