Swift sdk versions adjustment and pom file fix
TBD54566975/developer.tbd.website pull request #1372
Opened 2024-04-04 16:02 UTC by dayhaysoos

This PR updates how swift dependencies get added to the <Dependency /> components as well as fix how the pom files get updated.

2024-04-04 16:11 UTC, blackgirlbytes approved these changes

2024-04-04 21:19 UTC, leordev commented on site/testsuites/testsuite-kotlin/pom.xml
> -      <!-- tbDEX Dependency Management (BOM)-->
@dayhaysoos why did you remove and delete the way the file was structured with the comments? Maybe it was an IDE autosave mistake?

2024-04-05 04:35 UTC, angiejones requested changes

2024-04-05 04:35 UTC, angiejones commented on site/testsuites/testsuite-swift/Package.resolved
> +        "version" : "1.0.0"
not ready to merge this til that other PR is merged

2024-04-05 15:38 UTC, leordev commented on site/testsuites/testsuite-kotlin/pom.xml
> -      <!-- tbDEX Dependency Management (BOM)-->
Since I don't see your PR as a blocker because we are manually setting the Swift and Maven versions manually, I'd rather have you take your time and figure this issue out and then we can merge even after 1.0.0 release.

WDYT?

cc @ALRubinger

2024-04-05 15:38 UTC, leordev commented on site/testsuites/testsuite-swift/Package.resolved
> +        "version" : "1.0.0"
Which other PR? The one with the 1.0.0 release? I believe this PR is going to be merged into that "other PR" if I'm getting it right!

2024-04-10 05:35 UTC, angiejones commented on site/testsuites/testsuite-swift/Package.resolved
> +        "version" : "1.0.0"
can we revert this change now? Not sure if it revision is different

2024-04-10 07:19 UTC, ALRubinger commented on site/testsuites/testsuite-kotlin/pom.xml
> -      <!-- tbDEX Dependency Management (BOM)-->
+1 @leordev

2024-04-18 16:37 UTC, closed without merging