Include support for multiple KMS types
TBD54566975/developer.tbd.website pull request #1386
Opened 2024-04-11 12:09 UTC by acekyd

This pull request includes changes to the `key-management.mdx` file in the `site/docs/web5/build/decentralized-identifiers` directory. The changes primarily focus on updating the description of the `KeyManager` interface and adding more examples of key management solutions.

Key changes include:

* [`site/docs/web5/build/decentralized-identifiers/key-management.mdx`](diffhunk://#diff-83dafc02d54448c17f0398fd3c40c396dca039e0cf578a27d052091a2330a988L18-R18): The description of the `KeyManager` interface has been updated to highlight its flexibility, stating that it can be used with any key management solution of the user's choice. Previously, the document stated that the Web5 SDK offered two distinct `KeyManager` implementations.
* [`site/docs/web5/build/decentralized-identifiers/key-management.mdx`](diffhunk://#diff-83dafc02d54448c17f0398fd3c40c396dca039e0cf578a27d052091a2330a988R29-R30): Additional examples of production-friendly key management solutions have been provided, including Azure Key Vault, Google Cloud KMS, and HashiCorp Vault.

2024-04-11 23:35 UTC, angiejones requested changes

2024-04-11 23:35 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Other production friendly KMS solutions include [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault), [Google Cloud KMS](https://cloud.google.com/security/products/security-key-man
add a sentence at the end that if they want to use one of these, they can implement the `KeyManager` interface and link to the API ref for each language

2024-04-13 13:08 UTC, acekyd commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Other production friendly KMS solutions include [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault), [Google Cloud KMS](https://cloud.google.com/security/products/security-key-man
Updated.

2024-04-14 19:27 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Other production friendly KMS solutions include [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault), [Google Cloud KMS](https://cloud.google.com/security/products/security-key-man
```suggestion
Other production-friendly KMS solutions include [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault), [Google Cloud KMS](https://cloud.google.com/security/products/security-key-management), and [HashiCorp Vault](https://www.hashicorp.com/products/vault) etc. Any of these can be used by implementing the <LanguageSwitchLink text="KeyManager" links='{"JavaScript": "https://tbd54566975.github.io/web5-js/classes/_web5_dids.BearerDid.html#keyManager", "Kotlin": "https://tbd54566975.github.io/web5-kt/docs/-web5%20-s-d-k%20-documentation/web5.sdk.crypto/-key-manager/index.html", "Swift":"https://swiftpackageindex.com/tbd54566975/web5-swift/main/documentation/web5/keymanager"}' /> interface.
```

2024-04-14 19:30 UTC, angiejones requested changes

2024-04-14 19:30 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Other production-friendly KMS solutions include [Azure Key Vault](https://azure.microsoft.com/en-us/products/key-vault), [Google Cloud KMS](https://cloud.google.com/security/products/security-key-man
the JS interface is called [CryptoApi](https://tbd54566975.github.io/web5-js/interfaces/_web5_crypto.CryptoApi.html). will likely need to use our `LanguageSwitchBlock` component for this since the text changes based on language

2024-04-15 15:47 UTC, angiejones commented on site/docs/web5/build/decentralized-identifiers/key-management.mdx
> +Any of these can be used by implementing the [keyManager](https://swiftpackageindex.com/tbd54566975/web5-swift/main/documentation/web5/keymanager) interface.
```suggestion
Any of these can be used by implementing the [KeyManager](https://swiftpackageindex.com/tbd54566975/web5-swift/main/documentation/web5/keymanager) interface.
```

2024-04-18 12:18 UTC, angiejones approved these changes

2024-04-21 20:41 UTC, angiejones commented
im overriding the Swift failure. it's irrelevant to this PR. will fix that issue with another PR

2024-04-21 20:41 UTC, merged