createFrom added to guide
TBD54566975/developer.tbd.website pull request #1423
Opened 2024-05-10 06:17 UTC by blackgirlbytes

This pull request primarily involves updates to the documentation and tests related to the creation of records in the `write-to-dwn` module. The changes include renaming the `functionName` attribute to `snippetName` in the `CodeSnippet` component, adding a new section to the documentation about creating records from an existing record, and updating the tests to reflect these changes.

Updates to the documentation:

* [`site/docs/web5/build/decentralized-web-nodes/write-to-dwn.mdx`](diffhunk://#diff-5752dfa162025e7e670ffd654532efc6e61f1632423d0a9bfd38a693fc7fc6dbL12-R16): Renamed the `functionName` attribute to `snippetName` in the `CodeSnippet` component for creating text, JSON, and mixed records.
* [`site/docs/web5/build/decentralized-web-nodes/write-to-dwn.mdx`](diffhunk://#diff-5752dfa162025e7e670ffd654532efc6e61f1632423d0a9bfd38a693fc7fc6dbR31-R34): Added a new section about creating records from an existing record.

Updates to the tests:

* [`site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/write-to-dwn.test.js`](diffhunk://#diff-aa48069f8d206290c34cfea31e8b0996e62e800813045d9b0c5d07dc53898338L24-R51): Updated the tests for creating text and JSON records to reflect the change from `functionName` to `snippetName`.
* [`site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/write-to-dwn.test.js`](diffhunk://#diff-aa48069f8d206290c34cfea31e8b0996e62e800813045d9b0c5d07dc53898338R87-R117): Added a new test for creating a record from an existing record.

2024-05-10 12:49 UTC, acekyd requested changes

2024-05-10 12:49 UTC, acekyd commented on site/docs/web5/build/decentralized-web-nodes/write-to-dwn.mdx
>  <CodeSnippet functionName='createMixedRecord'/>
Think you missed this one in the rename @blackgirlbytes

2024-05-10 12:49 UTC, acekyd commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/write-to-dwn.test.js
> +        recordId: record.id,
nitpick?: any way to improve this so readers don't confuse it for the record that is being assigned? maybe something like `knownRecord.id` or anything to reduce the possible confusion.

2024-05-10 13:43 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/write-to-dwn.test.js
> +        recordId: record.id,
good point. I tried to give a more specific name. I hope I didn't make it look more confusing. Let me know!

2024-05-10 13:44 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/write-to-dwn.mdx
>  <CodeSnippet functionName='createMixedRecord'/>
🙈 actually, I was just being lazy because I was like eh, it's out of scope, but I updated all of it from function name to snippet name now. You caught me LOL

2024-05-11 13:31 UTC, acekyd approved these changes

2024-05-13 00:55 UTC, angiejones requested changes

2024-05-13 00:55 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/write-to-dwn.test.js
> +        recordId: originalRecord.id,
if you already have the `originalRecord`, you would just use that versus calling `read()` to get the same object. 

I suggest deleting this call and just using `originalRecord` on line 164

2024-05-13 16:09 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/write-to-dwn.test.js
> +      dataFormat: 'application/json',
oh okay I was trying to show that you can also update the data format, but it doesn't make sense for the example/I didn't pointit out.

2024-05-13 16:29 UTC, angiejones approved these changes

2024-05-13 16:56 UTC, merged