add blog component
TBD54566975/developer.tbd.website pull request #1439
Opened 2024-05-28 22:43 UTC by dayhaysoos

Adding blog component, will be setting up a "guide" page too

2024-05-29 09:49 UTC, angiejones commented on site-new/src/components/BlogCard.tsx
> +  size?: "large" | "small";
what's this mean?

2024-05-29 09:50 UTC, angiejones commented on site-new/src/components/BlogCard.tsx
> +  date = "date",
can you change "date" to the actual date format that's needed so we'll always have that example conveniently there

2024-05-29 09:51 UTC, angiejones commented on site-new/src/components/BlogCard.tsx
> +  const cardSizeClass = size === "large" ? "max-w-[840px]" : "max-w-[400px]";
based on the layout are there ever multiple large cards? I thought only the Featured post would be large

2024-05-29 09:54 UTC, angiejones requested changes

2024-05-29 09:54 UTC, angiejones commented on site-new/src/components/BlogCard.tsx
> +  image = require("/static/img/test-image.png").default,
instead of "test-image.png", can you use this to let us know the ideal size of the image? Something like:

`require("/static/img/1200x800.png").default,`

2024-05-29 15:46 UTC, dayhaysoos commented on site-new/src/components/BlogCard.tsx
> +  size?: "large" | "small";
There's a large version of the blog card post and a small version. I think I'ma make small the default but it's just an option for different sizes/styling.

2024-05-29 15:48 UTC, dayhaysoos commented on site-new/src/components/BlogCard.tsx
> +  const cardSizeClass = size === "large" ? "max-w-[840px]" : "max-w-[400px]";
I don't know if we'd ever have pages with multiple large cards but we have the option to use large or small whenever/where ever we want from this size value

2024-05-29 16:50 UTC, dayhaysoos commented on site-new/src/components/BlogCard.tsx
> +  image = require("/static/img/test-image.png").default,
I'm actually not sure about this, gonna look into it tho

2024-05-30 15:56 UTC, angiejones commented on site-new/src/components/BlogCard.tsx
> +  const cardSizeClass = size === "large" ? "max-w-[840px]" : "max-w-[400px]";
you think blog cards would be used outside the blog?

2024-05-30 15:58 UTC, merged