Wallet quickstart
TBD54566975/developer.tbd.website pull request #1447
Opened 2024-06-14 20:22 UTC by chris-tbd

This pull request includes changes to three main areas: the `quickstart.js` file, the `quickstart.mdx` documentation, and the `quickstart.test.js` test file. The changes include the addition of new functions and methods, the modification of existing ones, and the creation of new tests.

New functions and methods:

* [`site/code-snippets/tbdex/quickstart.js`](diffhunk://#diff-967bda23e2ed9492a2fc45046518137e5e88e1354afb8194c1a72f62b0c4b5f6R1-R191): Added several new functions and methods to manage the creation, sending, and processing of requests, offerings, credentials, quotes, and orders. Also added functions to handle the closing of processes.

Documentation updates:

* [`site/docs/tbdex/wallet/quickstart.mdx`](diffhunk://#diff-e1b8c5cb95719fbc2a8daa3403bfa3d8da3950d8e41e5276f8c0d3ed613f82ffR1-R138): Added comprehensive documentation for the quickstart guide, including overviews, step-by-step instructions, and code snippets.

Test updates:

* [`site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js`](diffhunk://#diff-3bd66c733978770fee09d75232f10cc67eedd2b4821fb64d91dc365ba4246aaaR1-R186): Created new tests for the quickstart guide, including tests for getting offerings, pulling wallet credentials, creating and sending RFQs, processing quotes and creating orders, and processing closes.

Additional changes:

* [`site/src/components/WalletQuickstartCodeRunner.jsx`](diffhunk://#diff-b37c00876be5252983d9bafa2ab6b3cc2e9fdfe454b721acc8aa93265e5d96ddR1-R107): Added a new component to handle the execution of code snippets in the quickstart guide.

2024-06-14 22:25 UTC, angiejones requested changes
JS tests failing

https://github.com/TBD54566975/developer.tbd.website/actions/runs/9521919443/job/26250389102?pr=1447#step:8:125

2024-06-16 00:07 UTC, angiejones requested changes

2024-06-16 00:07 UTC, angiejones commented on site/code-snippets/tbdex/quickstart.js
> +    context.reasonForClose = close.data.reason;
also include `close.data.success` (before reason)

2024-06-16 00:07 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        while (!close) {
start the snippet here

2024-06-16 00:07 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +## Process a Quote
```suggestion
## Process Quote
```

2024-06-16 00:07 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +## Place an Order
```suggestion
## Place Order
```

2024-06-16 00:07 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +## Close out the Exchange
```suggestion
## End Transaction
```

2024-06-16 00:14 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        expect(reasonForClose).toBeDefined();
add assertion that ensures `close.data.success` is true

2024-06-17 15:25 UTC, blackgirlbytes commented on site/code-snippets/tbdex/quickstart.js
hey hey, @chris-tbd -- you might've followed the format I used for my quickstart. Here's the context of why i had a `quickstart.js` and a `quickstart.test.js`

`Quickstart.test.js` created the static code snippets in the guide and tested the code.
`Quickstart.js` already existed as well. The project was originally in vanilla JS. I switched it over to React..but that file had executable functions that ran and output a value when someone pressed the 'run' button. I left that file in and refactored it to manage React state. 

so check to see if you need that file for your case.

2024-07-02 00:27 UTC, chris-tbd commented on site/code-snippets/tbdex/quickstart.js
> +    context.reasonForClose = close.data.reason;
Added

2024-07-02 00:28 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        expect(reasonForClose).toBeDefined();
Added

2024-07-04 02:22 UTC, angiejones requested changes

2024-07-04 02:22 UTC, angiejones commented on site/code-snippets/tbdex/quickstart.js
> +                    phoneNumber: '123-456-7890',                 // Recipient's BTC wallet address
update comment here

2024-07-04 02:22 UTC, angiejones commented on site/code-snippets/tbdex/quickstart.js
> +    const BTC_ADDRESS = 'bc1q52csjdqa6cq5d2ntkkyz8wk7qh2qevy04dyyfd'
not needed

2024-07-04 02:22 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                    phoneNumber: '123-456-7890',                 // Recipient's BTC wallet address
update comment

2024-07-08 18:01 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +            from: customerDid,         // Customer's DID
should be `customerDid.uri`

2024-07-08 18:03 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        const order = Order.create({
remove `const` if wanting to assign to the `order` variable declared at top of the file

2024-07-08 18:03 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +            await order.sign(customerDid);
this will be undefined until `const` above is removed

2024-07-08 19:26 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                did: customerDid.uri,
this one expects a `BearerDid` so you wanna pass the whole `customerDid`

2024-07-08 21:07 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +            const exchange = await TbdexHttpClient.getExchange({
wrap this in a `try/catch` so we can continue our while loop if it throws

```
           try {
                const exchange = await TbdexHttpClient.getExchange({
                    pfiDid: pfiDid,
                    did: customerDid,
                    exchangeId: exchangeId
                });

                quote = exchange.find(msg => msg instanceof Quote);

                if (!quote) {
                    // Make sure the exchange is still open
                    close = exchange.find(msg => msg instanceof Close);
                    
                    if(close) { break; } 
                    else {
                    // Wait 2 seconds before making another request
                    await new Promise(resolve => setTimeout(resolve, 2000));
                    }
                }
            } catch (e) {
                //handle error          
            }     
```

2024-07-08 21:08 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +            const exchange = await TbdexHttpClient.getExchange({
for sanity lets wrap this in a `try/catch` block too!

2024-07-08 21:08 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        await new Promise(resolve => setTimeout(resolve, 5000));
can remove this since we can rely on our loop

2024-07-08 21:08 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        await new Promise(resolve => setTimeout(resolve, 5000));
can remove this also since we can rely on our loop

2024-07-08 21:08 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                rfq.verifyOfferingRequirements(selectedOffering);
this should be `await`ed

2024-07-09 16:54 UTC, chris-tbd commented on site/code-snippets/tbdex/quickstart.js
That's exactly what I was thinking here! `quickstart` manages the runner, `quickstart.test` takes care of snippets. Because I had to create a new React component as well to run these, I left everything as separate as possible to reduce error bleed if something goes wrong

2024-07-09 17:12 UTC, blackgirlbytes commented
Excellent job! I feel like in our team I probably have the least tbdex knowledge and it was a good primer for me.

I have a few things that could be room for improvement:
- react18 json viewer (mentioned in Slack) This PR gives an example https://github.com/TBD54566975/developer.tbd.website/pull/1463/files
- Maybe we could add install instructions and tell people to create a wallet.js since you mention wallet.js in the `Import Classes` section
- Also in the beginning there are two run buttons enabled. I expected the second one to be disabled until after the first one runs because it doesn't output anything. Was that intentional ? Screen recording attached.

https://github.com/TBD54566975/developer.tbd.website/assets/22990146/89b4daf4-2746-4692-aa5f-68e9f9c6146e

That's it from me!!! Everything else I liked :D

2024-07-09 17:13 UTC, blackgirlbytes reviewed
Excellent job! @chris-tbd I feel like in our team I probably have the least tbdex knowledge and it was a good primer for me.

I have a few things that could be room for improvement:
- react18 json viewer (mentioned in Slack) This PR gives an example https://github.com/TBD54566975/developer.tbd.website/pull/1463/files
- Maybe we could add install instructions and tell people to create a wallet.js since you mention wallet.js in the `Import Classes` section
- Also in the beginning there are two run buttons enabled. I expected the second one to be disabled until after the first one runs because it doesn't output anything. Was that intentional ? Screen recording attached.

https://github.com/TBD54566975/developer.tbd.website/assets/22990146/89b4daf4-2746-4692-aa5f-68e9f9c6146e

That's it from me!!! Everything else I liked :D

2024-07-09 17:14 UTC, blackgirlbytes commented on site/code-snippets/tbdex/quickstart.js
Oh that's great! That kinda validates my approach then 😄

2024-07-09 18:46 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
@chris-tbd bumping this

2024-07-09 18:51 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +✅  Connect your wallet app with a PFI (Participating Financial Institution)
```suggestion
✅  Connect a wallet app with a PFI (Participating Financial Institution)
```

2024-07-09 18:51 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +✅  Connect your wallet app with a PFI (Participating Financial Institution)
```suggestion
✅  Connect a wallet app with a PFI (Participating Financial Institution)
```

2024-07-09 18:51 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +✅  Send tbDEX messages to a PFI to facilitate an exchange
```suggestion
✅  Use a wallet app to send tbDEX messages to a PFI to facilitate an exchange
```

2024-07-09 18:53 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +title: Quickstart
```suggestion
title: Wallet Quickstart
```

2024-07-09 18:54 UTC, angiejones commented on site/docs/tbdex/wallet/quickstart.mdx
> +Ensure your `wallet.js` makes all the necessary imports:
@chris-tbd bumping this

2024-07-09 19:57 UTC, chris-tbd commented on site/docs/tbdex/wallet/quickstart.mdx
> +
Removing

2024-07-09 19:59 UTC, chris-tbd commented on site/docs/tbdex/wallet/quickstart.mdx
> +Ensure your `wallet.js` makes all the necessary imports:
Removing

2024-07-09 20:06 UTC, chris-tbd commented on site/docs/tbdex/wallet/quickstart.mdx
> +
Added snippet to find the offering

2024-07-09 20:17 UTC, chris-tbd commented on site/docs/tbdex/wallet/quickstart.mdx
> +The Offering you received will likely have a `requiredClaims` section that specifies which, if any, [Verifiable Credentials](https://developer.tbd.website/docs/web5/learn/verifiable-credentials) (VCs
Added

2024-07-10 06:42 UTC, angiejones commented
[JS tests](https://github.com/TBD54566975/developer.tbd.website/actions/runs/9863724529/job/27237116388?pr=1447) failing again

>  Serialized Error: { statusCode: 404, details: { errors: [ { detail: 'No exchange found for rfq_01j2cjxp9yeby9wg8h7s36kfr8' } ] }, recipientDid: 'did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy', url: 'https://pfiexemplar.tbddev.org/exchanges/rfq_01j2cjxp9yeby9wg8h7s36kfr8' }

2024-07-11 16:29 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        try {
hey hey @chris-tbd just a heads up this `try/catch` needs to be inside the `while` loop. otherwise when it throws itll just end the loop. 

so you want
```
while (!quote) { 
  try { 
     ...
     quote = ...
  } catch {
     ... 
  }
}
// will loop over the try catch block until quote is assigned
```

2024-07-11 16:34 UTC, kirahsapong commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        try {
and then same for this one (linked here: https://github.com/TBD54566975/developer.tbd.website/pull/1447/files#r1674325532)

`try/catch` should go inside the `while` loop, so even if it throws the first time it can try again and the quote will eventually be assigned once ready. if you don't want to retry too quickly you can add a timeout after the try to make the loop wait a couple seconds, but not necessarily needed

```
while (!quote) { 
  try { 
     ...
     quote = ...
  } catch {
     ... 
  }
  await new Promise(resolve => setTimeout(resolve, 2000));
}
// will loop over the try catch block until quote is assigned with 2s interval between retries
```

2024-07-11 18:45 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        try {
Updated

2024-07-11 18:45 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        try {
Updated

2024-07-11 21:55 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +In order for you to communicate with PFIs on Alice's behalf, she'll need a DID (as will all of your customers). Here's how to create a DID:
```suggestion
In order for you to communicate with PFIs on your customers' behalf, they will need a DID. Let's create one for Alice now:
```

2024-07-11 21:58 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +To connect to a PFI, all you need is their DID. Let's get connected to a mock PFI whose DID is `did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy`.
this section seems a bit off because there's no action. then we use a variable named `pfiDid` in the next section.

You should probably add a code block here

```js
const pfiDid = did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy
```

2024-07-11 21:59 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +To connect to a PFI, all you need is their DID. Let's get connected to a mock PFI whose DID is `did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy`.
```suggestion
To connect to a PFI, all you need is their DID. Let's use the DID of a mock PFI: 
```

2024-07-11 22:02 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +[Offerings](/docs/tbdex/message-types#offerings) describe the currency pair and transaction parameters. With the PFI's DID, your app can fetch all of their offerings:
```suggestion
All PFIs have [Offerings](/docs/tbdex/message-types#offerings) which are a menu of services they provide. Offerings describe the currency pairs and transaction parameters offered . Let's fetch all of the offerings from the PFI:
```

2024-07-11 22:04 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        // Try the first offering that matches our criteria
```suggestion
        // Select the first offering that matches our criteria
```

2024-07-11 22:08 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +The Offering you received will likely have a `requiredClaims` section that specifies which, if any, [Verifiable Credentials](/docs/web5/learn/verifiable-credentials) (VCs) you’ll need to present in o
```suggestion
The Offering we selected has a `requiredClaims` section that specifies [Verifiable Credentials](/docs/web5/learn/verifiable-credentials) (VCs) Alice needs  in order to be eligible for the Offering. 
```

show a code block with the requiredClaims part of the offering.

Then add:

> The PFI requires Alice to have a Sanctions credential. Let's help Alice apply for this VC.

2024-07-11 22:12 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeApplyForCredential" stepIndex={2} customPlaceholder={"Apply for a SanctionCredential"}/>
should show an assignment to `myCredentials`. this variable is used in the next step but hasnt been introduced

2024-07-12 01:14 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeApplyForCredential" stepIndex={2} customPlaceholder={"Apply for a SanctionCredential"}/>
Totally understand where you're coming from wanting to show assignment of `myCredentials`, and I looked for how else we showed the usage of the `PresentationExchange.selectCredentials()` method in our docs ([found here](https://developer.tbd.website/docs/tbdex/wallet/managing-credentials#obtain-eligible-offerings)). In the other example we're just kicking the problem up one layer where we hard-code in JWT values, which is potentially more confusing(?) My thought is that it's sufficient to describe in text outside the code block what `myCredentials` is instead of adding in more code that doesn't really make it all that much clearer

2024-07-12 01:21 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +To connect to a PFI, all you need is their DID. Let's get connected to a mock PFI whose DID is `did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy`.
Added

2024-07-12 01:22 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeApplyForCredential" stepIndex={2} customPlaceholder={"Apply for a SanctionCredential"}/>
@angiejones see updated text for explainer

2024-07-12 14:59 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +The Offering you received will likely have a `requiredClaims` section that specifies which, if any, [Verifiable Credentials](/docs/web5/learn/verifiable-credentials) (VCs) you’ll need to present in o
Chris, see the other part of the comment:

show a code block with the requiredClaims part of the offering.

Then add:

> The PFI requires Alice to have a Sanctions credential. Let's help Alice apply for this VC.

right now. it's still a bit confusing without this context

![Screenshot_20240712_095527_Chrome](https://github.com/user-attachments/assets/1d83b8f8-f630-410e-bba8-bdcc683baad2)

2024-07-12 15:01 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeApplyForCredential" stepIndex={2} customPlaceholder={"Apply for a SanctionCredential"}/>
ok, gonna rephrase it a bit

2024-07-12 15:05 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +VCs are stored as JWTs - in this case we're assuming that they have been fetched from local storage and placed into a string array called `myCredentials` -, and once you've saved the token above you
```suggestion
VCs are stored as JSON Web Tokens (JWTs). Your wallet app has saved Alice's new VC into an array named `myCredentials`. Let's now find which of Alice’s credentials meet the PFI's requirements:
```

2024-07-12 15:16 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<CodeSnippet snippetName="walletQuickstartSendRfq" />
Going through it, it just feels like something is missing here.

can we make this runnable where the user gets a 200 code or something? You can even fake it where they press Run and it just writes the status.

2024-07-12 15:29 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +The Quote message will contain the exact exchange rate including any fees. Your app can present this to Alice to determine if she wants to proceed with the transaction. If she does, you'll create an
```suggestion
The Quote contains the exact exchange rate including any fees. Your app can present this to Alice to determine if she wants to proceed with the transaction. If she does, you'll create an Order message, sign it with Alice's DID, and send it to the PFI:
```

2024-07-12 15:30 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<CodeSnippet snippetName="walletQuickstartCreateOrder" />
the sign and send are not shown

2024-07-12 15:31 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<CodeSnippet snippetName="walletQuickstartProcessClose" />
show how to get `success`

2024-07-12 15:33 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +Congratulations on creating your first Wallet! In just a few minutes you were able to contact a PFI for its offerings, request a quote, place an order, and finish your transaction.
```suggestion
Congratulations on creating your first Wallet! In just a few minutes you were able to contact a PFI for its offerings, request a quote, and place an order for Alice to swap USD for KES.
```

2024-07-15 15:15 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeApplyForCredential" stepIndex={2} customPlaceholder={"Apply for a SanctionCredential"}/>
Resolving after applied suggestion

2024-07-15 15:44 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +<CodeSnippet snippetName="walletQuickstartProcessClose" />
added

2024-07-15 15:44 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +<CodeSnippet snippetName="walletQuickstartCreateOrder" />
added

2024-07-15 15:44 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +<CodeSnippet snippetName="walletQuickstartSendRfq" />
added

2024-07-15 16:15 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +The Offering you received will likely have a `requiredClaims` section that specifies which, if any, [Verifiable Credentials](/docs/web5/learn/verifiable-credentials) (VCs) you’ll need to present in o
Clarified, added a snippet of the `requiredClaims` as well as more explicit `SanctionsCredential` application text

2024-07-15 16:38 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +✅  Use a wallet app to send tbDEX messages to a PFI to facilitate an exchange
```suggestion
✅  Use a wallet app to send tbDEX messages to a PFI to facilitate a transaction
```

2024-07-15 16:41 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +All PFIs have [Offerings](/docs/tbdex/message-types#offerings) which are a menu of services they provide. Offerings describe the currency pairs and transaction parameters offered . Let's fetch all of
```suggestion
All PFIs have [Offerings](/docs/tbdex/message-types#offerings) which are a menu of services they provide. Offerings describe the currency pairs and transaction parameters offered. Let's fetch all of the offerings from the PFI:
```

2024-07-15 16:50 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        //:snippet-start: walletQuickstartSelectOffering
for this snippet, i think we can simplify it. can you test this to make sure it works?

```kt
if(offerings) {
  selectedOffering = offerings.find { offering ->
    offering.data.payin.currencyCode == "USD" &&
      offering.data.payout.currencyCode == "KES"
  }
}
```

2024-07-15 16:53 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +                'const': 'SanctionsCredential'
```suggestion
                //highlight-start
                'const': 'SanctionsCredential'
                //highlight-end
```

2024-07-15 16:56 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +VCs are stored as JSON Web Tokens (JWTs). Your wallet app has saved Alice's new VC into an array named `myCredentials`. Let's now find which of Alice’s credentials meet the PFI's requirements:
```suggestion
VCs are stored as JSON Web Tokens (JWTs). Your wallet app has saved Alice's new VC into an array named `myCredentials`. Let's now select Alice’s credential to meet the PFI's requirements:
```

2024-07-15 17:21 UTC, angiejones commented on site/code-snippets/tbdex/quickstart.js
> +            // Wait 2 seconds before making another request
```suggestion
                // Wait 2 seconds before making another request
```

2024-07-15 17:22 UTC, angiejones commented on site/code-snippets/tbdex/quickstart.js
> +            await new Promise(resolve => setTimeout(resolve, 2000));
```suggestion
                await new Promise(resolve => setTimeout(resolve, 2000));
```

2024-07-15 17:23 UTC, angiejones commented on site/code-snippets/tbdex/quickstart.js
> +            // the exchange hasn't populated yet
an exception shouldn't be thrown, right?

2024-07-15 17:24 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeProcessQuote" stepIndex={5} customPlaceholder={"View Quote"} viewJsonObj={true} collapseLevel={1}/>
I get an error here

<img width="326" alt="image" src="https://github.com/user-attachments/assets/9e7a6eeb-c6fb-4ed8-9b4e-996e4dbc32af">

2024-07-15 17:25 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeDidCreate" stepIndex={0} customPlaceholder={"See your DID"}/>
```suggestion
<WalletQuickstartCodeRunner executeCodeName="executeDidCreate" stepIndex={0} customPlaceholder={"See Alice's DID"}/>
```

2024-07-15 17:25 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeCreateRfq" stepIndex={3} customPlaceholder={"See your RFQ"} viewJsonObj={true} collapseLevel={1}/>
```suggestion
<WalletQuickstartCodeRunner executeCodeName="executeCreateRfq" stepIndex={3} customPlaceholder={"See the RFQ"} viewJsonObj={true} collapseLevel={1}/>
```

2024-07-15 17:29 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +## Request a Quote
```suggestion
## Request Quote
```

2024-07-15 17:29 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeCreateOrder" stepIndex={6} customPlaceholder={"Create your order"} viewJsonObj={true} collapseLevel={1}/>
```suggestion
<WalletQuickstartCodeRunner executeCodeName="executeCreateOrder" stepIndex={6} customPlaceholder={"Create Alice's Order"} viewJsonObj={true} collapseLevel={1}/> 
```

2024-07-15 17:30 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +<WalletQuickstartCodeRunner executeCodeName="executeSendOrder" stepIndex={7} customPlaceholder={"Submit your order"} viewJsonObj={true} collapseLevel={1}/>
```suggestion
<WalletQuickstartCodeRunner executeCodeName="executeSendOrder" stepIndex={7} customPlaceholder={"Submit Order to PFI"} viewJsonObj={true} collapseLevel={1}/> 
```

2024-07-15 17:32 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // the exchange hasn't populated yet
ignore an exception?

2024-07-15 17:32 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // do nothing to let the loop keep running in the event
ignore an exception?

2024-07-15 17:32 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                    // do nothing to let the loop keep running in the event
ignore an exception?

2024-07-15 18:07 UTC, chris-tbd commented on site/code-snippets/tbdex/quickstart.js
> +            // the exchange hasn't populated yet
No it should not, but we run into an issue where if we try and immediately fetch the exchange before the PFI has finished populating it, then it will throw a DNE error. To avoid this, we let it catch the error and just try again. This works better than setting a timeout/retry because there's 1) no guarantee that works and 2) if the exchange is available faster than the retry loop then we wasted time waiting.

2024-07-15 18:12 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // the exchange hasn't populated yet
We are ignoring it because we run into an issue where if we try and immediately fetch the exchange before the PFI has finished populating it, then it will throw a DNE error. To avoid this, we let it catch the error and just try again. This works better than setting a timeout/retry because there's 1) no guarantee that works and 2) if the exchange is available faster than the retry loop then we wasted time waiting.

2024-07-15 18:12 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                    // do nothing to let the loop keep running in the event
We are ignoring it because we run into an issue where if we try and immediately fetch the exchange before the PFI has finished populating it, then it will throw a DNE error. To avoid this, we let it catch the error and just try again. This works better than setting a timeout/retry because there's 1) no guarantee that works and 2) if the exchange is available faster than the retry loop then we wasted time waiting.

2024-07-15 18:30 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // the exchange hasn't populated yet
this should only be applicable to the Quote step, right? After the PFI has added the RFQ to the exchange, we're good to go? so should be removed from the subsequent polls

2024-07-15 18:34 UTC, angiejones commented
[JS test failing](https://github.com/TBD54566975/developer.tbd.website/actions/runs/9944599473/job/27470991957?pr=1447#step:8:125). Be sure to run the tests locally before pushing

2024-07-15 19:31 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // the exchange hasn't populated yet
I totally agree, although I've seen cases where the exchange isn't present in later steps because of a threading issue where the tests run out of order.  I've updated all the try/catch blocks in snippets to look out for the `ResponseError` type, which is [invoked in the `tbDEX` SDK here](https://github.com/TBD54566975/tbdex-js/blob/8f07e7e06d6a9aa808048d0ecf6044ac35c78bf4/packages/http-client/src/client.ts#L228). This will allow us to catch a server error, which would be due to something db related, and still throw issues for client errors

2024-07-15 19:35 UTC, chris-tbd commented
> [JS test failing](https://github.com/TBD54566975/developer.tbd.website/actions/runs/9944599473/job/27470991957?pr=1447#step:8:125). Be sure to run the tests locally before pushing

They've been passing locally, trying to see if it's a race condition or something similar

2024-07-15 20:16 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        //:snippet-start: walletQuickstartSelectOffering
I verified this, did you want to go by ID instead?

2024-07-15 20:25 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // the exchange hasn't populated yet
you should probably flag this for dev

2024-07-15 20:28 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                if (e.name != 'ResponseError') {
eh this specific error type is so generic that it's not even worth checking for, imo. You can change it back. I think throwing it, as you do below, is better than ignoring.

2024-07-15 20:30 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                if (e.name != 'ResponseError') {
If we throw it indiscriminately then we no longer protect against the case where the exchange does not exist. Do you want to go forward with that solution for everything that happens after we get the `Quote`?

2024-07-15 20:30 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // handle failed verification
```suggestion

```

2024-07-15 20:31 UTC, angiejones approved these changes

2024-07-15 20:34 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                if (e.name != 'ResponseError') {
if you decide to keep it, change this to 

```kt
catch(e: ResponseError){

}
catch(e){

}
```

and handle both accordingly

2024-07-15 20:34 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                if (e.name != 'ResponseError') {
btw im on a plane so didn't test that. so make sure it actually compiles

2024-07-16 00:28 UTC, angiejones requested changes
fix catch blocks and we should be good to go

2024-07-16 15:10 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                if (e.name != 'ResponseError') {
Looked into it, everything I'm seeing is that while TypeScript might support the above, JS (which is what are tests are in) won't let me explicitly type the error, and the recommendation is to use the `e.name` property as shown. Let me know if there's a different way you'd prefer to handle it, otherwise the changes as are should be good to go

2024-07-16 15:11 UTC, chris-tbd commented
> fix catch blocks and we should be good to go

@angiejones it looks like we can't do the try/catch as requested because we can't explicitly type for the error, therefore the way it's handled referencing `e.name` should be sufficient. Let me know thoughts and if we can merge

2024-07-17 00:42 UTC, angiejones commented
> > fix catch blocks and we should be good to go
> 
> @angiejones it looks like we can't do the try/catch as requested because we can't explicitly type for the error, therefore the way it's handled referencing `e.name` should be sufficient. Let me know thoughts and if we can merge

@chris-tbd I narrowed the scope of the exception to only ignore exceptions that's of type 404 since that's a better indicator that the exact problem is that the RFQ hasn't been added to the exchange yet

```js
            } catch (e) {
                if (e.statusCode === 404) {
                    //waiting on RFQ to be added to exchange
                }
                else throw e;
            }
```

But once I did this, it exposed that the blanket `catch` is covering up an entirely different issue:

```
Serialized Error: { statusCode: 401, details: { errors: [ { detail: 'Malformed Authorization header: RequestTokenAudienceMismatchError: Request token contains invalid audience. Expected aud property to be PFI DID.' } ] }, recipientDid: 'did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy', url: 'https://pfiexemplar.tbddev.org/exchanges/rfq_01j2z0nqf3efcbkz6rf30hybzx' }
```

Didn't we see this one before? Did you ever resolve it, or was it just missed when you added the blanket catch?

Digging deeper here, the `requiredClaims` on the Offering expects the VC's issuer to be the PFI's DID (which is `did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy`). But the SanctionCredential is being issued by the `issuerDid` (`did:dht:hge69zswp474myt94d149pftycsgk6yr9tufrh7new48re76b5ny`).

You need to change your `applyForCredentials()` to issue this VC using the PFI's DID

2024-07-17 00:55 UTC, angiejones requested changes
VC Issuer should be the PFI

2024-07-17 01:16 UTC, angiejones commented on site/docs/tbdex/quickstart.mdx
> +```js
this is different than what the selected offering has. It has 2 input descriptors

2024-07-17 01:29 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                    //race condition bug
be sure to open a bug for this. 404 shouldnt be thrown if the exchange has already actually been created. add bug number on this line so we can track it.

2024-07-17 01:30 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                    //race condition bug
add bug number on this line so we can track it.

2024-07-17 01:30 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                //race condition bug
add bug number on this line so we can track it.

2024-07-17 01:52 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // the exchange hasn't populated yet
I set the suite so that it runs in chronological order, but it still fails with 404 because the exchange truly wasnt ever created because the VC doesnt meet the offering requirements.

<img width="407" alt="image" src="https://github.com/user-attachments/assets/5f914997-4228-42e4-8ee5-e1b0afb02ec2">

2024-07-17 01:58 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +        //:snippet-start: walletQuickstartSelectOffering
no, they would have to know the offering's ID in advance

2024-07-17 16:38 UTC, chris-tbd commented
> > > fix catch blocks and we should be good to go
> > 
> > 
> > @angiejones it looks like we can't do the try/catch as requested because we can't explicitly type for the error, therefore the way it's handled referencing `e.name` should be sufficient. Let me know thoughts and if we can merge
> 
> @chris-tbd I narrowed the scope of the exception to only ignore exceptions that's of type 404 since that's a better indicator that the exact problem is that the RFQ hasn't been added to the exchange yet
> 
> ```js
>             } catch (e) {
>                 if (e.statusCode === 404) {
>                     //waiting on RFQ to be added to exchange
>                 }
>                 else throw e;
>             }
> ```
> 
> But once I did this, it exposed that the blanket `catch` is covering up an entirely different issue:
> 
> ```
> Serialized Error: { statusCode: 401, details: { errors: [ { detail: 'Malformed Authorization header: RequestTokenAudienceMismatchError: Request token contains invalid audience. Expected aud property to be PFI DID.' } ] }, recipientDid: 'did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy', url: 'https://pfiexemplar.tbddev.org/exchanges/rfq_01j2z0nqf3efcbkz6rf30hybzx' }
> ```
> 
> Didn't we see this one before? Did you ever resolve it, or was it just missed when you added the blanket catch?
> 
> Digging deeper here, the `requiredClaims` on the Offering expects the VC's issuer to be the PFI's DID (which is `did:dht:ccqamm6qgbe763ya8f3bo5mkrtxx1pz7i789zeqq4bmoae4qnixy`). But the SanctionCredential is being issued by the `issuerDid` (`did:dht:hge69zswp474myt94d149pftycsgk6yr9tufrh7new48re76b5ny`).
> 
> You need to change your `applyForCredentials()` to issue this VC using the PFI's DID

I did try that, the issue that it's complaining about with the audience is in the JWT token and not the credential, which is why the getExchange method is the one that is failing. This was brought up in a thread earlier with Kirah, linked here: https://sq-tbd.slack.com/archives/C05SXUR39FE/p1720472770911859?thread_ts=1720055894.132309&cid=C05SXUR39FE
According to her it was a transient issue, which is confirmed by the fact as far as I can tell that the tests eventually do pass. If that 401: Unauthorized error kept repeating every time, the test would never exit the while loop in the Process Quote test because the quote variable at the top of the while loop would remain null, therefore making it so the loop runs infinitely

2024-07-17 16:43 UTC, chris-tbd commented on site/testsuites/testsuite-javascript/__tests__/tbdex/wallet/quickstart.test.js
> +                // the exchange hasn't populated yet
Looked deeper into this, it is a race condition fixed by simply waiting it out because the PFI is still processing. I verified the VC is using the correct data

2024-07-17 16:47 UTC, chris-tbd commented on site/docs/tbdex/quickstart.mdx
> +```js
Added the second input descriptor

2024-07-18 18:55 UTC, angiejones approved these changes

2024-07-18 18:58 UTC, merged