WIP: Move examples to their own repos
TBD54566975/developer.tbd.website pull request #1449
Opened 2024-06-21 19:37 UTC by finn-tbd

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR moves the examples code into the [tbd-examples](https://github.com/TBD54566975/tbd-examples) repo.

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2024-06-24 18:46 UTC, EbonyLouis commented
They're separated by languages should be separate them by project too? like web5 and tbDEX?

2024-06-25 16:25 UTC, angiejones commented
All tbDEX examples use web5 by default. I'd prefer if the README files only listed tbDEX and not the comma-delimited `tbDEX, web5`.

2024-06-25 16:28 UTC, angiejones requested changes

2024-06-25 16:28 UTC, angiejones commented on site/docs/docs-index.js
These 2 links also need to be updated

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/22b8fa3b-5e39-448c-be97-9d7e640ede4a)

2024-07-02 17:42 UTC, finn-tbd commented on site/docs/docs-index.js
ooo good catch! i updated the iOS wallet link, but we haven't moved the pfi-exemplar yet ([ongoing discussion on that](https://github.com/TBD54566975/tbdex-pfi-exemplar/pull/52)) so I'm not going to update that link yet. I left a note on that side to remind us to update this one when we decide what to do over there.

2024-07-05 19:29 UTC, angiejones approved these changes

2024-07-05 21:32 UTC, merged