activate-polyfills guide
TBD54566975/developer.tbd.website pull request #1476
Opened 2024-07-18 10:31 UTC by blackgirlbytes

- Moved activate polyfills out of connect guide
- Updated community DWN info to match @angiejones's updates in main
- Created guide called Accessing Data with DRLs 
- Created tests for code snippets for Accessing Data with DRLs

2024-07-18 18:19 UTC, chris-tbd requested changes

2024-07-18 18:19 UTC, chris-tbd commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +A **Decentralized Web App (DWA)** is a Progressive Web App (PWA) that incorporates Web5 functionalities, providing offline capabilities, Decentralized Resource Locators (DRLs), and offline synchroniz
Link to resource to read more?

2024-07-18 18:19 UTC, chris-tbd commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +A **Decentralized Web App (DWA)** is a Progressive Web App (PWA) that incorporates Web5 functionalities, providing offline capabilities, Decentralized Resource Locators (DRLs), and offline synchroniz
Link to DWN guide

2024-07-18 18:19 UTC, chris-tbd commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Configure a service worker to activate Web5 polyfills while managing caching and data synchronization tasks.
Not totally sure what this means - is this something that devs will more inherently understand?

2024-07-18 18:19 UTC, chris-tbd commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +## Import packages
Before jumping into the code can we add a sentence or two of what the point of this page is?

2024-07-18 18:19 UTC, chris-tbd commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +After you [write records](/docs/web5/build/decentralized-web-nodes/write-to-dwn) to a DWN, you can Decentralized Resource Locators (DRLs) to fetch data directly from the decentralized network.
How are `DRLs` resolved/used? Can I just use one via my browser, or do I need a special app/library?

2024-07-18 18:19 UTC, chris-tbd commented on site/docs/web5/build/decentralized-web-nodes/web5-connect.mdx
> +This instance hosted by Google and DIF provide a reliable staging environment for apps. Note: data on your DWN stays encrypted and in your control.
Do we need to explain what a Community Node is, how access/permissions work, or link to any other documentation/references?

2024-07-18 18:28 UTC, leordev commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Configure a service worker to activate Web5 polyfills while managing caching and data synchronization tasks.
service workers are something that PWA developers understand: https://web.dev/learn/pwa/service-workers

2024-07-18 18:30 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Configure a service worker to activate Web5 polyfills while managing caching and data synchronization tasks.
I'll add a link to that that then.

2024-07-18 19:29 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Configure a service worker to activate Web5 polyfills while managing caching and data synchronization tasks.
Thanks @chris-tbd and @leordev! I updated the doc. I tend to be a little wordy/verbose in documentation, so I was trying to be terse and get to the point, but I think I was too terse 😆 . Hopefully, this strikes a better balance.

2024-07-18 19:30 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +## Import packages
done

2024-07-18 19:30 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +A **Decentralized Web App (DWA)** is a Progressive Web App (PWA) that incorporates Web5 functionalities, providing offline capabilities, Decentralized Resource Locators (DRLs), and offline synchroniz
Linked!

2024-07-18 19:30 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +A **Decentralized Web App (DWA)** is a Progressive Web App (PWA) that incorporates Web5 functionalities, providing offline capabilities, Decentralized Resource Locators (DRLs), and offline synchroniz
I linked to a blog post you wrote. Not too sure what if I have resources on DWAs.

2024-07-18 19:31 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +After you [write records](/docs/web5/build/decentralized-web-nodes/write-to-dwn) to a DWN, you can Decentralized Resource Locators (DRLs) to fetch data directly from the decentralized network.
Hopefully, my updated explanation is more clear!

2024-07-18 19:47 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/web5-connect.mdx
> +This instance hosted by Google and DIF provide a reliable staging environment for apps. Note: data on your DWN stays encrypted and in your control.
at first a link wasn't live but now it is, so i can add more details! thanks!

2024-07-19 04:37 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/web5-connect.mdx
> +Use up to 1GB of free storage on a Community DWN instance hosted by [Google and the Decentralized Identity Foundation (DIF)](https://identity.foundation/dwn/) for staging environments.
```suggestion
Use up to 1GB of free storage on a Community DWN instance hosted by [Google and the Decentralized Identity Foundation (DIF)](https://identity.foundation/dwn/) for non-production environments.
```

2024-07-19 04:39 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Import the following package to handle interactions with Decentralized Web Nodes (DWNs) and manage offline data:
```suggestion
Import the following package to handle interactions with DWNs and manage offline data:
```

2024-07-19 04:41 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Decentralized Resource Locators (DRLs) enable direct access to data stored in Decentralized Web Nodes (DWNs). After writing records to a DWN, you can use DRLs (prefixed with `dweb://`) to fetch data.
```suggestion
Decentralized Resource Locators (DRLs) enable direct access to data stored in DWNs. After writing records to a DWN, you can use DRLs (prefixed with `dweb://`) to fetch data. 
```

2024-07-19 04:44 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Decentralized Resource Locators (DRLs) enable direct access to data stored in Decentralized Web Nodes (DWNs). After writing records to a DWN, you can use DRLs (prefixed with `dweb://`) to fetch data.
the prefix note doesn't match the example:

```
https://dweb/${did}/read/records/${recordId
```

2024-07-19 04:52 UTC, angiejones requested changes

2024-07-19 04:52 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Decentralized Resource Locators (DRLs) enable direct access to data stored in Decentralized Web Nodes (DWNs). After writing records to a DWN, you can use DRLs (prefixed with `dweb://`) to fetch data.
```suggestion
Decentralized Resource Locators (DRLs) enable direct read access to permussioned data stored in DWNs. To read records from a DWN, you can use DRLs (prefixed with `dweb://`) to fetch the data. 
```

2024-07-19 04:52 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +DRLs return JSON data that can be used throughout your web app, from populating UI elements to setting attributes on HTML tags.
should show an example below of using it inline as the `src` of an `<img>` or something like that

2024-07-19 04:52 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Decentralized Resource Locators (DRLs) enable direct access to data stored in Decentralized Web Nodes (DWNs). After writing records to a DWN, you can use DRLs (prefixed with `dweb://`) to fetch data.
Oh true. It should be dweb/ . Thats a typo on my part

2024-07-19 04:55 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +# Upgrade to DWA
```suggestion
# Accessing Data with DRLs
```

what do you think of something like this for the title? I'm thinking i may not be upgrading an existing app, so the current title might not grab my attention

2024-07-19 04:56 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +# Upgrade to DWA
if you change the title, I'd just delete the next header and go right into the text of that section

2024-07-19 05:03 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +This guide will walk you through upgrading your PWA to a DWA. For a practical implementation, refer to the [DWA starter app](https://github.com/TBD54566975/dwa-starter).
```suggestion
This guide will walk you through how to read from DWNs within your DWA. For a practical implementation, refer to the [DWA starter app](https://github.com/TBD54566975/dwa-starter).
```

2024-07-19 05:04 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +# Upgrade to DWA
also if you change the title, change the file name too

2024-07-19 09:57 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +Decentralized Resource Locators (DRLs) enable direct access to data stored in Decentralized Web Nodes (DWNs). After writing records to a DWN, you can use DRLs (prefixed with `dweb://`) to fetch data.
done

2024-07-19 09:58 UTC, blackgirlbytes commented on site/docs/web5/build/decentralized-web-nodes/upgrade-to-dwa.mdx
> +# Upgrade to DWA
I like your suggestion!

2024-07-21 20:39 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/access-data-with-drls.mdx
> +# Accessing Data with DRLs
```suggestion
# Access Data with DRLs
```

2024-07-21 20:39 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/access-data-with-drls.mdx
> +## Import packages
```suggestion
## Import package
```

2024-07-21 20:41 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/access-data-with-drls.mdx
> +DRLs enable direct read access to permussioned data stored in DWNs. To read records from a DWN,  After writing records to a DWN, you can use DRLs (prefixed with `https://dweb`) to fetch the data.
```suggestion
Decentralized Resource Locators (**DRLs**) enable direct read access to permissioned data stored in DWNs. To read records from a DWN,  After writing records to a DWN, you can use DRLs (prefixed with `https://dweb`) to fetch the data. 
```

2024-07-21 20:44 UTC, angiejones requested changes

2024-07-21 20:44 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/access-data-with-drls.test.js
> +    const dwebUrl = `https://dweb/${did}/read/records/${recordId}`;
can you rename to `drl`. it probably won't be clear that `dwebUrl` and `drl` mean the same thing

2024-07-21 20:46 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-web-nodes/access-data-with-drls.test.js
> +    const dwebUrl = `https://dweb/${did}/read/records/${recordId}`;
True!

2024-07-22 00:19 UTC, angiejones approved these changes

2024-07-22 00:37 UTC, merged