PFI Quickstart
TBD54566975/developer.tbd.website pull request #1477
Opened 2024-07-18 19:06 UTC by chris-tbd

This pull request introduces multiple changes to improve the documentation and code snippets for the tbDEX platform. The changes include new scripts for the PFI Quickstart guide, modifications to the sidebar positions of the documentation, and the addition of a new PFI Quickstart guide.

New PFI Quickstart Guide:

* [`site/docs/tbdex/pfi-quickstart.mdx`](diffhunk://#diff-d49ab09c0cc326b94dd71709511ebff1d51c7fe243adf698878111085ab9f990R1-R231): Added a new PFI Quickstart guide that provides a step-by-step tutorial on how to create a PFI, open endpoints for tbDEX-enabled Wallets, broadcast Offerings, process Requests for Quote and respond with Quotes, accept Orders, provide OrderStatus Updates, and Close out Orders.

Code Snippets:

* [`site/code-snippets/tbdex/pfi-quickstart.js`](diffhunk://#diff-867255964d34633609eaeaee1555b5d69928ac78e84a1cf907f3bb9f948f31f2R1-R202): Added new code snippets that demonstrate how to create a PFI, open endpoints for tbDEX-enabled Wallets, broadcast Offerings, process Requests for Quote and respond with Quotes, accept Orders, provide OrderStatus Updates, and Close out Orders.
* [`site/src/components/PfiQuickstartCodeRunner.jsx`](diffhunk://#diff-e2c4b4755ae3daa96f9911cd0ed2b1f32da8e5a3214247fa9db71e4c20a4a79eR1-R106): Added a new component that runs the code snippets in the PFI Quickstart guide.

Documentation Changes:

* `site/docs/tbdex/issuer/_category_.json`, `site/docs/tbdex/pfi/_category_.json`, `site/docs/tbdex/wallet/_category_.json`: Changed the sidebar positions of the Issuers, PFIs, and Wallets sections in the documentation. [[1]](diffhunk://#diff-98a9226f73252619510cb83ef49e292e092929f08bba72fcaca68d899572197eL3-R3) [[2]](diffhunk://#diff-927d8f24aa6b4204e852efd3c6740c0009b4d4fe26cbadd17dc2c8dc1f56d9e2L3-R3) [[3]](diffhunk://#diff-1b15df38b779b2a1ce5fa92de2c9aa80af57f76f389a07e89169d7d502307cafL3-R3)
* [`site/docs/tbdex/wallet-quickstart.mdx`](diffhunk://#diff-6aef0a6d79ce1d8b7653876f891fb240f5a521ef94d28919eeca09f3b8d675bfL2-R2): Renamed the file from `quickstart.mdx` to `wallet-quickstart.mdx` and changed the sidebar position.

Test Suite Changes:

* [`site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfiStructure.test.js`](diffhunk://#diff-6034931b0be95f8b7602c871fb3c186de2d8d550e18a524bd9e5fb6bdc3cbbe5R17-R18): Modified the test suite to accommodate the new PFI structure. [[1]](diffhunk://#diff-6034931b0be95f8b7602c871fb3c186de2d8d550e18a524bd9e5fb6bdc3cbbe5R17-R18) [[2]](diffhunk://#diff-6034931b0be95f8b7602c871fb3c186de2d8d550e18a524bd9e5fb6bdc3cbbe5L25-R28)

2024-07-19 15:51 UTC, blackgirlbytes requested changes
Hmm when i run the first step, no PFI DID shows up for me
<img width="892" alt="Screenshot 2024-07-19 at 11 51 17 AM" src="https://github.com/user-attachments/assets/85a27da7-b6a5-45ee-b78f-926772a5a6a3">

2024-07-19 20:05 UTC, chris-tbd commented
> Hmm when i run the first step, no PFI DID shows up for me <img alt="Screenshot 2024-07-19 at 11 51 17 AM" width="892" src="https://private-user-images.githubusercontent.com/22990146/350457889-85a27da7-b6a5-45ee-b78f-926772a5a6a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTc5NDQsIm5iZiI6MTcyMTQxNzY0NCwicGF0aCI6Ii8yMjk5MDE0Ni8zNTA0NTc4ODktODVhMjdkYTctYjZhNS00NWVlLWI3OGYtOTI2NzcyYTVhNmEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE5MzQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBiMWE4OGRjZjBhZTZkYzVmMzMwZGI0ODVhNzExYTg1NjhlOWM2MzgyNTM0NTE4OTYyN2FlY2NlOGVkNzdmZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PY7jjabfSOfSoEaA_oy1yu5TVPd9Qug5-g_paCRyEAY">

All ironed out!

2024-07-19 23:15 UTC, angiejones commented on site/code-snippets/tbdex/wallet-quickstart.js
update the issuer DID here to be the PFI's DID. should highlight it as well

<img width="814" alt="image" src="https://github.com/user-attachments/assets/5c4f1158-33ee-43b3-ad0d-2738beb76736">



```js
const pfiDid = did:dht:rj9xmgqcqs1rysongf833wo5g1dtabbhnimcorczcyurke4fmizo
```

2024-07-19 23:20 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +                      const: issuerDid.trim() // Use the read issuer DID here
dont think you want to show this here. especially the comment

2024-07-19 23:33 UTC, angiejones commented on site/code-snippets/tbdex/pfi-quickstart.js
> +          description: 'fake offering 1',
can we show a realistic description and also simplify the description? like a bare bones offering with only the required fields.

2024-07-20 15:30 UTC, blackgirlbytes requested changes

2024-07-20 15:30 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +<PfiQuickstartCodeRunner executeCodeName="executeGetOfferings" stepIndex={3} customPlaceholder={"Ping the /offerings API Endpoint"} viewJsonObj={true} collapseLevel={1}/>
Hmm change the collapseLevel to 2 or 3 so I can see a bit more of the object by default 
<img width="968" alt="Screenshot 2024-07-20 at 11 28 48 AM" src="https://github.com/user-attachments/assets/d7db1f02-fd68-4dae-9f10-0cc702b54677">

2024-07-20 15:30 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +<PfiQuickstartCodeRunner executeCodeName="executeGetExchanges" stepIndex={4} customPlaceholder={"Fetch a sample Exchange"} viewJsonObj={true} collapseLevel={1}/>
Hmm change the collapseLevel to 2 or 3 so I can see a bit more of the object by default 
<img width="968" alt="Screenshot 2024-07-20 at 11 28 48 AM" src="https://github.com/user-attachments/assets/d7db1f02-fd68-4dae-9f10-0cc702b54677">

2024-07-22 04:00 UTC, angiejones requested changes
let's set up some time to review together. want this to be more streamlined into a quickstart vs a lengthy full tutorial.

2024-07-22 04:00 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +Let’s build a tbDEX-enabled PFI in under 5 minutes, right here in the browser. You will learn how to:
This is a quickstart, meaning it's likely the very first stop for people. So, you need to provide some context here. What does PFI stand for? what does a PFI do on tbDEX?

Doesn't have to be long, but one or two lines to set the stage would be very helpful

2024-07-22 04:00 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +In this exercise, your PFI app is responsible for creating an `Offering` that swaps `USD` for `KES` and facilitating that transaction for your customer Alice.
This line feels out of place here since you go into creating a DID. Maybe it should be moved down to where you make the offering

2024-07-22 04:00 UTC, angiejones commented on site/code-snippets/tbdex/pfi-quickstart.js
> +                serviceEndpoint: 'https://localhost:8080'
should be a real url. you can use the one you've deployed

2024-07-22 04:00 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +### Declare your PFI with a DID
```suggestion
### Create a DID
```

2024-07-22 04:00 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +In order for your app to be recognized as a PFI by other apps, you’ll need to create a DID that declares a `pfi` service and an associated `serviceEndpoint` that is the hostname you want Wallets to b
```suggestion
On tbDEX, PFIs are identified with [Decentralized Identifiers (DIDs)](/docs/web5/learn/decentralized-identifiers). Let's create a DID for your PFI and specify a service endpoint where Wallet apps can reach you to transact:
```

2024-07-22 16:16 UTC, angiejones commented on site/docs/tbdex/wallet-quickstart.mdx
> +
```suggestion
```

2024-07-23 14:32 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +title: PFI Quickstart
```suggestion
title: 'Quickstart: PFI'
```

2024-07-25 05:25 UTC, chris-tbd commented on site/code-snippets/tbdex/pfi-quickstart.js
> +                serviceEndpoint: 'https://localhost:8080'
Updated

2024-07-25 05:25 UTC, chris-tbd commented on site/code-snippets/tbdex/pfi-quickstart.js
> +          description: 'fake offering 1',
Simplified some of the descriptions, how many more fields can we strip away ?

2024-07-25 05:25 UTC, chris-tbd commented on site/docs/tbdex/pfi-quickstart.mdx
> +In this exercise, your PFI app is responsible for creating an `Offering` that swaps `USD` for `KES` and facilitating that transaction for your customer Alice.
Moved

2024-07-25 05:25 UTC, chris-tbd commented on site/docs/tbdex/pfi-quickstart.mdx
> +                      const: issuerDid.trim() // Use the read issuer DID here
Removed

2024-07-25 05:25 UTC, chris-tbd commented on site/docs/tbdex/pfi-quickstart.mdx
> +                      const: issuerDid.trim() // Use the read issuer DID here
Would you want to put a code example of creating an offering? or skip out on that alltogether?

2024-07-25 05:25 UTC, chris-tbd commented on site/docs/tbdex/pfi-quickstart.mdx
> +<PfiQuickstartCodeRunner executeCodeName="executeGetOfferings" stepIndex={3} customPlaceholder={"Ping the /offerings API Endpoint"} viewJsonObj={true} collapseLevel={1}/>
Good call, updating

2024-07-25 05:25 UTC, chris-tbd commented on site/docs/tbdex/pfi-quickstart.mdx
> +<PfiQuickstartCodeRunner executeCodeName="executeGetExchanges" stepIndex={4} customPlaceholder={"Fetch a sample Exchange"} viewJsonObj={true} collapseLevel={1}/>
Updating

2024-07-25 05:25 UTC, chris-tbd commented on site/docs/tbdex/pfi-quickstart.mdx
> +Let’s build a tbDEX-enabled PFI in under 5 minutes, right here in the browser. You will learn how to:
Added

2024-07-25 05:28 UTC, chris-tbd commented on site/code-snippets/tbdex/wallet-quickstart.js
I might've misunderstood your other comment but I thought you had suggested removing the offering? or did you just want to refactor what we're showing?

2024-07-25 05:35 UTC, chris-tbd commented
@angiejones went ahead and merged with main/updated comments, I'm seeing some intermittent failures that I'll take a look at tomorrow evening! Outside of that comments should be addressed with just a few questions for ya

2024-07-25 05:40 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +                      const: issuerDid.trim() // Use the read issuer DID here
i think we can skip creating it from scratch for the quickstart and just show one

2024-09-11 19:52 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +A Participating Financial Institution (PFI) in the tbDEX ecosystem provides liquidity offerings to customers via Wallets. Customers can place orders and execute transactions if they meet the necessar
```suggestion
A [Participating Financial Institution (PFI)](/docs/tbdex/pfi/overview) in the tbDEX ecosystem provides liquidity offerings to customers via Wallets. Customers can place orders and execute transactions if they meet the necessary requirements.
```
add link to more about PFIs

2024-09-11 20:43 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +A Participating Financial Institution (PFI) in the tbDEX ecosystem provides liquidity offerings to customers via Wallets. Customers can place orders and execute transactions if they meet the necessar
Okay on second thought..you might even be able to make these sentences even more short but clear..and more connected

```suggestion
A [Participating Financial Institution (PFI)](/docs/tbdex/pfi/overview) in the tbDEX ecosystem provides liquidity offerings to customers via [Wallets](/docs/tbdex/wallet/overview), allowing eligible customers to place orders and execute transactions.
```

2024-09-11 20:45 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +- Handle Orders, provide `OrderStatus` updates, and close out Orders
not a requirement but the other quickstarts have checkmarks instead of bullet points..maybe we can add that just for consistency?

2024-09-11 22:05 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +There are two primary components to a PFI: the `OfferingsApi` and the `ExchangesApi`. The `OfferingsApi` allows Wallets to query your PFI for available offerings, while the `ExchangesApi` handles RFQ
okay I think it's cuz im neurodivergent, but there's too many words enclosed by backticks/that are greyed code snippets for me, so my eyes keep jumping around..What if you did something like this for readability? Feel free to change to your liking

```suggestion
PFIs are [Express](https://expressjs.com/) servers enhanced with the [tbDEX SDK](/docs/tbdex/). You'll need a:

Server
Database (e.g., PostgreSQL) with offerings and exchanges tables
There are two primary components to a PFI:

[OfferingsApi](/docs/tbdex/pfi/anatomy-of-a-pfi/#offerings-api-provider): Allows Wallets to query available offerings
[ExchangesApi](/docs/tbdex/pfi/anatomy-of-a-pfi/#exchange-api-provider): Handles RFQs, Orders, and exchange closures
```

2024-09-11 22:51 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +
most of your headings are gerunds (words ending with -ing) do you want to change these two headings to Creating a DID and Structuring your PFI App for consistency?

2024-09-11 23:34 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +With your `offeringsApi` all setup to return offerings when requested, this is what wallet providers would receive when they call `TbdexHttpClient.getOfferings()` :
sometimes you write `offeringsApi` and sometimes you write `OfferingsApi`.

Which one should you write for consistency?

2024-09-11 23:38 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +<CodeSnippet snippetName="pfiCreateQuickstartOfferingJs" title="offeringsApiProvider.ts" />
I wish this could be runnable code, but I guess I get why it's not

2024-09-11 23:38 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +<CodeSnippet snippetName="pfiOverviewConfigJs" title="main.ts" />
I wish this could be runnable code, but I guess I get why it's not

2024-09-12 00:04 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +Here's an example:
what if you said something like
```suggestion
Without Offerings, your PFI doesn't have anything to present to customers. Let's [create an Offering](/docs/tbdex/pfi/creating-offerings) for USD to KES and and insert it into your `offerings` table:
```

2024-09-12 00:07 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +<PfiQuickstartCodeRunner executeCodeName="executeGetOfferings" stepIndex={1} customPlaceholder={"Fetch offerings from the PFI Endpoint"} viewJsonObj={true} collapseLevel={3} />
is this return value correct? -- undefined?
<img width="915" alt="Screenshot 2024-09-11 at 8 05 18 PM" src="https://github.com/user-attachments/assets/c510a1c1-e05a-45e5-a2e6-fb3cdc72ad30">

2024-09-12 00:08 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +When a customer selects an offering, they make a `Request for Quote` along with their credentials that match the `requiredClaims` of the offering. Using this submitted data, your PFI generates a  `Qu
Instead of Request for Quote being in a the code backticks..maybe we can link to the guide about RFQs 
docs/tbdex/wallet/send-rfq

2024-09-12 00:12 UTC, blackgirlbytes requested changes
Some `Run` buttons don't run and some of them return errors or undefined :(, but maybe you're in the process of resolving these and my comment is redundant
<img width="909" alt="Screenshot 2024-09-11 at 8 12 25 PM" src="https://github.com/user-attachments/assets/98b8f263-0efa-4067-a674-3a49d12f48c2">

2024-09-12 20:00 UTC, acekyd commented on site/docs/tbdex/pfi-quickstart.mdx
> +- Handle Orders, provide `OrderStatus` updates, and close out Orders
I'll likely change those. Not sure I like the checkmarks since they are not done yet.

2024-09-12 20:13 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +- Handle Orders, provide `OrderStatus` updates, and close out Orders
aww i liked them 🤣 but okay!

2024-09-12 21:55 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +- Handle Orders, provide `OrderStatus` updates, and close out Orders
dont be boring Ace lol! maybe another emoji?

2024-09-12 21:55 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +- Handle Orders, provide `OrderStatus` updates, and close out Orders
```suggestion
- Handle Orders, provide OrderStatus updates, and close out Orders
```

none of the other message types that are listed are encoded

2024-09-12 21:57 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/pfi/pfiStructure.test.js
>                      serviceEndpoint: 'https://localhost:8080'
```suggestion
                    serviceEndpoint: 'https://example.com'
```

this needs to show a real deployed URL, otherwise it's misleading.

2024-09-12 22:39 UTC, angiejones requested changes

2024-09-12 22:39 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +### Structure Your PFI App
Ok this section and the next are TMI (tooooo much info). We want people to get right into playing around. I recommend replacing lines 40 - 88 with this:

```
### Structure Your PFI App
To operate as a PFI on the tbDEX network, you'll need a server that handles incoming requests, a database that holds Offerings and Exchanges, and implementations of the OfferingsApi and ExchangesApi. We'll spare you the details in this Quickstart, however, for more info, check out the guide on [Structuring a PFI App](/docs/tbdex/pfi/anatomy-of-a-pfi).

### Fetching Offerings for Wallets
With your database populated with Offerings and the OfferingsApi set up, Wallet applications can now call `TbdexHttpClient.getOfferings()` to obtain a list of the currency conversions you offer and the requirements to transact. 

[runnable code thingy]
```

2024-09-12 22:45 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +When a customer selects an offering, they make a `Request for Quote` along with their credentials that match the `requiredClaims` of the offering. Using this submitted data, your PFI generates a  `Qu
```suggestion
When a customer selects an offering, they make a `RFQ` (Request for Quote) that includes the methods of payment they'd prefer and the credentials that match the `requiredClaims` of the Offering. Using this submitted data, your PFI generates a  `Quote`:
```

2024-09-12 22:46 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +
Add a sentence here explaining what's a "tbDEX message"

2024-09-12 22:47 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +The customer has accepted the quote and places an order. Let's process accepted Quotes, manage Orders, and send `OrderStatus` updates:
be careful with capitalization. in this first sentence "quote" and "order" are lowercase. In the second sentence they are capitalized. and OrderStatus is the only one of the messages enclosed in backticks. Review the guide and make the tbDEX message types consistent throughout

2024-09-12 22:48 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +<PfiQuickstartCodeRunner executeCodeName="executeGetQuote" stepIndex={2} customPlaceholder={"See the Quote"} viewJsonObj={true} collapseLevel={1} />
can we increase the collapseLevel throughout to either 2 or 3? want to see more of the output so it makes more sense.

2024-09-12 22:51 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +Once the order is fulfilled, or cancelled by the PFI for whatever reason, you close orders with a `Close` message along with the `reason`:
```suggestion
Once the order is completed (whether that means fulfilled or cancelled) fulfilled, you close the exchange with a `Close` message which can optionally include a `reason` and a `success` indicator:
```

2024-09-12 22:51 UTC, blackgirlbytes commented on site/docs/tbdex/pfi-quickstart.mdx
> +### Structure Your PFI App
that was my fault. i tried to make the structure pfi part shorter/readable..but it still wasnt. I like your suggestion

2024-09-12 22:52 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +Congratulations on building your first PFI! To explore further, check out the full [PFI guide](/docs/tbdex/pfi/overview) or learn about [building a Wallet](/docs/tbdex/wallet/overview) and [becoming
```suggestion
Congratulations on building your first PFI! To explore further, check out the full [PFI guide](/docs/tbdex/pfi/overview).
```

2024-09-12 23:05 UTC, angiejones commented
Don't forget to mention that for every tbDEX message the PFI creates, they need to save it to their database so that the Wallet app can call an endpoint to retrieve it. This doesn't have to be a big proclamation. Just kinda slide it into the existing wording, something along the lines of "here's the quote message that you will write to your database for the wallet application".

2024-09-13 08:32 UTC, acekyd commented on site/docs/tbdex/pfi-quickstart.mdx
> +With your `offeringsApi` all setup to return offerings when requested, this is what wallet providers would receive when they call `TbdexHttpClient.getOfferings()` :
The `OfferingsApi` is the interface to extend, the `offeringsApi` is the argument to pass to the server instance. Will try to reduce the occurrence of this so it's less confusing to the reader.

2024-09-13 09:36 UTC, acekyd commented
It's definitely quick now lol.

2024-09-15 00:01 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +✅  Process Requests for `Quote` and respond with Quotes
```suggestion
✅  Provide a `Quote` when requested
```

2024-09-15 00:02 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +✅  Set up a basic PFI with offerings
```suggestion
✅  Set up a basic PFI with `Offerings`
```

2024-09-15 00:02 UTC, angiejones commented on site/docs/tbdex/pfi-quickstart.mdx
> +✅  Handle Orders, provide `OrderStatus` updates, and close out Orders
```suggestion
✅  Process `Orders`
```

2024-09-15 03:25 UTC, angiejones approved these changes

2024-09-16 08:31 UTC, merged