KBC Guide: Skeleton
TBD54566975/developer.tbd.website pull request #1526
Opened 2024-08-05 22:18 UTC by blackgirlbytes

Draft for now. Need to add:
- Kotlin snippets
- Scenario
- More explanation for each heading

2024-08-05 22:30 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +KBCs help businesses gain access to PFIs providing regulated financial services.
```suggestion
By issuing this credential, the PFI attests to the business’s legitimacy and compliance with regulations, allowing the PFI to engage in financial activities with the Wallet application without requiring individual KYC for each customer.
```

wanna rephrase this

2024-08-05 22:32 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Install packages
Install and Import sections not needed. Instead, you can point them to the Issuer setup guide (/docs/tbdex/issuer/vc-serversetup/)

2024-08-05 22:33 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +        const vc = await VerifiableCredential.create({
can we rename to kbc?

2024-08-05 22:34 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +            subject: subjectDid.uri,
PFI won't have the subject's BearerDID, so this should be `subjectDidUri` or something like that

2024-08-05 22:35 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                id: subjectDid.uri
dont use BearerDid

2024-08-05 22:37 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                id: subjectDid.uri
actually I think `VerifiableCredential.create()` adds the `id` to `data` by default. You may be able to leave this empty. Test it out without the `id` and see what the VC's JSON looks like

2024-08-05 22:41 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Issue and Sign Credential
Let's add a lil text here. Something like:

"To issue a KBC, call `VerifiableCredential.create()` and pass in the URL to the credential schema the VC is based on. We have designed an open source schema for KBCs that you're welcome use at https://vc.schemas.host/kbc.schema.json"

2024-08-05 22:44 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +        const vc = await VerifiableCredential.create({
can we add comments next to each property so they know what it is?

```js
{
    issuer: pfiDid.uri, // Issuer's DID URI
    subject: subjectDidUri, // Wallet app's DID URI
    expirationDate: '2025-09-30T12:34:56Z', // Date the KBC should expire
    data: { },
    credentialSchema: {
        type: "JsonSchema", // Format type of the schema used for the KBC
        id: "https://vc.schemas.host/kbc.schema.json" // URL to the schema used for the KBC
    }
}
```

2024-08-05 22:44 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +        const vc = await VerifiableCredential.create({
done!

2024-08-05 22:44 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Issue and Sign Credential
```suggestion
## Issue Credential
```

2024-08-05 22:45 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Specify a KBC as a required claim in an Offering
```suggestion
## Specify KBC as Requirement
```

2024-08-05 22:47 UTC, blackgirlbytes commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Install packages
done!

2024-08-05 22:50 UTC, blackgirlbytes commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Issue and Sign Credential
oh okay so I will remove the part where I show how to sign a credential. I wasn't sure if that was extra or they would need to do that.

2024-08-05 22:51 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Specify a KBC as a required claim in an Offering
Add text description:

"If you issue a KBC to a business, you'll want to specify that credential as a [required claim](/docs/tbdex/pfi/creating-offerings#required-claims) on any applicable Offerings you may provide. You can do this via a [Presentation Definition](/docs/web5/verifiable-credentials/presentation-definition) where your input descriptors will specify that the KBC must be issued by your PFI (as noted by your DID URI) and the KBC's credential schema ID must be a specific URL (the one you used to issue the credential)."

2024-08-05 22:52 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Issue and Sign Credential
no, leave that. just dont need it in the title. Signing is a part of issuing

2024-08-05 22:53 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                    protocol: "1.0"
```suggestion

```

we're about to update to 2.0. can just leave this off. Ace will update the offering when he updates the site to 2.0

2024-08-05 22:54 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                id: subjectDid.uri
yes you are right it does add it. I will remove this then and leave data as an empty object

2024-08-05 22:55 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +### Specify required claim in Offering
```suggestion
### Add Required Claim to Offering
```

2024-08-05 22:56 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +### Specify required claim in Offering
Add text:

> Now that you've defined your requirements, you can add them to any relevant Offerings.

2024-08-05 22:58 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +            subject: subjectDid.uri,
done!

2024-08-05 23:11 UTC, blackgirlbytes commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +### Specify required claim in Offering
done!

2024-08-05 23:11 UTC, blackgirlbytes commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +### Specify required claim in Offering
done!

2024-08-05 23:11 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                    protocol: "1.0"
good point. done!

2024-08-05 23:12 UTC, blackgirlbytes commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Specify a KBC as a required claim in an Offering
done!

2024-08-05 23:13 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                    payin: {
let's make this smaller so we can get to the `requiredClaims` faster:

```
        payin: {
          currencyCode: "USD",
          max: "100.00",
          methods: [
            {
              description: "Pay in via Debit Card, Apple Pay, or CashApp Pay",
              kind: "PAYMENT_LINK",
              name: "Debit Card, ApplePay, CashApp Pay"
            }
          ]
        },
```

2024-08-05 23:17 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                                path: ["$.credentialSchema.id"],
```suggestion
                                path: ["$.vc.credentialSchema[0].id"],
```

2024-08-05 23:17 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                                path: ["$.issuer"],
```suggestion
                                path: ["$.vc.issuer"],
```

2024-08-05 23:37 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +If you haven't already, please follow the [Credential Issuance Server Setup Guide](/docs/tbdex/issuer/vc-serverSetup) for detailed instructions on the dependencies and packages needed to set up your
```suggestion
If you haven't already, please follow the [Credential Issuance Server Setup Guide](/docs/tbdex/issuer/vc-serverSetup) for detailed instructions on the dependencies and packages needed to set up your server.
```

2024-08-05 23:41 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +If you issue a KBC to a business, you'll want to specify that credential as a required claim on any applicable Offerings you may provide.
```suggestion
If you issue a KBC to a business, you'll want to specify that credential as a [required claim](/docs/tbdex/pfi/creating-offerings#required-claims) on any applicable Offerings you may provide. 
```

2024-08-05 23:41 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +:::note
can remove this. you cover it in the comment within the PD 👍🏾

2024-08-06 02:24 UTC, blackgirlbytes commented on site/testsuites/testsuite-kotlin/src/test/kotlin/docs/tbdex/issuer/kbc/KnownBusinessCredentialIssuerTest.kt
> +            data = AdditionalData(), // Custom attributes for the KBC
Kotlin won't let me put an empty object

2024-08-06 02:29 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +                    id: "known-business-credential_1", // required unique id for the input descriptor
I think I had two id fields inside of input_descriptors

2024-08-06 02:54 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +            data: {}, // Optional: Custom attributes for the KBC
should probably put the comment inside the braces. This seems like `data` is option, but it's required.

```js
data: { 
    // Optional: Custom attributes for the KBC
},
```

2024-08-06 02:58 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## Specify KBC as Requirement
```suggestion
In the example above, `signedKbc` is a [token](/docs/web5/verifiable-credentials/jwt-to-vc#what-is-a-jwt) that you can safely provide to the business you're issuing the KBC to.

## Specify KBC as Requirement
```

2024-08-06 03:57 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/tbdex/issuer/kbc/knownBusinessCredentialIssuer.test.js
> +            data: {}, // Optional: Custom attributes for the KBC
oh true. okay I will even take out the words optional because that is misleading

2024-08-06 04:01 UTC, blackgirlbytes commented
@angiejones okay i tried to add a scenario. I hope it's accurate. And I tried to keep it terse, so I won't lose people from the code.

2024-08-06 10:20 UTC, blackgirlbytes commented on site/docs/tbdex/issuer/overview.mdx
> +5. [Issuing a Known Business Credential](/docs/tbdex/issuer/kbc/kbc-issuer)
does it make sense to add this here?

2024-08-06 11:22 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +## TL;DR
yeah let's remove the story.

2024-08-06 11:25 UTC, angiejones requested changes

2024-08-06 11:25 UTC, angiejones commented on site/docs/tbdex/issuer/kbc/kbc-issuer.mdx
> +For example, Alice's company runs a wallet app for international money transfers, handling various currencies. Each large currency exchange requires a costly and time-consuming KYC check for every cu
```suggestion

```

2024-08-06 11:53 UTC, merged