Web5 cli guide
TBD54566975/developer.tbd.website pull request #1568
Opened 2024-09-04 20:30 UTC by blackgirlbytes

This pull request includes significant updates to the `site/docs/web5/cli.mdx` documentation, additions to dependencies in `site/testsuites/testsuite-rust/Cargo.toml`, and a new test in `site/testsuites/testsuite-rust/tests/web5_cli_test.rs`. The most important changes are summarized below:

### Documentation Enhancements:

* [`site/docs/web5/cli.mdx`](diffhunk://#diff-8864b2386690184decad4a480e68876968036d8d8b5b0e26419575205600a1b3R1-R109): Added a comprehensive guide for the Web5 CLI, including installation instructions, commands for creating and resolving DIDs, creating and signing VCs, and verifying VCs.

### Dependency Additions:

* [`site/testsuites/testsuite-rust/Cargo.toml`](diffhunk://#diff-8ce7b5c1956bef6cb40724f4a2cde1140debd44a74ca0214bf4d525ff29dfd16L7-R15): Added dependencies for `web5`, `web5_cli`, `tokio`, and `anyhow` to support the new CLI functionalities and tests.

### Testing Improvements:

* [`site/testsuites/testsuite-rust/tests/web5_cli_test.rs`](diffhunk://#diff-f1ca549a75f75df901d2cc1d245c102c2142c21934401f2c719428694d03721fR1-R20): Added a new test to verify the `did create dht` command functionality using the `web5_cli` library.

2024-09-04 21:01 UTC, blackgirlbytes commented
@angiejones I spent all day trying to figure out if I can get these snippets tested, so that I can include them in Shnips, but I just spoke with Kendall and he said it's not really possible since it's an executable.

2024-09-05 00:23 UTC, angiejones requested changes

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +The `web5 did create` command [creates a DID](/docs/web5/decentralized-identifiers/how-to-create-did) using different DID methods such as `did:dht`, `did:jwk`, and `did:web`.
are these 3 the only methods?

maybe they should be listed out like `Options` are and remove them from this sentence. You should link them to the the glossary entries as well so people can compare their method choices.

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +The `web5 did create` command [creates a DID](/docs/web5/decentralized-identifiers/how-to-create-did) using different DID methods such as `did:dht`, `did:jwk`, and `did:web`.
dont think you should link to the Create a DID guide since that gives them the SDK approach. I imagine that would be really confusing. Maybe instead, in the intro you can say "we support creating a DID via [SDK](link here) or via CLI, which is detailed in this guide"

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +* `--no-publish`: For the dht method, prevents publishing the DID immediately.
is JWK automatically published, or not?

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +The `web5 did resolve` command [resolves a DID](/docs/web5/decentralized-identifiers/how-to-resolve-a-did).
```suggestion
The `web5 did resolve` command resolves a DID to retrieve its [DID Document](/docs/web5/decentralized-identifiers/did_documents)
```

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +### Options
can you bold all the Options and Examples headings (instead of ###) so they dont clutter the right sidebar?

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +The `web5 vc create` command [creates and sign VCs](/docs/web5/verifiable-credentials/vc-issuance).
```suggestion
The `web5 vc create` command creates and sign verifiable credentials. It returns the VC in [JWT](https://jwt.io/) format.
```

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +* `--portable-did <did>`: specifies the DID used to sign the Verifiable Credential. If omitted, VC will be unsigned
is this different than issuer DID? trying to understand why i would need to provide both

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +* `--issuer <issuer-did>`: Specifies the issuer of the credential. If issuer is provided issuer without `--portable-did`, the VC will be unsigned.
```suggestion
* `--issuer <issuer-did>`: Specifies the issuer of the credential. If issuer is provided without `--portable-did`, the VC will be unsigned.
```

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +* `--expiration-date <date>`: Set an expiration date for the credential.
in what format?

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +web5 vc create "alice" --portable-did $PORTABLE_DID
instead of "alice", show a real DID.

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +web5 vc create "alice" --portable-did $PORTABLE_DID --expiration-date 2025-12-31
instead of "alice", show a real DID.

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +```
add one more example for unsigned vc

```
## Create unsigned VC
web5 vc create "real_did_here" --issuer "real_did_here"
```
can issuer DID's ID be obtained from the portable did?

2024-09-05 00:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +The `web5 vc verify` command [verifies a VC](/docs/web5/verifiable-credentials/verify-vc) in JWT format.
```suggestion
The `web5 vc verify` command verifies a VC that is in JWT format.
```

2024-09-05 00:30 UTC, blackgirlbytes commented on site/docs/web5/cli.mdx
> +* `--no-publish`: For the dht method, prevents publishing the DID immediately.
did:jwk's can't get published -- see Gabe's comment on Discord here: https://discord.com/channels/937858703112155166/1245544729345527829/1245787004713701478

The no-publish flag is only for dht. Should I write anything to make it more clear?

2024-09-05 00:39 UTC, blackgirlbytes commented on site/docs/web5/cli.mdx
> +web5 vc create "alice" --portable-did $PORTABLE_DID --expiration-date 2025-12-31
done

2024-09-05 00:56 UTC, blackgirlbytes commented on site/docs/web5/cli.mdx
> +The `web5 did create` command [creates a DID](/docs/web5/decentralized-identifiers/how-to-create-did) using different DID methods such as `did:dht`, `did:jwk`, and `did:web`.
okay done. so far only three did methods are supported

2024-09-05 01:12 UTC, blackgirlbytes commented on site/docs/web5/cli.mdx
> +The `web5 vc verify` command [verifies a VC](/docs/web5/verifiable-credentials/verify-vc) in JWT format.
done

2024-09-05 01:12 UTC, blackgirlbytes commented on site/docs/web5/cli.mdx
> +The `web5 did create` command [creates a DID](/docs/web5/decentralized-identifiers/how-to-create-did) using different DID methods such as `did:dht`, `did:jwk`, and `did:web`.
good point

2024-09-05 04:23 UTC, angiejones commented on site/docs/web5/cli.mdx
> +## Create an Unsigned VC
hmm does this need its own section? can we just do "Create a VC" and add one example of creating an unsigned VC? btw, what does that return, VC as JSON?

2024-09-05 04:25 UTC, angiejones commented on site/docs/web5/cli.mdx
> +* `--expiration-date <date>`: Set an expiration date for the credential.
```suggestion
* `--expiration-date <date>`: Set an expiration date for the credential in YYYY-MM-DD format
```

2024-09-05 04:25 UTC, angiejones commented on site/docs/web5/cli.mdx
> +**Examples**
```suggestion
**Example**
```

2024-09-05 04:26 UTC, angiejones commented on site/docs/web5/cli.mdx
> +**Examples**
```suggestion
**Example**
```

2024-09-05 08:25 UTC, blackgirlbytes commented on site/docs/web5/cli.mdx
> +## Create an Unsigned VC
OHHHH i misunderstood your initial comment about adding info about Creating an unsigned VC

2024-09-05 21:18 UTC, angiejones approved these changes

2024-09-05 21:22 UTC, merged