Guide: Import a Bearer Did
TBD54566975/developer.tbd.website pull request #1628
Opened 2024-09-15 19:06 UTC by blackgirlbytes

This pull request introduces a new guide for importing Decentralized Identifiers (DIDs) and includes corresponding test cases in JavaScript, Kotlin, and Swift. The guide explains how to export and import DIDs, ensuring users can maintain their identity across different platforms.

### Documentation:

* **New Guide for Importing DIDs**: Added a detailed guide on how to export and import DIDs, including code snippets for JavaScript, Kotlin, and Swift. (`site/docs/web5/decentralized-identifiers/how-to-import-did.mdx`)

### Test Cases:

* **JavaScript Tests**: Added tests to verify the export and import functionality of DIDs using the `DidDht` and `DidJwk` methods. (`site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/how-to-import-did.test.js`)
* **Kotlin Tests**: Implemented test cases for exporting and importing DIDs using `DidDht`, `DidJwk`, and `BearerDid` classes. (`site/testsuites/testsuite-kotlin/src/test/kotlin/docs/web5/build/decentralizedidentifiers/HowToImportDidTest.kt`)
* **Swift Tests**: Added tests to ensure the correct export and import of `DIDJWK` using the `InMemoryKeyManager`. (`site/testsuites/testsuite-swift/Tests/DevSiteTestSuiteTests/web5/build/decentralizedidentifiers/HowToImportDidTests.swift`)

2024-09-16 13:13 UTC, acekyd commented
Nice! I was planning a short to cover this as it came up during the hackathon - but I ran into a question I want to pose now. For the title, would it be better to use something like "Managing DIDs or reusing DIDs etc since it covers both exporting and importing - for the sole purpose of reusing an existing DID 🤔

2024-09-16 14:10 UTC, blackgirlbytes commented
> Nice! I was planning a short to cover this as it came up during the hackathon - but I ran into a question I want to pose now. For the title, would it be better to use something like "Managing DIDs or reusing DIDs etc since it covers both exporting and importing - for the sole purpose of reusing an existing DID 🤔

oh okay! That's fair. Angie assigned a ticket to me called Import DIDs so I just named it that LOL but that's fair/a clearer name

2024-09-16 17:10 UTC, angiejones commented on site/docs/web5/decentralized-identifiers/how-to-import-did.mdx
> +You will start by exporting your DID. This method converts your [Bearer DID](/docs/web5/decentralized-identifiers/how-to-create-did/#create-did) into a [Portable DID](/docs/web5/decentralized-identif
we should add glossary terms for Bearer DID and Portable DID and link to those

2024-09-16 17:15 UTC, angiejones requested changes

2024-09-16 17:15 UTC, angiejones commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/how-to-import-did.test.js
> +      const portableDhtDid = await didDht.export();
in these 2 lines, it's not clear that didDht is a bearer did. can you rename these variables up top to `dhtBearerDid` and `jwkBearerDid`?

2024-09-16 17:15 UTC, angiejones commented on site/docs/web5/decentralized-identifiers/how-to-import-did.mdx
> +Now, you can import your Portable DID to a desired location using the `import` method.
```suggestion
You can import your Portable DID to an application using the `import` method. 
```

2024-09-16 17:15 UTC, angiejones commented on site/docs/web5/decentralized-identifiers/how-to-import-did.mdx
> +You will start by exporting your DID. This method converts your [Bearer DID](/docs/web5/decentralized-identifiers/how-to-create-did/#create-did) into a [Portable DID](/docs/web5/decentralized-identif
can you specify what exactly gets returned? is it a JSON?

2024-09-17 04:10 UTC, blackgirlbytes commented on site/testsuites/testsuite-javascript/__tests__/web5/build/decentralized-identifiers/how-to-import-did.test.js
> +      const portableDhtDid = await didDht.export();
done

2024-09-19 00:15 UTC, blackgirlbytes commented on site/docs/web5/decentralized-identifiers/how-to-import-did.mdx
> +You will start by exporting your DID. This method converts your [Bearer DID](/docs/web5/decentralized-identifiers/how-to-create-did/#create-did) into a [Portable DID](/docs/web5/decentralized-identif
added!

2024-09-19 00:41 UTC, blackgirlbytes commented
## Updates

- Changed the title from Import a DID to Reuse a DID based on @acekyd's suggestions
- Added Bearer DID and Portable DID to glossary, updated mentions of it based on @angiejones's suggestions.

2024-09-19 14:03 UTC, angiejones approved these changes

2024-09-19 17:55 UTC, merged