Hacktoberfest 2024 Blog Post: Preptember Diaries- Amping it Up for Hacktoberfest 2024!
TBD54566975/developer.tbd.website pull request #1681
Opened 2024-09-26 22:56 UTC by taniashiba

## What type of PR is this? (check all applicable)
- [x] 📖 Content

## Description

This PR adds the "Preptember Diaries- Amping it Up for Hacktoberfest 2024!" blog post and its associated blog banner. 

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

No tasks needed other than @taniashiba and @blackgirlbytes making sure leaderboard is up by next week.

2024-09-26 23:11 UTC, dayhaysoos approved these changes

2024-09-27 04:01 UTC, angiejones commented on site/blog/2024-09-26-preptember-amping-it-up-for-hacktoberfest24.md
> +**📅 Mark Your Calendars!** We're kicking off Hacktoberfest with two events, one on September 27th and the other October 2nd. Stay in the loop and don't miss out on any of our events by checking our [
do we not know what the 2 events are yet? If we do, we should list them

2024-09-27 05:33 UTC, angiejones requested changes
about to commit some changes...

2024-09-27 14:17 UTC, taniashiba reviewed
### Addressed the following changes:

- Added link to hacktoberfest Discord channel
- Added DCX Project Hub
- Updated Mark Your Calendars section to describe and link to events in detail, without duplicating Livestreams & Office Hours section

2024-09-27 14:36 UTC, angiejones approved these changes

2024-09-27 15:14 UTC, merged