#Add Blog Post About Verifiable Credentials (VCs)
TBD54566975/developer.tbd.website pull request #1794
Opened 2024-10-05 10:49 UTC by KiranBaliga

Closes #1732 

Please review the PR and action accordingly. Thank you!

2024-10-05 19:58 UTC, blackgirlbytes requested changes

2024-10-05 19:58 UTC, blackgirlbytes commented on site/src/externalContributors.json
> +        "thumbnail": "/img/external-contributor/kiranbaliga.png",
Cool, blog post! One thing I'm curious about..would you be willing to choose a different image so that the web page shows a variety of pictures. Perhaps, you can use your blog banner as the thumbnail?

![image](https://github.com/user-attachments/assets/5b37ce20-a152-478a-ba20-acdfb61b65fc)

2024-10-05 20:59 UTC, KiranBaliga commented on site/src/externalContributors.json
> +        "thumbnail": "/img/external-contributor/kiranbaliga.png",
I have made the changes. Please review

2024-10-05 23:12 UTC, blackgirlbytes approved these changes
Awesome. This looks good to me, but let me double check with @EbonyLouis

2024-10-06 03:18 UTC, angiejones commented
this is how your image is showing up:

<img width="297" alt="image" src="https://github.com/user-attachments/assets/5c5f0c21-2984-4fdf-a1f7-7aa73b47be3f">

2024-10-06 06:00 UTC, KiranBaliga commented
@angiejones @blackgirlbytes I have made the changes to the resolution of the image. Please check.

2024-10-06 15:48 UTC, blackgirlbytes approved these changes
Looks good! Thanks for your contribution. I'll merge it.

2024-10-06 15:48 UTC, merged