Issue #500 - Add hero CTA for API Docs on Getting Started
TBD54566975/developer.tbd.website pull request #502
Opened 2023-05-25 21:16 UTC by ALRubinger

2023-05-25 21:17 UTC, ALRubinger commented
Pending @csuwildcat @angiejones review and +1.

2023-05-25 23:05 UTC, angiejones requested changes

2023-05-25 23:05 UTC, angiejones commented on docs/docs-index.js
> +      <div className='padding-top--md'>
The two big hero sections does not look nice. Let's brainstorm a better layout

2023-05-25 23:06 UTC, angiejones commented on docs/docs-index.js
> +      <div className='padding-top--md'>
Not sure you had the latest file, ALR. My formatting changes of the code image have been lost
https://github.com/TBD54566975/developer.tbd.website/pull/492/files

2023-05-26 03:13 UTC, ALRubinger commented on docs/docs-index.js
> +      <div className='padding-top--md'>
Yep, I've just put back your image and image class changes on this branch to show:

```
          imgSrc="/img/docs-web5-code-connect.png"
          imgClass="w-[50%] bottom-[1vh]"
```

Looks a little wonky when it's in column view:

<img width="832" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/199891/e772598f-5674-4318-b24d-490c35f745b9">

Anything you want to do I'm cool with if you want to push changes to fix it up however you think is best, then squash/merge this PR to put it to bed. :)

2023-05-26 03:16 UTC, ALRubinger commented on docs/docs-index.js
> +      <div className='padding-top--md'>
Idea I took from a UX guideline thing where you have primary and secondary big CTAs, if possible for us:

3 column layout where Quickstart takes up 2 of the slots (66%) and Web5 API Reference takes up 1 (33%).

2023-05-26 04:10 UTC, angiejones commented on docs/docs-index.js
> +      <div className='padding-top--md'>
oh i like that idea! and we don't need the code image there anymore since the card is much smaller

2023-05-26 04:16 UTC, angiejones commented on docs/docs-index.js
> +      <div className='padding-top--md'>
a preview just to see if we like this

![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/166f0b13-e662-455a-a1f3-b30af7f3c0a2)

2023-05-26 04:22 UTC, angiejones commented on docs/docs-index.js
> +      <div className='padding-top--md'>
here's 2-1 with code image
![image](https://github.com/TBD54566975/developer.tbd.website/assets/15972783/2b01988f-73fd-4a12-b333-3acecf2a1af1)

2023-05-26 14:21 UTC, angiejones approved these changes

2023-05-26 14:22 UTC, angiejones commented
@ALRubinger good to merge

2023-05-26 14:47 UTC, merged