Issue#432 - Quickstart: Match all console.logs
TBD54566975/developer.tbd.website pull request #556
Opened 2023-06-13 20:46 UTC by bobbilee19

https://github.com/TBD54566975/developer.tbd.website/issues/432

Refactoring to match all other console.log examples

2023-06-14 13:20 UTC, angiejones requested changes
this PR is not needed

2023-06-14 13:20 UTC, angiejones commented on docs/web5/_quickstart-05-write-record.mdx
> +    writeResult _Record {}
this doesn't match what's on line 37

2023-06-14 18:05 UTC, bobbilee19 commented on docs/web5/_quickstart-05-write-record.mdx
> +    writeResult _Record {}
ha duh that's what i meant to change :/ ...moving too fast yesterday

2023-06-20 10:24 UTC, angiejones approved these changes

2023-06-20 10:24 UTC, merged