Update guides to modify records without creating them first #494
TBD54566975/developer.tbd.website pull request #580
Opened 2023-07-05 20:18 UTC by bobbilee19

https://github.com/TBD54566975/developer.tbd.website/issues/494

2023-07-05 23:04 UTC, thehenrytsai approved these changes
Looks good to me though I suspect the intent for these two snippets is for a developer to be able to copy and paste to test or setup through the behavior. With that intent in mind, it makes sense why a record is created first before a delete or query is executed.

I get however that it is not a practical scenario to have one create a record then immediately delete it. So if the intent is mimic a real world scenario, then your change is good.

No strong push back either way for me!

2023-07-06 04:56 UTC, angiejones requested changes

2023-07-06 04:56 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/delete-from-dwn.mdx
> -The following snippet allows you to delete from your Web5 instance’s DWN:
leave the word snippet so that it's clear this is not a standalone block of code

2023-07-06 04:56 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/delete-from-dwn.mdx
> +The following allows you to delete a record from your Web5 instance’s DWN:
can we change this to ...'from a DWN'?

2023-07-06 04:56 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/read-from-dwn.mdx
> +// Query the record
//Query records with plain text data format

2023-07-06 04:56 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/read-from-dwn.mdx
> +
//Loop through returned records and print text from each

2023-07-06 04:56 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/read-from-dwn.mdx
> +  const readResult = await record.data.text();
this would keep overwriting the variable's value with every iteration of the loop. change to:

console.log(await record.data.text());

2023-07-06 04:56 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/read-from-dwn.mdx
> +response.records.forEach(async (record) => {
parentheses aren't needed around `record`

2023-07-07 04:26 UTC, bobbilee19 commented on site/docs/web5/build/decentralized-web-nodes/delete-from-dwn.mdx
> -The following snippet allows you to delete from your Web5 instance’s DWN:
ah ok!

2023-07-07 04:28 UTC, bobbilee19 commented on site/docs/web5/build/decentralized-web-nodes/delete-from-dwn.mdx
> +The following allows you to delete a record from your Web5 instance’s DWN:
"The following snippet allows you to delete from a DWN:" 

is this what you want?

2023-07-07 04:34 UTC, bobbilee19 commented on site/docs/web5/build/decentralized-web-nodes/read-from-dwn.mdx
> +  const readResult = await record.data.text();
Ah yes, sorry my head wasn't in the mindset of someone taking this and using it right in their app just more like "here is the read result" - thanks for suggestion

2023-07-07 04:38 UTC, bobbilee19 commented
Angie did you see Henry's comment above? Did you reply to that somewhere that I accidently resolved?

Besides that let me know your thoughts now after your first review.

2023-07-07 04:39 UTC, bobbilee19 commented
I think build is failing bc I didn't run npm i :)

2023-07-07 18:15 UTC, angiejones approved these changes

2023-07-07 19:05 UTC, angiejones requested changes

2023-07-07 19:05 UTC, angiejones commented on package-lock.json
> +{
was it intentional to add this file?

2023-07-07 19:05 UTC, angiejones commented on package-lock.json
> +{
and the pnpm lock file

2023-07-07 21:30 UTC, dayhaysoos commented on package-lock.json
> +{
@angiejones the pnpm-lock file is necessary now after the change to pnpm.

@bobbilee19 my bad I should have coordinated something with you before merging the pnpm branch. Is all of this stuff ready to go with no more needed changes? If so, I can focus on bringing this into main myself

2023-07-08 00:34 UTC, angiejones commented on package-lock.json
> +{
yes @dayhaysoos it's ready to go

2023-07-08 02:03 UTC, angiejones commented
> 

the reason I asked for it to be changed is because when a developer needs to know how to do this, it will be at the point where they need to get the record. We weren't showing them how to properly obtain an already existing record.

2023-07-10 18:39 UTC, merged