New guide for updating DWN records
TBD54566975/developer.tbd.website pull request #590
Opened 2023-07-11 23:17 UTC by bobbilee19

2023-07-12 01:11 UTC, angiejones requested changes

2023-07-12 01:11 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/update-to-dwn.mdx
> +const updateResult = await record.update({ data: "Hello, I'm updated!" });
This is using an already existing (unseen) `record` object, so the query is not necessary. Couple of options here:

1. remove the query (lines 11-18)
2. change the query to look for the string record id to obtain the record in object form, then use the query results to get the first object and update it:

```js
// Query for the particular record
const {records} = await web5.dwn.records.query({
  message: {
    recordID: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy',
    filter: {
      dataFormat: 'text/plain',
    }
  }
});
// Update the record
const status = await records[0].update({ data: "Hello, I'm updated!" });
```

2023-07-12 20:25 UTC, angiejones approved these changes
left a couple of nit comments. take em or leave em

2023-07-12 20:25 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/update-to-dwn.mdx
> +```jsx
just put **js** not jsx

2023-07-12 20:25 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/update-to-dwn.mdx
> +// Update the record
add line break for readability

2023-07-12 23:35 UTC, bobbilee19 commented on site/docs/web5/build/decentralized-web-nodes/update-to-dwn.mdx
> +```jsx
oh this is from write file

2023-07-13 03:03 UTC, angiejones approved these changes

2023-07-13 03:04 UTC, merged