Adding Germany event page
TBD54566975/developer.tbd.website pull request #605
Opened 2023-07-14 21:49 UTC by EbonyLouis

##  Issue being addressed:

We are going to pass out cards with a QR Code that directs people to this dedicated splash/landing page for the WeAreDevelopers conference. That has CTAs for: 

- GitHub
- Docs
- Discord

<img width="1728" alt="Screenshot 2023-07-14 at 5 47 35 PM" src="https://github.com/TBD54566975/developer.tbd.website/assets/55366651/6aadda60-1307-4087-845a-af72af5622ba">

2023-07-17 04:30 UTC, angiejones requested changes

2023-07-17 04:30 UTC, angiejones commented on site/static/img/docs-task-list.svg
Can you rename this file so that you add a new one vs overriding this existing image?

2023-07-17 04:30 UTC, angiejones commented on site/src/theme/MDXComponents.js
> +  ),EventCommunity: EventCommunity,
I'm not sure if any changes are needed to this file. we don't usually add the components here. what happens without these changes?

2023-07-17 04:30 UTC, angiejones commented on site/src/components/EventCommunity.jsx
> +function EventCommunity() {
can we rename the component/file? i wouldn't think to look for this component for a conference event.

2023-07-17 14:04 UTC, EbonyLouis commented on site/src/theme/MDXComponents.js
> +  ),EventCommunity: EventCommunity,
When I was playing around with it if it wasn't there it wouldn't render on the site. I just tried again and yea it needs to be there, it seems all the used components are passed there.

2023-07-18 04:51 UTC, angiejones commented
looking good @EbonyLouis! We should add the workshop location (Workshops M5), and maybe tell them they can stop by the booth any time (in addition to the Happy Hour)

2023-07-18 04:58 UTC, angiejones requested changes

2023-07-18 04:58 UTC, angiejones commented on site/src/components/ConferenceScheduleSection.jsx
> +          EventDetails={`Angie Jones, TBD`}
remove TBD

2023-07-18 04:58 UTC, angiejones commented on site/src/pages/wad23.mdx
> +TBD is a developer-focused business unit from Block focused on creating a decentralized future that returns ownership and control over your finances,
TBD is building platforms and protocols that enable developers to easily build decentralized applications. TBD’s vision is a decentralized future that returns ownership and control over finances, data, and identity to individuals.  We invite you to join us in creating and adopting open and decentralized technologies that solve real problems for real people.

2023-07-19 00:10 UTC, angiejones approved these changes

2023-07-19 00:11 UTC, merged