Change issuerKid to verificationMethodId in Issue VC blog post
TBD54566975/developer.tbd.website pull request #628
Opened 2023-07-31 17:52 UTC by bobbilee19

2023-07-31 21:59 UTC, angiejones requested changes

2023-07-31 21:59 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +# Issue Verfiable Credentials
Issue Credentials

writing 'Verifiable Credentials' is gonna get repetitive on the sidebar once we add more guides

2023-07-31 21:59 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +credentials and is **not intended to be used in production applications**.
is this still true?

2023-07-31 21:59 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +2. **[Create Verifiable Credential](#create-verifiable-credential)**
Create and Issue Verifiable Credential

2023-07-31 21:59 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +:::info
Can we remove lines 73-83 and instead just point them to the DID guide above?

2023-07-31 21:59 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +In the world of [Self-Sovereign Identity](/docs/glossary#self-sovereign-identity-ssi) (SSI), [Decentralized Identifiers](/docs/glossary#decentralized-identifier-did) (DIDs) are used to identify any s
change DID link to the guide on DIDs

2023-07-31 21:59 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +If Alice has an identity wallet she will be able to store the credential and use it however she wishes.
is this the issuance of the VC or is another step required?

2023-07-31 21:59 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +- Our `schema` object conforms to the Draft 2020-12 schema version, so set its `$schema` property to https://json-schema.org/draft/2020-12/schema.
remove this as a link. it's downloading a file to people's computer and that's frowned upon, especially without warning

2023-07-31 22:02 UTC, angiejones commented on site/docs/ssi/issue-verifiable-credentials.md
> +- Set `verificationMethodId` set to the KID of the issuer's private key to sign the schema.
is KID still the right word to use here?

2023-08-01 12:44 UTC, bobbilee19 commented on site/docs/ssi/issue-verifiable-credentials.md
> +credentials and is **not intended to be used in production applications**.
this is what we had before, so has it changed to being prod or not?

2023-08-01 20:15 UTC, bobbilee19 commented on site/docs/ssi/issue-verifiable-credentials.md
> +credentials and is **not intended to be used in production applications**.
Can we just more so say the SSI Service / TBD is in tech preview mode vs making it seem like VCs explicitly are not made for prod right now.

like:
`This is a walk through of the Verifiable Credential (VC) issuance process from the perspective of the issuer. It is using a manual approach to issue verifiable credentials and the SSI Service is still in tech preview and **not intended to be used in production applications**.`

2023-08-01 21:01 UTC, bobbilee19 commented on site/docs/ssi/issue-verifiable-credentials.md
> +- Set `verificationMethodId` set to the KID of the issuer's private key to sign the schema.
we actually do not need this, it's not required actually after i did some digging, doing some digging here on SSI Service steps — in the schema creation step, we don’t need the `verificationMethodId` [see here](https://github.com/TBD54566975/ssi-service/blob/main/doc/howto/credential.md) and [here to confirm](https://github.com/TBD54566975/ssi-service/blob/main/pkg/service/schema/model.go#L30) It looks like it’s not required based on this, if it has that value then it validates it, if not it just returns nil) — so going to remove that for now to remove any confusion

2023-08-01 21:02 UTC, bobbilee19 commented on site/docs/ssi/issue-verifiable-credentials.md
> +- Set `verificationMethodId` set to the KID of the issuer's private key to sign the schema.
so im going to remove this, it is still the KID field though yes

2023-08-03 13:02 UTC, angiejones commented
@bobbilee19 there are broken links causing the build to fail

<img width="1165" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/fc64ee05-06f5-445d-8771-b42af6cadb02">

2023-08-03 13:16 UTC, angiejones requested changes

2023-08-03 18:28 UTC, angiejones requested changes

2023-08-03 18:28 UTC, angiejones commented on site/docs/ssi/create-credentials.md
> +## **1. SSI Service Setup**
isn't this redundant to what's in the Run SSI Service guide? Can we skip this section and simply point them to the guide on this?

2023-08-03 18:50 UTC, bobbilee19 commented
@angiejones I'm going to remove the SSI Service setup section and link to the SSI Service Setup Guide

2023-08-03 18:51 UTC, bobbilee19 commented on site/docs/ssi/create-credentials.md
> +## **1. SSI Service Setup**
yep just doing this now on the Create Did guide, so i just noted that below before i saw this comment!

2023-08-03 18:52 UTC, bobbilee19 commented on site/docs/ssi/create-credentials.md
> +## Next Steps
do u want to remove next steps from all (like in the Create a DID doc im creating right now too?)

2023-08-04 02:47 UTC, angiejones requested changes

2023-08-04 02:47 UTC, angiejones commented on site/docs/ssi/create-credentials.md
> +## Next Steps
yes, I think it'll get redundant and doesn't really make sense to point to SSI Setup after they've already ready how to create, etc. Maybe we can come back after we have quite a few SSI guides and make more meaningful references in each versus the same ones in all.

2023-08-04 13:44 UTC, angiejones approved these changes

2023-08-04 13:45 UTC, merged