Issue 592/tests v2
TBD54566975/developer.tbd.website pull request #629
Opened 2023-07-31 19:08 UTC by dayhaysoos

This is a second attempt at this issue:

https://github.com/TBD54566975/developer.tbd.website/pull/617

Both tests and building docusaurus work fine. Had to set a flag for proper browser support using vitest

2023-07-31 21:35 UTC, ALRubinger approved these changes
LGTM! "YEER" 🤣

```
pnpm test                       in zsh at 14:30:31

> @ test /Users/alr/git/TBD54566975/developer.tbd.website
> pnpm vitest --config vite.config.ts


 DEV  v0.33.0 /Users/alr/git/TBD54566975/developer.tbd.website
      Browser runner started at http://localhost:63315

 ✓ site/__tests__/quickstart.test.js (5) 2527ms
   ✓ /site/tests/quickstart.test.js (5) 2526ms
     ✓ didCreate returns a decentralized ID
     ✓ dwnWriteTextRecord returns a record with aliceDid being the same value as the author attribute 666ms
     ✓ recordResult returns a record with the textInput being the same value as the data attribute
     ✓ recordResult successfully sends an updated textInput
     ✓ recordResult successfully deletes the record

 Test Files  1 passed (1)
      Tests  5 passed (5)
   Start at  14:31:51
   Duration  6.83s (transform 0ms, setup 0ms, collect 910ms, tests 2.53s, environment 0ms, prepare 0ms)
```

2023-07-31 21:43 UTC, angiejones requested changes

2023-07-31 21:43 UTC, angiejones commented on site/src/util/web5.js
> +export async function didCreate() {
should this just return the response instead of destructuring it? You already pull `web5` and `aliceDid` out and assign them in the `beforeAll`.

So something like

```js
return await Web5.connect();
```

2023-07-31 21:43 UTC, angiejones commented on site/src/util/web5.js
the name and filepath here confuse me. I wouldn't know that this was for testing purposes. Can we add something to the filename or directory structure to indicate the purpose of this file?

2023-07-31 21:43 UTC, angiejones commented on site/src/util/web5.js
> +export async function dwnWriteTextRecord(web5, textData) {
rename to `createTextRecord`

2023-07-31 21:43 UTC, angiejones commented on site/src/util/web5.js
> +  return record;
should return the entire response so that the status code can also be verified

2023-07-31 21:43 UTC, angiejones commented on site/__tests__/quickstart.test.js
> +
need a test that verifies the status code of create

2023-07-31 21:43 UTC, angiejones commented on site/__tests__/quickstart.test.js
> +    expect(updatedRecordResult.status.code).toBe(202);
if this fails, does it do the next check? I want to know everything that's wrong when the tests run. I think you need to run it as [expect.soft()](https://vitest.dev/api/expect.html#soft) so that both expect statements are executed and we know if we have 2 problems on our hands

2023-07-31 21:43 UTC, angiejones commented on site/__tests__/quickstart.test.js
> +    expect(deletedRecordResult.status.code).toBe(202);
use expect.soft() when a test has multiple expect statements or break these into separate tests.

2023-07-31 22:40 UTC, dayhaysoos commented on site/src/util/web5.js
This isn't necessarily for testing, it's a file that separated the functions in the quickstart.js so that we would have the ability to test them.

They pretty much are helper functions for web5 within the context of docusaurus. Perhaps I can name them `web5-helpers`? What do you think?

2023-07-31 22:53 UTC, dayhaysoos commented on site/src/util/web5.js
> +  return record;
Updated, added `expect.soft()` to the status code test

2023-07-31 22:57 UTC, dayhaysoos commented
Hey @angiejones, every point should be resolved except for renaming the web5 file. lemme know if I happen to have missed something/

Lemme know what you think of my proposed change for the web5 file to `web5-helpers`

2023-07-31 22:57 UTC, dayhaysoos commented on site/__tests__/quickstart.test.js
> +    expect(updatedRecordResult.status.code).toBe(202);
Just to answer your question, it'll fail and abort everything after. I've added the soft function to each test with the status codes on them.

2023-08-01 02:59 UTC, angiejones commented on site/src/util/web5.js
or `code-snippets` or something that's distinct from the actual web5.js library

2023-08-01 22:36 UTC, angiejones approved these changes

2023-08-01 22:38 UTC, merged