Create DID SSI Service Guide
TBD54566975/developer.tbd.website pull request #638
Opened 2023-08-04 03:11 UTC by bobbilee19

2023-08-04 13:37 UTC, angiejones requested changes

2023-08-04 13:37 UTC, angiejones commented on site/docs/ssi/create-did.md
> +The DID returned is using `key` as its DID method. Learn more about other [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).
I'm losing a bit of context because the response was so long. Let's reshow the code here and make it clear that we're doing a breakdown. 

> The DID returned is using `key` as its DID method because that's what we specified in our request:
> ```bash
> curl -X PUT -d '{"keyType":"Ed25519"}' localhost:8080/v1/dids/key
> ```
> 
> Other supported DID methods are `ion` and `web`. Learn more about [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).

2023-08-04 13:37 UTC, angiejones commented on site/docs/ssi/create-did.md
> +title: Create DID
Create a DID

2023-08-04 13:37 UTC, angiejones commented on site/docs/ssi/create-did.md
> +Follow guide to [Clone & Run SSI Service](run-ssi-service).
perfect!

2023-08-04 13:37 UTC, angiejones commented on site/docs/ssi/create-did.md
> +Each DID has one or more keys, and each key has a type. Some [keytypes](https://w3c-ccg.github.io/did-method-key/#format) give you different properties and can be used for different purposes. Some ke
Rephrase:

> Each DID has one or more keys, and each key has a type. In our request, we specified `Ed25519` as it's sufficient for most use cases:
> 
> ```bash
> curl -X PUT -d '{"keyType":"Ed25519"}' localhost:8080/v1/dids/key
> ```
> 
> Some [keytypes](https://w3c-ccg.github.io/did-method-key/#format) give you different properties and can be used for different purposes. Some keys are better for signing, others for encryption. Some are even provided by the government (NIST). There are variations on how they're constructed to give different security properties.

2023-08-04 13:37 UTC, angiejones commented on site/docs/ssi/create-did.md
> +sidebar_position: 3
should be position 2 - making it appear before creating a credential since you need a DID to create a credential.

2023-08-04 13:37 UTC, angiejones commented on site/docs/ssi/create-did.md
> +**To create your DID run:**
To create a DID, run the following request:

2023-08-04 21:05 UTC, angiejones requested changes

2023-08-04 21:05 UTC, angiejones commented on site/docs/ssi/create-did.md
> +The returned DID is using `key` as its DID method because that's what we specified in our request:
this segment should go after the response

2023-08-04 21:05 UTC, angiejones commented on site/docs/ssi/create-did.md
> +**To create your DID run the following request**
comma after 'DID'. I keep reading it as a 'DID run' lol

2023-08-04 21:05 UTC, angiejones commented on site/docs/ssi/create-did.md
> +The DID returned is using `key` as its DID method. Learn more about other [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).
the section above should go here, after the response

2023-08-06 22:02 UTC, bobbilee19 commented on site/docs/ssi/create-did.md
> +The DID returned is using `key` as its DID method. Learn more about other [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).
Not sure I am following what you are saying. What exactly is 'here' now...is it the DID Methods section or the "The returned DID is using a key" example you suggested i break up into the copy you added in the comment above.

Are you wanting me to move ...
```
The returned DID is using key as its DID method because that's what we specified in our request:

`curl -X PUT -d '{"keyType":"Ed25519"}' localhost:8080/v1/dids/key`

Other supported DID methods are ion and web. Learn more about [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).
```
To be below the response now?

2023-08-06 22:04 UTC, bobbilee19 commented on site/docs/ssi/create-did.md
> +The DID returned is using `key` as its DID method. Learn more about other [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).
see my next commit, i may understand what ur suggesting

2023-08-06 23:05 UTC, angiejones commented on site/docs/ssi/create-did.md
> +The DID returned is using `key` as its DID method. Learn more about other [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).
yes, this should go under the DID Methods header. looks like the code block is missing on the [deploy preview](https://deploy-preview-638--tbd-website-developer.netlify.app/docs/ssi/create-did#did-methods).

Also for the code section under DID Methods and DID Keytypes, can you use the 3 ticks with the lang as bash like you did in the very first code block so that it's styled as a code block with a copy button?

**Correct:**
<img width="843" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/5a8fa8df-13c7-4178-88c4-9b9d23ada7ab">

**Incorrect:**
<img width="589" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/49364578-be61-47bb-a468-8d371748df4f">

2023-08-07 02:31 UTC, angiejones commented on site/docs/ssi/create-did.md
> +The DID returned is using `key` as its DID method. Learn more about other [DID methods](https://www.w3.org/TR/did-spec-registries/#did-methods).
i fixed it

2023-08-07 02:42 UTC, angiejones approved these changes

2023-08-07 02:42 UTC, merged