WIP: Filterable record properties chart
TBD54566975/developer.tbd.website pull request #642
Opened 2023-08-08 23:01 UTC by bobbilee19

WIP because I'd like Henry and Diane to cross check the way I've described these in a succint way. And for the examples I've added for `contextId` and `parentId`

2023-08-08 23:03 UTC, bobbilee19 commented
Context to add from spec:
- `schema` property, and if present its value MUST be a URI string that indicates the schema of the associated data.

- `recordId` property, and its value MUST be a [Computed Record ID](https://identity.foundation/decentralized-web-node/spec/#computed-record-ids).

- `contextId` property, and its value MUST be the deterministic ID for a contextually linked set of objects.

- `protocol` property, and its value MUST be a URI that denotes the Protocol an object is a part of.

- `parentId` property if the currently active entry for the record is a RecordsDelete or a CollectionWrite that has a declared a Commit Strategy. The object MUST NOT contain a `parentId` under any other circumstance. If present, the value of the `parentId` property MUST be the stringified [Version 1 CID](https://docs.ipfs.io/concepts/content-addressing/#identifier-formats) of the [DAG CBOR](https://github.com/ipld/specs/blob/master/block-layer/codecs/dag-cbor.md) encoded descriptor object of the previous RecordsWrite or RecordsDelete entry the message is intending to overwrite.

2023-08-09 01:06 UTC, diehuxx commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`parentId`**      | RecordsWrite message’s `entryId`                     | "91011123" |
```suggestion
| **`parentId`**      | `recordId` of the parent record in a protocol          | "bafyreianzpmhbgcgam5mys722vnsiuwn7y4ek6kjeyjptttquasw4hge2m" |
```

2023-08-09 01:16 UTC, diehuxx commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`contextId`**     | Message thread contextId                             | "12345678" |
```suggestion
| **`contextId`**     | `recordId` of a root record of a protocol                             | 'bafyreianzpmhbgcgam5mys722vnsiuwn7y4ek6kjeyjptttquasw4hge2m'
 |
```

This is a tough one to express succinctly if it hasn't already been established that records within a protocol form a number of trees. Each `contextId` refers to one of those trees. When a new top-level "root" record is written, it starts a new tree. The `contextId` is `recordId` of the root record. All descendants of a given root record have the same `contextId`.

Personally, I would just assume the reader has some knowledge that dwn protocols form trees of records and that they learned this a previous page of documentation. If this isn't covered in our docs on protocols, we should update those.

2023-08-09 01:17 UTC, diehuxx commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`attester`**      | Author DID of message                                | "did:example:bob" |
Omit this one please. I looked through our code and we're not actually indexing on it, so the query is useless AFAICT. I'm either going to update the name or rip it out entirely.

2023-08-09 01:30 UTC, diehuxx commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`parentId`**      | RecordsWrite message’s `entryId`                     | "91011123" |
Also, I'm not sure how literal you mean to get with your example values. For `recordId`s, we're using [CIDs](https://docs.ipfs.tech/concepts/content-addressing/#cids-are-not-file-hashes), specifically CBOR + SHA256. I just used [this test fixture](https://github.com/TBD54566975/dwn-sdk-js/blob/main/tests/utils/test-data-generator.ts#L797-L802) to generate one randomly.

2023-08-09 19:33 UTC, angiejones requested changes

2023-08-09 19:33 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +
Add a one-liner sentence here explaining what these are for

2023-08-09 19:33 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`contextId`**     | Message thread contextId                             | "12345678" |
@bobbilee19 let's add a new issue to add this info to the Protocol doc and add a link here telling people to read more about it.

For this particular guide, let's incorporate Diane's suggestion minus the long string

2023-08-09 19:33 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +
Can we add an example code snippet using one of the filters just to show people where this shows up?

> **Code Sample**
> This snippet queries the DWN for records that have a parent record with a specific record ID:
> 
> ```js
> const response = await web5.dwn.records.query({
>   message: {
>     filter: {
>       parentId: 'bafyreianzpmhbgcgam5mys722vnsiuwn7y4ek6kjeyjptttquasw4hge2m',
>     }
>   }
> });
> ```

2023-08-10 17:10 UTC, bobbilee19 commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`attester`**      | Author DID of message                                | "did:example:bob" |
Ok cool just wanted to make sure it was there before you removed it. But I'll remove it. Thanks!

2023-08-10 18:02 UTC, diehuxx commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`contextId`**     | Message thread contextId                             | "12345678" |
How bout as a compromise, we use a truncated version of the real possible value i provided? eg “bafyreian…"

2023-08-10 18:15 UTC, bobbilee19 commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`contextId`**     | Message thread contextId                             | "12345678" |
https://github.com/TBD54566975/developer.tbd.website/issues/651

2023-08-10 18:15 UTC, bobbilee19 commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`parentId`**      | RecordsWrite message’s `entryId`                     | "91011123" |
https://github.com/TBD54566975/developer.tbd.website/issues/651

2023-08-11 02:00 UTC, angiejones requested changes

2023-08-11 02:29 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +| **`schema`**        | The URI of the schema bucket in which to query       | "https://schema.org/Message" |
i fixed it

2023-08-11 02:29 UTC, angiejones approved these changes

2023-08-11 02:30 UTC, merged