Verify a Credential with SSI Service
TBD54566975/developer.tbd.website pull request #644
Opened 2023-08-09 00:41 UTC by bobbilee19

2023-08-09 00:43 UTC, bobbilee19 commented
@angiejones

1. Should I now add the following to the VC creation guide...after Getting Credentails section..
```
### Verifying Credentials
To build upon this tutorial, copy your newly created VC's `credentialJwt` field to [verify your credential](verify-credentials) like so:

```bash
curl -X PUT localhost:8080/v1/credentials/verification -d '{
    "credentialJwt": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6..."
}'
```
```
2. Presentation Exchange section should I add this sentence after the first paragraph?
`The SSI Service supports Presentation Exchange. Its usage will be covered in another guide coming soon.`

2023-08-09 19:23 UTC, angiejones requested changes

2023-08-09 19:23 UTC, angiejones commented on site/docs/ssi/verify-credentials.md
> +# Verify a Verifiable Credential (VC)
such a mouthful haha. can we change to Verify a Credential?

2023-08-09 19:23 UTC, angiejones commented on site/docs/ssi/verify-credentials.md
> +- **Signature Verification** - Signed by the issuer? Has the signature been tampered with?
Can we put the description in sentence form? Example:

- **Signature Verification** - Has it been signed by the issuer? If so, has the signature been tampered with?
- **Credential Status** - Is it still active, and not revoked or suspended?
- **Credential Validity** - Has it expired?
- **Credential Issuer** - Is the issuer trusted for the claims they're attesting to?
- **Credential Evidence** - Is there evidence supporting the claims being made?
- **Credential Schema** - Does it conform to a schema defined in the `credentialSchema` property?

2023-08-09 19:23 UTC, angiejones commented on site/docs/ssi/verify-credentials.md
> +## **Verify the VC**
nit: when you use ## it makes an H2, so you don't also need to use ** which makes it bold

2023-08-09 19:23 UTC, angiejones commented on site/docs/ssi/verify-credentials.md
> +- In the future this endpoint can (and should!) be expanded to support status checks and external schema resolution, among other optional checks.
make the last bullet an info section instead:

```
:::info
In the future, this endpoint will likely be expanded to support status checks and external schema resolution, as well as other optional checks.
:::
```

2023-08-09 19:23 UTC, angiejones commented on site/docs/ssi/verify-credentials.md
> +The example we've gone through above verifies a credential from an issuer. But what about verifying the presentation of a credential, or set of credentials, from a holder to a verifier? To do this, a
change wording in the final sentence:

"Learn more in the guide on Verifying a Presentation"

2023-08-09 19:23 UTC, angiejones commented on site/docs/ssi/verify-credentials.md
> +What about applying more complex logic to the verification process? Like checking if a credential was issued from a known set of issuers? Or requesting two of one type of credential and three of anot
Add comma after "Foundation"

2023-08-10 04:37 UTC, angiejones commented
> @angiejones
> 
> 1. Should I now add the following to the VC creation guide...after Getting Credentails section...
> 
> ```
> ### Verifying Credentials
> To build upon this tutorial, copy your newly created VC's `credentialJwt` field to [verify your credential](verify-credentials) like so:
> 
> ```bash
> curl -X PUT localhost:8080/v1/credentials/verification -d '{
>     "credentialJwt": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6..."
> }'
> ```
> 
> 2. Presentation Exchange section should I add this sentence after the first paragraph?
> 
> `The SSI Service supports Presentation Exchange. Its usage will be covered in another guide coming soon.`

1. nah, we should make a new guide for that. I'll add a task to do so. Should also make a separate guide for Getting Credentials
2. left a note here: https://github.com/TBD54566975/developer.tbd.website/pull/644#discussion_r1289093647

2023-08-11 01:40 UTC, angiejones approved these changes

2023-08-11 01:41 UTC, merged