Adding new blog post
TBD54566975/developer.tbd.website pull request #649
Opened 2023-08-10 12:54 UTC by EbonyLouis

2023-08-10 19:38 UTC, ALRubinger requested changes
Please review extra dep as I'm noting in line changes?

2023-08-10 19:39 UTC, ALRubinger requested changes

2023-08-10 19:39 UTC, ALRubinger commented on package.json
> +    "react-markdown": "^8.0.7"
Should this new dependency be added for the new blog post? Seems off in this PR, no?

2023-08-10 19:42 UTC, EbonyLouis commented on package.json
> +    "react-markdown": "^8.0.7"
when I was trying to get it to compile locally, It kept saying it couldn't resolve 'react-markdown' so I had to npm install it. I can remove it.

2023-08-10 20:16 UTC, dayhaysoos commented on package.json
> +    "react-markdown": "^8.0.7"
Pretty sure this is due to mic's changes for the ChatGPT plugin

2023-08-10 20:46 UTC, angiejones requested changes

2023-08-10 20:47 UTC, angiejones commented on package.json
> +    "react-markdown": "^8.0.7"
so should this line be removed?

2023-08-10 21:25 UTC, dayhaysoos commented on package.json
> +    "react-markdown": "^8.0.7"
@angiejones she just recently pulled in changes from main so I think it's fine now.

2023-08-10 21:52 UTC, ALRubinger commented on package.json
> +    "react-markdown": "^8.0.7"
Yeah even if it's needed on the dev site, should be in the deps for the `site` workspace and not top-level. Sounds sorted now; thanks all.

2023-08-10 21:52 UTC, ALRubinger commented on package.json
> +    "react-markdown": "^8.0.7"
Rather, I guess it'll be sorted once this line is off the diffs on this PR :)

2023-08-11 14:41 UTC, angiejones commented on package.json
> +    "react-markdown": "^8.0.7"
confirming that this is already in main
https://github.com/TBD54566975/developer.tbd.website/blame/main/site/package.json#L38

2023-08-11 14:41 UTC, angiejones approved these changes

2023-08-11 14:42 UTC, merged