SSI: Create Schemas
TBD54566975/developer.tbd.website pull request #656
Opened 2023-08-12 04:25 UTC by bobbilee19

2023-08-12 04:46 UTC, bobbilee19 commented
Would love your thoughts on this @decentralgabe !

2023-08-14 00:04 UTC, angiejones requested changes

2023-08-14 00:04 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +As mentioned earlier, the signed version of a schema is packaged as a VC. In some cases it is useful to package a JSON Schema as a VC to retain information about authorship (who created the schema),
This can get moved to the proposed section on Signed vs Unsigned Schemas

2023-08-14 00:04 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +The following response should be returned:
A response resembling the following should be returned:

2023-08-14 00:04 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +Once you've created multiple schemas, you can view them all by make a `GET` request to the `v1/schemas` endpoint. Future enhancements may enable filtering based on name, author, or other properties.
make -> making

2023-08-14 00:04 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +Once you've created multiple schemas, you can view them all by make a `GET` request to the `v1/schemas` endpoint. Future enhancements may enable filtering based on name, author, or other properties.
remove sentence about Future enhancements

2023-08-14 00:04 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +You can get a specific schema by make a `GET` request to the `v1/schemas/{schemaId}` endpoint.
remove and let's make a ticket for a new guide on getting schemas. can show how to get one by id, and how to get all (if there's an endpoint for that)

2023-08-14 17:45 UTC, bobbilee19 commented on site/docs/ssi/create-schema.md
> +  "type": "JsonSchema2023",
do u want me to highlight ID and type or just ID - i see your comment twice around the same area so want to clarify

2023-08-14 17:53 UTC, bobbilee19 commented on site/docs/ssi/create-schema.md
> +The following response should be returned:
I'm keeping things consistent across tutorials, would you like me to change this elsewhere ie create credentials and run ssi service etc

2023-08-14 18:07 UTC, decentralgabe commented on site/docs/ssi/create-schema.md
> +  "credentialSchema": "eyJhbGciOiJFZERTQSIsImtpZCI6ImRpZDprZXk6ejZNa2plU..."
this will change a bit with https://github.com/TBD54566975/ssi-service/issues/633
not blocking, just a note

2023-08-14 18:07 UTC, decentralgabe approved these changes

2023-08-14 19:22 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +  "type": "JsonSchema2023",
yeah highlight all the things mentioned in your sentence

> Upon success you'll see a response which includes the **schema** you passed in, with a service-generated **identifier for the schema**. You'll also notice a type **JsonSchema2023**, which is defined by the VC JSON Schema specification

2023-08-14 23:50 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +For more background checkout out our SSI Service Guide on [Schemas](https://github.com/TBD54566975/ssi-service/blob/main/doc/howto/schema.md).
Is there more info in that guide than this one? Ideally, we'd like to cover everything that's there and have it live on the website.

2023-08-14 23:52 UTC, angiejones commented on site/docs/ssi/create-schema.md
> +
this still isn't completely clear to me. I wouldn't know when to create a signed vs unsigned VC. @decentralgabe what type of VC would I want to be unsigned?

2023-08-15 00:03 UTC, decentralgabe commented on site/docs/ssi/create-schema.md
> +
It wouldn't be a VC just a json schema.

A json schema can exist on its own as a piece of json, and is still usable. If we want it to be signed it's packaged as a VC.

2023-08-15 03:55 UTC, angiejones approved these changes

2023-08-15 03:56 UTC, merged