SSI Guide: Revoke Credential
TBD54566975/developer.tbd.website pull request #664
Opened 2023-08-16 17:03 UTC by bobbilee19

Here is version one, tested, and split into two guides. Would love to hear your thoughts @decentralgabe.

2023-08-16 17:29 UTC, decentralgabe approved these changes
looks great!

2023-08-16 19:23 UTC, angiejones requested changes

2023-08-16 19:23 UTC, angiejones commented on site/docs/ssi/revoke-credentials.md
> +These options are exposed to give issuers the ability to specify [status for credentials](credential-status) they create in the service. In this guide we'll go over how to revoke a credential!
Move first sentence to previous paragraph, and change exclamation point to a period in the second sentence.

2023-08-16 19:23 UTC, angiejones commented on site/docs/ssi/revoke-credentials.md
> +## Create a Revocable Credential
Let's move this entire section to the Credential Status guide since the purpose of this guide is simply to revoke an existing credential, and the other guide is purposed to teach devs how to create credentials that include status.

I think all that's needed in this guide is what you have under step 4

2023-08-16 19:23 UTC, angiejones commented on site/docs/ssi/revoke-credentials.md
> +To do so, we would make request to the [update credential status endpoint](/docs/apis/ssi-service#tag/Credentials/paths/~1v1~1credentials~1%7Bid%7D~1status/put) which is a `PUT` request to `/v1/crede
> As the creator of a credential, you're able to change the status of that credential.
> 
> To do so, make a `PUT` request to `/v1/credentials/{id}/status` and specify a boolean value for the status you'd like to change.
> 
> Given a credential was created with `revocable` as true, you can revoke that credential by setting `revoked` to true:
> 
> ```bash
> curl -X PUT localhost:8080/v1/credentials/8f9d58b2-c978-4317-96bd-35949ce76121/status -d '{ "revoked": true }'
> ```
> 
> Upon success, you'll see the following response:
> 
> ```json
> { 
>   "revoked": true
> }
> ```
> 
> _Note that if the credential is also suspendable, the `suspended` status will also appear in the response above._
>

2023-08-16 19:23 UTC, angiejones commented on site/docs/ssi/revoke-credentials.md
> +Let's update the credential's status to revoked:
can remove lines 156-174

2023-08-16 19:23 UTC, angiejones commented on site/docs/ssi/revoke-credentials.md
> +:::note
> :::note
> It is possible to reverse the status of a credential. To do so, make a `PUT` request to `/v1/credentials/{id}/status`, and set the value of `revoked` to false.
> :::

2023-08-16 19:26 UTC, angiejones commented on site/docs/ssi/credential-status.md
> +## Example Credential Status Credential:
or ## "Credential Status" Credential

The quotes will help with readability

2023-08-16 19:55 UTC, bobbilee19 commented on site/docs/ssi/credential-status.md
> +## Example Credential Status Credential:
that's what i thought at first, but if you keep reading the other credential we make as a SLC as well in it.

2023-08-16 21:17 UTC, angiejones commented on site/docs/ssi/credential-status.md
> +In this example below we have a **status list credential** which is used for many credentials issued by the issuer identified by the DID `did:example:12345`:
ah ok cool. @bobbilee19 we can go with this

> Here is an example of a status list credential. Note that in addition to being of type `VerifiableCredential`, it also is of type `StatusList2021Credential`. Also note the `credentialSubject.type` property is set to `Status2021`:

2023-08-17 00:54 UTC, bobbilee19 commented on site/docs/ssi/credential-status.md
> +In this example below we have a **status list credential** which is used for many credentials issued by the issuer identified by the DID `did:example:12345`:
Let me know what you like better.

2023-08-17 01:10 UTC, bobbilee19 commented on site/docs/ssi/revoke-credentials.md
> +To do so, we would make request to the [update credential status endpoint](/docs/apis/ssi-service#tag/Credentials/paths/~1v1~1credentials~1%7Bid%7D~1status/put) which is a `PUT` request to `/v1/crede
This is what the response is even though I didn't set suspendable so going to leave as is unless you got something different?...

```json
{ 
  //highlight-next-line
  "revoked": true,
  "suspended": false
}

2023-08-17 01:39 UTC, bobbilee19 commented on site/docs/ssi/credential-status.md
> +In this example below we have a **status list credential** which is used for many credentials issued by the issuer identified by the DID `did:example:12345`:
I put in yours for now.

2023-08-17 03:00 UTC, angiejones commented on site/docs/ssi/revoke-credentials.md
> +To do so, we would make request to the [update credential status endpoint](/docs/apis/ssi-service#tag/Credentials/paths/~1v1~1credentials~1%7Bid%7D~1status/put) which is a `PUT` request to `/v1/crede
@decentralgabe why is the suspendable status here even though only revocable was specified when creating the credential?

2023-08-17 03:04 UTC, angiejones approved these changes

2023-08-17 03:05 UTC, merged