Credential Manifest Request Setup Guide
TBD54566975/developer.tbd.website pull request #674
Opened 2023-08-18 21:37 UTC by bobbilee19

2023-08-19 03:13 UTC, angiejones requested changes

2023-08-19 03:13 UTC, angiejones commented on site/docs/ssi/credential-manifests.md
> +Return all Manifests:
can remove this line and end line 93 with a colon

2023-08-19 03:13 UTC, angiejones commented on site/docs/ssi/credential-manifests.md
> +Return all Manifests associated with a specific Issuer `id`:
To return all Manifests associated with a specific issuer, pass in Issuer's DID as the `id`:

2023-08-19 03:13 UTC, angiejones commented on site/docs/ssi/credential-manifests.md
> +Via a `GET` request to `/v1/manifests/{id}`, pass in the `id` of the Manifest you wish to read.
To get a specific Manifest, submit a `GET` request to `/v1/manifests/{id}` and pass in the `id` of the Manifest:

2023-08-19 03:13 UTC, angiejones commented on site/docs/ssi/credential-manifests.md
> +If there is a matching Manifest `id`, you'll see the following response:
If there is a matching Manifest, it will be returned as a JSON object:

2023-08-19 16:12 UTC, angiejones commented on site/docs/ssi/credential-manifests.md
> +- `outputDescriptors` - Array of objects `manifest.OutputDescriptor` as defined in the Credential Manifest [Output Descripter](https://identity.foundation/credential-manifest/#output-descriptor) spec
can we be more specific here and not link to the spec? can use some of the language from the new intro

2023-08-21 17:30 UTC, bobbilee19 commented on site/docs/ssi/credential-manifests.md
> +Credential Manifest is a draft specification being developed within the [Decentralized Identity Foundation](https://identity.foundation/) (DIF). The design work on the data model is ongoing and parti
the actual spec 404ing so this is the only link we have rn

2023-08-21 17:35 UTC, bobbilee19 commented on site/docs/ssi/credential-manifests.md
> +Credential Manifest is a draft specification being developed within the [Decentralized Identity Foundation](https://identity.foundation/) (DIF). The design work on the data model is ongoing and parti
not sure what you mean by github to github, i am linking to github

2023-08-21 18:09 UTC, angiejones requested changes

2023-08-21 19:16 UTC, angiejones requested changes

2023-08-21 19:16 UTC, angiejones commented on site/docs/ssi/credential-manifests.md
> +Issuers create and host Credential Manifests for the credentials they offer. Assuming the DMV wants to create a Credential Manifest for their digital driver's license credential, they can use the SSI
Can we move this above the fields definitions section? right after ### Create a Credential Manifest

2023-08-21 20:01 UTC, angiejones commented
@bobbilee19 hold off on this. I'm looking more into input descriptors vs output descriptors. will report back in a few

2023-08-21 22:08 UTC, angiejones commented
> @bobbilee19 hold off on this. I'm looking more into input descriptors vs output descriptors. will report back in a few

ok I've updated the guide to focus on input descriptors as that's where the manifest specifies the required data. should be good to go now

2023-08-21 22:09 UTC, angiejones commented
@decentralgabe can you please review this for accuracy?
https://vercel.live/open-feedback/developer-tbd-website-site-git-issue-669-set-beb610-tbd54566975.vercel.app

2023-08-21 22:09 UTC, angiejones approved these changes

2023-08-22 13:51 UTC, decentralgabe approved these changes
great guide! we should add this to the ssi service docs too

2023-08-22 14:04 UTC, merged