Well Known DID Configuration Guide
TBD54566975/developer.tbd.website pull request #680
Opened 2023-08-22 23:23 UTC by bobbilee19

As mentioned to Angie in slack verification section to the guide will come tomorrow.

2023-08-22 23:57 UTC, angiejones requested changes

2023-08-22 23:57 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +- An origin you control (e.g., https://www.tbd.website)
use https://example.com throughout the guide as the domain

2023-08-22 23:57 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +The SSI Service does all the heavy lifting to set this up for you, linking DIDs that were created within the service to a website you control.
let's remove 'does all of the heavy lifting' since people have to do a big step (place a file on their server) outside of the service

2023-08-22 23:57 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +```
At this point let's instruct them how to do this:

## Host the Created DID Configuration
Now that we have `wellKnownLocation`, let's ensure it resolves to a JSON file.

1. Create a directory at the root of the public folder of their server called `.well-known`
2. Create a new file in the `.well-known` directory called `did-configuration.json`
3. Copy the json and paste it into the `did-configuration.json` file and save it
```json
{
  "@context": "https://identity.foundation/.well-known/did-configuration/v1",
  "linked_dids": [
    "eyJhbGciOiJFZERTQSIs..."
  ]
}
```

With that in mind, in our example the URL `https://example.com/.well-known/did-configuration.json` should return the JSON object.

2023-08-22 23:57 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +- [Create an Issuer DID](create-did): Save the DID `id` and `verificationMethodId`
Create a DID (or use an existing one)

2023-08-22 23:57 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +  "issuerDid": "did:key:z6MkmM43K3x5xAgzkLRW9r6HCv5c4QKfD2wjfi6tiW3CuzjZ",
@decentralgabe why is this `issuerDid` and not the controller's DID? Like if an issuer issues me a DID and I want to associate it with my website, I'd put their DID and not mine? I think I'm missing something.

2023-08-22 23:57 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +    "linked_dids": [
@decentralgabe how does this get populated? can I add more here in my .json file later?

2023-08-23 00:34 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +Enabling the bridge between current systems and DIDs is essential to amplify their adoption and practicality. A method to achieve this connection involves utilizing a resource known as a [Well Known
Connecting DIDs to existing systems is essential to amplify their adoption and practicality. One way to do this is by proving that the entity that controls a DID is also in control of a specific web origin (a website's location). A method to achieve this connection involves utilizing a resource known as a [Well Known DID Configuration](https://identity.foundation/.well-known/resources/did-configuration/).

2023-08-23 00:46 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +The SSI Service does all the heavy lifting to set this up for you, linking DIDs that were created within the service to a website you control.
can change both paragraphs to:


Imagine Alice controls a reputable website, example.com. She can use DID Configuration to prove that she is the same entity controlling both the DID and the website. This proof involves cryptographic signatures that show Alice are connected to both, allowing others to verify that Alice's DID and her website are indeed managed by the same entity.

This can be accomplished via the SSI Service.

2023-08-23 02:18 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +# Well Known DID Configuration
let's make the guide title "Connect DID to Domain"

2023-08-23 02:19 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +This type of resource serves as proof of a bi-directional link between a website manager and their DID. This verification is established through a cryptographically secure digital signature associate
For lines 9-12, let's change to:

> ## Well Known DID Configuration
> 
> Imagine Alice controls a reputable website, example.com. She can use DID Configuration to prove that she is the same entity controlling her DID and her website. This proof involves cryptographic signatures that show Alice is connected to both, allowing others to verify that Alice's DID and her website are indeed managed by the same entity.
> 
> This configuration can be created via the SSI Service.

2023-08-23 03:36 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +
include description of `linked_ids`

2023-08-23 14:33 UTC, decentralgabe commented on site/docs/ssi/well-known-did.md
> +# Well Known DID Configuration
maybe Link instead of connect?

2023-08-23 14:33 UTC, decentralgabe commented on site/docs/ssi/well-known-did.md
> +  "issuerDid": "did:key:z6MkmM43K3x5xAgzkLRW9r6HCv5c4QKfD2wjfi6tiW3CuzjZ",
that's right Angie, the issuer = controller here. Usually we say 'issuer' when we're referring to the party that's signing over the document

2023-08-23 14:34 UTC, decentralgabe commented on site/docs/ssi/well-known-did.md
> +    "linked_dids": [
I'm not actually certain who set this up, perhaps @andresuribe87 or @mistermoe know

2023-08-23 14:34 UTC, decentralgabe approved these changes

2023-08-23 16:59 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +# Well Known DID Configuration
yes that's better "Link a DID to a Domain"

2023-08-23 22:11 UTC, andresuribe87 reviewed
@angiejones I'm curious what the

2023-08-23 23:29 UTC, bobbilee19 commented
Also do we want to add this note below verification section? It's from the spec, but I don't think it's needed because we aren't referencing anywhere that Alice may have two DIDs, so it could confuse ppl...

:::note
Alice's Domain Linkage Credentials (other DIDs Alice may own e.g, `did:ion:74839` and `did:key:jdfakj389`) are separate from each other. So, if one of them turns out to be valid or invalid, it doesn't impact the status of the others.
:::

2023-08-24 04:01 UTC, angiejones commented on site/docs/ssi/well-known-did.md
> +    "linked_dids": [
@andresuribe87 I'm trying to understand how this works in practice. if I have an existing did-configuration file in place and I want to link another DID with my origin, I'd use SSI service to obtain another credential and then just paste the new JWT into the array in my existing file?

2023-08-24 06:43 UTC, angiejones approved these changes

2023-08-24 06:51 UTC, merged

2023-08-24 14:14 UTC, decentralgabe commented on site/docs/ssi/well-known-did.md
> +    "linked_dids": [
I don't know if we support updating yet. I believe it would work to just create a fresh new configuration with the old + new info