test snippets for how-to-create-did
TBD54566975/developer.tbd.website pull request #682
Opened 2023-08-23 17:12 UTC by dayhaysoos

2023-09-05 14:03 UTC, dayhaysoos commented
Will continue work on this once #688 is merged

2023-09-15 17:06 UTC, dayhaysoos commented on site/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
Skipped tests that involve creating a did manually

2023-09-15 17:07 UTC, dayhaysoos commented on site/code-snippets/api/web5-js/did.js
Skipping tests that involve creating did manually (this is the function that gets tested, not he test itself)

2023-09-15 17:08 UTC, dayhaysoos commented on site/code-snippets/api/web5-js/dwn/protocol.js
I think we're waiting for a new protocol syntax here?

2023-09-15 17:09 UTC, dayhaysoos commented on site/code-snippets/web5/build/decentralized-identifiers/how-to-create-did.js
> +export async function createDidManually() {
Skipping until creating did manually works

2023-09-15 17:11 UTC, dayhaysoos commented
@angiejones I think this PR is ready for review. Let me know if you have any questions

2023-09-15 23:01 UTC, angiejones commented on site/code-snippets/api/web5-js/dwn/protocols.js
no, we can add some tests now

2023-09-15 23:01 UTC, angiejones commented on site/code-snippets/api/web5-js/dwn/protocol.js
no, we can add some tests now

2023-09-19 21:23 UTC, angiejones requested changes

2023-09-19 21:23 UTC, angiejones commented on site/__tests__/api/web5-js/dwn/protocols.test.js
> +    expect(result).toBeDefined();
will these help us know if the code snippet is still valid? is the assumption here that we won't get a result of the query was not successful?

I think a good sanity check on all of these would be to check for the status code

2023-09-19 21:23 UTC, angiejones commented on site/__tests__/api/web5-js/did.test.js
> +test.skip('create did', async () => {
when we skip a test, can we add a comment or some other formal thing indicating why it's skipped and the issue number to track the fix?

2023-09-19 21:23 UTC, angiejones commented on site/__tests__/api/web5-js/index.js
> +    console.log(result);
why the log statement? should we add some sort of assertion?

2023-09-19 21:23 UTC, angiejones commented on site/__tests__/web5/build/decentralized-identifiers/how-to-create-did.test.js
> +test.skip('createDidManually returns a DID', async () => {
need to associate with an issue

2023-09-19 21:23 UTC, angiejones commented on site/__tests__/quickstart.test.js
> -    expect.soft(response.status.code).toBe(202);
how come status code removed?

2023-09-19 22:16 UTC, dayhaysoos commented on site/__tests__/api/web5-js/dwn/protocols.test.js
> +    expect(result).toBeDefined();
Yes for right now, we know it can run and it returns successfully. I can adjust to check statuses at least

2023-09-19 22:17 UTC, dayhaysoos commented on site/__tests__/quickstart.test.js
> -    expect.soft(response.status.code).toBe(202);
I think that was a mistake, will double check

2023-09-20 00:34 UTC, dayhaysoos commented on site/__tests__/quickstart.test.js
> -    expect.soft(response.status.code).toBe(202);
ooh this was removed because we don't have status being returned in the code snippet. So the only thing I have to test here is the record itself. Do you want me to put it back?

This was part of the discussion I wanted to have about standardizing how we write our code snippets. Some snippets we include status and can use that for testing, others, we don't.

2023-09-20 00:36 UTC, dayhaysoos commented
@angiejones The tests with 202 responses normally means the requests were accepted, but hasn't returned anything due to processing. I think it might be the nature of the testing environment. I'd like to ask OSE what they think of this, if this is acceptable to them. Otherwise, we'd have to figure out to get back the finished request.

Any thoughts? I just pushed the changes

2023-09-20 18:20 UTC, dayhaysoos commented
![Screenshot 2023-09-20 at 2 19 57 PM](https://github.com/TBD54566975/developer.tbd.website/assets/1852675/ab1d8d74-60eb-4399-a12e-53f3295d8de4)

This is in response to the 202 responses we're getting back in the tests. I'd say this is okay

2023-09-20 18:25 UTC, dayhaysoos commented
Created the issue for creating dids manually:

https://github.com/TBD54566975/developer.tbd.website/issues/733

2023-09-20 18:58 UTC, dayhaysoos commented on site/__tests__/api/web5-js/index.js
> +    console.log(result);
This was actually an unfinished test, just wrapped it up

2023-09-20 21:43 UTC, angiejones commented on site/code-snippets/api/web5-js/dwn/records.js
> +  // assuming the record is a text payload, logs the text
did a `console.log` line get removed here?

2023-09-20 22:56 UTC, dayhaysoos commented on site/code-snippets/api/web5-js/dwn/records.js
> +  // assuming the record is a text payload, logs the text
Added it back

2023-09-20 23:08 UTC, merged