adding community landing page
TBD54566975/developer.tbd.website pull request #701
Opened 2023-08-25 21:37 UTC by EbonyLouis

## **To Be Added:**

- Google Calendar integration, getting it integrated shouldn't be hard , but getting the API keys is a process so still working on that. I will add it once I get them
- Right now the incubation button links to the incubation page in open-source. Will add a highlight page later.

2023-08-25 22:56 UTC, angiejones commented on site/src/pages/community/index.js
> +        <h2 className="pt-6">TBD Spotlight</h2>
maybe 'TBD Monthly Spotlight' so that it's clear these aren't ALL of our contributors? the verbiage below should also indicate how/why these contributors were featured

2023-08-25 22:58 UTC, angiejones commented on site/static/img/discord-avatar.png
do we need this file? we have discord-icon.svg on the server already

2023-08-25 22:59 UTC, angiejones commented
adding @dayhaysoos since there's Netlify functions being added

2023-08-25 23:00 UTC, angiejones requested changes

2023-08-25 23:00 UTC, angiejones commented on site/src/pages/community/index.js
the title of the page (on the window tab) is TBD Developer Docs
https://deploy-preview-701--tbd-website-developer.netlify.app/community

2023-08-26 03:48 UTC, EbonyLouis commented on site/src/pages/community/index.js
ah good catch! A few of the page tittles we're messed up. In the `docusaurus.config.js` file the global tittle for the entire site was set to `TBD Developer Docs`. I updated it to just `TBD` and in the docs` index.js` I changed that from being `Getting Started` to `Developer Docs`. (this I can change back if you prefer, left a comment).  I updated some other pages as well.

2023-08-26 03:48 UTC, EbonyLouis commented on site/static/img/discord-avatar.png
nope, we can use the one we already have.

2023-08-27 14:07 UTC, angiejones commented on .env.local.example
> +DISCORD_BOT_TOKEN=your_discord_token_goes_here
what token is this exactly? does everyone who wants to contribute to this site have to get this token? @dayhaysoos can this be disabled locally like the search widget is?

2023-08-28 14:57 UTC, dayhaysoos commented on .env.local.example
> +DISCORD_BOT_TOKEN=your_discord_token_goes_here
Going to follow up with @EbonyLouis on this

2023-09-08 13:37 UTC, EbonyLouis commented
@angiejones when you get a chance can I have a final review on this please so I can merge it?

2023-09-08 14:07 UTC, angiejones approved these changes

2023-09-08 14:19 UTC, EbonyLouis commented
@dayhaysoos ready for the test you needed to run before I merge.

2023-09-08 14:54 UTC, dayhaysoos commented
> @dayhaysoos ready for the test you needed to run before I merge.

Taking a look now

2023-09-08 15:02 UTC, dayhaysoos approved these changes
Good to go!

2023-09-08 15:50 UTC, merged