Presentation Requests
TBD54566975/developer.tbd.website pull request #708
Opened 2023-09-05 23:30 UTC by bobbilee19

2023-09-06 15:08 UTC, decentralgabe commented on site/docs/ssi/presentation-requests.md
> +[Presentation Requests](https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-request) are transport mechanisms used to send a [Presentation Definition](https://identity.foundat
```suggestion
[Presentation Requests](https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-request) are data models used to send a [Presentation Definition](https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-definition) from a Verifier to a Holder. Presentations (aka Presentation Definition) are objects that articulate which claims a Verifier requires. These help the Verifier to decide how or whether to interact with a Holder. They consist of input descriptions and optional selection rules to offer Holders flexibility in meeting input requirements.
```

2023-09-06 15:09 UTC, decentralgabe commented on site/docs/ssi/presentation-requests.md
> +## Presentation API Requests
This is all accurate, but it may be worth noting that an issuer must first create a presentation definition to reference, which uses a different API (`/v1/presentations/definitions` I think). You may also want to show the submission portion at the end

2023-09-06 15:10 UTC, decentralgabe reviewed
looks good few comments

2023-09-06 16:30 UTC, angiejones requested changes

2023-09-06 20:00 UTC, bobbilee19 commented on site/docs/ssi/presentation-requests.md
> +## Presentation API Requests
Oh yeah I reference that in the prerequisite section...

```
:::info
## Prerequisites
- Follow guide to [Run SSI Service](run-ssi-service)
- Create a [Presentation Definition](/docs/apis/ssi-service#tag/Presentations/paths/~1v1~1presentations~1definitions/put)
- Create a [DID](create-did)
:::
```

2023-09-06 20:01 UTC, bobbilee19 commented on site/docs/ssi/presentation-requests.md
> +- `audience`	(array of strings) - The audience claim identifies the recipients that the JWT is
This is the only link referenced in our api ref, @decentralgabe is there another reference for this to link to?

2023-09-06 20:18 UTC, decentralgabe commented on site/docs/ssi/presentation-requests.md
> +- `audience`	(array of strings) - The audience claim identifies the recipients that the JWT is
no, that's the right link

2023-09-06 20:19 UTC, bobbilee19 commented on site/docs/ssi/presentation-requests.md
> +The following response should be returned:
it says presentationRequest in the response

2023-09-06 20:22 UTC, bobbilee19 commented on site/docs/ssi/presentation-requests.md
> +[Presentation Requests](https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-request) are transport mechanisms used to send a [Presentation Definition](https://identity.foundat
@decentralgabe can you review angie's edit to the first paragraph, it is different than yours, which one would you like me to go with.

2023-09-06 20:26 UTC, bobbilee19 commented on site/docs/ssi/presentation-requests.md
> +## Presentation API Requests
Yep will do. I was following your edits to my cred manifest guide. Mirroring that guide for consistency.

2023-09-06 20:59 UTC, bobbilee19 commented
I've made all changes just waiting on my questions above before adding my commit.

2023-09-06 21:43 UTC, decentralgabe commented on site/docs/ssi/presentation-requests.md
> +[Presentation Requests](https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-request) are transport mechanisms used to send a [Presentation Definition](https://identity.foundat
sounds good to me

2023-09-07 05:17 UTC, angiejones approved these changes

2023-09-07 05:17 UTC, merged