adding devcontainer to open in Codespaces
TBD54566975/developer.tbd.website pull request #722
Opened 2023-09-13 21:41 UTC by blackgirlbytes

## Description
This PR adds a devcontainer to open the TBD website in Codespaces. The dev container installs all necessary project dependencies, runs the project, and opens up a browser preview of the project. 

**Please note**: If you click the button before merging, it won't have any of the configurations I set up because it's not merged yet. You can try out this link to see what the experience would be like. This is the link that points to my personal branch: https://codespaces.new/galaxy-bytes/developer.tbd.website/tree/adding-codespaces-hacktoberfest?quickstart=1

The first time you click it, it might be slow, but it will be a little faster on additional attempts.

This option is for contributor use; Codesandbox will be for workshops/code snippets.

## What type of PR is this? (check all applicable)

- [x] 🆕  Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
N/A
## Mobile & Desktop Screenshots/Recordings
https://github.com/TBD54566975/developer.tbd.website/assets/22990146/06b74b51-95a8-4eac-8401-7f40b575f8f5

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [x] 📜 README.md
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?
N/A

## [optional] What gif best describes this PR or how it makes you feel?

2023-09-13 21:46 UTC, blackgirlbytes commented
also side note: @angiejones @EbonyLouis -- what do yall think of this PR template? If you all haven't decided on one yet, we can use something like this for contributors (with changes that suit this organization)

2023-09-13 22:09 UTC, angiejones requested changes

2023-09-13 22:09 UTC, angiejones commented on .devcontainer/devcontainer.json
> +    "name": "TBD Website - GitHub Codespaces container",
TBDeveloper Website

2023-09-13 23:45 UTC, dayhaysoos commented
Hey @blackgirlbytes, this looks really cool! I love that this is an easier way for contributors to jump right in.

I also really like the PR template, would be down to adapt it to our needs (things like web5 version etc etc).

Curious about what the others think

2023-09-14 13:30 UTC, EbonyLouis commented
I like it, I had it as an item to do especially with hacktoberfest coming up, and yours is really cute! Nick and Andrew should be able to provide more guidance on the specific tweaks that are needed. 

I also love the option under test, "no, because I need help". Thanks Rizel!

2023-09-14 13:48 UTC, EbonyLouis commented
@blackgirlbytes here are the other 3 repos that you can add codespaces too as well please

- `Dwn-server`
- `Dwn-sdk-js`
- `Web5-js`

2023-09-15 02:13 UTC, angiejones approved these changes

2023-09-15 03:17 UTC, blackgirlbytes commented
Thanks before anyone merges this, let me know how yall feel about my Discord message

2023-09-19 19:11 UTC, blackgirlbytes commented
Closing this PR as we're moving to code sandbox instead. Thank you!

2023-09-19 19:11 UTC, closed without merging