add steps for adding code-snippets
TBD54566975/developer.tbd.website pull request #752
Opened 2023-09-25 19:11 UTC by dayhaysoos

2023-09-25 19:48 UTC, dayhaysoos commented on site/src/pages/open-source/contributing.mdx
> +It's important to make your function name as specific as possible, because it me used to reference the code snippet in the code-snippets.json file. Similar names will overwrite one another.
This would definitely be a better, safer approach!

2023-09-26 03:12 UTC, angiejones requested changes

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +2. The second update you'll make would be on the content page itself. Where you wanted the code snippet to exist at `api/web5-js/protocols.md`, you'd add the following:
```suggestion
2. The second update you'll make would be on the content page itself. Add the following snippet where you'd like the code snippet to exist:
```

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +3. The 3rd step from here is to write tests for the code snippet.
```suggestion
3. Write tests for the code snippet.
```

Don't wanna include "3rd step" because we'd need to remember to change this if we ever added a step before this one

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +Below is a template we can use that will be necessary for nearly every test we write for Web5.
```suggestion
Below is an example test file
```

Where do the tests go? Need directory and file name

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +// import your functions from your codesnippet file here
should add an example of the import

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +    const { protocols, status } = await queryMusicProtocol(web5);
```suggestion
    //this calls the function that returns the code snippet
    const { protocols, status } = await queryMusicProtocol(web5);
```

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +    // This will return an empty array, if it fails it will be undefined.
```suggestion
    // expect.soft() will note any failures if they occur but will continue running the test
```

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +    // We do 202 for this test because protocols comes back undefined, need to check if this is expected behavior.
remove this from the readme

2023-09-26 03:12 UTC, angiejones commented on site/src/pages/open-source/contributing.mdx
> +- Tests won't be high quality depending on what gets returned. In some examples we only return a DID, but not the status code so we'll have to make tests around those types of instances.
```suggestion
- These tests are only testing the code snippets. There are more thorough tests that actually test the SDK.
```

2023-09-27 15:07 UTC, merged