Add padding to the feedback widget #748  -->  Fixed
TBD54566975/developer.tbd.website pull request #758
Opened 2023-09-28 03:46 UTC by LynxSumit

🚀 PR #748 Update: Added padding to the feedback widget 🚀

🔧 Changes Made:
Hi team! I'm excited to share my latest contribution to our project. In this PR, I've addressed issue #748 by adding padding to the feedback widget. This improvement not only enhances the visual aesthetics of the widget but also ensures a better user experience.

🛠️ What I've Done:
- Added appropriate padding to the feedback widget.
- Conducted thorough testing to confirm that the padding works as expected.
- Updated relevant documentation to reflect these changes.

🧐 Why This Matters:
This PR improves the overall user interface by providing a more polished and user-friendly appearance to the feedback widget. This small but meaningful change aligns with our commitment to delivering a top-notch user experience.

🌟 Let's Collaborate:
I'm looking forward to your feedback and any suggestions for further improvement. Please feel free to review and provide your thoughts. Together, we can ensure that our project continues to shine!

🙏 Thank you for your time and consideration!

2023-09-28 16:23 UTC, angiejones requested changes

2023-09-28 16:23 UTC, angiejones commented on site/src/util/code-snippets-map.json
this file should not be updated

2023-09-28 16:23 UTC, angiejones commented on site/src/contributors.json
> +  {
@EbonyLouis are you ok with this?

2023-09-28 16:23 UTC, angiejones commented on site/src/components/Card.jsx
> +      className={`flex flex-col bg-transparent border-[#282828] border-2 shadow overflow-hidden sm:rounded-lg p-8 lg:p-10  sm:p-5 ${className}`}
```suggestion
      className={`flex flex-col bg-transparent border-[#282828] border-2 shadow overflow-hidden sm:rounded-lg p-8 lg:p-10 sm:p-5 ${className}`}
```
removed extra space

2023-09-28 17:41 UTC, angiejones commented on site/src/components/Card.jsx
> +      className={`flex flex-col bg-transparent border-[#282828] border-2 shadow overflow-hidden sm:rounded-lg p-8 lg:p-10  sm:p-5 ${className}`}
and revert code-snippets-map.json, thats the most important change to make

2023-09-28 19:51 UTC, angiejones commented
@LynxSumit thanks so much! would you like us to wait until Monday to merge this so that you get credit for Hacktoberfest?

2023-09-29 13:56 UTC, EbonyLouis commented on site/src/contributors.json
> +  {
yes that's fine.

2023-10-01 04:21 UTC, angiejones requested changes
@LynxSumit there's merge conflicts with code-snippets-map.json. Please completely remove any changes to this file from your PR

2023-10-01 04:36 UTC, angiejones commented on site/src/util/code-snippets-map.json
are you able to just remove this file from your PR? i'm not sure why it's being automatically updated

2023-10-01 05:12 UTC, angiejones approved these changes

2023-10-01 05:18 UTC, merged

2023-10-01 05:18 UTC, angiejones commented
merging this one @EbonyLouis. can you add to Leaderboard?