Example snippet to query by protocolPath and structure
TBD54566975/developer.tbd.website pull request #763
Opened 2023-09-28 17:30 UTC by blackgirlbytes

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR adds an example of how to query records by protocolPath and type. I saw someone ask about this in Discord, and I feel like it would help to have a more explicit example.

I got Nick's review, so I guess I only need a review for clarity and structure. 

## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

<img width="770" alt="Screenshot 2023-09-29 at 9 59 21 AM" src="https://github.com/TBD54566975/developer.tbd.website/assets/22990146/92963fcd-cb0f-44fa-a8f4-eb4156df02d3">

## Added code snippets?
- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help (will add)

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?
![giphy](https://github.com/TBD54566975/developer.tbd.website/assets/22990146/352a7668-792e-4340-a338-712d2ac5e997)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205620813630998

2023-09-28 19:45 UTC, angiejones requested changes

2023-09-28 19:45 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +  const musicProtocolDefinition = {
this part should also go in a snippet. For example, they added `published` as a required field on protocols and we didn't know - and our code snippets didn't reflect that. this is the problem we're trying to solve for with snippets and tests.

2023-09-28 19:45 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +The following snippets demonstrate how to query records by path and type to match a defined protocol. The protocol definition below has an audio type and a video type:
```suggestion
The following snippets demonstrate how to query records by protocol path and type to match a defined protocol. The protocol definition below has an audio type and a video type:
```

2023-09-28 19:45 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +The following snippets demonstrate how to query records by path and type to match a defined protocol. The protocol definition below has an audio type and a video type:
Not sure if you're actually querying by `type`. I think it's actually on structure. 

For example, in this example, my protocolPath is `protocolPath: 'message/reply',` (not just `reply` - that doesn't work), where the protocol is:

```js
const protocolDefinition = {
    "protocol": "https://social-media.xyz",
    "published": true,
    "types": {
      "message": {
        "schema": "https://social-media.xyz/schemas/messageSchema",
        "dataFormats": ["text/plain"]
      },
      "reply": {
        "schema": "https://social-media.xyz/schemas/replySchema",
        "dataFormats": ["text/plain"]
      },
      "image": {
        "dataFormats": ["image/jpeg"]
      },
      "caption": {
        "schema": "https://social-media.xyz/schemas/captionSchema",
        "dataFormats": ["text/plain"]
      }
    },
    "structure": {
      "message": {
        "$actions": [...],
        "reply": {
          "$actions": [...]
        }
      },
      "image": {
        "$actions": [...],
        "caption": {
          "$actions": [...]
        },
        "reply": {
          "$actions": [...]
        }
      }
    }
};
```

2023-09-29 14:01 UTC, blackgirlbytes commented
I revised it based on your feedback @angiejones

2023-09-29 14:45 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +      // highlight-start
no need to change this time, but just wanted to let you know there's a `// highlight-next-line` for when you just need to highlight a single line 😊

2023-09-29 14:47 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        schema: "https://schema.org/Playlist",
if you'd like to use a resolvable schema, can use https://schema.org/AudioObject

2023-09-29 14:47 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        schema: "https://schema.org/Playlist",
https://schema.org/VideoObject

2023-09-29 14:50 UTC, angiejones requested changes

2023-09-29 14:50 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +    protocol: "https://music.org/protocol",
```suggestion
    protocol: "https://music.org/protocol",
    published:true,
```
The protocol won't install without the `published` property being defined

2023-09-29 14:51 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        schema: "https://schema.org/Playlist",
```suggestion
        schema: "https://schema.org/VideoObject",
```

2023-09-29 14:52 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        schema: "https://schema.org/Playlist",
```suggestion
        schema: "https://schema.org/AudioObject",
```

if you'd like to use a resolvable schema, can use https://schema.org/AudioObject

2023-09-29 14:55 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        protocolPath: 'audio',
do you think it's worth showing an example where you're not querying a root level object? For example, if your structure was defined as a Playlist that can include types Audio and Video, then the protocolPath would be `playlist/audio`. Not sure if that's obvious to folks.

2023-09-29 21:58 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +      playlist: {
who writes a playlist? did you test to see if the author can write a new one to their DWN based on this protocol?

2023-09-29 22:04 UTC, angiejones requested changes

2023-09-29 22:04 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +## Querying Records by Path and Structure
```suggestion
## Querying Records by Protocol Path
```

2023-09-29 22:04 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +The following snippet demonstrates how to query records by protocol path and structure to match a defined protocol:
```suggestion
The following snippet demonstrates how to query records that match a specific protocol path:
```

2023-09-30 01:21 UTC, angiejones approved these changes

2023-09-30 17:28 UTC, blackgirlbytes commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +      playlist: {
this is a similar structure i have for the dinger app. And it was working for me. Is the wrong way to set permissions? I thought this was saying:
Anyone can create a playlist.
If an author creates a playlist, they can read their playlist.
They can send a playlist to someone and that recipient can read their playlist.

Am I misunderstanding?

2023-10-01 02:06 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +      playlist: {
with the `anyone` can write permission, then yes. I think that was missing at first so no one would have been able to write a playlist object

```js
        $actions: [
          { who: "anyone", can: "write" },
          { who: "author", of: "playlist", can: "read" },
          { who: "recipient", of: "playlist", can: "read" },
        ],
```

it's correct now 😊

2023-10-01 02:14 UTC, angiejones requested changes

2023-10-01 02:14 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        protocolPath: 'playlist/videos',
```suggestion
        protocolPath: 'playlist/video',
```

2023-10-01 02:27 UTC, angiejones requested changes

2023-10-01 02:27 UTC, angiejones commented on site/docs/web5/build/decentralized-web-nodes/query-from-dwn.mdx
> +Before querying records by path and structure, ensure that the protocol is [defined](https://developer.tbd.website/docs/web5/learn/protocols/#defining-a-protocol) and [installed](https://developer.tb
```suggestion
Before querying records by protocol path, ensure that the protocol is [installed](https://developer.tbd.website/docs/web5/learn/protocols/#installing-a-protocol). 
```

2023-10-01 02:30 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        protocolPath: 'playlist/videos',
Always run any code you put out to make sure it actually works. I just ran all the code to make sure it works, and it's good to go (with this change):
- installed this protocol
- created a playlist record
- created a video record that's a child of playlist
- ran the query

2023-10-01 05:26 UTC, blackgirlbytes commented on site/code-snippets/web5/build/decentralized-web-nodes/query-from-dwn.js
> +        protocolPath: 'playlist/videos',
true after I made a bunch of changes, I did neglect to test it! Thanks!

2023-10-01 22:38 UTC, angiejones approved these changes

2023-10-01 22:38 UTC, merged