add missing snippet for protocols
TBD54566975/developer.tbd.website pull request #764
Opened 2023-09-28 18:27 UTC by dayhaysoos

Adding missing code snippet to the docs site

2023-09-28 19:47 UTC, angiejones approved these changes

2023-09-29 14:42 UTC, angiejones requested changes

2023-09-29 14:42 UTC, angiejones commented on site/code-snippets/api/web5-js/dwn/protocols.js
heads up, I've updated this code on the site so this needs to be updated

2023-09-29 16:02 UTC, dayhaysoos commented on site/code-snippets/api/web5-js/dwn/protocols.js
Taking a look now

2023-09-29 16:19 UTC, dayhaysoos commented on site/code-snippets/api/web5-js/dwn/protocols.js
Hey Angie, I'm looking at the code snippet now and it looks exactly the same as the one I replaced:

```
const { protocols } = await web5.dwn.protocols.query({
  from: "did:example:bob",
  message: {
    filter: {
      protocol: "https://music.org/protocol",
    },
  },
});

// logs an array of protocol configurations installed on Bob's DWN
console.log(protocols);
```

Is this the one you were referring to?

2023-09-29 21:56 UTC, angiejones commented on site/code-snippets/api/web5-js/dwn/protocols.js
sorry! i changed the code on the Protocol tutorial, not the API reference. Sorry for the confusion. No action needed

2023-09-29 21:56 UTC, angiejones approved these changes

2023-09-30 13:14 UTC, merged