Remove console statement and add retry logic for FeedbackWidget
TBD54566975/developer.tbd.website pull request #792
Opened 2023-10-03 12:02 UTC by Developerayo

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [x] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

### First Commit
This PR removes the not needed `console.info` statement which appears in the console when a rating is clicked, 

#### Second Sommit
In case of a failure in feedback submission due to any reason like network unreliability, added a retry mechanism which will attempt to resubmit the feedback up to three times before throwing an error in the console if it keeps failing.

2023-10-03 15:53 UTC, dayhaysoos approved these changes

2023-10-03 17:26 UTC, leordev commented on site/src/hooks/use-feedback-rating.js
> +          await new Promise(resolve => setTimeout(resolve, waitTime));
Suggestion: here you can create a utility function `wait` to make the code more readable!

2023-10-03 17:50 UTC, Developerayo commented on site/src/hooks/use-feedback-rating.js
> +  const submitUserRating = async (rating, maxTries = 3) => {
Hm, you are right, It will fail in both scineros, do not have to test it, to bypass this, we can create a new function to get a new CSRF token if the initial rating submission fails, what do you think?

2023-10-03 17:50 UTC, Developerayo commented on site/src/hooks/use-feedback-rating.js
> +          await new Promise(resolve => setTimeout(resolve, waitTime));
🦾

2023-10-03 19:24 UTC, leordev commented on site/src/hooks/use-feedback-rating.js
> +  const submitUserRating = async (rating, maxTries = 3) => {
Yeah, the retry should entail refreshing the CSRF token + retrying.

2023-10-05 20:50 UTC, leordev commented on site/src/hooks/use-feedback-rating.js
> +  const wait = (duration) => new Promise(resolve => setTimeout(resolve, duration));
Please move this to the `/util` functions, so other components can reuse it when needed

2023-10-05 20:52 UTC, leordev approved these changes
Just a small ask and then LGTM!

Thank you @Developerayo ! 👏 🚀

2023-10-10 20:54 UTC, leordev commented
I tested this locally and I noticed the request was not retrying. It was because the `postFeedbackRating` function was not awaiting and throwing the error.

Can you please replace the current fetch with the following?

```ts
  const res = await fetch(`${feedbackWidgetUrl}/feedback`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'x-csrf-token': csrfToken,
    },
    credentials: 'include',
    body: JSON.stringify(requestBody),
  });

  if (!res.ok) {
    throw new Error('Failed to submit feedback rating');
  }
```

We can merge as soon as you do this! 👍

2023-10-11 11:57 UTC, leordev requested changes

2023-10-11 11:57 UTC, leordev commented on site/src/hooks/use-feedback-rating.js
> +  }
There's a missing curly brace (`}`) at the end of the file. I've no idea how the build is passing. Can you please fix it?

2023-10-13 14:38 UTC, Developerayo commented on site/src/hooks/use-feedback-rating.js
> +  }
Oops! Just pasted it in, lol

2023-10-13 15:34 UTC, leordev approved these changes

2023-10-13 15:35 UTC, merged