Update Navigation issue for button links
TBD54566975/developer.tbd.website pull request #836
Opened 2023-10-07 05:33 UTC by Smartmind12

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR rectifies the navigation issue on button click and opens the button on the same page . 

## Related Tickets & Documents

Resolves #806 #807 #808 

## Mobile & Desktop Screenshots/Recordings

On clicking the button the url opens on the same tab this rectifies the scrolling issue.

On clicking the contributing button in the midddle of the page opens the url of the contribution page in the same tab and at the top of the page.
![Screenshot 2023-10-07 at 10 59 39 AM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/14d652af-f05a-4e28-be82-4eff23bdb6ff)

![Screenshot 2023-10-07 at 10 59 48 AM](https://github.com/TBD54566975/developer.tbd.website/assets/91927689/413b4676-6503-4d41-92b1-7ea8370efac6)

## Added code snippets?
- [X] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [X] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [X] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-10 04:22 UTC, angiejones requested changes

2023-10-10 04:22 UTC, angiejones commented on site/src/components/Button.jsx
> +      rel="noopener noreferrer"
can you remove the `rel` attribute? knowing the referring internal page can be valuable for analytics and such

2023-10-10 04:38 UTC, Smartmind12 commented on site/src/components/Button.jsx
> +      rel="noopener noreferrer"
@angiejones Yes i have made the change!

2023-10-10 04:39 UTC, Smartmind12 commented
@angiejones I have removed the 'ref' attribute as suggested by you!

2023-10-11 01:27 UTC, angiejones approved these changes

2023-10-11 06:05 UTC, angiejones commented
thank you @Smartmind12 
@EbonyLouis hacktoberfest

2023-10-11 06:05 UTC, merged