created a ssiservice component
TBD54566975/developer.tbd.website pull request #889
Opened 2023-10-13 18:33 UTC by ShavonHarris-Dev

## What type of PR is this? (check all applicable)

- [x] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR [adds/removes/fixes/replaces] this [feature/bug/etc]. 

## Related Tickets & Documents

Resolves #661

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-13 19:22 UTC, angiejones requested changes

2023-10-13 19:22 UTC, angiejones commented on site/src/components/SSIComponent.jsx
> +const SSIService = () => {
can we rename this (and the file) to SSISPrereq?

2023-10-13 19:22 UTC, angiejones commented on site/docs/ssi/create-did.mdx
> +<SSIComponent />
here are all the places we should this
https://developer.tbd.website/search?q=Clone%20%26%20Run%20SSI%20Service

2023-10-13 19:25 UTC, angiejones commented on site/docs/ssi/create-did.mdx
>  ## Prerequisites
can remove this header, because it's getting printed twice
<img width="857" alt="image" src="https://github.com/TBD54566975/developer.tbd.website/assets/15972783/e2f8d77d-6dfa-4424-89c2-e269d68e73e9">

2023-10-24 17:23 UTC, ShavonHarris-Dev commented
> @ShavonHarris-Dev Hey, just checking in, do you need any help on this issue? we can do a call in discord if you've gotten stuck on anything

Hi @EbonyLouis I was actually not well and was out. Will get to this today/ tomorrow. If thats ok? Thanks for checking in.

2023-10-25 18:34 UTC, EbonyLouis commented
@ShavonHarris-Dev no rush, just checking up on you. I hope you feel better

2023-10-30 22:20 UTC, ShavonHarris-Dev commented
> @ShavonHarris-Dev no rush, just checking up on you. I hope you feel better

Hey @EbonyLouis ! Im finally back on my feet. I went in and made the component more dynamic so that it could be used all over. Can you let me know if this is what you were going for? Want to make sure i'm on the right path! Thanks :)

2023-11-01 22:03 UTC, blackgirlbytes commented
Hey @ShavonHarris-Dev I sent you a quick text, but our team decided to be prioritize this issue, so I'm gonna close this pull request.  I appreciate your hard work immensely!

2023-11-01 22:03 UTC, closed without merging