Update All Broken links in Docs and Blogs Page
TBD54566975/developer.tbd.website pull request #938
Opened 2023-10-29 03:03 UTC by Smartmind12

## What type of PR is this? (check all applicable)

- [X] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description

This PR fixes the broken links in the docs and blogs page. 

## Related Tickets & Documents

Resolves #868 

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [X] 🙅 no documentation needed

### No docs? Add a note

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-29 15:08 UTC, angiejones requested changes

2023-10-29 15:08 UTC, angiejones commented on site/blog/2022-07-26-web5-roadmap.md
> +In Q3, we’ll deliver initial implementations of the [SSI SDK](https://github.com/TBD54566975/ssi-sdk), [SSI Service](https://github.com/TBD54566975/ssi-service), and [Decentralized Web Nodes](https:/
```suggestion
In Q3, we’ll deliver initial implementations of the [SSI SDK](https://github.com/TBD54566975/ssi-sdk#readme), [SSI Service](https://github.com/TBD54566975/ssi-service#readme), and [Decentralized Web Nodes](https://github.com/TBD54566975/dwn-sdk-js#readme) .
```

2023-10-29 15:08 UTC, angiejones commented on site/blog/2022-07-26-web5-roadmap.md
> +In Q1 of 2023, the [SSI SDK](https://github.com/TBD54566975/ssi-sdk), [SSI Service](https://github.com/TBD54566975/ssi-service), and [Decentralized Web Nodes](https://github.com/TBD54566975/dwn-sdk-j
```suggestion
In Q1 of 2023, the [SSI SDK](https://github.com/TBD54566975/ssi-sdk#readme), [SSI Service](https://github.com/TBD54566975/ssi-service#readme), and [Decentralized Web Nodes](https://github.com/TBD54566975/dwn-sdk-js#readme) will be feature complete.
```

2023-10-29 15:08 UTC, angiejones commented on site/src/content/open-source/open-source.js
> +        url: 'https://developer.tbd.website/open-source/contributing',
```suggestion
        url: '/open-source/contributing',
```

Don't want to use absolute URLs for internal pages

2023-10-29 15:08 UTC, angiejones commented on site/src/content/open-source/open-source.js
> +        url: 'https://developer.tbd.website/open-source/governance',
```suggestion
        url: '/open-source/governance',
```

2023-10-29 15:08 UTC, angiejones commented on site/src/content/open-source/open-source.js
> +        url: 'https://developer.tbd.website/open-source/code-of-conduct',
```suggestion
        url: '/open-source/code-of-conduct',
```

2023-10-29 15:08 UTC, angiejones commented on site/src/content/open-source/open-source.js
> +        url: 'https://developer.tbd.website/open-source/incubation',
```suggestion
        url: '/open-source/incubation',
```

2023-10-29 15:08 UTC, angiejones commented on site/src/pages/community/index.js
> +            buttonUrl="https://developer.tbd.website/open-source/contributing"
```suggestion
            buttonUrl="/open-source/contributing"
```

2023-10-29 15:08 UTC, angiejones commented on site/src/pages/community/index.js
> +            buttonUrl="https://developer.tbd.website/open-source/incubation"
```suggestion
            buttonUrl="/open-source/incubation"
```

2023-10-30 01:46 UTC, Smartmind12 commented
Hey @angiejones I have made the necessary updates so kindly look into it!

2023-10-30 01:50 UTC, angiejones approved these changes

2023-10-30 02:03 UTC, merged

2023-10-30 02:03 UTC, angiejones commented
thank you @Smartmind12 🙌🏾

@EbonyLouis hacktoberfest