feat: create code snippets file for updatedwn
TBD54566975/developer.tbd.website pull request #942
Opened 2023-10-29 22:49 UTC by CBID2

## What type of PR is this? (check all applicable)

- [ ] ♻️ Refactor
- [ ] ✨ New Feature
- [ ] 🐛 Bug Fix
- [X] 📝 Documentation Update
- [ ] 👷 Example Application
- [ ] 🧑‍💻 Code Snippet
- [ ] 🎨 Design
- [ ] 📖 Content
- [ ] 🧪 Tests
- [ ] 🔖 Release
- [ ] 🚩 Other

## Description
This PR creates a `CodeSnippet` component and tests for 'Update DWN Records` tutorial. 

## Related Tickets & Documents

Resolves #937

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [X] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [ ] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note
I'm turning code snippets into component. 

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

2023-10-29 23:20 UTC, angiejones requested changes

2023-10-29 23:20 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/ update-dwn.js
there's a leading space before the file name. please make sure to remove it.

` update-dwn.js` should be 
`update-dwn.js`

2023-10-29 23:20 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/ update-dwn.js
> +export async function updateDWN
```suggestion
export async function updateDwnRecord(web5, createdRecord) {
```

- changed function name to more accurately reflect what it's doing
- added parameter list. in order for this function to be executable, it'll need an instance of web5 and a created record. this needs to be passed to the function by the tests you'll create
- opening curly brace to begin the function's body

2023-10-29 23:20 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/ update-dwn.js
> +    recordId: 'bafyreiaz5oycqbrnmmpvffxqyoqxvx6bcnqueprmt2qnvzcurpc52r5uyy',
```suggestion
    recordId: createdRecord.id,
```

This code will execute in real time. So, this record ID won't be valid. It was fine when it was just a non-executable example, but now we'll need a variable. This is why we passed in `createdRecord` as a function argument. Now we can use its id here.

2023-10-29 23:20 UTC, angiejones commented on site/code-snippets/web5/build/decentralized-web-nodes/ update-dwn.js
> +```
```suggestion
return status;
}
```

- removed the leftover code block syntax that was copied over
- added a return statement. This will be needed for the test. In the test, you'll need to make sure that `status.code` is the correct value, indicating that the update was successful and the code snippet works.
- added closing curly brace for the function

2023-10-29 23:42 UTC, CBID2 commented on site/code-snippets/web5/build/decentralized-web-nodes/ update-dwn.js
Hi @angiejones! :) I made the change. Also the file is already named `update-dwn.js`

2023-10-30 01:40 UTC, angiejones approved these changes

2023-10-30 01:40 UTC, angiejones commented
@EbonyLouis hacktoberfest

2023-10-30 01:45 UTC, merged

2023-10-30 01:46 UTC, angiejones commented
thanks so much @CBID2! 🙌🏾

2023-10-30 01:46 UTC, CBID2 commented
> thanks so much @CBID2! 🙌🏾

Thank you for your patience @angiejones! :)