Troubleshooting guide
TBD54566975/developer.tbd.website pull request #998
Opened 2023-11-14 14:22 UTC by acekyd

## What type of PR is this? (check all applicable)

- [x] 📝 Documentation Update
- [x] 📖 Content

## Description

This PR adds a section to include common errors people run into and possible solutions - for search and SEO discovery.
## Related Tickets & Documents

Resolves #

## Mobile & Desktop Screenshots/Recordings

## Added code snippets?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### No tests? Add a note

## Added to documentation?

- [ ] 📜 readme
- [ ] 📜 contributing.md
- [x] 📓 general documentation
- [ ] 🙅 no documentation needed

### No docs? Add a note

![Ouroboros](https://64.media.tumblr.com/e45cbe00f08ceab889500c6df99f23fe/af63b395a8c340b9-1a/s1280x1920/cf3286ae1de0e0ec0a118fc08e7bc745d3ddf645.gif)

2023-11-14 15:18 UTC, blackgirlbytes commented on site/docs/web5/build/troubleshooting-guide.mdx
> +This seems to be an issue with Webpack that happens mostly in React / Next.js projects. Here's how to solve it.
Thanks for including!! Is it okay, if for this, you just say Next.js and remove React? React doesn't have a next config file and the way to solve the problem is different.

2023-11-14 15:22 UTC, blackgirlbytes commented on site/docs/web5/build/troubleshooting-guide.mdx
> +```
```suggestion
npm install crypto-browserify stream-browserify process
```

Actually when I gave people advice on Discord, I forgot to add process as a package they need to install. I'm sure they figured it out because it will throw an error that it's not installed.

2023-11-14 15:22 UTC, blackgirlbytes commented on site/docs/web5/build/troubleshooting-guide.mdx
> +```
oh I put it at the wrong line!

2023-11-14 15:24 UTC, blackgirlbytes commented
Thanks for starting this!!!

2023-11-14 15:29 UTC, blackgirlbytes commented on site/docs/web5/build/troubleshooting-guide.mdx
> +npm install crypto-browserify stream-browserify
```suggestion
npm install crypto-browserify stream-browserify process
```

I forgot to add  process when I was advising people on Discord. I'm sure they figured it out because it will throw an error that that is missing

2023-11-14 15:31 UTC, blackgirlbytes commented on site/docs/web5/build/troubleshooting-guide.mdx
> +This is most likely a syntax error. Check your code for any typos or missing attributes.
a syntax error where? Anywhere? In the protocol definition or..(sorry not trying to be annoying)

2023-11-14 15:33 UTC, blackgirlbytes commented on examples/tutorials/todo-starter/package.json
> +}
how come we added new lines to these?

2023-11-15 10:38 UTC, angiejones requested changes

2023-11-15 10:38 UTC, angiejones commented on site/docs/web5/build/troubleshooting-guide.mdx
> +This seems to be an issue with Webpack that happens mostly in React / Next.js projects. Here's how to solve it.
```suggestion
This is an issue with Webpack that happens mostly in Next.js projects. Here's how to solve it:
```

2023-11-15 10:38 UTC, angiejones commented on site/docs/web5/build/troubleshooting-guide.mdx
> +Run
```suggestion
1. Run the following command to install two packages that will enable cryptographic functions and stream handling within the browser:
```

2023-11-15 10:38 UTC, angiejones commented on site/docs/web5/build/troubleshooting-guide.mdx
> +Then, in your `next.config.js` file, add the following:
```suggestion
2. Then, in your `next.config.js` file, add the following:
```

2023-11-15 10:38 UTC, angiejones commented on site/docs/web5/build/troubleshooting-guide.mdx
> +When starting up and connecting to the Web5 sdk, some polyfills might be missing. To fix this at the moment, update your Web5 import to
```suggestion
When starting up and connecting to the Web5 SDK, some polyfills might be missing. To fix this, update your Web5 import:
```

2023-11-15 10:40 UTC, acekyd commented on site/docs/web5/build/troubleshooting-guide.mdx
> +This seems to be an issue with Webpack that happens mostly in React / Next.js projects. Here's how to solve it.
Gotcha. Thanks

2023-11-15 16:10 UTC, angiejones approved these changes

2023-11-15 16:11 UTC, merged